Repository sigp/lighthouse, pull requests merged in 2019-10, with the labels that each got.

#547 Refactor docs into mdbook
  Makefile
  README.md
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/client/src/lib.rs
  beacon_node/rest_api/api_spec.yaml
  beacon_node/rpc/src/attestation.rs
  beacon_node/rpc/src/beacon_block.rs
  book/README.md
  book/book.toml
  book/src/SUMMARY.md
  book/src/api.md
  book/src/ci.md
  book/src/cli.md
  book/src/contributing.md
  book/src/http.md
  book/src/interop-cheat-sheet.md
  book/src/interop-cli.md
  book/src/interop-environment.md
  book/src/interop-scenarios.md
  book/src/interop.md
  book/src/intro.md
  book/src/setup.md
  book/src/simple-testnet.md
  book/src/testnets.md
  book/src/websockets.md
  docs/README.md
  docs/config_examples/beacon-node.toml
  docs/documentation.md
  docs/env.md
  docs/interop.md
  docs/serenity.md
  eth2/README.md
  lcli/README.md
  tests/ef_tests/Makefile
  tests/ef_tests/README.md
  validator_client/src/block_producer/mod.rs
Labels: ready-for-review

#554 Update Milagro BLS to v0.11.0
  eth2/utils/bls/Cargo.toml
  eth2/utils/eth2_interop_keypairs/Cargo.toml
Labels: ready-to-merge

#562 Run EF tests on GitLab
  .gitignore
  .gitlab-ci.yml
  tests/ef_tests/Cargo.toml
  tests/ef_tests/Makefile
  tests/ef_tests/README.md
  tests/ef_tests/src/handler.rs
  tests/ef_tests/tests/tests.rs
Labels: ready-to-merge

#563 Implement push_leaf for MerkleTree
  beacon_node/beacon_chain/src/beacon_chain_builder.rs
  eth2/utils/merkle_proof/src/lib.rs
Labels: ready-for-review

#564 Rename get_permutated_index to compute_shuffled_index.
  eth2/utils/swap_or_not_shuffle/benches/benches.rs
  eth2/utils/swap_or_not_shuffle/src/compute_shuffled_index.rs
  eth2/utils/swap_or_not_shuffle/src/lib.rs
  eth2/utils/swap_or_not_shuffle/src/shuffle_list.rs
  tests/ef_tests/src/cases/shuffling.rs
Labels: ready-for-review

#573 Allow slot clock to work on genesis
  eth2/utils/slot_clock/src/system_time_slot_clock.rs
Labels: ready-to-merge

#577 Updates external dependencies
  Cargo.toml
  account_manager/Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/client/Cargo.toml
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/network/Cargo.toml
  beacon_node/rest_api/Cargo.toml
  beacon_node/rpc/Cargo.toml
  beacon_node/store/Cargo.toml
  beacon_node/websocket_server/Cargo.toml
  eth2/lmd_ghost/Cargo.toml
  eth2/operation_pool/Cargo.toml
  eth2/state_processing/Cargo.toml
  eth2/types/Cargo.toml
  eth2/types/src/test_utils/keypairs_file.rs
  eth2/types/src/test_utils/mod.rs
  eth2/utils/bls/Cargo.toml
  eth2/utils/eth2_config/Cargo.toml
  eth2/utils/eth2_hashing/Cargo.toml
  eth2/utils/eth2_interop_keypairs/Cargo.toml
  eth2/utils/int_to_bytes/Cargo.toml
  eth2/utils/lighthouse_bootstrap/Cargo.toml
  eth2/utils/lighthouse_metrics/Cargo.toml
  eth2/utils/logging/Cargo.toml
  eth2/utils/merkle_proof/Cargo.toml
  eth2/utils/serde_hex/Cargo.toml
  eth2/utils/slot_clock/Cargo.toml
  eth2/utils/ssz/Cargo.toml
  eth2/utils/ssz_types/Cargo.toml
  eth2/utils/swap_or_not_shuffle/Cargo.toml
  eth2/utils/tree_hash/Cargo.toml
  lcli/Cargo.toml
  protos/Cargo.toml
  protos/build.rs
  tests/ef_tests/Cargo.toml
  validator_client/Cargo.toml
Labels: ready-to-merge

#579 Only run non-ef tests when executing make test
  Makefile
Labels: waiting-on-author
