Repository sigp/lighthouse, pull requests merged in 2019-03, with the labels that each got.

#297 [WIP] Add OptimizedLMDGhost fork choice rule and tests
  eth2/fork_choice/src/lib.rs
  eth2/fork_choice/src/optimized_lmd_ghost.rs
  eth2/fork_choice/tests/tests.rs
Labels: WIP

#299 Fix test harness
  beacon_node/beacon_chain/test_harness/Cargo.toml
  beacon_node/beacon_chain/test_harness/benches/state_transition.rs
  beacon_node/beacon_chain/test_harness/src/beacon_chain_harness.rs
  beacon_node/beacon_chain/test_harness/src/beacon_chain_harness/generate_deposits.rs
  beacon_node/beacon_chain/test_harness/src/lib.rs
  beacon_node/beacon_chain/test_harness/src/run_test.rs
  beacon_node/beacon_chain/test_harness/src/test_case.rs
  beacon_node/beacon_chain/test_harness/tests/chain.rs
Labels: ready-for-review

#301 Add pubkey cache
  eth2/state_processing/benches/bench_block_processing.rs
  eth2/state_processing/benches/benches.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/errors.rs
  eth2/state_processing/src/per_block_processing/verify_deposit.rs
  eth2/types/src/beacon_state.rs
  eth2/types/src/beacon_state/pubkey_cache.rs
  eth2/types/src/lib.rs
  eth2/types/src/test_utils/testing_beacon_state_builder.rs
Labels: ready-for-review

#306 Update signature-scheme to v0.6.1
  eth2/utils/bls/Cargo.toml
Labels: ready-for-review

#316 Add editorconfig template
  .editorconfig
Labels: ready-for-review

#286 Beacon Node Syncing, Network Infrastructure and Core Services
  Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/initialise.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/client_config.rs
  beacon_node/client/src/client_types.rs
  beacon_node/client/src/error.rs
  beacon_node/client/src/lib.rs
  beacon_node/client/src/notifier.rs
  beacon_node/db/src/lib.rs
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/error.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/network_config.rs
  beacon_node/eth2-libp2p/src/rpc/methods.rs
  beacon_node/eth2-libp2p/src/rpc/mod.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/beacon_chain.rs
  beacon_node/network/src/error.rs
  beacon_node/network/src/lib.rs
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/network/src/sync/simple_sync.rs
  beacon_node/rpc/Cargo.toml
  beacon_node/rpc/src/beacon_block.rs
  beacon_node/rpc/src/config.rs
  beacon_node/rpc/src/lib.rs
  beacon_node/rpc/src/validator.rs
  beacon_node/src/config/mod.rs
  beacon_node/src/main.rs
  beacon_node/src/run.rs
  beacon_node/version/Cargo.toml
  beacon_node/version/src/lib.rs
  eth2/fork_choice/src/lib.rs
  eth2/types/Cargo.toml
  eth2/types/src/chain_spec.rs
  eth2/types/src/lib.rs
Labels: ready-for-review

#318 Libp2p rpc
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/network/src/service.rs
Labels: ready-for-review

#295 Persisting (random) Validator Keys
  Cargo.toml
  account_manager/Cargo.toml
  account_manager/README.md
  account_manager/src/main.rs
  eth2/utils/bls/src/keypair.rs
  validator_client/Cargo.toml
  validator_client/README.md
  validator_client/src/config.rs
  validator_client/src/lib.rs
  validator_client/src/main.rs
Labels: ready-for-review, val-client

#327 Libp2p patch
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/src/service.rs
  eth2/types/Cargo.toml
Labels: ready-for-review

#328 Libp2p patch
  beacon_node/eth2-libp2p/Cargo.toml
  eth2/types/Cargo.toml
Labels: ready-for-review

#319 Disable Signature verification in debug
  .travis.yml
  Jenkinsfile
  eth2/utils/bls/src/fake_aggregate_signature.rs
  eth2/utils/bls/src/fake_signature.rs
  eth2/utils/bls/src/lib.rs
Labels: ready-for-review

#331 [WIP] Validator Client Update
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/initialise.rs
  beacon_node/beacon_chain/test_harness/src/beacon_chain_harness.rs
  beacon_node/beacon_chain/test_harness/src/validator_harness/direct_beacon_node.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/lib.rs
  beacon_node/client/src/notifier.rs
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/network/src/beacon_chain.rs
  beacon_node/network/src/lib.rs
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/simple_sync.rs
  beacon_node/rpc/Cargo.toml
  beacon_node/rpc/src/beacon_attester.rs
  beacon_node/rpc/src/beacon_block.rs
  beacon_node/rpc/src/beacon_chain.rs
  beacon_node/rpc/src/beacon_node.rs
  beacon_node/rpc/src/lib.rs
  beacon_node/rpc/src/validator.rs
  beacon_node/src/run.rs
  eth2/attester/src/lib.rs
  eth2/attester/src/test_utils/simulated_beacon_node.rs
  eth2/attester/src/traits.rs
  eth2/state_processing/src/per_slot_processing.rs
  eth2/types/src/chain_spec.rs
  eth2/types/src/lib.rs
  eth2/types/src/test_utils/testing_beacon_state_builder.rs
  eth2/utils/slot_clock/src/lib.rs
  eth2/utils/slot_clock/src/system_time_slot_clock.rs
  eth2/utils/slot_clock/src/testing_slot_clock.rs
  protos/src/services.proto
  validator_client/Cargo.toml
  validator_client/src/attester_service/attestation_grpc_client.rs
  validator_client/src/attester_service/mod.rs
  validator_client/src/block_producer_service/beacon_block_grpc_client.rs
  validator_client/src/config.rs
  validator_client/src/duties/epoch_duties.rs
  validator_client/src/duties/grpc.rs
  validator_client/src/duties/mod.rs
  validator_client/src/duties/service.rs
  validator_client/src/duties/traits.rs
  validator_client/src/error.rs
  validator_client/src/main.rs
  validator_client/src/service.rs
Labels: ready-for-review
