Repository sigp/lighthouse, pull requests merged in 2019-08, with the labels that each got.

#486 Tree hash benches
  eth2/utils/tree_hash/Cargo.toml
  eth2/utils/tree_hash/benches/benches.rs
  eth2/utils/tree_hash/examples/flamegraph_beacon_state.rs
Labels: ready-for-review

#488 Disallow extra bytes in Bitfield from_bytes
  eth2/utils/ssz_types/src/bitfield.rs
Labels: ready-for-review

#479 Interop chain start strategies
  Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/beacon_chain_types.rs
  beacon_node/client/src/config.rs
  beacon_node/client/src/lib.rs
  beacon_node/src/main.rs
  beacon_node/src/run.rs
  docs/README.md
  docs/config_examples/beacon-node.toml
  docs/env.md
  docs/installation.md
  docs/interop.md
  docs/lighthouse.md
  docs/onboarding.md
  eth2/types/Cargo.toml
  eth2/types/src/beacon_block_body.rs
  eth2/types/src/beacon_state.rs
  eth2/types/src/chain_spec.rs
  eth2/types/src/fork.rs
  eth2/types/src/lib.rs
  eth2/types/src/test_utils/builders/testing_beacon_state_builder.rs
  eth2/types/src/test_utils/generate_deterministic_keypairs.rs
  eth2/types/src/test_utils/mod.rs
  eth2/types/src/utils.rs
  eth2/types/src/utils/serde_utils.rs
  eth2/utils/eth2_interop_keypairs/Cargo.toml
  eth2/utils/eth2_interop_keypairs/src/lib.rs
  tests/cli_util/.gitignore
  tests/cli_util/Cargo.toml
  tests/cli_util/src/main.rs
Labels: ready-to-merge

#472 Use SignatureBytes and PublicKeyBytes for deposits
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/errors.rs
  eth2/state_processing/src/per_block_processing/verify_deposit.rs
  eth2/types/src/deposit_data.rs
  eth2/types/src/test_utils/builders/testing_deposit_builder.rs
  eth2/types/src/test_utils/test_random.rs
  eth2/types/src/test_utils/test_random/public_key_bytes.rs
  eth2/types/src/test_utils/test_random/signature_bytes.rs
  eth2/utils/bls/src/lib.rs
  eth2/utils/bls/src/macros.rs
  eth2/utils/bls/src/public_key.rs
  eth2/utils/bls/src/public_key_bytes.rs
  eth2/utils/bls/src/signature.rs
  eth2/utils/bls/src/signature_bytes.rs
Labels: ready-to-merge

#489 Update ethereum types
  beacon_node/store/src/iter.rs
  eth2/types/Cargo.toml
  eth2/types/src/beacon_state/committee_cache/tests.rs
  eth2/types/src/beacon_state/tests.rs
  eth2/utils/cached_tree_hash/Cargo.toml
  eth2/utils/merkle_proof/Cargo.toml
  eth2/utils/ssz/Cargo.toml
  eth2/utils/ssz/fuzz/Cargo.toml
  eth2/utils/swap_or_not_shuffle/Cargo.toml
  eth2/utils/tree_hash/Cargo.toml
  tests/ef_tests/Cargo.toml
Labels: ready-to-merge

#490 Tidy ancestor iterators
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/iter.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/network/src/sync/simple_sync.rs
  beacon_node/rest_api/src/beacon_node.rs
  beacon_node/rpc/src/attestation.rs
  beacon_node/rpc/src/validator.rs
  beacon_node/store/src/iter.rs
  eth2/lmd_ghost/tests/test.rs
Labels: ready-to-merge

#492 Initial Interop Updates
  beacon_node/client/src/config.rs
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/eth2-libp2p/src/rpc/mod.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/http_server/src/api.rs
  beacon_node/http_server/src/lib.rs
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/simple_sync.rs
  beacon_node/rpc/src/attestation.rs
  beacon_node/rpc/src/beacon_block.rs
  beacon_node/rpc/src/beacon_node.rs
  beacon_node/rpc/src/lib.rs
  beacon_node/src/main.rs
  beacon_node/src/run.rs
  eth2/types/src/beacon_state/beacon_state_types.rs
  eth2/types/src/chain_spec.rs
  eth2/utils/eth2_config/src/lib.rs
  protos/src/services.proto
  validator_client/eth2_config.toml
  validator_client/src/main.rs
  validator_client/src/service.rs
Labels: review-in-process

#480 Changes to rest_api
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/client/src/config.rs
  beacon_node/rest_api/Cargo.toml
  beacon_node/rest_api/src/beacon.rs
  beacon_node/rest_api/src/beacon_node.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/macros.rs
  beacon_node/rest_api/src/node.rs
  beacon_node/rest_api/src/url_query.rs
  beacon_node/src/main.rs
  beacon_node/store/src/iter.rs
Labels: ready-to-merge

#497 Attestation processing
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/network/src/sync/simple_sync.rs
  beacon_node/rpc/src/attestation.rs
  beacon_node/store/src/iter.rs
  eth2/lmd_ghost/src/lib.rs
  eth2/lmd_ghost/src/reduced_tree.rs
  eth2/operation_pool/src/lib.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/verify_attestation.rs
  eth2/types/src/beacon_block.rs
Labels: ready-to-merge

#500 Fix block processing blowup, upgrade metrics
  .travis.yml
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/config.rs
  beacon_node/client/src/lib.rs
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/metrics.rs
  beacon_node/http_server/Cargo.toml
  beacon_node/http_server/src/api.rs
  beacon_node/http_server/src/key.rs
  beacon_node/http_server/src/lib.rs
  beacon_node/http_server/src/metrics.rs
  beacon_node/http_server/src/metrics/local_metrics.rs
  beacon_node/rest_api/Cargo.toml
  beacon_node/rest_api/src/config.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/metrics.rs
  beacon_node/src/main.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/impls.rs
  beacon_node/store/src/impls/beacon_state.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metrics.rs
  docs/config_examples/beacon-node.toml
  eth2/utils/lighthouse_metrics/Cargo.toml
  eth2/utils/lighthouse_metrics/src/lib.rs
  eth2/utils/slot_clock/Cargo.toml
  eth2/utils/slot_clock/src/lib.rs
  eth2/utils/slot_clock/src/metrics.rs
  eth2/utils/slot_clock/src/system_time_slot_clock.rs
  eth2/utils/slot_clock/src/testing_slot_clock.rs
Labels: ready-to-merge

#501 Bootstrap
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/beacon_chain_types.rs
  beacon_node/client/src/bootstrapper.rs
  beacon_node/client/src/config.rs
  beacon_node/client/src/lib.rs
  beacon_node/client/src/notifier.rs
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/network/src/service.rs
  beacon_node/rest_api/Cargo.toml
  beacon_node/rest_api/src/beacon.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/network.rs
  beacon_node/rest_api/src/spec.rs
  beacon_node/src/main.rs
  beacon_node/src/run.rs
  eth2/types/src/beacon_block_body.rs
  eth2/types/src/utils/serde_utils.rs
Labels: ready-for-review

#506 Update env.md
  docs/env.md
Labels: ready-for-review

#507 Bulk signature verification
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/rpc/src/attestation.rs
  eth2/lmd_ghost/tests/test.rs
  eth2/operation_pool/src/lib.rs
  eth2/state_processing/.gitignore
  eth2/state_processing/Cargo.toml
  eth2/state_processing/benches/benches.rs
  eth2/state_processing/src/common/get_indexed_attestation.rs
  eth2/state_processing/src/lib.rs
  eth2/state_processing/src/macros.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/block_signature_verifier.rs
  eth2/state_processing/src/per_block_processing/errors.rs
  eth2/state_processing/src/per_block_processing/is_valid_indexed_attestation.rs
  eth2/state_processing/src/per_block_processing/signature_sets.rs
  eth2/state_processing/src/per_block_processing/tests.rs
  eth2/state_processing/src/per_block_processing/verify_attestation.rs
  eth2/state_processing/src/per_block_processing/verify_attester_slashing.rs
  eth2/state_processing/src/per_block_processing/verify_deposit.rs
  eth2/state_processing/src/per_block_processing/verify_exit.rs
  eth2/state_processing/src/per_block_processing/verify_proposer_slashing.rs
  eth2/state_processing/src/per_block_processing/verify_transfer.rs
  eth2/state_processing/src/test_utils.rs
  eth2/state_processing/tests/tests.rs
  eth2/types/src/beacon_state.rs
  eth2/types/src/test_utils/builders/testing_beacon_block_builder.rs
  eth2/utils/bls/Cargo.toml
  eth2/utils/bls/src/aggregate_public_key.rs
  eth2/utils/bls/src/aggregate_signature.rs
  eth2/utils/bls/src/fake_aggregate_public_key.rs
  eth2/utils/bls/src/fake_aggregate_signature.rs
  eth2/utils/bls/src/fake_public_key.rs
  eth2/utils/bls/src/fake_signature.rs
  eth2/utils/bls/src/lib.rs
  eth2/utils/bls/src/signature_set.rs
  tests/ef_tests/src/cases/operations_attestation.rs
  tests/ef_tests/src/cases/operations_attester_slashing.rs
  tests/ef_tests/src/cases/operations_block_header.rs
  tests/ef_tests/src/cases/operations_exit.rs
  tests/ef_tests/src/cases/operations_proposer_slashing.rs
  tests/ef_tests/src/cases/operations_transfer.rs
  tests/ef_tests/src/cases/sanity_blocks.rs
Labels: under-review

#510 Ethereum 2.0 Network Specification Upgrade
  beacon_node/Cargo.toml
  beacon_node/client/src/lib.rs
  beacon_node/client/src/notifier.rs
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/eth2-libp2p/src/rpc/methods.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/import_queue.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/network/src/sync/simple_sync.rs
  beacon_node/rpc/src/attestation.rs
  beacon_node/rpc/src/beacon_block.rs
  beacon_node/src/main.rs
Labels: waiting-on-author
