Repository sigp/lighthouse, pull requests merged in 2019-11, with the labels that each got.

#589 Depend on sha2 in eth2_hashing for wasm32
  eth2/utils/eth2_hashing/Cargo.toml
Labels: ready-for-review

#574 Implement push_leaf for MerkleTree
  beacon_node/beacon_chain/src/beacon_chain_builder.rs
  eth2/utils/merkle_proof/src/lib.rs
Labels: ready-for-review

#591 Move EthSpec
  eth2/types/src/beacon_state.rs
  eth2/types/src/eth_spec.rs
  eth2/types/src/lib.rs
Labels: ready-for-review

#584 Implement tree hash caching
  Cargo.toml
  beacon_node/store/src/impls/beacon_state.rs
  eth2/types/Cargo.toml
  eth2/types/src/beacon_state.rs
  eth2/types/src/crosslink_committee.rs
  eth2/types/src/lib.rs
  eth2/types/src/tree_hash_impls.rs
  eth2/utils/bls/build.rs
  eth2/utils/bls/src/aggregate_signature.rs
  eth2/utils/bls/src/fake_aggregate_signature.rs
  eth2/utils/bls/src/fake_public_key.rs
  eth2/utils/bls/src/fake_signature.rs
  eth2/utils/bls/src/macros.rs
  eth2/utils/bls/src/public_key.rs
  eth2/utils/bls/src/public_key_bytes.rs
  eth2/utils/bls/src/secret_key.rs
  eth2/utils/bls/src/signature.rs
  eth2/utils/bls/src/signature_bytes.rs
  eth2/utils/cached_tree_hash/Cargo.toml
  eth2/utils/cached_tree_hash/src/cache.rs
  eth2/utils/cached_tree_hash/src/impls.rs
  eth2/utils/cached_tree_hash/src/lib.rs
  eth2/utils/cached_tree_hash/src/multi_cache.rs
  eth2/utils/cached_tree_hash/src/test.rs
  eth2/utils/eth2_hashing/Cargo.toml
  eth2/utils/eth2_hashing/src/lib.rs
  eth2/utils/merkle_proof/src/lib.rs
  eth2/utils/tree_hash/Cargo.toml
  eth2/utils/tree_hash/benches/benches.rs
  eth2/utils/tree_hash/src/impls.rs
  eth2/utils/tree_hash/src/lib.rs
  eth2/utils/tree_hash/src/merkleize_padded.rs
  eth2/utils/tree_hash_derive/src/lib.rs
  tests/ef_tests/Cargo.toml
  tests/ef_tests/src/cases/ssz_generic.rs
  tests/ef_tests/src/cases/ssz_static.rs
  tests/ef_tests/src/handler.rs
  tests/ef_tests/tests/tests.rs
Labels: ready-to-merge

#595 Derive `PartialEq` for Keypair
  eth2/utils/bls/src/keypair.rs
Labels: ready-to-merge

#559 BlockProcessing testing
  eth2/operation_pool/src/lib.rs
  eth2/state_processing/src/common/get_indexed_attestation.rs
  eth2/state_processing/src/per_block_processing/block_processing_builder.rs
  eth2/state_processing/src/per_block_processing/errors.rs
  eth2/state_processing/src/per_block_processing/tests.rs
  eth2/state_processing/src/per_block_processing/verify_attestation.rs
  eth2/state_processing/src/test_utils.rs
  eth2/types/Cargo.toml
  eth2/types/src/test_utils/builders/testing_attestation_builder.rs
  eth2/types/src/test_utils/builders/testing_attestation_data_builder.rs
  eth2/types/src/test_utils/builders/testing_attester_slashing_builder.rs
  eth2/types/src/test_utils/builders/testing_beacon_block_builder.rs
  eth2/types/src/test_utils/builders/testing_beacon_state_builder.rs
  eth2/types/src/test_utils/builders/testing_deposit_builder.rs
  eth2/types/src/test_utils/builders/testing_pending_attestation_builder.rs
  eth2/types/src/test_utils/builders/testing_proposer_slashing_builder.rs
Labels: ready-for-review

#610 Enables ENR auto-update based on new listen address
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/service.rs
Labels: ready-for-review

#601 Move account manager under main binary
  account_manager/Cargo.toml
  account_manager/src/cli.rs
  account_manager/src/lib.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/config.rs
  lighthouse/Cargo.toml
  lighthouse/environment/Cargo.toml
  lighthouse/environment/src/lib.rs
  lighthouse/src/main.rs
  validator_client/Cargo.toml
  validator_client/src/config.rs
Labels: ready-for-review

#621 Fix custom derive macros
  eth2/utils/ssz_derive/src/lib.rs
  eth2/utils/tree_hash_derive/src/lib.rs
Labels: ready-for-review

#633 Add cfg! check for fake_crypto
  beacon_node/rest_api/tests/test.rs
Labels: ready-to-merge

#508 Implement freezer database
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/beacon_chain_builder.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/iter.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/persisted_beacon_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/service.rs
  beacon_node/rest_api/src/beacon.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/chunked_vector.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/impls.rs
  beacon_node/store/src/impls/beacon_state.rs
  beacon_node/store/src/impls/partial_beacon_state.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  beacon_node/store/src/migrate.rs
  beacon_node/store/src/partial_beacon_state.rs
  eth2/lmd_ghost/src/reduced_tree.rs
  eth2/types/src/chain_spec.rs
Labels: ready-to-merge

#587 Testnet compatible network upgrade
  .github/workflows/test-suite.yml
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/rpc/codec/base.rs
  beacon_node/eth2-libp2p/src/rpc/codec/mod.rs
  beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/eth2-libp2p/src/rpc/methods.rs
  beacon_node/eth2-libp2p/src/rpc/mod.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/eth2-libp2p/tests/common/mod.rs
  beacon_node/eth2-libp2p/tests/gossipsub_tests.rs
  beacon_node/eth2-libp2p/tests/rpc_tests.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/message_processor.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
Labels: networking, ready-to-merge

#639 Address bugs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
Labels: ready-for-review

#605 Apply eth2.0 config spec to ChainSpec
  eth2/types/Cargo.toml
  eth2/types/src/chain_spec.rs
  eth2/types/src/utils/serde_utils.rs
Labels: waiting-on-author

#642 Remove duplication from bad merge
  eth2/types/src/chain_spec.rs
Labels: ready-for-review

#645 Correct and consolidate RPC protocol names
  beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
Labels: ready-for-review

#640 RPC Corrections and deadlock fix
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/eth2-libp2p/src/rpc/methods.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/service.rs
  beacon_node/src/cli.rs
  validator_client/src/config.rs
Labels: ready-for-review

#646 Updates libp2p to v0.13
  beacon_node/eth2-libp2p/Cargo.toml
Labels: ready-for-review

#624 Reduced tree encode/decode
  eth2/lmd_ghost/Cargo.toml
  eth2/lmd_ghost/src/lib.rs
  eth2/lmd_ghost/src/reduced_tree.rs
Labels: waiting-on-author

#643 Clean up network logging and code
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/eth2-libp2p/src/rpc/mod.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/message_processor.rs
  beacon_node/src/config.rs
Labels: ready-to-merge

#651 Correct ENR update and log formatting
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/eth2-libp2p/src/service.rs
Labels: ready-to-merge
