Repository sigp/lighthouse, pull requests merged in 2019-09, with the labels that each got.

#535 Add about and onboarding to book
  CONTRIBUTING.md
  README.md
  book/src/SUMMARY.md
  book/src/intro.md
  book/src/lighthouse.md
  book/src/onboarding.md
  book/src/serenity.md
Labels: under-review

#544 Robustify derive macro attribute parsing
  eth2/utils/compare_fields_derive/src/lib.rs
  eth2/utils/ssz_derive/src/lib.rs
  eth2/utils/test_random_derive/src/lib.rs
  eth2/utils/tree_hash_derive/src/lib.rs
Labels: ready-to-merge

#550 Fix the build for Rust 1.38, protobuf releases
  beacon_node/network/src/message_handler.rs
  eth2/state_processing/Cargo.toml
  eth2/types/src/attestation.rs
  eth2/types/src/attestation_data_and_custody_bit.rs
  eth2/types/src/attester_slashing.rs
  eth2/types/src/checkpoint.rs
  eth2/types/src/crosslink.rs
  eth2/types/src/deposit.rs
  eth2/types/src/deposit_data.rs
  eth2/types/src/eth1_data.rs
  eth2/types/src/historical_batch.rs
  eth2/types/src/pending_attestation.rs
  eth2/types/src/proposer_slashing.rs
  eth2/types/src/transfer.rs
  eth2/types/src/validator.rs
  eth2/types/src/voluntary_exit.rs
  eth2/utils/tree_hash/Cargo.toml
  eth2/utils/tree_hash_derive/src/lib.rs
  protos/Cargo.toml
  validator_client/src/attestation_producer/mod.rs
  validator_client/src/block_producer/mod.rs
  validator_client/src/duties/mod.rs
Labels: ready-for-review

#536 Clippy clean
  account_manager/src/main.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/beacon_chain_builder.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/client/src/lib.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/response_builder.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/rpc/src/attestation.rs
  beacon_node/rpc/src/beacon_block.rs
  beacon_node/src/config.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/metrics.rs
  eth2/lmd_ghost/src/reduced_tree.rs
  eth2/state_processing/benches/benches.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/is_valid_indexed_attestation.rs
  eth2/state_processing/src/per_block_processing/tests.rs
  eth2/state_processing/src/per_block_processing/verify_attestation.rs
  eth2/state_processing/src/test_utils.rs
  eth2/types/src/beacon_state/committee_cache/tests.rs
  eth2/types/src/beacon_state/tests.rs
  eth2/types/src/test_utils/builders/testing_beacon_state_builder.rs
  eth2/types/src/utils/serde_utils.rs
  eth2/utils/bls/src/secret_key.rs
  eth2/utils/eth2_interop_keypairs/src/lib.rs
  eth2/utils/eth2_interop_keypairs/tests/generation.rs
  eth2/utils/lighthouse_metrics/src/lib.rs
  eth2/utils/merkle_proof/src/lib.rs
  eth2/utils/ssz/examples/large_list.rs
  eth2/utils/ssz/examples/large_list_of_structs.rs
  eth2/utils/ssz/examples/struct_definition.rs
  eth2/utils/ssz/src/encode/impls.rs
  lcli/src/parse_hex.rs
  tests/ef_tests/src/cases/ssz_generic.rs
  validator_client/src/config.rs
  validator_client/src/duties/epoch_duties.rs
Labels: under-review
