Repository sigp/lighthouse, pull requests merged in 2019-07, with the labels that each got.

#426 Add ssz_types crate
  Cargo.toml
  eth2/utils/ssz/src/lib.rs
  eth2/utils/ssz_types/Cargo.toml
  eth2/utils/ssz_types/src/bitfield.rs
  eth2/utils/ssz_types/src/fixed_vector.rs
  eth2/utils/ssz_types/src/lib.rs
  eth2/utils/ssz_types/src/variable_list.rs
Labels: ready-for-review

#436 Padding efficent merkle root algo
  eth2/utils/tree_hash/Cargo.toml
  eth2/utils/tree_hash/src/impls.rs
  eth2/utils/tree_hash/src/lib.rs
  eth2/utils/tree_hash/src/merkleize_padded.rs
  eth2/utils/tree_hash/src/merkleize_standard.rs
  eth2/utils/tree_hash_derive/src/lib.rs
  eth2/utils/tree_hash_derive/tests/tests.rs
Labels: ready-for-review

#429 Fix syncing bugs by recursively attempting to process parents in the …
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/notifier.rs
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/http_server/Cargo.toml
  beacon_node/http_server/src/lib.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/import_queue.rs
  beacon_node/network/src/sync/simple_sync.rs
  beacon_node/rpc/Cargo.toml
  beacon_node/rpc/src/attestation.rs
  beacon_node/rpc/src/beacon_block.rs
  beacon_node/rpc/src/lib.rs
  beacon_node/src/main.rs
  beacon_node/store/src/iter.rs
  eth2/lmd_ghost/src/reduced_tree.rs
Labels: WIP

#441 RPC Rewrite
  beacon_node/client/src/notifier.rs
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/rpc/codec/base.rs
  beacon_node/eth2-libp2p/src/rpc/codec/mod.rs
  beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/eth2-libp2p/src/rpc/methods.rs
  beacon_node/eth2-libp2p/src/rpc/mod.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/simple_sync.rs
Labels: ready-for-review

#455 Spec. for REST API
  docs/rest_oapi.yaml
Labels: ready-for-review

#449 Fork choice bug fixes
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/store/src/iter.rs
  eth2/lmd_ghost/Cargo.toml
  eth2/lmd_ghost/src/reduced_tree.rs
  eth2/lmd_ghost/tests/test.rs
Labels: ready-for-review

#457 Fix underflow in verify_transfer
  eth2/state_processing/src/per_block_processing/verify_transfer.rs
Labels: ready-for-review

#451 Testnet stability
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/client/src/beacon_chain_types.rs
  beacon_node/client/src/lib.rs
  beacon_node/client/src/notifier.rs
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/http_server/src/metrics/local_metrics.rs
  beacon_node/network/src/sync/simple_sync.rs
  beacon_node/src/main.rs
  beacon_node/src/run.rs
  validator_client/src/main.rs
Labels: reviewer-awaiting-changes

#466 Add v0.8 genesis tests
  eth2/state_processing/src/common/get_compact_committees_root.rs
  eth2/state_processing/src/genesis.rs
  eth2/state_processing/src/lib.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/types/src/beacon_state/pubkey_cache.rs
  tests/ef_tests/src/cases.rs
  tests/ef_tests/src/cases/genesis_initialization.rs
  tests/ef_tests/src/cases/genesis_validity.rs
  tests/ef_tests/src/doc.rs
  tests/ef_tests/tests/tests.rs
Labels: ready-to-merge

#465 Remove old benches
  eth2/state_processing/Cargo.toml
  eth2/state_processing/benches/bench_block_processing.rs
  eth2/state_processing/benches/bench_epoch_processing.rs
  eth2/state_processing/benches/benches.rs
  eth2/state_processing/benches/block_benching_builder.rs
  eth2/utils/cached_tree_hash/Cargo.toml
  eth2/utils/cached_tree_hash/benches/benches.rs
Labels: ready-for-review

#461 add logging functionality for aligning key value pairs after message
  Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/src/main.rs
  eth2/utils/logging/Cargo.toml
  eth2/utils/logging/src/lib.rs
  validator_client/Cargo.toml
  validator_client/src/main.rs
Labels: ready-for-review

#474 Add `cargo fmt` to .travis.yml
  .travis.yml
  eth2/utils/logging/src/lib.rs
Labels: ready-for-review

#399 First RESTful HTTP API
  Cargo.toml
  beacon_node/client/Cargo.toml
  beacon_node/client/src/config.rs
  beacon_node/client/src/lib.rs
  beacon_node/rest_api/Cargo.toml
  beacon_node/rest_api/src/beacon_node.rs
  beacon_node/rest_api/src/config.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/macros.rs
  beacon_node/src/main.rs
Labels: ready-for-review, task, val-client

#476 Change gitter link to discord
  README.md
Labels: ready-to-merge

#477 Delete stray RocksDB store implementation
  beacon_node/store/src/disk_db.rs
  beacon_node/store/src/store.rs
Labels: ready-to-merge
