Repository sigp/lighthouse, pull requests merged in 2019-12, with the labels that each got.

#655 Add discv5 corrections
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/discovery.rs
Labels: ready-to-merge

#662 Allow multiple proposals per validator per epoch
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
  validator_client/src/duties_service.rs
Labels: ready-to-merge

#665 Implements a timeout for peer banning
  account_manager/Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/eth1/Cargo.toml
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/genesis/Cargo.toml
  beacon_node/network/Cargo.toml
  beacon_node/network/src/service.rs
  lighthouse/Cargo.toml
  lighthouse/environment/Cargo.toml
  tests/eth1_test_rig/Cargo.toml
  validator_client/Cargo.toml
Labels: ready-for-review

#649 Improve freezer DB efficiency with periodic restore points
  beacon_node/beacon_chain/tests/persistence_tests.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/lib.rs
  eth2/types/src/beacon_state.rs
Labels: ready-for-review

#671 Faster BeaconState enc/dec
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/benches/benches.rs
  beacon_node/store/examples/ssz_encode_state.rs
  beacon_node/store/src/impls/beacon_state.rs
  beacon_node/store/src/lib.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/signature_sets.rs
  eth2/state_processing/src/per_block_processing/verify_deposit.rs
  eth2/types/Cargo.toml
  eth2/types/benches/benches.rs
  eth2/types/examples/ssz_encode_state.rs
  eth2/types/src/beacon_state.rs
  eth2/types/src/beacon_state/pubkey_cache.rs
  eth2/types/src/test_utils/builders/testing_beacon_state_builder.rs
  eth2/types/src/validator.rs
  eth2/utils/bls/src/lib.rs
  eth2/utils/bls/src/macros.rs
  eth2/utils/bls/src/signature_set.rs
  eth2/utils/remote_beacon_node/src/lib.rs
  validator_client/src/attestation_service.rs
  validator_client/src/duties_service.rs
Labels: ready-to-merge

#660 Improve beacon node logging
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/lib.rs
  beacon_node/client/src/notifier.rs
  beacon_node/rest_api/src/config.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/router.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/src/lib.rs
  beacon_node/websocket_server/src/config.rs
  tests/node_test_rig/src/lib.rs
Labels: waiting-on-author

#672 Forwards block root iterators
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/persistence_tests.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/src/lib.rs
  beacon_node/store/src/block_at_slot.rs
  beacon_node/store/src/chunked_iter.rs
  beacon_node/store/src/chunked_vector.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/impls/beacon_state.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  beacon_node/store/src/migrate.rs
  beacon_node/store/src/partial_beacon_state.rs
  eth2/lmd_ghost/src/lib.rs
  eth2/lmd_ghost/src/reduced_tree.rs
  eth2/lmd_ghost/tests/test.rs
Labels: ready-for-review

#675 Remove a dbg! and println!
  beacon_node/store/src/hot_cold_store.rs
Labels: ready-to-merge

#678 Add decimals display to notifier sync speed
  beacon_node/client/src/notifier.rs
Labels: ready-for-review

#676 Add timeout when notifier waits for libp2p lock
  beacon_node/client/src/notifier.rs
Labels: ready-for-review

#677 Add block/state caching on beacon chain
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/checkpoint_cache.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/store/src/impls/beacon_state.rs
  eth2/types/benches/benches.rs
  eth2/types/src/beacon_state.rs
Labels: work-in-progress

#674 Fix issues when starting with mainnet spec
  beacon_node/src/config.rs
  eth2/types/src/chain_spec.rs
  lcli/src/deploy_deposit_contract.rs
  lcli/src/main.rs
  lcli/src/parse_hex.rs
  lcli/src/pycli.rs
  lcli/src/transition_blocks.rs
  lighthouse/src/main.rs
Labels: ready-for-review

#657 Add test for when skip slots remove all active validators
  beacon_node/beacon_chain/tests/tests.rs
Labels: ready-for-review

#684 Add Cargo.lock
  .gitignore
  Cargo.lock
Labels: ready-for-review

#697 est_time for syncing is lower than distance
  book/src/become-a-validator.md
Labels: ready-to-merge

#696 Add note about rustup update
  book/src/installation.md
Labels: ready-to-merge

#701 Hopefully fix NaN issue in sync speed
  beacon_node/client/src/notifier.rs
Labels: ready-to-merge

#712 Store states in the DB before their blocks
  beacon_node/beacon_chain/src/beacon_chain.rs
Labels: ready-to-merge

#668 Add maximum slot limit when processing blocks
  beacon_node/beacon_chain/src/beacon_chain.rs
Labels: ready-to-merge

#715 Clean up database metrics, add freezer DB size
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/client/src/builder.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/metrics.rs
  beacon_node/rest_api/src/router.rs
  beacon_node/store/src/impls/beacon_state.rs
  beacon_node/store/src/metrics.rs
Labels: ready-for-review

#721 Add logging level when using logfile
  lighthouse/environment/src/lib.rs
  lighthouse/src/main.rs
Labels: ready-for-review

#686 Create backup instead of overwriting log files
  lighthouse/environment/src/lib.rs
Labels: waiting-on-author

#723 Add simulator to CI
  .github/workflows/test-suite.yml
Labels: ready-for-review

#728 Add more eth1 metrics
  Cargo.lock
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/eth1/Cargo.toml
  beacon_node/eth1/src/lib.rs
  beacon_node/eth1/src/metrics.rs
  beacon_node/eth1/src/service.rs
Labels: ready-to-merge

#719 Delete outdated deposits handling in operation pool
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/tests/tests.rs
  eth2/operation_pool/src/lib.rs
  eth2/operation_pool/src/persistence.rs
Labels: ready-to-merge

#735 Clean cargo in dockerfile
  Dockerfile
Labels: ready-to-merge

#741 Add banner for testnet being down
  book/src/become-a-validator.md
Labels: ready-to-merge

#739 Enable bulk signature verification
  beacon_node/beacon_chain/src/beacon_chain.rs
  tests/ef_tests/src/cases/sanity_blocks.rs
Labels: ready-for-review

#702 Make API friendly to block explorers
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/rest_api/src/beacon.rs
  beacon_node/rest_api/src/consensus.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/router.rs
  beacon_node/rest_api/src/url_query.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
  book/book.toml
  book/src/SUMMARY.md
  book/src/css/custom.css
  book/src/http.md
  book/src/http_beacon.md
  book/src/http_consensus.md
  book/src/http_network.md
  book/src/http_validator.md
  eth2/state_processing/src/per_epoch_processing.rs
  eth2/types/src/beacon_state.rs
  eth2/types/src/beacon_state/committee_cache.rs
  eth2/utils/bls/src/aggregate_signature.rs
  eth2/utils/bls/src/fake_public_key.rs
  eth2/utils/bls/src/fake_signature.rs
  eth2/utils/bls/src/macros.rs
  eth2/utils/bls/src/public_key.rs
  eth2/utils/bls/src/secret_key.rs
  eth2/utils/bls/src/signature.rs
  eth2/utils/remote_beacon_node/src/lib.rs
  validator_client/src/duties_service.rs
Labels: ready-to-merge

#736 Filter gossipsub message duplication
  Cargo.lock
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/eth2-libp2p/src/topics.rs
  beacon_node/network/src/lib.rs
  beacon_node/network/src/message_handler.rs
  beacon_node/network/src/message_processor.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  beacon_node/network/src/sync/range_sync/range.rs
  beacon_node/rest_api/src/helpers.rs
Labels: ready-to-merge

#737 Adds support for the `step` parameter in BlocksByRange request
  beacon_node/network/src/message_processor.rs
Labels: ready-to-merge

#749 got Docker image down to 138mb from 1.8gb
  Dockerfile
Labels: ready-for-review

#738 Documents and simplifies syncing code
  beacon_node/eth2-libp2p/src/rpc/mod.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-review
