Repository sigp/lighthouse, pull requests merged in 2020-05, with the labels that each got.

#1047 Connect RPC to Peer Manager
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/discovery/mod.rs
  beacon_node/eth2-libp2p/src/peer_manager/client.rs
  beacon_node/eth2-libp2p/src/peer_manager/mod.rs
  beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs
  beacon_node/eth2-libp2p/src/rpc/codec/base.rs
  beacon_node/eth2-libp2p/src/rpc/codec/mod.rs
  beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2-libp2p/src/rpc/codec/ssz_snappy.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/eth2-libp2p/src/rpc/methods.rs
  beacon_node/eth2-libp2p/src/rpc/mod.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/tests/rpc_tests.rs
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/router/processor.rs
Labels: ready-for-review

#1015 Dns discovery
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
Labels: ready-for-review

#1097 Fix typo in lcli new-testnet
  lcli/src/new_testnet.rs
Labels: low-hanging-fruit, ready-to-squerge

#1095 Add skip-slots command to lcli
  lcli/src/main.rs
  lcli/src/skip_slots.rs
  lcli/src/transition_blocks.rs
Labels: ready-to-squerge

#1094 Add note about building from testnet5
  book/src/become-a-validator.md
Labels: docs, low-hanging-fruit, ready-to-squerge

#1099 Delete macros.rs
  eth2/utils/ssz/src/macros.rs
Labels: code-quality, under-review

#1108 Use schlesi as default testnet
  Cargo.lock
  eth2/utils/eth2_testnet_config/.gitignore
  eth2/utils/eth2_testnet_config/build.rs
  eth2/utils/eth2_testnet_config/src/lib.rs
  lighthouse/Cargo.toml
  lighthouse/src/main.rs
Labels: low-hanging-fruit, ready-to-squerge

#983 Add attestation gossip pre-verification
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification/block_processing_outcome.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/naive_aggregation_pool.rs
  beacon_node/beacon_chain/src/observed_attestations.rs
  beacon_node/beacon_chain/src/observed_attesters.rs
  beacon_node/beacon_chain/src/observed_block_producers.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/validator_pubkey_cache.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/attestation_tests.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
  eth2/state_processing/src/per_block_processing/block_signature_verifier.rs
  eth2/state_processing/src/per_block_processing/signature_sets.rs
  eth2/state_processing/src/per_block_processing/tests.rs
  eth2/types/src/aggregate_and_proof.rs
  eth2/types/src/selection_proof.rs
  eth2/types/src/signed_aggregate_and_proof.rs
  eth2/types/src/signed_beacon_block.rs
  tests/ef_tests/src/cases/bls_sign_msg.rs
  validator_client/src/attestation_service.rs
  validator_client/src/duties_service.rs
  validator_client/src/validator_store.rs
Labels: consensus, may-sec-review, ready-to-squerge

#1121 Port account_manager to stable futures
  account_manager/Cargo.toml
  account_manager/src/deposits.rs
  account_manager/src/lib.rs
  validator_client/src/validator_directory.rs
Labels: work-in-progress

#1123 Allow for generating block/pre/post states from some unit tests
  .github/workflows/test-suite.yml
  Cargo.lock
  Cargo.toml
  Makefile
  eth2/state_processing/src/per_block_processing/tests.rs
  eth2/state_processing/src/per_block_processing/tests/exit.rs
  eth2/state_processing/src/test_utils.rs
  tests/state_transition_vectors/.gitignore
  tests/state_transition_vectors/Cargo.toml
  tests/state_transition_vectors/Makefile
  tests/state_transition_vectors/README.md
  tests/state_transition_vectors/src/exit.rs
  tests/state_transition_vectors/src/macros.rs
  tests/state_transition_vectors/src/main.rs
Labels: may-sec-review, ready-for-review

#1110 Fix parallelism bug in exit processing
  .github/workflows/test-suite.yml
  Cargo.lock
  Cargo.toml
  Makefile
  beacon_node/beacon_chain/tests/store_tests.rs
  eth2/operation_pool/src/lib.rs
  eth2/state_processing/src/common/mod.rs
  eth2/state_processing/src/common/slash_validator.rs
  eth2/state_processing/src/macros.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/block_processing_builder.rs
  eth2/state_processing/src/per_block_processing/tests.rs
  eth2/state_processing/src/per_block_processing/verify_attester_slashing.rs
  eth2/state_processing/src/per_epoch_processing/process_slashings.rs
  eth2/state_processing/src/test_utils.rs
  eth2/types/src/slot_epoch.rs
  eth2/types/src/test_utils/builders/testing_attestation_data_builder.rs
  eth2/types/src/test_utils/builders/testing_beacon_block_builder.rs
  eth2/types/src/test_utils/builders/testing_beacon_state_builder.rs
  eth2/utils/bls/src/signature_set.rs
  tests/state_transition_vectors/.gitignore
  tests/state_transition_vectors/Cargo.toml
  tests/state_transition_vectors/Makefile
  tests/state_transition_vectors/README.md
  tests/state_transition_vectors/src/exit.rs
  tests/state_transition_vectors/src/macros.rs
  tests/state_transition_vectors/src/main.rs
Labels: may-sec-review, ready-for-review

#1070 Attestation service test suite
  Cargo.lock
  beacon_node/network/Cargo.toml
  beacon_node/network/src/attestation_service/mod.rs
Labels: ready-for-review

#1125 Stop eth1 from always enabling
  beacon_node/src/cli.rs
Labels: bug, low-hanging-fruit, ready-to-squerge

#1071 EIP-2335: Keystore
  Cargo.lock
  Cargo.toml
  eth2/utils/eth2_keystore/Cargo.toml
  eth2/utils/eth2_keystore/src/derived_key.rs
  eth2/utils/eth2_keystore/src/json_keystore/checksum_module.rs
  eth2/utils/eth2_keystore/src/json_keystore/cipher_module.rs
  eth2/utils/eth2_keystore/src/json_keystore/hex_bytes.rs
  eth2/utils/eth2_keystore/src/json_keystore/kdf_module.rs
  eth2/utils/eth2_keystore/src/json_keystore/mod.rs
  eth2/utils/eth2_keystore/src/keystore.rs
  eth2/utils/eth2_keystore/src/lib.rs
  eth2/utils/eth2_keystore/src/plain_text.rs
  eth2/utils/eth2_keystore/tests/eip2335_vectors.rs
  eth2/utils/eth2_keystore/tests/json.rs
  eth2/utils/eth2_keystore/tests/params.rs
  eth2/utils/eth2_keystore/tests/tests.rs
Labels: may-sec-review, ready-for-review

#1104 EIP-2333: Key derivation
  Cargo.lock
  Cargo.toml
  eth2/utils/eth2_key_derivation/Cargo.toml
  eth2/utils/eth2_key_derivation/src/derived_key.rs
  eth2/utils/eth2_key_derivation/src/lamport_secret_key.rs
  eth2/utils/eth2_key_derivation/src/lib.rs
  eth2/utils/eth2_key_derivation/src/secret_bytes.rs
  eth2/utils/eth2_key_derivation/src/secret_hash.rs
  eth2/utils/eth2_key_derivation/tests/eip2333_vectors.rs
  eth2/utils/eth2_key_derivation/tests/tests.rs
Labels: may-sec-review, ready-for-review

#1117 EIP-2386 (draft): Eth2 wallet
  Cargo.lock
  Cargo.toml
  eth2/utils/eth2_key_derivation/src/path.rs
  eth2/utils/eth2_keystore/src/keystore.rs
  eth2/utils/eth2_keystore/src/lib.rs
  eth2/utils/eth2_wallet/Cargo.toml
  eth2/utils/eth2_wallet/src/json_wallet/mod.rs
  eth2/utils/eth2_wallet/src/lib.rs
  eth2/utils/eth2_wallet/src/validator_path.rs
  eth2/utils/eth2_wallet/src/wallet.rs
  eth2/utils/eth2_wallet/tests/eip2386_vectors.rs
  eth2/utils/eth2_wallet/tests/json.rs
  eth2/utils/eth2_wallet/tests/tests.rs
Labels: may-sec-review, ready-for-review

#1129 Move docs over to Schelsi
  account_manager/src/cli.rs
  book/src/become-a-validator-source.md
  book/src/become-a-validator.md
  book/src/js/deposit.js
Labels: low-hanging-fruit, ready-to-squerge

#1134 Switch to ring for hkdf
  Cargo.lock
  eth2/utils/eth2_key_derivation/Cargo.toml
  eth2/utils/eth2_key_derivation/src/derived_key.rs
  eth2/utils/eth2_keystore/tests/eip2335_vectors.rs
  eth2/utils/eth2_keystore/tests/json.rs
  eth2/utils/eth2_keystore/tests/tests.rs
Labels: low-hanging-fruit, may-sec-review, ready-for-review, security

#1137 Move long-running atestation tests to release
  beacon_node/beacon_chain/src/observed_attestations.rs
Labels: low-hanging-fruit, ready-to-squerge

#1141 Move wallet tests to release only
  eth2/utils/eth2_wallet/tests/tests.rs
Labels: low-hanging-fruit, ready-for-review

#1140 Tiny improvement: assertions
  beacon_node/beacon_chain/src/naive_aggregation_pool.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/rest_api/tests/test.rs
Labels: ready-to-squerge

#1142 Stable futures: fixes to vc, eth1 and account manager
  account_manager/src/lib.rs
  beacon_node/client/src/builder.rs
  beacon_node/eth1/src/service.rs
  beacon_node/src/lib.rs
  lcli/src/deploy_deposit_contract.rs
  lcli/src/main.rs
  lighthouse/src/main.rs
  scripts/local_testnet_beacon_node.sh
  scripts/local_testnet_clean.sh
  scripts/local_testnet_setup.sh
  scripts/local_testnet_valdiator_client.sh
  scripts/whiteblock_start.sh
  validator_client/src/attestation_service.rs
  validator_client/src/block_service.rs
  validator_client/src/duties_service.rs
  validator_client/src/fork_service.rs
  validator_client/src/lib.rs
  validator_client/src/notifier.rs
Labels: ready-for-review

#1144 Fix multiple runtimes in lcli
  lcli/src/deploy_deposit_contract.rs
  lcli/src/eth1_genesis.rs
  lcli/src/main.rs
  lcli/src/refund_deposit_contract.rs
Labels: ready-for-review

#1120 removed state-cache-size flag from beacon_node/src
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/config.rs
Labels: low-hanging-fruit, ready-to-squerge

#1132 Race condition fix + Reliability improvements around forks pruning
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/head_tracker.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
Labels: ready-to-squerge

#1149 Stable futures: Vc sync
  validator_client/src/attestation_service.rs
  validator_client/src/duties_service.rs
  validator_client/src/is_synced.rs
  validator_client/src/lib.rs
  validator_client/src/notifier.rs
Labels: may-sec-review, ready-for-review

#1151 Stable futures: Fix VC bug, update agg pool, add more metrics
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/naive_aggregation_pool.rs
  beacon_node/beacon_chain/src/observed_attesters.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/lib.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/service.rs
  eth2/state_processing/src/per_epoch_processing.rs
  eth2/state_processing/src/per_slot_processing.rs
  eth2/utils/lighthouse_metrics/src/lib.rs
  tests/ef_tests/src/cases/sanity_slots.rs
  validator_client/src/duties_service.rs
Labels: consensus, may-sec-review, ready-for-review

#1091 Cleanup `ExitCache`
  eth2/types/src/beacon_state/exit_cache.rs
Labels: consensus, ready-to-squerge

#1155 v0.1.2
  Cargo.lock
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/client/Cargo.toml
  beacon_node/eth1/Cargo.toml
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/genesis/Cargo.toml
  beacon_node/network/Cargo.toml
  beacon_node/rest_api/Cargo.toml
  beacon_node/store/Cargo.toml
  beacon_node/timer/Cargo.toml
  beacon_node/version/Cargo.toml
  beacon_node/websocket_server/Cargo.toml
  book/src/become-a-validator-source.md
  book/src/installation.md
  lighthouse/Cargo.toml
  lighthouse/environment/Cargo.toml
  validator_client/Cargo.toml
Labels: ready-for-review

#1116 Implement Slashing Protection
  Cargo.lock
  Cargo.toml
  book/src/become-a-validator-source.md
  book/src/local-testnets.md
  eth2/types/Cargo.toml
  eth2/types/src/lib.rs
  eth2/types/src/sqlite.rs
  eth2/utils/bls/src/fake_public_key.rs
  eth2/utils/bls/src/public_key.rs
  tests/node_test_rig/src/lib.rs
  tests/simulator/src/eth1_sim.rs
  tests/simulator/src/no_eth1_sim.rs
  validator_client/Cargo.toml
  validator_client/slashing_protection/Cargo.toml
  validator_client/slashing_protection/src/attestation_tests.rs
  validator_client/slashing_protection/src/block_tests.rs
  validator_client/slashing_protection/src/lib.rs
  validator_client/slashing_protection/src/parallel_tests.rs
  validator_client/slashing_protection/src/signed_attestation.rs
  validator_client/slashing_protection/src/signed_block.rs
  validator_client/slashing_protection/src/slashing_database.rs
  validator_client/slashing_protection/src/test_utils.rs
  validator_client/src/attestation_service.rs
  validator_client/src/block_service.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/duties_service.rs
  validator_client/src/lib.rs
  validator_client/src/validator_directory.rs
  validator_client/src/validator_store.rs
Labels: may-sec-review, ready-to-squerge, security, val-client

#1138 Wallet-based, encrypted key management
  .github/workflows/test-suite.yml
  Cargo.lock
  Cargo.toml
  account_manager/Cargo.toml
  account_manager/src/cli.rs
  account_manager/src/common.rs
  account_manager/src/deposits.rs
  account_manager/src/lib.rs
  account_manager/src/upgrade_legacy_keypairs.rs
  account_manager/src/validator/create.rs
  account_manager/src/validator/deposit.rs
  account_manager/src/validator/mod.rs
  account_manager/src/wallet/create.rs
  account_manager/src/wallet/list.rs
  account_manager/src/wallet/mod.rs
  beacon_node/rest_api/src/validator.rs
  book/src/SUMMARY.md
  book/src/become-a-validator-source.md
  book/src/key-managment.md
  book/src/validator-create.md
  book/src/wallet-create.md
  eth2/utils/eth2_keystore/src/keystore.rs
  eth2/utils/eth2_wallet/src/lib.rs
  eth2/utils/eth2_wallet/src/wallet.rs
  eth2/utils/eth2_wallet_manager/Cargo.toml
  eth2/utils/eth2_wallet_manager/src/filesystem.rs
  eth2/utils/eth2_wallet_manager/src/lib.rs
  eth2/utils/eth2_wallet_manager/src/locked_wallet.rs
  eth2/utils/eth2_wallet_manager/src/wallet_manager.rs
  eth2/utils/validator_dir/Cargo.toml
  eth2/utils/validator_dir/src/builder.rs
  eth2/utils/validator_dir/src/insecure_keys.rs
  eth2/utils/validator_dir/src/lib.rs
  eth2/utils/validator_dir/src/manager.rs
  eth2/utils/validator_dir/src/unencrypted_keys.rs
  eth2/utils/validator_dir/src/validator_dir.rs
  eth2/utils/validator_dir/tests/tests.rs
  lcli/Cargo.toml
  lcli/src/main.rs
  lighthouse/Cargo.toml
  lighthouse/src/main.rs
  lighthouse/tests/account_manager.rs
  tests/node_test_rig/Cargo.toml
  tests/node_test_rig/src/lib.rs
  tests/simulator/Cargo.toml
  tests/simulator/src/eth1_sim.rs
  tests/simulator/src/local_network.rs
  tests/simulator/src/no_eth1_sim.rs
  tests/simulator/src/sync_sim.rs
  validator_client/Cargo.toml
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/duties_service.rs
  validator_client/src/lib.rs
  validator_client/src/validator_store.rs
Labels: may-sec-review, ready-to-squerge

#1165 Remove duplicate code (and noisy eth1 log)
  beacon_node/eth1/src/service.rs
Labels: low-hanging-fruit, ready-to-squerge

#1164 Improve bls::SecretKey privacy
  Cargo.lock
  beacon_node/operation_pool/src/lib.rs
  common/validator_dir/Cargo.toml
  common/validator_dir/src/unencrypted_keys.rs
  common/validator_dir/tests/tests.rs
  consensus/state_processing/src/per_block_processing/block_processing_builder.rs
  consensus/state_processing/src/test_utils.rs
  consensus/tree_hash/examples/flamegraph_beacon_state.rs
  consensus/types/src/beacon_state/tests.rs
  consensus/types/src/test_utils/builders/testing_beacon_state_builder.rs
  consensus/types/src/test_utils/keypairs_file.rs
  consensus/types/src/test_utils/mod.rs
  crypto/bls/Cargo.toml
  crypto/bls/src/keypair.rs
  crypto/bls/src/lib.rs
  crypto/bls/src/plain_text.rs
  crypto/bls/src/secret_key.rs
  crypto/eth2_keystore/src/keystore.rs
  crypto/eth2_keystore/src/lib.rs
  crypto/eth2_keystore/tests/eip2335_vectors.rs
  crypto/eth2_keystore/tests/tests.rs
  crypto/eth2_wallet/Cargo.toml
  crypto/eth2_wallet/tests/tests.rs
  lcli/src/main.rs
  lighthouse/tests/account_manager.rs
  validator_client/src/validator_store.rs
Labels: may-sec-review, ready-to-merge

#1166 Fix Schlesi-splitting penalty bug
  consensus/state_processing/src/per_epoch_processing/apply_rewards.rs
  consensus/types/src/eth_spec.rs
  lcli/src/parse_hex.rs
  lcli/src/skip_slots.rs
  lcli/src/transition_blocks.rs
Labels: ready-to-squerge

#1169 Remove v0.1.2 install instructions
  book/src/become-a-validator-source.md
  book/src/installation.md
Labels: low-hanging-fruit, ready-to-squerge

#1191 Update docs to indicate that Schelsi is down
  book/src/become-a-validator.md
Labels: low-hanging-fruit, ready-for-review

#1188 Avoid implicit validator status assumption
  consensus/state_processing/src/per_epoch_processing/registry_updates.rs
Labels: work-in-progress

#1103 Improve genesis service
  Cargo.lock
  beacon_node/client/Cargo.toml
  beacon_node/client/src/notifier.rs
  beacon_node/eth1/src/service.rs
  beacon_node/genesis/src/eth1_genesis_service.rs
  beacon_node/genesis/src/lib.rs
Labels: ready-for-review

#1122 Custom net behaviour
  beacon_node/eth2-libp2p/src/behaviour/handler/delegate.rs
  beacon_node/eth2-libp2p/src/behaviour/handler/mod.rs
  beacon_node/eth2-libp2p/src/behaviour/mod.rs
Labels: work-in-progress

#1195 Update rusqlite to safer v0.23
  Cargo.lock
  consensus/types/Cargo.toml
  validator_client/slashing_protection/Cargo.toml
Labels: ready-to-squerge

#1193 Integrate Witti testnet
  Cargo.lock
  book/src/become-a-validator.md
  book/src/js/deposit.js
  common/eth2_testnet_config/.gitignore
  common/eth2_testnet_config/build.rs
  common/eth2_testnet_config/src/lib.rs
  common/validator_dir/Cargo.toml
  common/validator_dir/src/builder.rs
  common/validator_dir/src/validator_dir.rs
  common/validator_dir/tests/tests.rs
  validator_client/src/lib.rs
Labels: ready-to-squerge

#1196 Drop runtime after task completion
  lighthouse/src/main.rs
Labels: ready-to-squerge

#1192 Add cargo audit to CI
  .github/workflows/test-suite.yml
  Makefile
Labels: security

#1184 Update local testnet scripts, fix eth1 sim
  .github/workflows/test-suite.yml
  Cargo.lock
  book/src/local-testnets.md
  book/src/simple-testnet.md
  common/validator_dir/Cargo.toml
  common/validator_dir/src/builder.rs
  common/validator_dir/src/insecure_keys.rs
  common/validator_dir/src/manager.rs
  common/validator_dir/tests/tests.rs
  crypto/eth2_keystore/src/keystore.rs
  crypto/eth2_keystore/tests/tests.rs
  lcli/Cargo.toml
  lcli/src/insecure_validators.rs
  lcli/src/main.rs
  scripts/local_testnet/README.md
  scripts/local_testnet/beacon_node.sh
  scripts/local_testnet/clean.sh
  scripts/local_testnet/reset_genesis_time.sh
  scripts/local_testnet/second_beacon_node.sh
  scripts/local_testnet/setup.sh
  scripts/local_testnet/validator_client.sh
  scripts/local_testnet/vars.env
  scripts/local_testnet_clean.sh
  testing/simulator/src/eth1_sim.rs
  validator_client/src/validator_store.rs
Labels: crypto, ready-to-merge

#1201 Allow discovery to be more lenient in enr eth2 fields
  Cargo.lock
  account_manager/Cargo.toml
  beacon_node/eth1/Cargo.toml
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/discovery/mod.rs
  lcli/Cargo.toml
  testing/eth1_test_rig/Cargo.toml
  validator_client/Cargo.toml
Labels: ready-for-review

#1198 Revert runtime drop
  lighthouse/environment/src/lib.rs
  lighthouse/src/main.rs
Labels: ready-for-review

#1207 Upgrade docker rust version
  Dockerfile
Labels: ready-for-review

#1197 Add /node/health endpoint
  beacon_node/rest_api/src/metrics.rs
  beacon_node/rest_api/src/node.rs
  beacon_node/rest_api/src/router.rs
  beacon_node/rest_api/tests/test.rs
  book/src/http/node.md
  common/remote_beacon_node/src/lib.rs
  common/rest_types/Cargo.toml
  common/rest_types/src/lib.rs
  common/rest_types/src/node.rs
Labels: low-hanging-fruit, ready-to-squerge

#1199 Strip off newline chars from password
  account_manager/src/common.rs
  account_manager/src/wallet/create.rs
Labels: crypto, ready-to-squerge

#1210 Fix eval-order clippy lint
  consensus/ssz_derive/src/lib.rs
Labels: low-hanging-fruit, ready-to-squerge

#1220 Update the RPC handler's keep alive logic
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/eth2-libp2p/src/rpc/mod.rs
Labels: ready-to-merge

#1183 Update `milagro_bls` to new release
  Cargo.lock
  common/eth2_interop_keypairs/Cargo.toml
  common/eth2_interop_keypairs/tests/generation.rs
  crypto/bls/Cargo.toml
  crypto/bls/src/aggregate_public_key.rs
  crypto/bls/src/aggregate_signature.rs
  crypto/bls/src/fake_aggregate_public_key.rs
  crypto/bls/src/fake_aggregate_signature.rs
  crypto/bls/src/fake_public_key.rs
  crypto/bls/src/fake_signature.rs
  crypto/bls/src/lib.rs
  crypto/bls/src/macros.rs
  crypto/bls/src/public_key.rs
  crypto/bls/src/secret_hash.rs
  crypto/bls/src/secret_key.rs
  crypto/bls/src/signature.rs
  crypto/eth2_key_derivation/Cargo.toml
  crypto/eth2_key_derivation/src/derived_key.rs
  crypto/eth2_key_derivation/src/lib.rs
  crypto/eth2_key_derivation/src/plain_text.rs
  crypto/eth2_keystore/Cargo.toml
  crypto/eth2_keystore/src/keystore.rs
  crypto/eth2_keystore/src/lib.rs
  lighthouse/tests/account_manager.rs
  testing/ef_tests/src/cases/bls_aggregate_sigs.rs
  testing/ef_tests/src/cases/bls_sign_msg.rs
Labels: spec_change
