Repository sigp/lighthouse, pull requests merged in 2020-06, with the labels that each got.

#1226 Doc updates
  book/src/SUMMARY.md
  book/src/http/node.md
  book/src/http_advanced.md
  book/src/http_beacon.md
  book/src/http_consensus.md
  book/src/http_network.md
  book/src/http_spec.md
  book/src/http_validator.md
  book/src/key-managment.md
  book/src/validator-create.md
Labels: ready-for-review

#1235 Update docs to suit sigp/docker-compose updates
  book/src/become-a-validator-docker.md
  common/validator_dir/src/manager.rs
Labels: low-hanging-fruit, ready-to-squerge

#1228 Consensus updates for v0.12
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/src/config.rs
  book/src/http/spec.md
  common/clap_utils/src/lib.rs
  common/eth2_testnet_config/src/lib.rs
  consensus/state_processing/benches/benches.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_block_processing/is_valid_indexed_attestation.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
  consensus/state_processing/src/per_block_processing/verify_attestation.rs
  consensus/state_processing/src/per_block_processing/verify_exit.rs
  consensus/state_processing/src/per_epoch_processing/apply_rewards.rs
  consensus/state_processing/tests/tests.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/lib.rs
  consensus/types/src/signed_beacon_block.rs
  consensus/types/src/signing_data.rs
  lighthouse/environment/src/lib.rs
  lighthouse/environment/tests/environment_builder.rs
  lighthouse/environment/tests/minimal_spec/eth2-spec.toml
  lighthouse/src/main.rs
  testing/ef_tests/Makefile
  testing/ef_tests/src/cases/bls_aggregate_sigs.rs
  testing/ef_tests/src/cases/bls_aggregate_verify.rs
  testing/ef_tests/src/cases/operations.rs
  testing/ef_tests/tests/tests.rs
  testing/state_transition_vectors/src/exit.rs
Labels: ready-to-squerge, spec_change

#1181 Improve tokio task execution
  Cargo.lock
  account_manager/Cargo.toml
  account_manager/src/validator/deposit.rs
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/client/src/lib.rs
  beacon_node/client/src/notifier.rs
  beacon_node/eth1/Cargo.toml
  beacon_node/eth1/src/service.rs
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/eth2-libp2p/tests/common/mod.rs
  beacon_node/eth2-libp2p/tests/noise.rs
  beacon_node/genesis/Cargo.toml
  beacon_node/genesis/tests/tests.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/service/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/rest_api/Cargo.toml
  beacon_node/rest_api/src/lib.rs
  beacon_node/src/lib.rs
  beacon_node/tests/test.rs
  beacon_node/timer/Cargo.toml
  beacon_node/timer/src/lib.rs
  beacon_node/websocket_server/Cargo.toml
  beacon_node/websocket_server/src/lib.rs
  common/eth2_testnet_config/Cargo.toml
  common/eth2_testnet_config/src/lib.rs
  common/hashset_delay/Cargo.toml
  common/lighthouse_metrics/src/lib.rs
  lcli/Cargo.toml
  lcli/src/eth1_genesis.rs
  lighthouse/Cargo.toml
  lighthouse/environment/Cargo.toml
  lighthouse/environment/src/executor.rs
  lighthouse/environment/src/lib.rs
  lighthouse/environment/src/metrics.rs
  lighthouse/src/main.rs
  testing/eth1_test_rig/Cargo.toml
  testing/simulator/Cargo.toml
  validator_client/Cargo.toml
  validator_client/src/attestation_service.rs
  validator_client/src/block_service.rs
  validator_client/src/duties_service.rs
  validator_client/src/fork_service.rs
  validator_client/src/lib.rs
  validator_client/src/notifier.rs
Labels: ready-for-review

#1236 Attestation gossip verification v0.12
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
Labels: ready-for-review

#1107 Add first Server Sent Events API endpoint
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/events.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/rest_api/Cargo.toml
  beacon_node/rest_api/src/beacon.rs
  beacon_node/rest_api/src/error.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/router.rs
  beacon_node/src/lib.rs
Labels: ready-to-squerge

#1211 Deposit functionality now works with IPC & RPC
  account_manager/src/validator/deposit.rs
Labels: ready-for-review

#1241 beacon_node, consensus: fix possible deadlocks when comparing with itself
  beacon_node/operation_pool/src/lib.rs
  consensus/proto_array_fork_choice/src/proto_array_fork_choice.rs
Labels: bug, ready-for-review

#1247 Cleanup logs, increase test timeouts, remove gossipsub tests
  beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs
  beacon_node/eth2-libp2p/tests/gossipsub_tests.rs
  beacon_node/eth2-libp2p/tests/rpc_tests.rs
Labels: ready-for-review

#1243 Add error handling to iterators
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/router/processor.rs
  beacon_node/rest_api/Cargo.toml
  beacon_node/rest_api/src/helpers.rs
  beacon_node/rest_api/tests/test.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
Labels: ready-to-squerge

#1252 Add raspberry pi docs
  book/src/SUMMARY.md
  book/src/installation.md
  book/src/pi.md
Labels: low-hanging-fruit, ready-to-squerge

#1259 Update v0.12.0 to v0.12.1
  beacon_node/genesis/src/eth1_genesis_service.rs
  book/src/http/spec.md
  consensus/state_processing/src/genesis.rs
  consensus/types/src/chain_spec.rs
  lcli/src/main.rs
  lcli/src/new_testnet.rs
  lighthouse/environment/tests/minimal_spec/eth2-spec.toml
  lighthouse/environment/tests/testnet_dir/config.yaml
  testing/ef_tests/Makefile
  testing/simulator/src/eth1_sim.rs
  testing/simulator/src/no_eth1_sim.rs
  testing/simulator/src/sync_sim.rs
Labels: ready-to-squerge

#1258 Handle syncing edge case
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/peer_sync_info.rs
Labels: ready-for-review

#1244 Use SSZ types in rpc
  Cargo.lock
  beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2-libp2p/src/rpc/codec/ssz_snappy.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/eth2-libp2p/src/rpc/methods.rs
  beacon_node/eth2-libp2p/src/rpc/mod.rs
  beacon_node/eth2-libp2p/tests/rpc_tests.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/mod.rs
Labels: waiting-on-author

#1261 Increase RPC test timeouts
  beacon_node/eth2-libp2p/tests/rpc_tests.rs
Labels: ready-for-review

#1230 Remove interop
  Cargo.lock
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/eth2-libp2p/src/types/pubsub.rs
  beacon_node/eth2-libp2p/src/types/topics.rs
  beacon_node/eth2-libp2p/tests/noise.rs
Labels: waiting-on-author

#1263 Update main REAMDE
  README.md
Labels: low-hanging-fruit, ready-to-squerge

#1250 Add explicit bounds for ssz decoding in rpc
  beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2-libp2p/src/rpc/codec/ssz_snappy.rs
  beacon_node/eth2-libp2p/src/rpc/methods.rs
  beacon_node/eth2-libp2p/src/rpc/mod.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
Labels: ready-to-merge

#1262 Check for unused deps in CI
  .github/workflows/test-suite.yml
  Cargo.lock
  Makefile
  account_manager/Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/network/Cargo.toml
  beacon_node/store/Cargo.toml
  common/compare_fields/Cargo.toml
  common/validator_dir/Cargo.toml
  consensus/proto_array_fork_choice/Cargo.toml
  consensus/ssz_types/Cargo.toml
  consensus/state_processing/Cargo.toml
  consensus/swap_or_not_shuffle/Cargo.toml
  consensus/types/Cargo.toml
  crypto/bls/Cargo.toml
  lcli/Cargo.toml
  lighthouse/environment/Cargo.toml
  testing/ef_tests/Cargo.toml
  validator_client/Cargo.toml
  validator_client/slashing_protection/Cargo.toml
Labels: ready-to-squerge

#1268 Avoid pruning when there are no forks
  beacon_node/beacon_chain/src/migrate.rs
Labels: ready-to-squerge

#1267 Make key value storage abstractions more accurate
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/persistence_tests.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/network/src/attestation_service/tests/mod.rs
  beacon_node/network/src/persisted_dht.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/service/tests.rs
  beacon_node/rest_api/src/beacon.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/src/lib.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/chunked_iter.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  beacon_node/store/src/state_batch.rs
Labels: ready-to-squerge

#1229 v0.12 fork choice update
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/beacon_fork_choice_store.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/fork_choice/checkpoint_manager.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/persisted_fork_choice.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/beacon_chain/tests/persistence_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/network/src/attestation_service/tests/mod.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  beacon_node/network/src/sync/range_sync/sync_type.rs
  beacon_node/rest_api/src/advanced.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
  beacon_node/store/Cargo.toml
  common/remote_beacon_node/Cargo.toml
  common/remote_beacon_node/src/lib.rs
  common/slot_clock/src/lib.rs
  common/slot_clock/src/manual_slot_clock.rs
  common/slot_clock/src/system_time_slot_clock.rs
  consensus/fork_choice/Cargo.toml
  consensus/fork_choice/src/fork_choice.rs
  consensus/fork_choice/src/fork_choice_store.rs
  consensus/fork_choice/src/lib.rs
  consensus/fork_choice/tests/tests.rs
  consensus/proto_array/.gitignore
  consensus/proto_array/Cargo.toml
  consensus/proto_array/src/bin.rs
  consensus/proto_array/src/error.rs
  consensus/proto_array/src/fork_choice_test_definition.rs
  consensus/proto_array/src/fork_choice_test_definition/ffg_updates.rs
  consensus/proto_array/src/fork_choice_test_definition/no_votes.rs
  consensus/proto_array/src/fork_choice_test_definition/votes.rs
  consensus/proto_array/src/lib.rs
  consensus/proto_array/src/proto_array.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/proto_array/src/ssz_container.rs
  consensus/types/src/checkpoint.rs
Labels: consensus, ready-for-review, spec_change

#1251 Make all features explicit
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/rest_api/Cargo.toml
Labels: ready-to-squerge

#1257 Use all attestation subnets
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/eth2-libp2p/src/types/pubsub.rs
  beacon_node/eth2-libp2p/src/types/topics.rs
  beacon_node/network/src/attestation_service/mod.rs
  beacon_node/network/src/attestation_service/tests/mod.rs
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/service.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
  common/remote_beacon_node/src/lib.rs
  common/rest_types/src/validator.rs
  consensus/fork_choice/tests/tests.rs
  consensus/types/src/attestation.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/subnet_id.rs
  validator_client/src/attestation_service.rs
  validator_client/src/duties_service.rs
Labels: consensus, ready-for-review

#1253 Process exits and slashings off the network
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/observed_operations.rs
  beacon_node/beacon_chain/tests/op_verification.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/eth2-libp2p/src/types/pubsub.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/operation_pool/src/persistence.rs
  beacon_node/rest_api/src/beacon.rs
  beacon_node/rest_api/tests/test.rs
  consensus/ssz_types/src/variable_list.rs
  consensus/state_processing/src/lib.rs
  consensus/state_processing/src/verify_operation.rs
  consensus/types/Cargo.toml
  consensus/types/src/attester_slashing.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/fork.rs
  consensus/types/src/indexed_attestation.rs
  consensus/types/src/lib.rs
  consensus/types/src/test_utils/builders/testing_attester_slashing_builder.rs
Labels: consensus, ready-to-squerge

#1274 Silky smooth discovery
  Cargo.lock
  Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/client/Cargo.toml
  beacon_node/eth2-libp2p/src/discovery/mod.rs
  beacon_node/eth2_libp2p/Cargo.toml
  beacon_node/eth2_libp2p/src/behaviour/handler/delegate.rs
  beacon_node/eth2_libp2p/src/behaviour/handler/mod.rs
  beacon_node/eth2_libp2p/src/behaviour/mod.rs
  beacon_node/eth2_libp2p/src/config.rs
  beacon_node/eth2_libp2p/src/lib.rs
  beacon_node/eth2_libp2p/src/metrics.rs
  beacon_node/eth2_libp2p/src/peer_manager/client.rs
  beacon_node/eth2_libp2p/src/peer_manager/discovery/enr.rs
  beacon_node/eth2_libp2p/src/peer_manager/discovery/enr_ext.rs
  beacon_node/eth2_libp2p/src/peer_manager/discovery/mod.rs
  beacon_node/eth2_libp2p/src/peer_manager/discovery/subnet_predicate.rs
  beacon_node/eth2_libp2p/src/peer_manager/mod.rs
  beacon_node/eth2_libp2p/src/peer_manager/peer_info.rs
  beacon_node/eth2_libp2p/src/peer_manager/peer_sync_status.rs
  beacon_node/eth2_libp2p/src/peer_manager/peerdb.rs
  beacon_node/eth2_libp2p/src/rpc/codec/base.rs
  beacon_node/eth2_libp2p/src/rpc/codec/mod.rs
  beacon_node/eth2_libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2_libp2p/src/rpc/codec/ssz_snappy.rs
  beacon_node/eth2_libp2p/src/rpc/handler.rs
  beacon_node/eth2_libp2p/src/rpc/methods.rs
  beacon_node/eth2_libp2p/src/rpc/mod.rs
  beacon_node/eth2_libp2p/src/rpc/protocol.rs
  beacon_node/eth2_libp2p/src/service.rs
  beacon_node/eth2_libp2p/src/types/error.rs
  beacon_node/eth2_libp2p/src/types/globals.rs
  beacon_node/eth2_libp2p/src/types/mod.rs
  beacon_node/eth2_libp2p/src/types/pubsub.rs
  beacon_node/eth2_libp2p/src/types/sync_state.rs
  beacon_node/eth2_libp2p/src/types/topics.rs
  beacon_node/eth2_libp2p/tests/common/mod.rs
  beacon_node/eth2_libp2p/tests/gossipsub_tests.rs
  beacon_node/eth2_libp2p/tests/noise.rs
  beacon_node/eth2_libp2p/tests/rpc_tests.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/attestation_service/mod.rs
  beacon_node/network/src/service.rs
  beacon_node/rest_api/Cargo.toml
  beacon_node/src/lib.rs
  lcli/Cargo.toml
  lighthouse/environment/Cargo.toml
  lighthouse/environment/src/executor.rs
Labels: ready-for-review

#1276 Discovery metrics
  beacon_node/eth2_libp2p/src/config.rs
  beacon_node/eth2_libp2p/src/lib.rs
  beacon_node/eth2_libp2p/src/metrics.rs
  beacon_node/eth2_libp2p/src/peer_manager/discovery/mod.rs
  beacon_node/rest_api/src/metrics.rs
  common/lighthouse_metrics/src/lib.rs
Labels: ready-to-squerge

#1265 Lighthouse bootnode
  Cargo.lock
  Cargo.toml
  beacon_node/eth2_libp2p/src/peer_manager/discovery/enr_ext.rs
  boot_node/Cargo.toml
  boot_node/src/cli.rs
  boot_node/src/config.rs
  boot_node/src/lib.rs
  boot_node/src/server.rs
  lighthouse/Cargo.toml
  lighthouse/src/main.rs
Labels: ready-for-review

#1277 Userland clean up
  beacon_node/eth2_libp2p/src/config.rs
  beacon_node/eth2_libp2p/src/discovery/enr.rs
  beacon_node/eth2_libp2p/src/discovery/enr_ext.rs
  beacon_node/eth2_libp2p/src/discovery/mod.rs
  beacon_node/eth2_libp2p/src/discovery/subnet_predicate.rs
  beacon_node/eth2_libp2p/src/lib.rs
  beacon_node/eth2_libp2p/src/peer_manager/mod.rs
  beacon_node/eth2_libp2p/src/service.rs
  beacon_node/eth2_libp2p/tests/common/mod.rs
  beacon_node/eth2_libp2p/tests/noise.rs
  beacon_node/network/src/service.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
Labels: ready-to-squerge

#1278 Replace unreachable expect with tidier solution
  beacon_node/beacon_chain/src/beacon_chain.rs
Labels: code-quality, consensus, low-hanging-fruit, ready-to-squerge

#1279 Remove beacon-chain config file
  beacon_node/Cargo.toml
  beacon_node/src/config.rs
Labels: ready-to-squerge

#1296 Swap hasher for is_aggregator
  consensus/types/src/selection_proof.rs
Labels: consensus, ready-to-squerge

#1286 Fix clippy's performance lints
  Cargo.lock
  Makefile
  beacon_node/beacon_chain/src/observed_attesters.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/eth2_libp2p/src/behaviour/handler/delegate.rs
  beacon_node/eth2_libp2p/src/behaviour/handler/mod.rs
  beacon_node/eth2_libp2p/src/behaviour/mod.rs
  beacon_node/eth2_libp2p/src/discovery/mod.rs
  beacon_node/eth2_libp2p/src/peer_manager/mod.rs
  beacon_node/eth2_libp2p/src/rpc/handler.rs
  beacon_node/network/src/attestation_service/mod.rs
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/src/config.rs
  common/eth2_testnet_config/build.rs
  common/validator_dir/src/builder.rs
  consensus/proto_array_fork_choice/src/fork_choice_test_definition.rs
  consensus/proto_array_fork_choice/src/fork_choice_test_definition/ffg_updates.rs
  consensus/proto_array_fork_choice/src/fork_choice_test_definition/no_votes.rs
  consensus/proto_array_fork_choice/src/fork_choice_test_definition/votes.rs
  consensus/types/src/beacon_block.rs
  crypto/eth2_keystore/src/keystore.rs
  lighthouse/environment/src/lib.rs
  validator_client/src/duties_service.rs
Labels: low-hanging-fruit, ready-to-squerge

#1295 Bake in Altona (without genesis state)
  common/eth2_testnet_config/.gitignore
  common/eth2_testnet_config/build.rs
  common/eth2_testnet_config/src/lib.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
Labels: ready-to-squerge

#1299 Decrypt keys earlier in VC lifecycle
  validator_client/src/lib.rs
  validator_client/src/validator_store.rs
Labels: ready-to-squerge

#1298 Cache deposit signature verification
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/client/src/builder.rs
  beacon_node/eth1/src/deposit_cache.rs
  beacon_node/eth1/src/deposit_log.rs
  beacon_node/eth1/src/inner.rs
  beacon_node/eth1/src/service.rs
  beacon_node/eth1/tests/test.rs
  beacon_node/genesis/src/eth1_genesis_service.rs
  beacon_node/genesis/tests/tests.rs
  lcli/src/eth1_genesis.rs
Labels: ready-to-squerge

#1301 Add Altona bootnodes
  common/eth2_testnet_config/build.rs
Labels: ready-for-review

#1305 Add waker to attestation service
  beacon_node/network/src/attestation_service/mod.rs
Labels: ready-for-review

#1294 fix(eth1/service): use self instead of Service
  beacon_node/eth1/src/service.rs
  beacon_node/eth1/tests/test.rs
  beacon_node/genesis/src/eth1_genesis_service.rs
Labels: code-quality, ready-for-review

#1310 Add more Altona boot ENR
  common/eth2_testnet_config/build.rs
  common/eth2_testnet_config/src/lib.rs
Labels: low-hanging-fruit, ready-for-review

#1300 get_active_validator_indices() now has bound check
  beacon_node/genesis/src/eth1_genesis_service.rs
  consensus/state_processing/src/genesis.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/tests.rs
Labels: ready-to-squerge

#1314 Loosen VC lockfile and slashing protection registers
  common/validator_dir/src/manager.rs
  common/validator_dir/src/validator_dir.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/lib.rs
Labels: ready-for-review

#1306 Fix a retry limit condition
  beacon_node/eth2_libp2p/src/discovery/mod.rs
Labels: ready-for-review
