Repository sigp/lighthouse, pull requests merged in 2020-03, with the labels that each got.

#873 Add support for noise protocol
  Cargo.lock
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/eth2-libp2p/tests/common/mod.rs
  beacon_node/eth2-libp2p/tests/noise.rs
Labels: ready-for-review

#872 Correct typo
  tests/eth1_test_rig/src/ganache.rs
Labels: ready-to-squerge

#862 Attempt to remove a tree hash from block replaying
  beacon_node/store/src/hot_cold_store.rs
Labels: ready-to-squerge

#865 Add optimized SSZ decoding for fixed-len items
  Cargo.lock
  eth2/utils/ssz/Cargo.toml
  eth2/utils/ssz/src/decode.rs
  eth2/utils/ssz/src/encode.rs
  eth2/utils/ssz/src/encode/impls.rs
  eth2/utils/ssz_derive/src/lib.rs
Labels: ready-to-squerge

#853 Add "new-testnet" command to lcli
  Dockerfile
  lcli/src/deploy_deposit_contract.rs
  lcli/src/helpers.rs
  lcli/src/main.rs
  lcli/src/new_testnet.rs
Labels: ready-to-squerge

#888 Fix incorrect error message in ClientBuilder
  beacon_node/client/src/builder.rs
Labels: under-review

#843 Add method to delete states from the database
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
Labels: ready-to-squerge

#838 Faster attestation production
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/rest_api/src/beacon.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/rest_api/src/metrics.rs
  beacon_node/rest_api/src/router.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
  beacon_node/tests/test.rs
  eth2/types/src/beacon_state.rs
Labels: ready-to-squerge

#892 Testnet5 docs
  book/src/become-a-validator-source.md
  book/src/become-a-validator.md
  book/src/http_advanced.md
  book/src/http_beacon.md
  book/src/http_validator.md
  book/src/websockets.md
Labels: ready-for-review

#893 Fix compile issue on master
  beacon_node/beacon_chain/tests/attestation_production.rs
Labels: bug

#841 Optimize attestation processing
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/shuffling_cache.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/validator_pubkey_cache.rs
  beacon_node/beacon_chain/tests/attestation_tests.rs
  beacon_node/beacon_chain/tests/persistence_tests.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/client/src/lib.rs
  beacon_node/network/src/message_processor.rs
  beacon_node/network/src/persisted_dht.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/service/tests.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  eth2/operation_pool/src/attestation.rs
  eth2/operation_pool/src/attestation_id.rs
  eth2/operation_pool/src/lib.rs
  eth2/proto_array_fork_choice/src/fork_choice_test_definition.rs
  eth2/proto_array_fork_choice/src/proto_array.rs
  eth2/proto_array_fork_choice/src/proto_array_fork_choice.rs
  eth2/state_processing/src/common/get_attesting_indices.rs
  eth2/state_processing/src/common/get_indexed_attestation.rs
  eth2/state_processing/src/lib.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/block_signature_verifier.rs
  eth2/state_processing/src/per_block_processing/signature_sets.rs
  eth2/state_processing/src/per_block_processing/verify_attestation.rs
  eth2/state_processing/src/per_epoch_processing/validator_statuses.rs
Labels: ready-to-squerge

#851 Optimise beacon chain persistence
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/persisted_beacon_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/persistence_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/store/src/lib.rs
  eth2/operation_pool/Cargo.toml
  eth2/operation_pool/src/persistence.rs
Labels: ready-to-squerge

#901 Less noisy logs for unaligned finalized blocks
  beacon_node/store/src/migrate.rs
Labels: ready-for-review

#895 Upgrade the parent lookup logic
  beacon_node/network/src/sync/manager.rs
Labels: ready-for-review

#910 Validator API book correction
  book/src/http_validator.md
Labels: ready-to-squerge

#915 Fix master failing test
  eth2/types/src/test_utils/test_random/secret_key.rs
  eth2/utils/bls/src/secret_key.rs
Labels: ready-for-review

#904 fix typo in httpnetwork doc
  book/src/http_network.md
Labels: ready-to-squerge

#925 Test corrections
  beacon_node/beacon_chain/tests/attestation_tests.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/network/src/persisted_dht.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/service/tests.rs
  eth2/operation_pool/src/lib.rs
Labels: ready-for-review

#898 Add sync-speed metric
  Cargo.lock
  beacon_node/client/Cargo.toml
  beacon_node/client/src/lib.rs
  beacon_node/client/src/metrics.rs
  beacon_node/client/src/notifier.rs
Labels: ready-to-squerge

#911 Book corrections to allow http api access for docker use
  book/src/docker.md
Labels: ready-for-review

#921 Update reward calculations to v0.11.0 - Handle u64 overflow
  eth2/state_processing/src/per_epoch_processing/apply_rewards.rs
Labels: under-review

#935 Eth2TestnetConfig: Fix incomplete build
  eth2/utils/eth2_testnet_config/build.rs
Labels: under-review

#937 Github: Add version to issue template
  .github/ISSUE_TEMPLATE.md
Labels: ready-to-squerge

#944 Fix race condition in the syncing sim
  tests/simulator/src/local_network.rs
  tests/simulator/src/sync_sim.rs
Labels: ready-to-squerge

#928 Become a Validator guides: update
  book/src/become-a-validator-docker.md
  book/src/become-a-validator-source.md
  book/src/become-a-validator.md
Labels: docs, ready-to-squerge

#952 Timing correction in the attester service
  beacon_node/network/src/attestation_service/mod.rs
Labels: ready-for-review

#951 Ensure correct path for genesis state file
  eth2/utils/eth2_testnet_config/src/lib.rs
Labels: low-hanging-fruit, ready-to-squerge

#950 Update VC and BN APIs for naive aggregation
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/naive_aggregation_pool.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_tests.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/rest_api/src/error.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/rest_api/src/url_query.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
  beacon_node/timer/src/lib.rs
  book/src/http_validator.md
  eth2/operation_pool/Cargo.toml
  eth2/operation_pool/src/lib.rs
  eth2/operation_pool/src/persistence.rs
  eth2/types/src/aggregate_and_proof.rs
  eth2/types/src/lib.rs
  eth2/types/src/signed_aggregate_and_proof.rs
  eth2/types/src/test_utils/mod.rs
  eth2/types/src/test_utils/test_random.rs
  eth2/utils/remote_beacon_node/src/lib.rs
  validator_client/src/attestation_service.rs
  validator_client/src/duties_service.rs
  validator_client/src/lib.rs
  validator_client/src/validator_store.rs
Labels: ready-for-review

#961 Connects the attestation service to network components
  Cargo.lock
  beacon_node/client/src/builder.rs
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/eth2-libp2p/src/discovery/enr_helpers.rs
  beacon_node/eth2-libp2p/src/discovery/mod.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/eth2-libp2p/src/types/topics.rs
  beacon_node/eth2-libp2p/tests/common/mod.rs
  beacon_node/eth2-libp2p/tests/noise.rs
  beacon_node/network/src/attestation_service/mod.rs
  beacon_node/network/src/attestation_service/process.rs
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/service.rs
Labels: ready-for-review

#967 Enr fork
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/fork/Cargo.toml
  beacon_node/fork/src/forks.rs
  beacon_node/fork/src/lib.rs
  beacon_node/network/src/service.rs
  eth2/types/src/chain_spec.rs
  eth2/types/src/fork_data.rs
  eth2/types/src/lib.rs
  eth2/utils/slot_clock/src/lib.rs
  eth2/utils/slot_clock/src/manual_slot_clock.rs
  eth2/utils/slot_clock/src/system_time_slot_clock.rs
Labels: ready-for-review

#960 Ensure attestations are created with empty signature
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  book/src/http_validator.md
  eth2/utils/bls/src/aggregate_signature.rs
Labels: low-hanging-fruit, ready-for-review

#969 Update /validator/subscribe
  beacon_node/rest_api/src/router.rs
  beacon_node/rest_api/src/validator.rs
  eth2/types/src/aggregate_and_proof.rs
  eth2/types/src/lib.rs
  eth2/types/src/selection_proof.rs
  eth2/utils/rest_types/src/validator.rs
  validator_client/src/attestation_service.rs
  validator_client/src/duties_service.rs
  validator_client/src/validator_store.rs
Labels: ready-for-review
