Repository sigp/lighthouse, pull requests merged in 2020-04, with the labels that each got.

#859 Fix error in /consensus/individual_votes
  beacon_node/rest_api/src/consensus.rs
  beacon_node/rest_api/src/lib.rs
  eth2/utils/remote_beacon_node/src/lib.rs
Labels: low-hanging-fruit, ready-to-squerge

#929 Allow slot clock to handle clock disparity
  Cargo.lock
  eth2/utils/slot_clock/Cargo.toml
  eth2/utils/slot_clock/src/lib.rs
  eth2/utils/slot_clock/src/manual_slot_clock.rs
  eth2/utils/slot_clock/src/system_time_slot_clock.rs
Labels: ready-to-squerge

#940 Add lcli tool for checking deposit data
  Cargo.lock
  eth2/utils/deposit_contract/Cargo.toml
  eth2/utils/deposit_contract/src/lib.rs
  lcli/Cargo.toml
  lcli/src/check_deposit_data.rs
  lcli/src/helpers.rs
  lcli/src/main.rs
  tests/eth1_test_rig/src/lib.rs
  validator_client/src/validator_directory.rs
Labels: ready-to-squerge

#941 Enable --eth1 flag when --eth1-endpoint is suppilied
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
Labels: low-hanging-fruit, ready-to-squerge

#946 Fix bug when resuming from DB prior to genesis
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
Labels: low-hanging-fruit, ready-to-squerge

#948 Don't override the fork in `lcli eth1-genesis`
  lcli/src/eth1_genesis.rs
  lcli/src/main.rs
Labels: low-hanging-fruit, ready-to-squerge

#912 Tidy Eth2Config generation at runtime
  Cargo.lock
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  lighthouse/environment/Cargo.toml
  lighthouse/environment/src/lib.rs
  lighthouse/environment/tests/environment_builder.rs
  lighthouse/environment/tests/minimal_spec/eth2-spec.toml
  lighthouse/environment/tests/testnet_dir/config.yaml
  lighthouse/src/main.rs
Labels: ready-to-squerge

#984 Add snappy encoding to gossipsub messages
  Cargo.lock
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/eth2-libp2p/src/types/pubsub.rs
  beacon_node/eth2-libp2p/src/types/topics.rs
  beacon_node/eth2-libp2p/tests/gossipsub_tests.rs
Labels: ready-for-review

#863 Add no-copy block processing cache
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/beacon_snapshot.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/fork_choice/checkpoint_manager.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/snapshot_cache.rs
  beacon_node/client/src/builder.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  beacon_node/store/src/state_batch.rs
Labels: ready-to-squerge

#982 Add FAQ section to the book
  book/src/SUMMARY.md
  book/src/become-a-validator-docker.md
  book/src/become-a-validator-source.md
  book/src/faq.md
Labels: ready-to-squerge

#849 Use global pubkey cache for block processing
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/validator_pubkey_cache.rs
  beacon_node/rest_api/src/validator.rs
  eth2/operation_pool/src/lib.rs
  eth2/state_processing/Cargo.toml
  eth2/state_processing/src/common/get_attesting_indices.rs
  eth2/state_processing/src/lib.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/block_signature_verifier.rs
  eth2/state_processing/src/per_block_processing/is_valid_indexed_attestation.rs
  eth2/state_processing/src/per_block_processing/signature_sets.rs
  eth2/state_processing/src/per_block_processing/verify_exit.rs
  eth2/state_processing/src/per_block_processing/verify_proposer_slashing.rs
  eth2/types/src/beacon_state.rs
  eth2/utils/bls/src/fake_aggregate_public_key.rs
  eth2/utils/bls/src/fake_public_key.rs
  eth2/utils/bls/src/macros.rs
  eth2/utils/bls/src/public_key.rs
  lighthouse/environment/tests/environment_builder.rs
Labels: ready-to-squerge

#977 Fix Eth1 data underflow
  eth2/state_processing/src/per_block_processing.rs
  eth2/types/src/beacon_state.rs
  eth2/types/src/beacon_state/tests.rs
Labels: ready-to-squerge

#988 Update benchmarks, add to CI
  .github/workflows/test-suite.yml
  Makefile
  eth2/state_processing/benches/benches.rs
  eth2/types/benches/benches.rs
  eth2/types/src/beacon_state/tests.rs
  eth2/utils/tree_hash/benches/benches.rs
Labels: low-hanging-fruit, ready-to-squerge

#989 v0.11.1 Network update
  Cargo.lock
  beacon_node/client/src/lib.rs
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/discovery/enr.rs
  beacon_node/eth2-libp2p/src/discovery/mod.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/peer_manager/mod.rs
  beacon_node/eth2-libp2p/src/peer_manager/peer_info.rs
  beacon_node/eth2-libp2p/src/peer_manager/peerdb.rs
  beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2-libp2p/src/rpc/methods.rs
  beacon_node/eth2-libp2p/src/rpc/mod.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/eth2-libp2p/src/types/globals.rs
  beacon_node/eth2-libp2p/src/types/mod.rs
  beacon_node/eth2-libp2p/src/types/peer_info.rs
  beacon_node/eth2-libp2p/tests/gossipsub_tests.rs
  beacon_node/eth2-libp2p/tests/noise.rs
  beacon_node/eth2-libp2p/tests/rpc_tests.rs
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/service.rs
  beacon_node/rest_api/src/network.rs
  eth2/utils/hashmap_delay/src/hashset_delay.rs
Labels: work-in-progress

#971 Added purge subcommand to purge beacon chain db
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
Labels: ready-to-squerge

#866 Add snappy compression support
  beacon_node/eth2-libp2p/src/rpc/codec/mod.rs
  beacon_node/eth2-libp2p/src/rpc/codec/ssz_snappy.rs
  beacon_node/eth2-libp2p/src/rpc/protocol.rs
  beacon_node/eth2-libp2p/tests/rpc_tests.rs
  eth2/types/src/attestation_data.rs
  eth2/types/src/beacon_block.rs
Labels: ready-for-review

#998 Shifts tests to use random ports
  beacon_node/eth2-libp2p/tests/common/mod.rs
  beacon_node/eth2-libp2p/tests/gossipsub_tests.rs
  beacon_node/eth2-libp2p/tests/noise.rs
  beacon_node/eth2-libp2p/tests/rpc_tests.rs
Labels: ready-to-squerge

#992 Fix issues with testnet dir, update docs
  Cargo.lock
  Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/genesis/src/interop.rs
  beacon_node/genesis/src/lib.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  book/src/SUMMARY.md
  book/src/intro.md
  book/src/local-testnets.md
  book/src/simple-testnet.md
  eth2/utils/eth2_config/src/lib.rs
  eth2/utils/lighthouse_bootstrap/Cargo.toml
  eth2/utils/lighthouse_bootstrap/src/lib.rs
  lighthouse/environment/src/lib.rs
  lighthouse/environment/tests/environment_builder.rs
  lighthouse/src/main.rs
  validator_client/Cargo.toml
Labels: ready-to-squerge

#1001 Update testnet tooling
  .github/workflows/test-suite.yml
  Cargo.lock
  Cargo.toml
  Makefile
  account_manager/Cargo.toml
  account_manager/src/cli.rs
  account_manager/src/deposits.rs
  account_manager/src/lib.rs
  beacon_node/eth1/Cargo.toml
  beacon_node/eth2-libp2p/src/discovery/enr.rs
  beacon_node/eth2-libp2p/src/discovery/mod.rs
  beacon_node/eth2-libp2p/src/lib.rs
  beacon_node/eth2-libp2p/src/service.rs
  book/src/local-testnets.md
  eth2/utils/clap_utils/Cargo.toml
  eth2/utils/clap_utils/src/lib.rs
  eth2/utils/deposit_contract/src/lib.rs
  lcli/Cargo.toml
  lcli/src/check_deposit_data.rs
  lcli/src/deploy_deposit_contract.rs
  lcli/src/generate_bootnode_enr.rs
  lcli/src/main.rs
  lcli/src/new_testnet.rs
  lcli/src/refund_deposit_contract.rs
  lighthouse/Cargo.toml
  lighthouse/environment/src/lib.rs
  lighthouse/src/main.rs
  tests/eth1_test_rig/Cargo.toml
  validator_client/Cargo.toml
  validator_client/src/validator_directory.rs
Labels: ready-for-review

#1022 Fix defaults on lcli new-testnet
  lcli/src/main.rs
  lcli/src/new_testnet.rs
Labels: ready-for-review

#900 Check attestation shuffling when producing blocks
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  eth2/operation_pool/src/lib.rs
  eth2/proto_array_fork_choice/src/proto_array.rs
Labels: ready-to-squerge

#1009 Use checked arithmetic in types and state proc
  .github/workflows/test-suite.yml
  Cargo.lock
  Cargo.toml
  Makefile
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/genesis/src/eth1_genesis_service.rs
  eth2/state_processing/Cargo.toml
  eth2/state_processing/src/common/deposit_data_tree.rs
  eth2/state_processing/src/common/get_base_reward.rs
  eth2/state_processing/src/common/slash_validator.rs
  eth2/state_processing/src/genesis.rs
  eth2/state_processing/src/lib.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/block_signature_verifier.rs
  eth2/state_processing/src/per_block_processing/errors.rs
  eth2/state_processing/src/per_block_processing/verify_deposit.rs
  eth2/state_processing/src/per_epoch_processing.rs
  eth2/state_processing/src/per_epoch_processing/apply_rewards.rs
  eth2/state_processing/src/per_epoch_processing/errors.rs
  eth2/state_processing/src/per_epoch_processing/process_slashings.rs
  eth2/state_processing/src/per_epoch_processing/validator_statuses.rs
  eth2/types/Cargo.toml
  eth2/types/src/beacon_state.rs
  eth2/types/src/beacon_state/committee_cache.rs
  eth2/types/src/beacon_state/exit_cache.rs
  eth2/types/src/beacon_state/pubkey_cache.rs
  eth2/types/src/beacon_state/tree_hash_cache.rs
  eth2/types/src/chain_spec.rs
  eth2/types/src/eth_spec.rs
  eth2/types/src/lib.rs
  eth2/types/src/slot_epoch.rs
  eth2/types/src/slot_epoch_macros.rs
  eth2/types/src/test_utils/builders/testing_beacon_state_builder.rs
  eth2/types/src/test_utils/builders/testing_deposit_builder.rs
  eth2/types/src/test_utils/builders/testing_proposer_slashing_builder.rs
  eth2/types/src/test_utils/mod.rs
  eth2/types/src/tree_hash_impls.rs
  eth2/types/src/utils/serde_utils.rs
  eth2/utils/bls/src/aggregate_public_key.rs
  eth2/utils/cached_tree_hash/src/cache.rs
  eth2/utils/cached_tree_hash/src/cache_arena.rs
  eth2/utils/merkle_proof/Cargo.toml
  eth2/utils/merkle_proof/src/lib.rs
  eth2/utils/safe_arith/Cargo.toml
  eth2/utils/safe_arith/src/lib.rs
  eth2/utils/serde_hex/src/lib.rs
  eth2/utils/ssz_derive/src/lib.rs
  eth2/utils/tree_hash/src/merkle_hasher.rs
Labels: ready-to-squerge

#974 Protect against OOB offset in variable list SSZ decoding
  eth2/utils/ssz/src/decode.rs
  eth2/utils/ssz/src/decode/impls.rs
  eth2/utils/ssz/tests/tests.rs
  eth2/utils/ssz_types/src/fixed_vector.rs
  eth2/utils/ssz_types/src/variable_list.rs
  lcli/src/helpers.rs
  lcli/src/main.rs
  lcli/src/parse_ssz.rs
Labels: bug, ready-for-review, security

#916 Prune abandoned forks
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/head_tracker.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/eth1/src/service.rs
  beacon_node/src/lib.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/migrate.rs
  eth2/types/src/beacon_state.rs
  eth2/types/src/lib.rs
  eth2/types/src/signed_beacon_block.rs
  eth2/types/src/slot_epoch.rs
  eth2/types/src/slot_epoch_macros.rs
Labels: ready-for-review

#1045 Allow lcli new-testnet to optionally overwrite files
  eth2/utils/eth2_testnet_config/src/lib.rs
  lcli/src/main.rs
  lcli/src/new_testnet.rs
Labels: ready-for-review

#1046 Add feature flag for writing ssz pre/post to disk
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/block_verification.rs
  lighthouse/Cargo.toml
Labels: low-hanging-fruit, ready-for-review

#1048 Fix mapping bug in YamlConfig
  eth2/types/src/chain_spec.rs
  tests/ef_tests/tests/tests.rs
Labels: ready-to-squerge

#985 Milagro BLS update
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  eth2/state_processing/src/per_block_processing/block_signature_verifier.rs
  eth2/state_processing/src/per_block_processing/signature_sets.rs
  eth2/utils/bls/Cargo.toml
  eth2/utils/bls/src/aggregate_public_key.rs
  eth2/utils/bls/src/aggregate_signature.rs
  eth2/utils/bls/src/fake_aggregate_public_key.rs
  eth2/utils/bls/src/fake_aggregate_signature.rs
  eth2/utils/bls/src/lib.rs
  eth2/utils/bls/src/signature_set.rs
  eth2/utils/eth2_interop_keypairs/Cargo.toml
  tests/ef_tests/src/cases/bls_aggregate_verify.rs
Labels: may-sec-review, work-in-progress

#1072 Update SecretKey to 32 bytes
  Cargo.lock
  eth2/types/src/test_utils/keypairs_file.rs
  eth2/utils/bls/Cargo.toml
  eth2/utils/bls/src/lib.rs
  eth2/utils/bls/src/secret_key.rs
  eth2/utils/eth2_interop_keypairs/Cargo.toml
  eth2/utils/eth2_interop_keypairs/src/lib.rs
  tests/ef_tests/src/cases/bls_sign_msg.rs
Labels: ready-to-merge

#1068 [lcli] the fork version is now inferred from the spec and can also be…
  lcli/src/interop_genesis.rs
  lcli/src/main.rs
Labels: bug

#1052 Ensure genesis is not triggered too early
  beacon_node/genesis/src/eth1_genesis_service.rs
  eth2/state_processing/src/genesis.rs
  eth2/state_processing/src/lib.rs
Labels: bug, low-hanging-fruit, ready-to-squerge

#1086 Fix duplicate proposer slashing bug
  eth2/operation_pool/src/lib.rs
  eth2/state_processing/src/per_block_processing.rs
  eth2/state_processing/src/per_block_processing/tests.rs
Labels: low-hanging-fruit, may-sec-review, ready-for-review

#1020 Improve aggregate validator logic
  beacon_node/network/src/attestation_service/mod.rs
Labels: waiting-on-author

#1035 Port websockets, timer and notifier to stable futures
  Cargo.lock
  beacon_node/client/src/notifier.rs
  beacon_node/timer/Cargo.toml
  beacon_node/timer/src/lib.rs
  beacon_node/websocket_server/Cargo.toml
  beacon_node/websocket_server/src/lib.rs
  eth2/utils/remote_beacon_node/Cargo.toml
  eth2/utils/remote_beacon_node/src/lib.rs
  lcli/src/deploy_deposit_contract.rs
  lcli/src/main.rs
Labels: ready-for-review

#1069 Add more detail to bad hardcoded dir error
  Cargo.lock
  beacon_node/Cargo.toml
  beacon_node/src/config.rs
  eth2/utils/clap_utils/src/lib.rs
Labels: low-hanging-fruit, ready-to-squerge

#1084 beacon/notifier: display block information for current slot
  beacon_node/client/src/notifier.rs
Labels: ready-for-review

#1082 Follow distance fix
  beacon_node/client/src/builder.rs
  beacon_node/eth1/src/service.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
Labels: low-hanging-fruit, waiting-on-author
