Repository sigp/lighthouse, pull requests merged in 2020-07, with the labels that each got.

#1321 Fix invalid attestation verification condition
  consensus/fork_choice/src/fork_choice.rs
  consensus/fork_choice/tests/tests.rs
Labels: bug, consensus, ready-to-squerge

#1285 Write new blocks and states to the database atomically
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/store/src/chunked_vector.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/impls/beacon_state.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  beacon_node/store/src/metrics.rs
  beacon_node/store/src/state_batch.rs
Labels: ready-to-squerge

#1270 swap out rust-crypto for RustCrypto libraries for key management
  Cargo.lock
  crypto/eth2_key_derivation/Cargo.toml
  crypto/eth2_key_derivation/src/derived_key.rs
  crypto/eth2_key_derivation/src/path.rs
  crypto/eth2_keystore/Cargo.toml
  crypto/eth2_keystore/src/json_keystore/kdf_module.rs
  crypto/eth2_keystore/src/keystore.rs
Labels: crypto, ready-for-review

#1323 Harden the freezing procedure against failures
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
Labels: ready-to-squerge

#1322 Update deps
  Cargo.lock
  Dockerfile
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/client/Cargo.toml
  beacon_node/eth1/Cargo.toml
  beacon_node/eth2_libp2p/Cargo.toml
  beacon_node/genesis/Cargo.toml
  beacon_node/network/Cargo.toml
  beacon_node/operation_pool/Cargo.toml
  beacon_node/rest_api/Cargo.toml
  beacon_node/store/Cargo.toml
  beacon_node/timer/Cargo.toml
  common/eth2_interop_keypairs/Cargo.toml
  common/lighthouse_metrics/Cargo.toml
  common/slot_clock/Cargo.toml
  crypto/eth2_hashing/Cargo.toml
  crypto/eth2_key_derivation/Cargo.toml
  crypto/eth2_keystore/Cargo.toml
  crypto/eth2_wallet/Cargo.toml
  lighthouse/environment/Cargo.toml
  testing/simulator/Cargo.toml
  validator_client/Cargo.toml
  validator_client/slashing_protection/Cargo.toml
Labels: low-hanging-fruit, ready-to-squerge

#1330 Add checksum verification for deposit contract
  Cargo.lock
  common/deposit_contract/Cargo.toml
  common/deposit_contract/build.rs
Labels: blocked, low-hanging-fruit

#1327 Remove old block processing shim
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification/block_processing_outcome.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/sync/manager.rs
Labels: low-hanging-fruit, ready-for-review

#1334 Remove outdated validator client README
  validator_client/README.md
Labels: ready-to-squerge

#1316 Add latest commit info to git version
  Cargo.lock
  lighthouse/Cargo.toml
  lighthouse/src/main.rs
Labels: ready-for-review

#1324 Update libp2p and gossipsub
  Cargo.lock
  beacon_node/eth2_libp2p/Cargo.toml
  beacon_node/eth2_libp2p/src/behaviour/mod.rs
  beacon_node/eth2_libp2p/src/config.rs
Labels: ready-for-review

#1284 Activate peer scoring
  beacon_node/eth2_libp2p/src/behaviour/handler/delegate.rs
  beacon_node/eth2_libp2p/src/behaviour/handler/mod.rs
  beacon_node/eth2_libp2p/src/behaviour/mod.rs
  beacon_node/eth2_libp2p/src/discovery/mod.rs
  beacon_node/eth2_libp2p/src/lib.rs
  beacon_node/eth2_libp2p/src/peer_manager/client.rs
  beacon_node/eth2_libp2p/src/peer_manager/mod.rs
  beacon_node/eth2_libp2p/src/peer_manager/peer_info.rs
  beacon_node/eth2_libp2p/src/peer_manager/peerdb.rs
  beacon_node/eth2_libp2p/src/peer_manager/score.rs
  beacon_node/eth2_libp2p/src/rpc/codec/ssz.rs
  beacon_node/eth2_libp2p/src/rpc/codec/ssz_snappy.rs
  beacon_node/eth2_libp2p/src/rpc/handler.rs
  beacon_node/eth2_libp2p/src/rpc/methods.rs
  beacon_node/eth2_libp2p/src/rpc/mod.rs
  beacon_node/eth2_libp2p/src/service.rs
  beacon_node/eth2_libp2p/src/types/pubsub.rs
  beacon_node/eth2_libp2p/tests/rpc_tests.rs
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/store.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  common/hashset_delay/src/hashset_delay.rs
Labels: ready-for-review

#1282 Fix race condition in VC block proposal service
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
  common/rest_types/src/validator.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/tests.rs
  testing/simulator/src/checks.rs
  testing/simulator/src/eth1_sim.rs
  testing/simulator/src/local_network.rs
  testing/simulator/src/no_eth1_sim.rs
  validator_client/src/block_service.rs
  validator_client/src/duties_service.rs
  validator_client/src/lib.rs
Labels: ready-to-squerge, val-client

#1339 Update smallvec
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/eth2_libp2p/Cargo.toml
  beacon_node/eth2_libp2p/src/behaviour/mod.rs
  beacon_node/network/Cargo.toml
  consensus/cached_tree_hash/Cargo.toml
  consensus/ssz/Cargo.toml
  consensus/tree_hash/Cargo.toml
Labels: ready-for-review

#1338 Correct book links
  book/src/become-a-validator-source.md
  book/src/faq.md
Labels: low-hanging-fruit, ready-for-review

#1348 Fix condition for resubscription
  validator_client/src/duties_service.rs
Labels: ready-for-review

#1360 Fix attestation propagation
  beacon_node/network/src/attestation_service/mod.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/service.rs
Labels: ready-for-review

#1367 Update libp2p
  Cargo.lock
  beacon_node/eth2_libp2p/Cargo.toml
Labels: ready-for-review

#1373 Discv5 update
  Cargo.lock
  beacon_node/eth2_libp2p/Cargo.toml
  beacon_node/eth2_libp2p/src/config.rs
  lighthouse/environment/Cargo.toml
Labels: ready-for-review

#1393 Add info about peer scoring to block/attestation errors
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
Labels: ready-for-review

#1405 Add testnet flags
  beacon_node/client/src/config.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  common/clap_utils/src/lib.rs
  common/eth2_testnet_config/build.rs
  common/eth2_testnet_config/src/lib.rs
  lighthouse/environment/tests/environment_builder.rs
  lighthouse/src/main.rs
Labels: ready-for-review
