Repository sigp/lighthouse, pull requests merged in 2020-01, with the labels that each got.

#762 Optimization: avoid recomputing known state roots
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/store/src/hot_cold_store.rs
  eth2/state_processing/src/per_slot_processing.rs
  lcli/src/transition_blocks.rs
  lighthouse/Cargo.toml
  tests/ef_tests/src/cases/sanity_blocks.rs
  tests/ef_tests/src/cases/sanity_slots.rs
Labels: ready-for-review

#682 Remove the logic allowing lighthouse to update it's own ENR
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/eth2-libp2p/src/service.rs
  beacon_node/src/config.rs
Labels: ready-for-review

#764 Update libp2p and updates gossipsub
  Cargo.lock
  beacon_node/eth2-libp2p/Cargo.toml
  beacon_node/eth2-libp2p/src/config.rs
  lighthouse/Cargo.toml
Labels: ready-to-merge

#747 Fix testnet docs
  book/src/simple-testnet.md
Labels: ready-to-merge

#750 Change genesis fork for testnets
  beacon_node/src/config.rs
  lcli/src/deploy_deposit_contract.rs
  lcli/src/eth1_genesis.rs
Labels: ready-to-merge

#759 Add timeouts to canonical head rwlock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/timeout_rw_lock.rs
  beacon_node/beacon_chain/tests/persistence_tests.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/client/src/notifier.rs
  beacon_node/network/src/message_processor.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  beacon_node/network/src/sync/range_sync/range.rs
  beacon_node/rest_api/src/beacon.rs
  beacon_node/rest_api/src/error.rs
  beacon_node/rest_api/src/helpers.rs
  beacon_node/rest_api/src/validator.rs
  beacon_node/rest_api/tests/test.rs
Labels: ready-to-merge

#745 Add individual processing for ef tests
  eth2/state_processing/src/per_block_processing/errors.rs
  eth2/state_processing/src/per_block_processing/signature_sets.rs
  eth2/types/src/beacon_state.rs
  eth2/utils/cached_tree_hash/src/lib.rs
  eth2/utils/ssz_types/src/lib.rs
  tests/ef_tests/src/cases/sanity_blocks.rs
Labels: waiting-on-author

#775 Use Cow for checkpoint cache
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/checkpoint_cache.rs
Labels: ready-to-merge

#746 Store states efficiently in the hot database
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/persisted_beacon_chain.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/block_root_tree.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/migrate.rs
  eth2/lmd_ghost/src/lib.rs
  eth2/lmd_ghost/src/reduced_tree.rs
  eth2/lmd_ghost/tests/test.rs
  eth2/types/src/beacon_state.rs
Labels: ready-to-squerge

#770 Improved RPC timeout handling
  Cargo.lock
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/network/src/sync/range_sync/chain.rs
Labels: ready-to-squerge

#782 Fix typo in eth1 service logs
  beacon_node/eth1/src/service.rs
Labels: ready-to-squerge

#783 Avoid building caches during block replay
  beacon_node/store/src/hot_cold_store.rs
  eth2/state_processing/src/common/initiate_validator_exit.rs
  eth2/types/src/beacon_state.rs
  eth2/types/src/beacon_state/exit_cache.rs
  tests/ef_tests/src/cases/epoch_processing.rs
  tests/ef_tests/src/cases/operations.rs
Labels: ready-to-squerge

#787 Fix off-by-one error in get_latest_restore_point
  beacon_node/store/src/hot_cold_store.rs
Labels: bug, ready-to-squerge

#784 Upgrade Sync Logging
  beacon_node/network/src/message_processor.rs
Labels: ready-to-squerge

#773 Update docs for testnet3
  README.md
  beacon_node/client/src/notifier.rs
  beacon_node/src/cli.rs
  book/src/SUMMARY.md
  book/src/become-a-validator-docker.md
  book/src/become-a-validator-source.md
  book/src/become-a-validator.md
  book/src/docker.md
Labels: ready-for-review

#788 Discv5 upgrade
  Cargo.lock
  beacon_node/eth2-libp2p/Cargo.toml
Labels: ready-for-review

#790 Increase default slots per restore point to 2048
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/config.rs
Labels: ready-to-squerge

#766 Optimization: reduce BLS decompression
  .dockerignore
  Cargo.lock
  eth2/state_processing/src/per_block_processing/signature_sets.rs
  eth2/types/src/beacon_state.rs
  eth2/types/src/validator.rs
  eth2/utils/bls/src/macros.rs
  eth2/utils/ssz/src/decode.rs
Labels: ready-to-squerge

#791 Print validator pubkeys during generation
  account_manager/src/lib.rs
  book/src/become-a-validator-docker.md
  book/src/become-a-validator-source.md
  eth2/utils/bls/src/public_key.rs
Labels: ready-for-review

#793 Notifier errors
  beacon_node/client/src/notifier.rs
Labels: ready-to-squerge

#792 Bump version tags
  beacon_node/beacon_chain/src/beacon_chain.rs
  lighthouse/Cargo.toml
Labels: ready-to-squerge

#794 Bump docker rust version
  .dockerignore
  Dockerfile
Labels: ready-for-review

#801 Sync fixes
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/network/src/message_processor.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/mod.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-review

#803 Correct stream timeout delay queue handling
  Cargo.lock
  beacon_node/eth2-libp2p/src/rpc/handler.rs
Labels: ready-for-review

#707 Update op_pool to use proper rewards
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  eth2/operation_pool/src/attestation.rs
  eth2/operation_pool/src/lib.rs
  eth2/state_processing/src/common/get_base_reward.rs
  eth2/state_processing/src/common/mod.rs
  eth2/state_processing/src/per_epoch_processing/apply_rewards.rs
Labels: ready-to-squerge

#820 Optimize block production
  eth2/operation_pool/src/lib.rs
Labels: ready-to-squerge

#816 Super/Silky smooth syncs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/network/src/message_processor.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/batch_processing.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  beacon_node/network/src/sync/range_sync/mod.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-review, syncing

#818 Correct discovery address CLI functionality
  beacon_node/eth2-libp2p/src/config.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
Labels: waiting-on-author

#758 Adds simulator for syncing
  .github/workflows/test-suite.yml
  Cargo.lock
  Cargo.toml
  tests/simulator/Cargo.toml
  tests/simulator/src/checks.rs
  tests/simulator/src/cli.rs
  tests/simulator/src/local_network.rs
  tests/simulator/src/main.rs
  tests/simulator/src/sync_sim.rs
Labels: ready-for-review

#659 Persist/load DHT on shutdown/startup
  Cargo.lock
  beacon_node/client/src/lib.rs
  beacon_node/eth2-libp2p/src/behaviour.rs
  beacon_node/eth2-libp2p/src/discovery.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/lib.rs
  beacon_node/network/src/persisted_dht.rs
  beacon_node/network/src/service.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/lib.rs
Labels: ready-for-review

#819 Advanced error handling for syncing
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-review, syncing

#768 Faster BLS Verification
  Cargo.lock
  eth2/utils/bls/Cargo.toml
  eth2/utils/eth2_interop_keypairs/Cargo.toml
Labels: waiting-on-author

#804 Add proto_array fork choice
  Cargo.lock
  Cargo.toml
  README.md
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/fork_choice.rs
  beacon_node/beacon_chain/src/fork_choice/checkpoint_manager.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/persisted_beacon_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/eth2-libp2p/src/rpc/handler.rs
  beacon_node/network/src/sync/range_sync/batch_processing.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  beacon_node/network/src/sync/range_sync/range.rs
  beacon_node/rest_api/src/advanced.rs
  beacon_node/rest_api/src/lib.rs
  beacon_node/rest_api/src/router.rs
  beacon_node/rest_api/tests/test.rs
  beacon_node/src/lib.rs
  beacon_node/store/src/block_root_tree.rs
  beacon_node/store/src/lib.rs
  eth2/lmd_ghost/Cargo.toml
  eth2/lmd_ghost/src/lib.rs
  eth2/lmd_ghost/src/reduced_tree.rs
  eth2/lmd_ghost/tests/test.rs
  eth2/proto_array_fork_choice/.gitignore
  eth2/proto_array_fork_choice/Cargo.toml
  eth2/proto_array_fork_choice/src/bin.rs
  eth2/proto_array_fork_choice/src/error.rs
  eth2/proto_array_fork_choice/src/fork_choice_test_definition.rs
  eth2/proto_array_fork_choice/src/fork_choice_test_definition/ffg_updates.rs
  eth2/proto_array_fork_choice/src/fork_choice_test_definition/no_votes.rs
  eth2/proto_array_fork_choice/src/fork_choice_test_definition/votes.rs
  eth2/proto_array_fork_choice/src/lib.rs
  eth2/proto_array_fork_choice/src/proto_array.rs
  eth2/proto_array_fork_choice/src/proto_array_fork_choice.rs
  eth2/proto_array_fork_choice/src/ssz_container.rs
  eth2/state_processing/Cargo.toml
  eth2/utils/logging/Cargo.toml
  eth2/utils/logging/src/lib.rs
  eth2/utils/remote_beacon_node/Cargo.toml
  eth2/utils/remote_beacon_node/src/lib.rs
Labels: waiting-on-author

#832 Prevent duplicate gossipsub loops/message amplification
  beacon_node/eth2-libp2p/src/behaviour.rs
Labels: waiting-on-author
