Repository sigp/lighthouse, pull requests merged in 2021-09, with the labels that each got.

#2568 Updated for latest changes in metrics
  Cargo.lock
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/service.rs
Labels: work-in-progress

#2561 Network Update for Weak Subjectivity Sync
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/notifier.rs
  beacon_node/eth2_libp2p/src/behaviour/mod.rs
  beacon_node/eth2_libp2p/src/peer_manager/mod.rs
  beacon_node/eth2_libp2p/src/service.rs
  beacon_node/eth2_libp2p/src/types/globals.rs
  beacon_node/eth2_libp2p/src/types/mod.rs
  beacon_node/eth2_libp2p/src/types/sync_state.rs
  beacon_node/http_api/src/database.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
  beacon_node/network/src/beacon_processor/worker/sync_methods.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/mod.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-review

#2599 Additional checkpoint sync logs
  beacon_node/client/src/builder.rs
Labels: ready-for-review

#2600 Log about historical backfill less frequently
  beacon_node/client/src/notifier.rs
  book/src/checkpoint-sync.md
Labels: ready-for-review

#2626 Fix clippy lints on merge-f2f
  beacon_node/beacon_chain/src/block_verification.rs
  consensus/ssz_derive/src/lib.rs
  consensus/state_processing/src/per_block_processing.rs
Labels: ready-for-review, merge-f2f

#2630 Update merge consensus to v1.1.0-beta.5
  consensus/state_processing/src/per_block_processing.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  testing/ef_tests/Makefile
Labels: ready-for-review, merge-f2f

#2631 Handle merge fork in web3signer
  validator_client/src/signing_method.rs
  validator_client/src/signing_method/web3signer.rs
Labels: ready-for-review

#2642 Update test vectors to v1.1.0
  consensus/state_processing/src/genesis.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/fork_name.rs
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/genesis_initialization.rs
  testing/ef_tests/src/handler.rs
Labels: ready-for-review, merge-f2f

#2643 Store execution block hash in fork choice
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/store/src/metadata.rs
  beacon_node/websocket_server/Cargo.toml
  beacon_node/websocket_server/src/lib.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/proto_array/src/fork_choice_test_definition.rs
  consensus/proto_array/src/proto_array.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/proto_array/src/ssz_container.rs
Labels: ready-for-review, merge-f2f

#2640 Finished Gossip Block Validation Conditions
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  common/slot_clock/src/lib.rs
  common/slot_clock/src/manual_slot_clock.rs
  common/slot_clock/src/system_time_slot_clock.rs
Labels: merge-f2f

#2635 [Merge] Implement `execution_layer`
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/fork_revert.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/eth1/src/http.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engines.rs
  beacon_node/execution_layer/src/execute_payload_handle.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  common/task_executor/src/lib.rs
  consensus/fork_choice/Cargo.toml
  consensus/fork_choice/src/fork_choice.rs
  consensus/fork_choice/tests/tests.rs
  consensus/serde_utils/src/hex.rs
  consensus/serde_utils/src/hex_vec.rs
  consensus/serde_utils/src/lib.rs
  consensus/serde_utils/src/list_of_bytes_lists.rs
  consensus/serde_utils/src/quoted_int.rs
  consensus/serde_utils/src/u64_hex_be.rs
  consensus/ssz_types/src/serde_utils/hex_fixed_vec.rs
  consensus/ssz_types/src/serde_utils/hex_var_list.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/lib.rs
Labels: ready-for-review, merge-f2f

#2649 [Merge] Add serde impls for `Transactions` type
  beacon_node/execution_layer/src/engine_api/http.rs
Labels: ready-for-review
