Repository sigp/lighthouse, pull requests merged in 2021-11, with the labels that each got.

#2769 Kintsugi rebase patches
  Cargo.lock
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  consensus/types/src/fork_name.rs
Labels: kintsugi 🍵

#2774 Publish kintsugi docker image
  .github/workflows/docker-kintsugi.yml
Labels: ready-for-review, kintsugi 🍵

#2777 Fix arbitrary check kintsugi
  consensus/types/src/execution_payload.rs
Labels: ready-for-review, low-hanging-fruit, kintsugi 🍵

#2781 1.1.5 merge spec tests
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  consensus/ssz_types/src/serde_utils/list_of_hex_var_list.rs
  consensus/ssz_types/src/serde_utils/mod.rs
  consensus/state_processing/src/common/slash_validator.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_epoch_processing/altair.rs
  consensus/state_processing/src/per_epoch_processing/altair/rewards_and_penalties.rs
  consensus/state_processing/src/per_epoch_processing/base.rs
  consensus/state_processing/src/per_epoch_processing/slashings.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/execution_payload.rs
  testing/ef_tests/Makefile
  testing/ef_tests/src/cases/epoch_processing.rs
Labels: waiting-on-author, kintsugi 🍵

#2799 Fixes after rebasing Kintsugi onto unstable
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/fork_revert.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/fork_choice/src/lib.rs
  consensus/fork_choice/tests/tests.rs
  testing/ef_tests/Cargo.toml
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/fork_choice.rs
Labels: work-in-progress, kintsugi 🍵

#2809 Skip memory intensive engine test
  beacon_node/execution_layer/src/engine_api/http.rs
Labels: kintsugi 🍵

#2810 Implement engine API v1.0.0-alpha.4
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/engines.rs
  beacon_node/execution_layer/src/execute_payload_handle.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/serde_utils/src/bytes_4_hex.rs
  consensus/serde_utils/src/fixed_bytes_hex.rs
  consensus/serde_utils/src/lib.rs
Labels: work-in-progress, kintsugi 🍵

#2798 Ensure difficulty/hash/epoch overrides change the `ChainSpec`
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  boot_node/Cargo.toml
  boot_node/src/config.rs
  boot_node/src/lib.rs
  common/clap_utils/Cargo.toml
  common/clap_utils/src/lib.rs
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/prater/config.yaml
  common/eth2_network_config/built_in_network_configs/pyrmont/config.yaml
  consensus/types/src/chain_spec.rs
  lighthouse/environment/src/lib.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
  lighthouse/src/main.rs
  lighthouse/tests/beacon_node.rs
  lighthouse/tests/boot_node.rs
Labels: ready-for-review, kintsugi 🍵

#2811 Kintsugi on_merge_block tests
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/types/src/beacon_block.rs
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/fork_choice.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-review, kintsugi 🍵

#2813 Remove Unused Code From Early Merge Work
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/eth1/src/http.rs
  beacon_node/eth1/src/service.rs
  beacon_node/eth1/tests/test.rs
  consensus/types/src/lib.rs
  consensus/types/src/pow_block.rs
Labels: kintsugi 🍵

#2829 Bump crate versions for Kintsugi
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/eth1/Cargo.toml
  beacon_node/execution_layer/Cargo.toml
  beacon_node/genesis/Cargo.toml
  beacon_node/http_api/Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/network/Cargo.toml
  beacon_node/operation_pool/Cargo.toml
  beacon_node/store/Cargo.toml
  boot_node/Cargo.toml
  common/clap_utils/Cargo.toml
  common/deposit_contract/Cargo.toml
  common/eth2/Cargo.toml
  common/eth2_network_config/Cargo.toml
  common/validator_dir/Cargo.toml
  consensus/cached_tree_hash/Cargo.toml
  consensus/fork_choice/Cargo.toml
  consensus/proto_array/Cargo.toml
  consensus/ssz/Cargo.toml
  consensus/ssz_types/Cargo.toml
  consensus/state_processing/Cargo.toml
  consensus/tree_hash/Cargo.toml
  consensus/types/Cargo.toml
  crypto/bls/Cargo.toml
  lcli/Cargo.toml
  slasher/Cargo.toml
  testing/ef_tests/Cargo.toml
  testing/state_transition_vectors/Cargo.toml
  validator_client/Cargo.toml
Labels: ready-for-review, kintsugi 🍵

#2831 Kintsugi review comments
  .github/workflows/docker-kintsugi.yml
  Cargo.lock
  Cargo.toml
  Makefile
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  common/eth2/Cargo.toml
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/proto_array/src/ssz_container.rs
  consensus/serde_utils/Cargo.toml
  consensus/ssz_types/Cargo.toml
  consensus/types/Cargo.toml
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/test_utils/test_random/hash256.rs
  consensus/types/src/test_utils/test_random/uint256.rs
  crypto/bls/Cargo.toml
  validator_client/Cargo.toml
  validator_client/slashing_protection/Cargo.toml
Labels: ready-for-review, kintsugi 🍵

#2836 Kintsugi Diva comments
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
Labels: ready-for-review, kintsugi 🍵
