Repository sigp/lighthouse, pull requests merged in 2021-07, with the labels that each got.

#2441 Fix tests for `block-replay`
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/src/attestation_service/tests/mod.rs
  beacon_node/store/src/iter.rs
  consensus/state_processing/src/lib.rs
  consensus/state_processing/src/per_block_processing/tests.rs
  consensus/state_processing/src/per_epoch_processing/tests.rs
  lcli/src/skip_slots.rs
  lcli/src/transition_blocks.rs
  testing/ef_tests/src/cases/operations.rs
  testing/ef_tests/src/cases/sanity_blocks.rs
  testing/ef_tests/src/cases/sanity_slots.rs
  testing/ef_tests/src/cases/transition.rs
  testing/state_transition_vectors/src/exit.rs
Labels: work-in-progress

#2442 Global Network Behaviour Refactor
  Cargo.lock
  beacon_node/eth2_libp2p/Cargo.toml
  beacon_node/eth2_libp2p/src/behaviour/handler/delegate.rs
  beacon_node/eth2_libp2p/src/behaviour/handler/mod.rs
  beacon_node/eth2_libp2p/src/behaviour/mod.rs
  beacon_node/eth2_libp2p/src/discovery/mod.rs
  beacon_node/eth2_libp2p/src/peer_manager/mod.rs
  beacon_node/eth2_libp2p/src/peer_manager/peer_info.rs
  beacon_node/eth2_libp2p/src/peer_manager/peerdb.rs
  beacon_node/eth2_libp2p/src/rpc/handler.rs
  beacon_node/eth2_libp2p/src/rpc/methods.rs
  beacon_node/eth2_libp2p/src/rpc/mod.rs
  beacon_node/eth2_libp2p/src/rpc/protocol.rs
  beacon_node/eth2_libp2p/src/service.rs
  beacon_node/eth2_libp2p/src/types/topics.rs
  beacon_node/eth2_libp2p/tests/rpc_tests.rs
  beacon_node/network/src/beacon_processor/worker/mod.rs
  beacon_node/network/src/service.rs
Labels: networking, ready-for-review

#2389 Network Updates for 1.5
  Cargo.lock
  account_manager/Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/client/Cargo.toml
  beacon_node/eth1/Cargo.toml
  beacon_node/eth2_libp2p/Cargo.toml
  beacon_node/eth2_libp2p/src/behaviour/gossipsub_scoring_parameters.rs
  beacon_node/eth2_libp2p/src/behaviour/handler/delegate.rs
  beacon_node/eth2_libp2p/src/behaviour/handler/mod.rs
  beacon_node/eth2_libp2p/src/behaviour/mod.rs
  beacon_node/eth2_libp2p/src/config.rs
  beacon_node/eth2_libp2p/src/discovery/mod.rs
  beacon_node/eth2_libp2p/src/peer_manager/mod.rs
  beacon_node/eth2_libp2p/src/peer_manager/peer_info.rs
  beacon_node/eth2_libp2p/src/peer_manager/peerdb.rs
  beacon_node/eth2_libp2p/src/peer_manager/score.rs
  beacon_node/eth2_libp2p/src/rpc/handler.rs
  beacon_node/eth2_libp2p/src/rpc/methods.rs
  beacon_node/eth2_libp2p/src/rpc/mod.rs
  beacon_node/eth2_libp2p/src/rpc/protocol.rs
  beacon_node/eth2_libp2p/src/service.rs
  beacon_node/eth2_libp2p/src/types/topics.rs
  beacon_node/eth2_libp2p/tests/common/mod.rs
  beacon_node/eth2_libp2p/tests/rpc_tests.rs
  beacon_node/genesis/Cargo.toml
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/tests/tests.rs
  beacon_node/http_metrics/Cargo.toml
  beacon_node/network/Cargo.toml
  beacon_node/network/src/beacon_processor/tests.rs
  beacon_node/network/src/beacon_processor/worker/mod.rs
  beacon_node/network/src/persisted_dht.rs
  beacon_node/network/src/service.rs
  beacon_node/timer/Cargo.toml
  boot_node/Cargo.toml
  boot_node/src/server.rs
  common/eth2_network_config/Cargo.toml
  common/hashset_delay/Cargo.toml
  common/monitoring_api/Cargo.toml
  common/remote_signer_consumer/Cargo.toml
  common/task_executor/Cargo.toml
  common/warp_utils/Cargo.toml
  lcli/Cargo.toml
  lighthouse/Cargo.toml
  lighthouse/environment/Cargo.toml
  slasher/service/Cargo.toml
  testing/eth1_test_rig/Cargo.toml
  testing/remote_signer_test/Cargo.toml
  testing/simulator/Cargo.toml
  validator_client/Cargo.toml
Labels: ready-for-bors, v1.5.0
