Repository sigp/lighthouse, pull requests merged in 2021-05, with the labels that each got.

#2341 [Altair] Add tests for decoding state/block with bad slot
  consensus/types/src/beacon_block.rs
  consensus/types/src/beacon_state/tests.rs
Labels: ready-for-review

#2348 [Altair] Nitpick fix to graffiti length checking.
  consensus/types/src/graffiti.rs
Labels: ready-for-review

#2351 [Altair] Replace a test removed during Altair upgrade
  consensus/types/src/beacon_state/tests.rs
Labels: ready-for-review

#2361 [Altair] Avoid slicing in `PartialBeaconState`
  beacon_node/store/src/partial_beacon_state.rs
Labels: ready-for-review

#2362 [Altair] Make anonymous var-length SSZ decoding explicit
  beacon_node/store/src/impls/beacon_state.rs
  consensus/ssz/src/decode.rs
  consensus/types/src/signed_beacon_block.rs
Labels: ready-for-review

#2349 [Altair] Rewards tests
  Cargo.lock
  Dockerfile
  consensus/state_processing/src/per_epoch_processing.rs
  consensus/state_processing/src/per_epoch_processing/altair/rewards_and_penalties.rs
  consensus/state_processing/src/per_epoch_processing/base/rewards_and_penalties.rs
  testing/ef_tests/Cargo.toml
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/rewards.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-bors

#2350 [Altair] Remove duplicate vars, panic on `u64::pow` overflow
  consensus/state_processing/src/per_epoch_processing/altair/inactivity_updates.rs
  consensus/state_processing/src/per_epoch_processing/altair/rewards_and_penalties.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/consts.rs
Labels: waiting-on-author

#2353 [Altair] Applying Base block to Altair chain
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/snapshot_cache.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/validator_pubkey_cache.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/op_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/src/beacon_processor/tests.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/network/src/service/tests.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/store/src/iter.rs
  consensus/fork_choice/tests/tests.rs
  consensus/state_processing/src/genesis.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
  consensus/state_processing/src/per_block_processing/tests.rs
  consensus/state_processing/src/per_epoch_processing.rs
  consensus/state_processing/src/per_epoch_processing/errors.rs
  consensus/state_processing/src/per_epoch_processing/tests.rs
  consensus/state_processing/src/per_epoch_processing/validator_statuses.rs
  consensus/state_processing/src/per_slot_processing.rs
  consensus/tree_hash/examples/flamegraph_beacon_state.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/committee_cache/tests.rs
  consensus/types/src/beacon_state/tests.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/fork_name.rs
  consensus/types/src/lib.rs
  consensus/types/src/signed_beacon_block.rs
  testing/state_transition_vectors/src/main.rs
Labels: ready-for-review

#2365 [Altair] Merge unstable
  .github/workflows/test-suite.yml
  Cargo.lock
  account_manager/Cargo.toml
  account_manager/src/validator/create.rs
  account_manager/src/validator/exit.rs
  account_manager/src/validator/import.rs
  account_manager/src/validator/recover.rs
  account_manager/src/wallet/create.rs
  account_manager/src/wallet/recover.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  book/src/installation-source.md
  book/src/slasher.md
  bors.toml
  common/account_utils/Cargo.toml
  common/account_utils/src/lib.rs
  common/account_utils/src/validator_definitions.rs
  common/filesystem/Cargo.toml
  common/filesystem/src/lib.rs
  common/lockfile/src/lib.rs
  common/remote_signer_consumer/tests/post.rs
  common/validator_dir/Cargo.toml
  common/validator_dir/src/builder.rs
  lighthouse/tests/beacon_node.rs
  remote_signer/backend/src/lib.rs
  remote_signer/backend/src/storage_raw_dir.rs
  remote_signer/tests/get_keys.rs
  remote_signer/tests/sign.rs
  slasher/Cargo.toml
  slasher/src/config.rs
  slasher/src/database.rs
  slasher/src/error.rs
  slasher/tests/attester_slashings.rs
  slasher/tests/proposer_slashings.rs
  slasher/tests/random.rs
  slasher/tests/wrap_around.rs
  testing/eth1_test_rig/src/ganache.rs
  testing/remote_signer_test/Cargo.toml
  testing/remote_signer_test/src/utils.rs
  validator_client/Cargo.toml
  validator_client/slashing_protection/Cargo.toml
  validator_client/slashing_protection/Makefile
  validator_client/slashing_protection/src/lib.rs
  validator_client/slashing_protection/src/slashing_database.rs
  validator_client/src/key_cache.rs
Labels: ready-for-review

#2366 [Altair] Return error when total balance is zero
  consensus/state_processing/src/common/altair.rs
  consensus/state_processing/src/common/base.rs
Labels: ready-for-review

#2367 [Altair] Minor justification/finalization changes
  consensus/state_processing/src/per_epoch_processing/errors.rs
  consensus/state_processing/src/per_epoch_processing/weigh_justification_and_finalization.rs
Labels: ready-for-review

#2369 [Altair] Optimization for `get_unslashed_participating_indices`
  beacon_node/operation_pool/src/lib.rs
  consensus/state_processing/src/per_epoch_processing/altair/inactivity_updates.rs
  consensus/state_processing/src/per_epoch_processing/altair/justification_and_finalization.rs
  consensus/state_processing/src/per_epoch_processing/altair/rewards_and_penalties.rs
  consensus/types/src/beacon_state.rs
Labels: ready-for-review
