Repository sigp/lighthouse, pull requests merged in 2021-06, with the labels that each got.

#2382 Discovery patch
  Cargo.lock
  beacon_node/eth2_libp2p/Cargo.toml
  beacon_node/eth2_libp2p/src/config.rs
  beacon_node/eth2_libp2p/src/discovery/mod.rs
  beacon_node/eth2_libp2p/src/peer_manager/mod.rs
Labels: do-not-merge, v1.5.0

#2390 Change the window mode of yamux
  beacon_node/eth2_libp2p/src/service.rs
Labels: v1.5.0

#2405 Update to spec v1.1.0-alpha.7
  common/eth2_network_config/src/lib.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/altair/sync_committee.rs
  consensus/types/presets/mainnet/altair.yaml
  consensus/types/src/beacon_state.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/consts.rs
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/operations.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-review
