Repository sigp/lighthouse, pull requests merged in 2022-11, with the labels that each got.

#3670 Couple blocks and blobs in gossip
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blobs.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/service/gossip_cache.rs
  beacon_node/lighthouse_network/src/types/mod.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/work_reprocessing_queue.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  common/eth2/src/lib.rs
  consensus/types/src/lib.rs
  consensus/types/src/signed_blobs_sidecar.rs
  validator_client/src/block_service.rs
  validator_client/src/validator_store.rs
Labels: eip-4844

#3673 Block processing eip4844
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/eip4844.rs
  consensus/state_processing/src/per_block_processing/eip4844/eip4844.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/types/src/consts.rs
  consensus/types/src/kzg_commitment.rs
  consensus/types/src/kzg_proof.rs
  consensus/types/src/lib.rs
  consensus/types/src/payload.rs
Labels: ready-for-review, eip-4844

#3675 Cleanup payload types
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/eth1/Cargo.toml
  beacon_node/operation_pool/Cargo.toml
  beacon_node/store/Cargo.toml
  common/eth2/Cargo.toml
  consensus/cached_tree_hash/Cargo.toml
  consensus/fork_choice/Cargo.toml
  consensus/proto_array/Cargo.toml
  consensus/ssz/Cargo.toml
  consensus/ssz/tests/tests.rs
  consensus/ssz_derive/Cargo.toml
  consensus/ssz_derive/src/lib.rs
  consensus/ssz_derive/tests/tests.rs
  consensus/state_processing/Cargo.toml
  consensus/tree_hash/Cargo.toml
  consensus/types/Cargo.toml
  consensus/types/src/beacon_state.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/kzg_commitment.rs
  consensus/types/src/kzg_proof.rs
  consensus/types/src/payload.rs
  slasher/Cargo.toml
  testing/ef_tests/Cargo.toml
Labels: eip-4844

#3684 Feature gate withdrawals
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/partial_beacon_state.rs
  consensus/state_processing/Cargo.toml
  consensus/state_processing/src/common/mod.rs
  consensus/state_processing/src/common/withdraw_balance.rs
  consensus/state_processing/src/per_epoch_processing/capella.rs
  consensus/state_processing/src/per_epoch_processing/capella/full_withdrawals.rs
  consensus/state_processing/src/per_epoch_processing/capella/partial_withdrawals.rs
  consensus/state_processing/src/upgrade/capella.rs
  consensus/state_processing/src/upgrade/eip4844.rs
  consensus/types/Cargo.toml
  consensus/types/src/beacon_state.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  lighthouse/Cargo.toml
Labels: eip-4844

#3719 Fixes to make EF Capella tests pass
  Makefile
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/store/src/hot_cold_store.rs
  consensus/state_processing/src/consensus_context.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/eip4844.rs
  consensus/state_processing/src/per_block_processing/eip4844/eip4844.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_block_processing/verify_bls_to_execution_change.rs
  consensus/state_processing/src/per_slot_processing.rs
  consensus/state_processing/src/upgrade/capella.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/tree_hash_cache.rs
  consensus/types/src/blobs_sidecar.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/kzg_commitment.rs
  consensus/types/src/kzg_proof.rs
  consensus/types/src/lib.rs
  consensus/types/src/payload.rs
  consensus/types/src/tree_hash_impls.rs
  consensus/types/src/validator.rs
  testing/ef_tests/Makefile
  testing/ef_tests/src/cases/epoch_processing.rs
  testing/ef_tests/src/cases/fork.rs
  testing/ef_tests/src/cases/genesis_initialization.rs
  testing/ef_tests/src/cases/operations.rs
  testing/ef_tests/src/cases/transition.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/src/lib.rs
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: test improvement, ready-for-review, consensus

#3743 Fix BlocksByRoot response types
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
Labels: ready-for-review, eip-4844

#3749 Two Capella bugfixes
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/payload.rs
Labels: ready-for-review

#3745 Rename excess blobs and update 4844 json RPC serialization/deserialization
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  consensus/serde_utils/src/lib.rs
  consensus/serde_utils/src/u256_hex_be_opt.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
Labels: eip-4844

#3726 Op pool and gossip for BLS to execution changes
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/observed_operations.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/lib.rs
  beacon_node/lighthouse_network/src/service/gossip_cache.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/router/mod.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/operation_pool/Cargo.toml
  beacon_node/operation_pool/src/lib.rs
  beacon_node/operation_pool/src/persistence.rs
  consensus/state_processing/src/per_block_processing/block_signature_verifier.rs
  consensus/state_processing/src/verify_operation.rs
  consensus/types/src/bls_to_execution_change.rs
  consensus/types/src/signed_bls_to_execution_change.rs
  testing/ef_tests/Makefile
Labels: ready-for-review
