Repository sigp/lighthouse, pull requests merged in 2022-12, with the labels that each got.

#3782 Fix some capella nits
  beacon_node/beacon_chain/src/beacon_chain.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/upgrade/eip4844.rs
  consensus/types/src/bls_to_execution_change.rs
  consensus/types/src/signed_bls_to_execution_change.rs
  consensus/types/src/validator.rs
  consensus/types/src/withdrawal.rs
Labels: capella

#3789 Fix `Withdrawal` serialisation and check address change fork
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  consensus/types/src/withdrawal.rs
Labels: ready-for-review, capella

#3803 Publish capella images on push
  .github/workflows/docker.yml
Labels: infra-ci, capella

#3829 Handle peers sending no blob when the blob is empty in range responses
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/range.rs
  consensus/types/src/blobs_sidecar.rs
Labels: eip-4844

#3832 Remove sync validation no longer valid + Fix bakcfill batch sizes
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/batch.rs
Labels: eip-4844

#3833 Empty blobs validation
  beacon_node/beacon_chain/src/attester_cache.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/worker/sync_methods.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  consensus/types/src/blobs_sidecar.rs
  consensus/types/src/signed_beacon_block.rs
  consensus/types/src/signed_block_and_blobs.rs
  crypto/kzg/src/kzg_proof.rs
Labels: eip-4844

#3841 create automatic docker build for eip4844
  .github/workflows/docker.yml
Labels: eip-4844

#3840 Blob cleanup (renames, remove , wrap BlockWrapper enum)
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
  beacon_node/network/src/beacon_processor/worker/sync_methods.rs
  beacon_node/network/src/router/processor.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/mod.rs
  beacon_node/network/src/sync/range_sync/range.rs
  consensus/types/src/signed_block_and_blobs.rs
Labels: eip-4844
