Repository sigp/lighthouse, pull requests merged in 2023-07, with the labels that each got.

#4467 update get blobs endpoint name from blobs to blob_sidecars
  beacon_node/http_api/src/lib.rs
  common/eth2/src/lib.rs
Labels: ready-for-review, low-hanging-fruit, deneb

#4472 fix failing network tests
  beacon_node/network/src/beacon_processor/tests.rs
Labels: ready-for-review, low-hanging-fruit, deneb

#4471 remove clang from Dockerfile
  Dockerfile
  lcli/Dockerfile
  testing/antithesis/Dockerfile.libvoidstar
Labels: ready-for-review, low-hanging-fruit, deneb

#4470 remove patched dependencies
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/eth1/Cargo.toml
  beacon_node/execution_layer/Cargo.toml
  beacon_node/genesis/Cargo.toml
  beacon_node/http_api/Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/network/Cargo.toml
  beacon_node/operation_pool/Cargo.toml
  beacon_node/store/Cargo.toml
  common/deposit_contract/Cargo.toml
  common/eth2/Cargo.toml
  common/validator_dir/Cargo.toml
  consensus/cached_tree_hash/Cargo.toml
  consensus/fork_choice/Cargo.toml
  consensus/proto_array/Cargo.toml
  consensus/state_processing/Cargo.toml
  consensus/types/Cargo.toml
  crypto/bls/Cargo.toml
  crypto/kzg/Cargo.toml
  lcli/Cargo.toml
  slasher/Cargo.toml
  testing/ef_tests/Cargo.toml
  validator_client/Cargo.toml
Labels: ready-for-review, low-hanging-fruit, deneb

#4469 remove uninlined arg lint suppression
  Makefile
Labels: ready-for-review, low-hanging-fruit, deneb

#4468 remove spec minimal feature gating in tests
  .github/workflows/test-suite.yml
  .gitignore
  Makefile
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/sync/block_lookups/tests.rs
  lighthouse/Cargo.toml
Labels: ready-for-review, deneb

#4483 Single-pass epoch processing
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/http_api/src/validator_inclusion.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/state_processing/src/all_caches.rs
  consensus/state_processing/src/common/slash_validator.rs
  consensus/state_processing/src/common/update_progressive_balances_cache.rs
  consensus/state_processing/src/epoch_cache.rs
  consensus/state_processing/src/lib.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_epoch_processing.rs
  consensus/state_processing/src/per_epoch_processing/altair.rs
  consensus/state_processing/src/per_epoch_processing/altair/inactivity_updates.rs
  consensus/state_processing/src/per_epoch_processing/altair/justification_and_finalization.rs
  consensus/state_processing/src/per_epoch_processing/altair/participation_cache.rs
  consensus/state_processing/src/per_epoch_processing/altair/rewards_and_penalties.rs
  consensus/state_processing/src/per_epoch_processing/base.rs
  consensus/state_processing/src/per_epoch_processing/capella.rs
  consensus/state_processing/src/per_epoch_processing/effective_balance_updates.rs
  consensus/state_processing/src/per_epoch_processing/epoch_processing_summary.rs
  consensus/state_processing/src/per_epoch_processing/registry_updates.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/state_processing/src/per_epoch_processing/slashings.rs
  consensus/state_processing/src/upgrade/altair.rs
  consensus/state_processing/src/upgrade/capella.rs
  consensus/state_processing/src/upgrade/merge.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/compact_state.rs
  consensus/types/src/beacon_state/progressive_balances_cache.rs
  consensus/types/src/beacon_state/slashings_cache.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/epoch_cache.rs
  lcli/src/skip_slots.rs
  lcli/src/transition_blocks.rs
  testing/ef_tests/src/cases/epoch_processing.rs
  testing/ef_tests/src/cases/operations.rs
Labels: ready-for-review, consensus, tree-states

#4455 Add Changes to BlobSidecars Endpoint
  beacon_node/http_api/src/block_id.rs
  beacon_node/http_api/src/lib.rs
  common/eth2/src/types.rs
Labels: ready-for-review, HTTP-API, deneb

#4511 Refactor deneb block processing
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/status_tests.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
  consensus/fork_choice/tests/tests.rs
  consensus/state_processing/src/consensus_context.rs
  consensus/types/src/lib.rs
  consensus/types/src/signed_beacon_block.rs
Labels: deneb

#4535 API - Handle blocks without blobs gracefully
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/block_id.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
Labels: waiting-on-author, HTTP-API, deneb
