Repository sigp/lighthouse, pull requests merged in 2023-05, with the labels that each got.

#4252 Prepare CI for merge queues
  .github/workflows/docker.yml
  .github/workflows/linkcheck.yml
  .github/workflows/local-testnet.yml
  .github/workflows/test-suite.yml
Labels: ready-for-bors, infra-ci

#4250 fix check on max request size blobs by range
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
Labels: ready-for-review, low-hanging-fruit, deneb

#4274 Implement KZG EF Tests
  Cargo.lock
  beacon_node/beacon_chain/src/kzg_utils.rs
  crypto/kzg/src/lib.rs
  testing/ef_tests/Cargo.toml
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/kzg_blob_to_kzg_commitment.rs
  testing/ef_tests/src/cases/kzg_compute_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_compute_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof_batch.rs
  testing/ef_tests/src/cases/kzg_verify_kzg_proof.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: deneb

#4203 Implement Overflow LRU Cache for Pending Blobs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/eth1_finalization_cache.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/client/src/builder.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/ssz_derive/src/lib.rs
  consensus/ssz_derive/tests/tests.rs
  consensus/state_processing/src/consensus_context.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/fork_name.rs
  consensus/types/src/lib.rs
  consensus/types/src/signed_beacon_block.rs
Labels: waiting-on-author, deneb

#4289 fix count usage in blobs by range
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
Labels: ready-for-review, low-hanging-fruit, deneb

#4298 Fix db startup
  beacon_node/store/src/hot_cold_store.rs
Labels: bug, ready-for-review, low-hanging-fruit, deneb
