Repository sigp/lighthouse, pull requests merged in 2023-04, with the labels that each got.

#4153 Block processing cleanup
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  consensus/types/src/blob_sidecar.rs
Labels: deneb

#4161 Unified Availability Cache into One
  beacon_node/beacon_chain/src/data_availability_checker.rs
Labels: ready-for-review, deneb

#4209 Remove unused function and type
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
Labels: deneb

#4218 update blob transaction
  beacon_node/execution_layer/src/lib.rs
  consensus/state_processing/src/per_block_processing/deneb/deneb.rs
  consensus/types/src/transaction.rs
Labels: deneb

#4164 Gossip conditions deneb
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/observed_blob_sidecars.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
Labels: waiting-on-author, deneb

#4229 update blobs by range protocol name
  beacon_node/lighthouse_network/src/rpc/protocol.rs
Labels: ready-for-review, low-hanging-fruit, deneb

#4219 Gossip verification cleanup
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/observed_blob_sidecars.rs
Labels: ready-for-review, deneb

#4124 Fix deneb doppelganger tests
  .github/workflows/local-testnet.yml
  .github/workflows/test-suite.yml
  scripts/local_testnet/beacon_node.sh
  scripts/local_testnet/el_bootnode.sh
  scripts/local_testnet/setup.sh
  scripts/local_testnet/vars.env
  scripts/tests/doppelganger_protection.sh
  scripts/tests/genesis.json
  scripts/tests/vars.env
Labels: ready-for-review, deneb

#4206 Rename constant to match spec
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/client/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
  consensus/types/src/consts.rs
Labels: ready-for-review, deneb

#4223 Update `engine_api` to latest version
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/network/src/beacon_processor/tests.rs
  consensus/fork_choice/tests/tests.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/lib.rs
  crypto/kzg/src/kzg_commitment.rs
  crypto/kzg/src/lib.rs
  testing/node_test_rig/src/lib.rs
Labels: deneb
