Repository sigp/lighthouse, pull requests merged in 2023-11, with the labels that each got.

#4731 Add missed blocks to monitored validators
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/beacon_proposer_cache.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/validator_monitor.rs
  beacon_node/beacon_chain/tests/main.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/validator_monitor.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/http_api/src/proposer_duties.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
  beacon_node/src/config.rs
  consensus/types/src/beacon_state.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-bors, v4.6.0

#4902 Add block-v3 SSZ tests
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
Labels: ready-for-bors

#4903 Bulk Verify KZG During Sync / Backfill
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
Labels: ready-for-bors

#4906 Delete deprecated cli flags
  account_manager/src/validator/slashing_protection.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  lighthouse/src/main.rs
  lighthouse/tests/beacon_node.rs
  lighthouse/tests/validator_client.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
Labels: code-quality, ready-for-bors, backwards-incompat

#4749 Update local testnet doc and parameters
  scripts/local_testnet/README.md
  scripts/local_testnet/el_bootnode.sh
  scripts/local_testnet/setup.sh
  scripts/local_testnet/setup_time.sh
  scripts/local_testnet/start_local_testnet.sh
  scripts/local_testnet/vars.env
Labels: docs, ready-for-bors

#4892 Always use a separate database for blobs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/tests/op_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/src/lib.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/metadata.rs
  database_manager/src/lib.rs
Labels: ready-for-bors, database, backwards-incompat, deneb

#4922 Fix missed block logs
  beacon_node/beacon_chain/src/validator_monitor.rs
Labels: low-hanging-fruit, ready-for-bors, UX-and-logs

#4919 Remove legacy database migrations
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v12.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v13.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v14.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v15.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v16.rs
  beacon_node/beacon_chain/tests/store_tests.rs
Labels: code-quality, ready-for-bors, database

#4932 Fix Rust beta compiler warnings (rustc 1.75.0-beta.1)
  Makefile
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/genesis/src/eth1_genesis_service.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_metrics/src/metrics.rs
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  common/slot_clock/src/system_time_slot_clock.rs
  consensus/merkle_proof/src/lib.rs
  consensus/types/src/sync_aggregator_selection_data.rs
  testing/state_transition_vectors/src/exit.rs
  watch/src/blockprint/mod.rs
  watch/src/database/mod.rs
Labels: code-quality, ready-for-bors

#4927 Sidecar inclusion api updates
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/observed_blob_sidecars.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/builder_client/src/lib.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/http_api/src/build_block_contents.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/produce_block.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/fork_choice/src/lib.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/builder_bid.rs
  consensus/types/src/lib.rs
  consensus/types/src/payload.rs
  consensus/types/src/sidecar.rs
  consensus/types/src/signed_beacon_block.rs
  testing/ef_tests/Makefile
  testing/ef_tests/src/cases/fork_choice.rs
  testing/ef_tests/src/cases/merkle_proof_validity.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
  validator_client/src/block_service.rs
Labels: deneb

#4939 Add more block v3 tests
  beacon_node/http_api/tests/tests.rs
Labels: test improvement, ready-for-review

#4949 Sidecar inclusion self review cleanup
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  common/eth2/src/types.rs
  consensus/types/presets/gnosis/deneb.yaml
  consensus/types/presets/mainnet/deneb.yaml
  consensus/types/presets/minimal/deneb.yaml
  consensus/types/src/beacon_block_header.rs
  consensus/types/src/blob_sidecar.rs
  testing/ef_tests/Cargo.toml
  testing/ef_tests/src/cases/fork_choice.rs
  testing/ef_tests/src/cases/merkle_proof_validity.rs
Labels: ready-for-review, deneb

#4920 Broadcast various requests as per #4684
  Cargo.lock
  lighthouse/tests/validator_client.rs
  testing/node_test_rig/Cargo.toml
  testing/node_test_rig/src/lib.rs
  testing/simulator/src/eth1_sim.rs
  testing/simulator/src/local_network.rs
  validator_client/Cargo.toml
  validator_client/src/attestation_service.rs
  validator_client/src/beacon_node_fallback.rs
  validator_client/src/block_service.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/duties_service.rs
  validator_client/src/lib.rs
  validator_client/src/preparation_service.rs
  validator_client/src/sync_committee_service.rs
Labels: val-client, waiting-on-author

#4956 Remove block-delay-ms
  lighthouse/tests/validator_client.rs
  validator_client/src/block_service.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/lib.rs
Labels: low-hanging-fruit, ready-for-bors, v4.6.0

#3954 API for `LightClientBootstrap`, `LightClientFinalityUpdate`, `LightClientOptimisticUpdate` and light client events
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/events.rs
  beacon_node/beacon_chain/src/light_client_finality_update_verification.rs
  beacon_node/beacon_chain/src/light_client_optimistic_update_verification.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/src/config.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/state_processing/src/upgrade/altair.rs
  consensus/types/src/lib.rs
  consensus/types/src/light_client_bootstrap.rs
  consensus/types/src/light_client_finality_update.rs
  consensus/types/src/light_client_header.rs
  consensus/types/src/light_client_optimistic_update.rs
  consensus/types/src/light_client_update.rs
  consensus/types/src/sync_committee.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-bors, HTTP-API, light-client

#4587 Add `lcli mock-el`
  Cargo.lock
  lcli/Cargo.toml
  lcli/src/main.rs
  lcli/src/mock_el.rs
Labels: ready-for-bors

#4957 Clean-up re-org tests
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_times_cache.rs
  beacon_node/execution_layer/src/lib.rs
  testing/ef_tests/Cargo.toml
  testing/ef_tests/src/cases/fork_choice.rs
Labels: ready-for-review, deneb

#4925 Clone state ahead of block production
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/state_advance_timer.rs
Labels: ready-for-review, optimization, v4.6.0

#4853 Standard Liveness Endpoint
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
  validator_client/src/doppelganger_service.rs
Labels: val-client, ready-for-bors, backwards-incompat, v4.6.0
