Repository sigp/lighthouse, pull requests merged in 2023-02, with the labels that each got.

#3934 Use Local Payload if More Profitable than Builder
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/http_api/tests/tests.rs
  consensus/types/src/execution_payload.rs
Labels: capella

#3942 Remove unused `u256_hex_be_opt`
  consensus/serde_utils/src/lib.rs
  consensus/serde_utils/src/u256_hex_be_opt.rs
Labels: ready-for-review, low-hanging-fruit, capella

#3919 Broadcast address changes at Capella
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v15.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/address_change_broadcast.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/lib.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/fork_tests.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/operation_pool/Cargo.toml
  beacon_node/operation_pool/src/bls_to_execution_changes.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/operation_pool/src/persistence.rs
  beacon_node/store/src/metadata.rs
  consensus/types/src/bls_to_execution_change.rs
  consensus/types/src/signed_bls_to_execution_change.rs
Labels: ready-for-review, backwards-incompat, capella

#3941 Blob decoding
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/lib.rs
  consensus/types/src/kzg_commitment.rs
  consensus/types/src/kzg_proof.rs
  consensus/types/src/lib.rs
  consensus/types/src/transaction.rs
Labels: ready-for-review, eip-4844

#3852 Prune blobs
  .gitignore
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/validator_pubkey_cache.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/impls/execution_payload.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metadata.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/types/src/slot_epoch.rs
  database_manager/src/lib.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-review, eip-4844

#3958 Update Mock Builder for Post-Capella Tests
  Cargo.lock
  Cargo.toml
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/http_api/tests/tests.rs
Labels: ready-for-review, capella

#3869 Blobs freezer
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/validator_pubkey_cache.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/http_api/src/block_id.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  beacon_node/store/src/garbage_collection.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metadata.rs
  database_manager/src/lib.rs
Labels: ready-for-bors, eip-4844

#3951 Encode blob transactions as signed blob transactions
  beacon_node/execution_layer/src/lib.rs
  consensus/types/src/transaction.rs
Labels: ready-for-review, eip-4844

#3973 Update Capella to latest `unstable`
  .github/workflows/docker.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  Makefile
  beacon_node/beacon_chain/src/attestation_rewards.rs
  beacon_node/beacon_chain/src/beacon_block_reward.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/validator_pubkey_cache.rs
  beacon_node/execution_layer/src/engines.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/standard_block_rewards.rs
  beacon_node/http_api/src/sync_committee_rewards.rs
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/rpc/config.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/rpc/rate_limiter.rs
  beacon_node/lighthouse_network/src/rpc/self_limiter.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  book/src/docker.md
  book/src/validator-inclusion.md
  common/eth2/src/lib.rs
  common/eth2/src/lighthouse.rs
  common/eth2/src/lighthouse/attestation_rewards.rs
  common/eth2/src/lighthouse/standard_block_rewards.rs
  common/eth2/src/lighthouse/sync_committee_rewards.rs
  common/eth2/src/types.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/proto_array/src/fork_choice_test_definition.rs
  consensus/proto_array/src/proto_array.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/serde_utils/src/lib.rs
  consensus/serde_utils/src/quoted_int.rs
  lighthouse/tests/beacon_node.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/duties_service.rs
  validator_client/src/http_metrics/metrics.rs
  validator_client/src/lib.rs
Labels: ready-for-review, capella, v3.5.0

#3967 Quote Capella BeaconState fields
  consensus/types/src/beacon_state.rs
Labels: ready-for-review, low-hanging-fruit, HTTP-API, capella

#3976 Simplify payload traits and reduce cloning
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/lighthouse_network/src/rpc/config.rs
  beacon_node/lighthouse_network/src/rpc/self_limiter.rs
  consensus/state_processing/src/per_block_processing/block_signature_verifier.rs
  consensus/state_processing/src/per_block_processing/verify_bls_to_execution_change.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/payload.rs
Labels: ready-for-review, capella

#3905 Debug CI
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/attester_cache.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/validator_pubkey_cache.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/op_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/execution_layer/src/block_hash.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/http_api/src/block_id.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/common.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/network/src/beacon_processor/tests.rs
  beacon_node/network/src/service/tests.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
  beacon_node/store/src/hot_cold_store.rs
  common/eth2_network_config/built_in_network_configs/eip4844/config.yaml
  common/eth2_network_config/src/lib.rs
  common/slot_clock/src/lib.rs
  consensus/ssz/src/decode/impls.rs
  consensus/state_processing/src/per_block_processing/eip4844/eip4844.rs
  consensus/state_processing/src/per_block_processing/tests.rs
  consensus/tree_hash/src/lib.rs
  consensus/types/Cargo.toml
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/blobs_sidecar.rs
  consensus/types/src/lib.rs
  consensus/types/src/signed_beacon_block.rs
  crypto/kzg/Cargo.toml
  crypto/kzg/src/kzg_commitment.rs
  crypto/kzg/src/kzg_proof.rs
  crypto/kzg/src/lib.rs
  lcli/src/new_testnet.rs
  lighthouse/tests/beacon_node.rs
  testing/ef_tests/src/cases/fork_choice.rs
  validator_client/slashing_protection/Cargo.toml
  validator_client/slashing_protection/src/slashing_database.rs
Labels: waiting-on-author, eip-4844

#3983 Suggestions for Capella `execution_layer`
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/engines.rs
  beacon_node/execution_layer/src/lib.rs
  consensus/ssz_types/src/variable_list.rs
Labels: ready-for-review, capella

#3981 Update `capella` to `unstable`
  .github/workflows/docker.yml
  .github/workflows/test-suite.yml
  Cargo.lock
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
  common/lru_cache/src/time.rs
  common/slot_clock/src/manual_slot_clock.rs
  consensus/types/Cargo.toml
  lighthouse/tests/beacon_node.rs
  testing/execution_engine_integration/Cargo.toml
  testing/execution_engine_integration/src/test_rig.rs
  validator_client/slashing_protection/Cargo.toml
  validator_client/slashing_protection/src/slashing_database.rs
Labels: ready-for-review, capella

#3997 Add Capella fork epoch for Sepolia
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
Labels: ready-for-review, capella

#4004 Fix Capella schema downgrades
  beacon_node/beacon_chain/src/schema_change/migration_schema_v14.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v15.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/operation_pool/src/persistence.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  book/src/database-migrations.md
Labels: ready-for-bors, capella, v3.5.0

#4008 Remove "eip4844" network config from Capella
  common/eth2_config/src/lib.rs
  common/eth2_network_config/built_in_network_configs/eip4844/boot_enr.yaml
  common/eth2_network_config/built_in_network_configs/eip4844/config.yaml
  common/eth2_network_config/built_in_network_configs/eip4844/deploy_block.txt
  common/eth2_network_config/built_in_network_configs/eip4844/genesis.ssz.zip
Labels: ready-for-bors, capella

#3999 Suggestions for Capella `beacon_chain`
  beacon_node/beacon_chain/src/capella_readiness.rs
  beacon_node/client/src/notifier.rs
Labels: ready-for-bors, capella, v3.5.0

#4012 Capella consensus review
  consensus/state_processing/src/per_block_processing.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/free_attestation.rs
  consensus/types/src/lib.rs
Labels: ready-for-review, capella, v3.5.0

#4013 Revert change to Sepolia `genesis.ssz.zip`
  common/eth2_network_config/built_in_network_configs/sepolia/genesis.ssz.zip
Labels: ready-for-bors, capella, v3.5.0

#4011 Allow for withdrawals in max block size
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  consensus/types/src/beacon_block.rs
Labels: ready-for-review, capella, v3.5.0

#4014 Fix post-Bellatrix checkpoint sync
  consensus/fork_choice/src/fork_choice.rs
Labels: ready-for-review, capella, v3.5.0

#4015 Modify some Capella comments
  consensus/fork_choice/src/fork_choice.rs
  consensus/state_processing/src/per_block_processing/verify_bls_to_execution_change.rs
Labels: ready-for-review, capella, v3.5.0

#4016 Don't subscribe to 4844 topics
  beacon_node/lighthouse_network/src/types/topics.rs
Labels: v3.5.0

#4020 Fix block queue metric in beacon processor
  beacon_node/network/src/beacon_processor/mod.rs
Labels: ready-for-bors, capella, v3.5.0
