Repository sigp/lighthouse, pull requests merged in 2023-01, with the labels that each got.

#3846 Dont verify the signature of the genesis block in backfill sync
  beacon_node/beacon_chain/src/historical_blocks.rs
Labels: eip-4844

#3848 Don't write empty blobs to db
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
Labels: ready-for-review, eip-4844

#3845 Capella cleanup
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
  beacon_node/network/src/sync/manager.rs
  common/eth2/src/lib.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/payload.rs
  lcli/src/create_payload_header.rs
  lcli/src/main.rs
  lcli/src/new_testnet.rs
  validator_client/src/signing_method.rs
  validator_client/src/signing_method/web3signer.rs
Labels: ready-for-review, capella

#3860 Bump MSRV to 1.65 for Capella
  lighthouse/Cargo.toml
Labels: capella

#3851 Embed trusted setup in network config
  Cargo.lock
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  common/eth2_network_config/Cargo.toml
  common/eth2_network_config/built_in_network_configs/testing_trusted_setups.json
  common/eth2_network_config/src/lib.rs
  crypto/kzg/Cargo.toml
  crypto/kzg/src/lib.rs
  crypto/kzg/src/trusted_setup.rs
  scripts/local_testnet/beacon_node.sh
  scripts/local_testnet/trusted_setup.txt
Labels: ready-for-review, eip-4844

#3865 add historical summaries
  beacon_node/store/src/chunked_vector.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/partial_beacon_state.rs
  consensus/state_processing/src/per_epoch_processing.rs
  consensus/state_processing/src/per_epoch_processing/capella.rs
  consensus/state_processing/src/per_epoch_processing/capella/historical_summaries_update.rs
  consensus/state_processing/src/upgrade/capella.rs
  consensus/state_processing/src/upgrade/eip4844.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/tree_hash_cache.rs
  consensus/types/src/historical_summary.rs
  consensus/types/src/lib.rs
  lcli/src/main.rs
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/epoch_processing.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/src/lib.rs
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-review, capella

#3864 Remove `withdrawals-processing` feature
  .github/workflows/docker.yml
  Makefile
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/client/src/builder.rs
  beacon_node/eth1/src/inner.rs
  beacon_node/eth1/src/service.rs
  beacon_node/eth1/tests/test.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/store/Cargo.toml
  consensus/state_processing/Cargo.toml
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  lighthouse/Cargo.toml
  testing/execution_engine_integration/src/test_rig.rs
Labels: ready-for-bors, capella

#3871 Back-merge unstable to Capella
  .github/workflows/test-suite.yml
  Cargo.lock
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/validator_monitor.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/builder_client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/block_hash.rs
  beacon_node/execution_layer/src/keccak.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/metrics.rs
  beacon_node/http_api/tests/common.rs
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/client.rs
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/service/behaviour.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/lighthouse_network/tests/common/behaviour.rs
  beacon_node/lighthouse_network/tests/common/swarm.rs
  beacon_node/lighthouse_network/tests/pm_tests.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/subnet_service/tests/mod.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  boot_node/Cargo.toml
  bors.toml
  common/clap_utils/Cargo.toml
  common/eth2_network_config/built_in_network_configs/gnosis/boot_enr.yaml
  common/lighthouse_version/src/lib.rs
  consensus/cached_tree_hash/Cargo.toml
  consensus/merkle_proof/Cargo.toml
  consensus/serde_utils/Cargo.toml
  consensus/ssz/Cargo.toml
  consensus/swap_or_not_shuffle/Cargo.toml
  consensus/tree_hash/Cargo.toml
  consensus/types/Cargo.toml
  consensus/types/src/execution_block_header.rs
  consensus/types/src/historical_summary.rs
  consensus/types/src/lib.rs
  consensus/types/src/payload.rs
  crypto/bls/Cargo.toml
  lcli/Cargo.toml
  lighthouse/Cargo.toml
  lighthouse/tests/beacon_node.rs
  testing/ef_tests/Cargo.toml
  testing/execution_engine_integration/Cargo.toml
  testing/node_test_rig/Cargo.toml
  validator_client/src/initialized_validators.rs
Labels: ready-for-review, capella

#3874 Fix some beacon_chain tests
  beacon_node/beacon_chain/tests/capella.rs
  beacon_node/beacon_chain/tests/merge.rs
Labels: ready-for-review, capella

#3877 Verify blockHash with withdrawals
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/execution_layer/src/block_hash.rs
  consensus/types/src/execution_block_header.rs
Labels: ready-for-review, capella

#3881 bump ef-tests
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
Labels: capella

#3893 Update engine_api to Latest spec
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
Labels: capella

#3897 execution API related fixes after capella merge
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
Labels: ready-for-review, eip-4844

#3892 Import BLS to execution changes before Capella
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/fork_tests.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/operation_pool/src/bls_to_execution_changes.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/operation_pool/src/persistence.rs
  common/eth2/src/lib.rs
  consensus/state_processing/src/verify_operation.rs
  consensus/types/src/bls_to_execution_change.rs
Labels: ready-for-review, capella

#3898 Use eth1_withdrawal_credentials in Test States
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/sync_committee_verification.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/genesis/src/interop.rs
  beacon_node/genesis/src/lib.rs
  consensus/types/src/beacon_state/tests.rs
Labels: waiting-on-author, capella

#3914 Fix the new BLS to execution change test
  Cargo.lock
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/light_client_optimistic_update_verification.rs
  beacon_node/beacon_chain/src/sync_committee_rewards.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/main.rs
  beacon_node/beacon_chain/tests/rewards.rs
  beacon_node/genesis/src/interop.rs
  beacon_node/genesis/src/lib.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/sync_committee_rewards.rs
  beacon_node/http_api/tests/common.rs
  beacon_node/http_api/tests/fork_tests.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/work_reprocessing_queue.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/network/src/beacon_processor/worker/sync_methods.rs
  beacon_node/network/src/metrics.rs
  common/eth2/src/lib.rs
  common/eth2/src/lighthouse.rs
  common/eth2/src/lighthouse/sync_committee_rewards.rs
Labels: capella

#3910 Block wrapper refactor
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/work_reprocessing_queue.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/network/src/beacon_processor/worker/sync_methods.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
  consensus/state_processing/src/consensus_context.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/eip4844/eip4844.rs
  consensus/types/src/signed_beacon_block.rs
  consensus/types/src/signed_block_and_blobs.rs
Labels: ready-for-review, eip-4844

#3912 Sync error handling
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
  consensus/types/src/signed_beacon_block.rs
Labels: eip-4844

#3915 built in devnetv4 config eip4844
  common/eth2_network_config/built_in_network_configs/eip4844/boot_enr.yaml
  common/eth2_network_config/built_in_network_configs/eip4844/config.yaml
  common/eth2_network_config/built_in_network_configs/eip4844/genesis.ssz.zip
Labels: eip-4844

#3921 Eip4844 capella rebase
  .cargo/config.toml
  .github/workflows/docker.yml
  .github/workflows/test-suite.yml
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/light_client_optimistic_update_verification.rs
  beacon_node/beacon_chain/src/sync_committee_rewards.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/main.rs
  beacon_node/beacon_chain/tests/rewards.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/sync_committee_verification.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/genesis/src/interop.rs
  beacon_node/genesis/src/lib.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/sync_committee_rewards.rs
  beacon_node/http_api/tests/common.rs
  beacon_node/http_api/tests/fork_tests.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/work_reprocessing_queue.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/network/src/beacon_processor/worker/sync_methods.rs
  beacon_node/network/src/metrics.rs
  beacon_node/operation_pool/src/bls_to_execution_changes.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/operation_pool/src/persistence.rs
  book/src/checkpoint-sync.md
  book/src/installation-source.md
  book/src/merge-migration.md
  book/src/run_a_node.md
  bors.toml
  common/eth2/src/lib.rs
  common/eth2/src/lighthouse.rs
  common/eth2/src/lighthouse/sync_committee_rewards.rs
  common/malloc_utils/Cargo.toml
  common/malloc_utils/src/jemalloc.rs
  common/malloc_utils/src/lib.rs
  consensus/state_processing/src/verify_operation.rs
  consensus/types/src/beacon_state/tests.rs
  consensus/types/src/bls_to_execution_change.rs
  lcli/Cargo.toml
  lcli/src/main.rs
  lighthouse/Cargo.toml
  lighthouse/environment/src/lib.rs
  lighthouse/src/main.rs
  lighthouse/tests/beacon_node.rs
  testing/antithesis/Dockerfile.libvoidstar
  testing/simulator/src/eth1_sim.rs
  testing/simulator/src/no_eth1_sim.rs
  testing/simulator/src/sync_sim.rs
  validator_client/src/block_service.rs
  validator_client/src/lib.rs
Labels: eip-4844

#3920 Fix and loosen execution block decoding
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/execution_layer/src/block_hash.rs
  beacon_node/network/src/beacon_processor/work_reprocessing_queue.rs
  consensus/types/src/execution_block_header.rs
Labels: eip-4844

#3926 send stream terminators
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
Labels: eip-4844

#3918 exchangeCapabilities & Capella Readiness Logging
  beacon_node/beacon_chain/src/capella_readiness.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/merge_readiness.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/notifier.rs
  beacon_node/eth1/src/inner.rs
  beacon_node/eth1/src/service.rs
  beacon_node/eth1/tests/test.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engines.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  testing/execution_engine_integration/src/test_rig.rs
Labels: ready-for-review, capella
