Repository sigp/lighthouse, pull requests merged in 2023-10, with the labels that each got.

#4732 add processing and processed caching to the DA checker
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/availability_view.rs
  beacon_node/beacon_chain/src/data_availability_checker/child_components.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/processing_cache.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/delayed_lookup.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/mod.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/signed_beacon_block.rs
  testing/ef_tests/src/cases/fork_choice.rs
Labels: ready-for-review, deneb

#4810 Address Clippy 1.73 lints on Deneb branch
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/eth1_finalization_cache.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/http_api/src/standard_block_rewards.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/score.rs
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/store/src/memory_store.rs
  consensus/types/src/blob_sidecar.rs
  validator_client/src/attestation_service.rs
  validator_client/src/duties_service/sync.rs
Labels: ready-for-review, deneb

#4801 Prevent Overflow LRU Cache from Exploding
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/availability_view.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  consensus/types/src/beacon_state.rs
Labels: ready-for-review, optimization, deneb

#4824 Delete unused ssz_types file
  consensus/ssz_types/src/serde_utils/list_of_hex_fixed_vec.rs
Labels: ready-for-review, low-hanging-fruit, deneb

#4790 Add `blob_sidecar` event to SSE
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/events.rs
  beacon_node/beacon_chain/tests/events.rs
  beacon_node/beacon_chain/tests/main.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  common/eth2/src/types.rs
Labels: ready-for-review, deneb

#4833 Fix cache logic for epoch boundary skips
  beacon_node/store/src/state_cache.rs
Labels: ready-for-review, tree-states

#4845 Very minor own nitpicks
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  book/src/developers.md
Labels: deneb

#4851 Deneb pr updates 2
  Cargo.lock
  beacon_node/client/src/builder.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/http_api/src/block_id.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  consensus/types/src/chain_spec.rs
  crypto/kzg/Cargo.toml
Labels: ready-for-review, deneb

#4861 Various small tree-states fixes
  .github/workflows/release.yml
  Dockerfile
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/metadata.rs
  book/src/api-lighthouse.md
  database_manager/src/lib.rs
  lcli/src/skip_slots.rs
Labels: tree-states

#4881 Handle out-of-order forks in epoch cache
  consensus/state_processing/src/epoch_cache.rs
Labels: consensus, tree-states
