Repository sigp/lighthouse, pull requests merged in 2023-12, with the labels that each got.

#4960 Fix cache initialization in block rewards API
  beacon_node/beacon_chain/src/beacon_block_reward.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/errors.rs
Labels: HTTP-API, tree-states

#4967 Sidecar Inclusion proof small refactor and updates
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/observed_blob_sidecars.rs
  beacon_node/execution_layer/src/lib.rs
  common/eth2/src/types.rs
Labels: ready-for-review, deneb

#4970 Make sure gossip invalid blobs are passed to the slasher
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  testing/ef_tests/src/cases/fork_choice.rs
Labels: ready-for-merge, deneb

#4974 Rename the block and blob wrapper types used in the beacon API interfaces
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/http_api/src/build_block_contents.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  validator_client/src/block_service.rs
Labels: ready-for-review, deneb

#4977 Fix stuck linkcheck on CI
  .github/workflows/linkcheck.yml
Labels: ready-for-review, infra-ci

#4958 EIP-3076 tests - complete database
  validator_client/slashing_protection/Makefile
  validator_client/slashing_protection/src/bin/test_generator.rs
  validator_client/slashing_protection/src/interchange_test.rs
Labels: test improvement, val-client, ready-for-merge, v4.6.0

#4571 CLI in Lighthouse Book
  .github/workflows/test-suite.yml
  Makefile
  book/src/SUMMARY.md
  book/src/help_bn.md
  book/src/help_general.md
  book/src/help_vc.md
  book/src/help_vm.md
  book/src/help_vm_create.md
  book/src/help_vm_import.md
  book/src/help_vm_move.md
  scripts/cli.sh
Labels: docs, ready-for-merge, infra-ci

#4935 upgrade libp2p to v0.53.*
  Cargo.lock
  Dockerfile
  beacon_node/client/src/builder.rs
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/service.rs
  lighthouse/Cargo.toml
Labels: ready-for-review, t Networking

#4982 Update docs for v4.6.0
  book/src/database-migrations.md
  book/src/redundancy.md
Labels: docs, low-hanging-fruit, ready-for-merge, v4.6.0

#4872 Implement POST validators/validator_balances APIs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/validators.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
Labels: enhancement, optimization, ready-for-merge, HTTP-API, v4.6.0

#4992 Remove delayed lookups
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
Labels: deneb

#4934 Batch Verify RPC Blobs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
Labels: ready-for-review, deneb

#4383 Disable flood publishing
  beacon_node/lighthouse_network/src/config.rs
Labels: RFC, ready-for-review, v4.6.0

#4917 Add `mergify` merge queue configuration file
  .github/mergify.yml
  .github/workflows/local-testnet.yml
  .github/workflows/test-suite.yml
  scripts/ci/check-success-job.sh
Labels: ready-for-merge, infra-ci, v4.6.0

#5002 Update Rust version in lcli `Dockerfile`.
  lcli/Dockerfile
Labels: ready-for-review

#4978 Block Verification Optimization
  beacon_node/beacon_chain/src/block_verification.rs
Labels: optimization, ready-for-merge

#5003 Optimise block_root computation in gossip verification
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/metrics.rs
Labels: optimization, ready-for-merge

#4880 Add attestation simulator
  beacon_node/beacon_chain/src/attestation_simulator.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/validator_monitor.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/validator_monitor.rs
  beacon_node/client/src/builder.rs
Labels: ready-for-merge

#5005 Fix the blinded v2 flow for local payloads
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/execution_layer/src/lib.rs
Labels: deneb

#5009 Add flag to disable warning logs for duplicate gossip messages
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  book/src/redundancy.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, v4.6.0

#5012 Fix off-by-one bug in missed block detection
  beacon_node/beacon_chain/src/validator_monitor.rs
  beacon_node/beacon_chain/tests/validator_monitor.rs
Labels: bug, ready-for-merge, UX-and-logs, v4.6.0

#4994 Update dependencies to get rid of the yanked deps
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/beacon_proposer_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/pre_finalization_cache.rs
  beacon_node/execution_layer/src/engines.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/payload_cache.rs
  beacon_node/http_api/src/block_rewards.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
  common/account_utils/src/validator_definitions.rs
  consensus/types/src/lib.rs
  consensus/types/src/non_zero_usize.rs
  lighthouse/tests/beacon_node.rs
  slasher/src/config.rs
  watch/Cargo.toml
  watch/src/cli.rs
  watch/src/server/error.rs
  watch/src/server/mod.rs
  watch/tests/tests.rs
Labels: ready-for-review, dependencies, v4.6.0

#5014 Fix incorrect blob queue metrics
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
Labels: ready-for-review, deneb

#4995 Suppress error on duplicate blobs, track slashable blobs in blob gossip cache
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/observed_blob_sidecars.rs
  beacon_node/beacon_chain/src/observed_block_producers.rs
  beacon_node/http_api/src/publish_blocks.rs
Labels: ready-for-review, deneb

#4961 Information for network testing
  testing/network_testing/README.md
Labels: ready-for-review, t Networking

#5015 Clean up blockv3 metadata and client
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/produce_block.rs
  beacon_node/http_api/src/version.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/fork_versioned_response.rs
  validator_client/src/lib.rs
Labels: enhancement, ready-for-review, HTTP-API

#5024 Bump `zerocopy` to address rustsec vuln
  Cargo.lock
Labels: ready-for-review
