Repository sigp/lighthouse, pull requests merged in 2023-03, with the labels that each got.

#4059 fix rpc types to free the blobs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
  consensus/types/src/blob_sidecar.rs
Labels: deneb

#4077 Update kzg interface
  Cargo.lock
  beacon_node/beacon_chain/src/kzg_utils.rs
  crypto/kzg/Cargo.toml
  crypto/kzg/src/kzg_commitment.rs
  crypto/kzg/src/kzg_proof.rs
  crypto/kzg/src/lib.rs
Labels: deneb

#4078 Update signed blob sidecar container
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  consensus/types/src/signed_blob.rs
Labels: deneb

#4086 Fix block and blob coupling in the network context
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
Labels: deneb

#4094 Free blob lints
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/http_api/src/build_block_contents.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  common/eth2/src/types.rs
  consensus/types/src/lib.rs
  consensus/types/src/signed_block_and_blobs.rs
  consensus/types/src/signed_block_contents.rs
  validator_client/src/block_service.rs
Labels: ready-for-review, deneb

#4096 Validator blob signing for the unblinded flow
  common/eth2/src/types.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/config_and_preset.rs
  consensus/types/src/signed_blob.rs
  validator_client/src/block_service.rs
  validator_client/src/signing_method.rs
  validator_client/src/validator_store.rs
Labels: ready-for-review, deneb

#4109 Update get blobs endpoint to return a list of BlobSidecars
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/http_api/src/block_id.rs
  beacon_node/http_api/src/lib.rs
  common/eth2/src/lib.rs
Labels: ready-for-review, deneb

#4104 Update Blob Storage Structure
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/http_api/src/block_id.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  consensus/tree_hash/src/impls.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/signed_blob.rs
Labels: deneb

#4123 Release Candidate v4.0.1-rc.0
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-review

#4131 use block wrapper in sync pairing
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/network_context.rs
Labels: deneb

#4142 Ef test version update
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/merkle_proof_validity.rs
  testing/ef_tests/src/handler.rs
Labels: ready-for-review, deneb

#4137 clean up blobs by range response
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
Labels: ready-for-review, deneb

#4136 clean up blob by root response
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/worker/rpc_methods.rs
Labels: ready-for-review, deneb
