Repository sigp/lighthouse, pull requests merged in 2023-06, with the labels that each got.

#4307 Validate & Store Blobs During Backfill
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/database.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/network/src/beacon_processor/worker/sync_methods.rs
Labels: ready-for-review, deneb

#4375 update automatic docker builds for the correct branch
  .github/workflows/docker.yml
Labels: deneb

#4391 Update max blobs per block
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  consensus/types/src/consts.rs
  consensus/types/src/eth_spec.rs
Labels: ready-for-review

#4392 Deneb merge from unstable 20230613
  .github/workflows/test-suite.yml
  Makefile
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/client/Cargo.toml
  beacon_node/execution_layer/src/lib.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  beacon_node/store/Cargo.toml
  book/src/imgs/ui-dash-logs.png
  book/src/imgs/ui-logs.png
  book/src/installation-source.md
  book/src/slasher.md
  book/src/ui-faqs.md
  book/src/ui-usage.md
  lighthouse/Cargo.toml
  lighthouse/tests/beacon_node.rs
  slasher/Cargo.toml
  slasher/service/Cargo.toml
  slasher/src/config.rs
  slasher/src/lib.rs
  slasher/tests/backend.rs
  validator_client/src/block_service.rs
Labels: deneb

#4152 Single blob lookups
  .github/workflows/test-suite.yml
  Cargo.lock
  Makefile
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/observed_blob_sidecars.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/beacon_processor/mod.rs
  beacon_node/network/src/beacon_processor/work_reprocessing_queue.rs
  beacon_node/network/src/beacon_processor/worker/gossip_methods.rs
  beacon_node/network/src/beacon_processor/worker/sync_methods.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/subnet_service/attestation_subnets.rs
  beacon_node/network/src/subnet_service/sync_subnets.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
  beacon_node/network/src/sync/block_lookups/delayed_lookup.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/range.rs
  beacon_node/store/src/hot_cold_store.rs
  common/slot_clock/src/lib.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/proto_array/src/fork_choice_test_definition.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/state_processing/src/per_slot_processing.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/signed_beacon_block.rs
  consensus/types/src/test_utils/test_random/bitfield.rs
Labels: ready-for-review, deneb

#4414 Address clippy lints in `tree-states`
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/sync_committee_rewards.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/genesis/src/interop.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/hdiff.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/leveldb_store.rs
  consensus/fork_choice/tests/tests.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_block_processing/tests.rs
  consensus/state_processing/src/per_block_processing/verify_attestation.rs
  consensus/types/src/beacon_state/tests.rs
  consensus/types/src/validator.rs
  lcli/src/new_testnet.rs
  lcli/src/state_diff.rs
  lcli/src/transition_blocks.rs
  testing/ef_tests/src/case_result.rs
  testing/ef_tests/src/cases/epoch_processing.rs
  testing/ef_tests/src/cases/operations.rs
  testing/ef_tests/src/cases/sanity_blocks.rs
  testing/ef_tests/src/cases/sanity_slots.rs
  testing/state_transition_vectors/src/exit.rs
  watch/src/updater/mod.rs
Labels: ready-for-review, tree-states

#4420 Configurable diff buffer cache size
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
Labels: ready-for-review, low-hanging-fruit, tree-states

#4416 Use rebasing to minimise BeaconState mem usage
  Cargo.lock
  beacon_node/store/src/hot_cold_store.rs
  consensus/types/Cargo.toml
  consensus/types/src/beacon_state.rs
Labels: ready-for-review, tree-states

#4423 Fix failing tests
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/http_api/tests/fork_tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  consensus/types/benches/benches.rs
  consensus/types/src/beacon_state.rs
  lighthouse/Cargo.toml
  lighthouse/tests/beacon_node.rs
  scripts/local_testnet/beacon_node.sh
  slasher/Cargo.toml
  testing/ef_tests/Cargo.toml
  testing/ef_tests/src/cases/operations.rs
  testing/ef_tests/src/cases/ssz_generic.rs
  testing/ef_tests/tests/tests.rs
Labels: work-in-progress, tree-states

#4441 Fix db-migration-period default
  beacon_node/src/cli.rs
  common/lighthouse_version/src/lib.rs
Labels: work-in-progress, tree-states

#4451 update clang in cross docker
  scripts/cross/Dockerfile
Labels: ready-for-review, low-hanging-fruit, deneb

#4454 Fix EpochCache handling in ef-tests
  consensus/state_processing/src/epoch_cache.rs
  consensus/state_processing/src/per_epoch_processing/altair.rs
  consensus/state_processing/src/per_epoch_processing/base.rs
  consensus/state_processing/src/per_epoch_processing/capella.rs
  consensus/types/src/beacon_state.rs
  testing/ef_tests/src/cases/epoch_processing.rs
  testing/ef_tests/src/cases/operations.rs
Labels: ready-for-review, tree-states
