Repository sigp/lighthouse, pull requests merged in 2023-08, with the labels that each got.

#4547 Fix todos in deneb code
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  common/eth2/src/types.rs
  common/eth2_network_config/built_in_network_configs/deneb/config.yaml
  consensus/types/src/eth_spec.rs
  consensus/types/src/test_utils/test_random/kzg_proof.rs
  crypto/kzg/src/lib.rs
Labels: ready-for-review, deneb

#4570 Fix execution block generator bug
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
Labels: deneb

#4561 Refactor deneb networking
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-review, deneb

#4573 Optimise mutations in single-pass epoch processing
  Cargo.lock
  consensus/state_processing/src/common/initiate_validator_exit.rs
  consensus/state_processing/src/genesis.rs
  consensus/state_processing/src/per_epoch_processing/effective_balance_updates.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
Labels: work-in-progress, tree-states

#4576 Fix deadlock in finalization migration
  beacon_node/beacon_chain/src/migrate.rs
Labels: tree-states

#4579 Improve single block/blob logging
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-review, low-hanging-fruit, deneb

#4589 Fix genesis state storage for genesis sync
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/store/src/hot_cold_store.rs
Labels: tree-states

#4518 Changes for `devnet-8`
  account_manager/src/validator/exit.rs
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_block_reward.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/execution_layer/src/block_hash.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/operation_pool/src/attestation.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  common/eth2/src/types.rs
  consensus/state_processing/src/common/get_attestation_participation.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
  consensus/state_processing/src/per_block_processing/verify_attestation.rs
  consensus/types/src/execution_block_header.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/voluntary_exit.rs
  lighthouse/tests/beacon_node.rs
  testing/ef_tests/Makefile
  testing/ef_tests/src/cases/operations.rs
  testing/execution_engine_integration/src/test_rig.rs
  validator_client/src/validator_store.rs
Labels: consensus, deneb, deneb-devnet-8

#4591 Merge unstable deneb aug 9
  Cargo.lock
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/beacon_processor/Cargo.toml
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/task_spawner.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/http_api/src/validator.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/service/tests.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  lighthouse/Cargo.toml
  lighthouse/tests/beacon_node.rs
  testing/node_test_rig/src/lib.rs
  watch/Cargo.toml
  watch/tests/tests.rs
Labels: ready-for-review, deneb

#4428 Builder flow for Deneb & Blobs
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_cache.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/builder_client/src/lib.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/payload_cache.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/http_api/src/build_block_contents.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  common/eth2/Cargo.toml
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/types/Cargo.toml
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/builder_bid.rs
  consensus/types/src/lib.rs
  consensus/types/src/payload.rs
  consensus/types/src/signed_blob.rs
  validator_client/src/block_service.rs
  validator_client/src/signing_method.rs
  validator_client/src/validator_store.rs
Labels: ready-for-review, deneb, builder API

#4602 Bump clang for deneb cross builds
  Cross.toml
Labels: deneb

#4627 Update docs to remove `lighthouse/database/historical_blocks`
  book/src/api-lighthouse.md
Labels: ready-for-review, docs, deneb

#4621 Add Test for deneb Block Hash Calculation
  beacon_node/execution_layer/src/block_hash.rs
Labels: deneb

#4632 Revive mplex (Deneb)
  Cargo.lock
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/service/utils.rs
Labels: deneb, deneb-devnet-8

#4607 Add Deneb builder test & update mock builder
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/builder_bid.rs
  consensus/types/src/payload.rs
  consensus/types/src/signed_blob.rs
  scripts/local_testnet/genesis.json
  scripts/local_testnet/start_local_testnet.sh
Labels: ready-for-review, deneb

#4645 fix beacon chain tests
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/lib.rs
Labels: ready-for-review, low-hanging-fruit, deneb

#4646 Fix proposer cache miss in blob verification
  beacon_node/beacon_chain/src/blob_verification.rs
Labels: ready-for-review, deneb

#4649 Merge `unstable` to deneb 20230822
  .github/workflows/docker-antithesis.yml
  Cargo.lock
  Makefile
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/beacon_fork_choice_store.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/events.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/http_api/src/attester_duties.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/metadata.rs
  book/src/checkpoint-sync.md
  book/src/setup.md
  consensus/fork_choice/src/fork_choice.rs
  crypto/kzg/Cargo.toml
  lighthouse/tests/beacon_node.rs
  testing/antithesis/Dockerfile.libvoidstar
  testing/antithesis/libvoidstar/libvoidstar.so
  testing/ef_tests/src/cases/fork_choice.rs
  testing/node_test_rig/src/lib.rs
  validator_client/src/duties_service/sync.rs
  validator_client/src/http_metrics/metrics.rs
  watch/tests/tests.rs
Labels: ready-for-review, deneb

#4659 rust 1.72 lints
  beacon_node/beacon_chain/src/observed_attesters.rs
  beacon_node/genesis/src/common.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/store/src/chunked_vector.rs
  beacon_node/store/src/leveldb_store.rs
  consensus/safe_arith/src/iter.rs
  crypto/bls/src/generic_public_key_bytes.rs
Labels: ready-for-review, low-hanging-fruit

#4658 Merge unstable deneb aug 24
  Makefile
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/observed_attesters.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/genesis/src/common.rs
  beacon_node/http_api/src/builder_states.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/store/src/chunked_vector.rs
  beacon_node/store/src/leveldb_store.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/safe_arith/src/iter.rs
  consensus/types/src/blob_sidecar.rs
  crypto/bls/src/generic_public_key_bytes.rs
Labels: ready-for-review, deneb
