Repository sigp/lighthouse, pull requests merged in 2023-09, with the labels that each got.

#4682 Fix stuck CI on Deneb branch
  .github/workflows/test-suite.yml
Labels: ready-for-review, infra-ci, deneb

#4678 Deneb review suggestions
  beacon_node/network/src/sync/manager.rs
  common/eth2_network_config/src/lib.rs
Labels: ready-for-review, deneb

#4680 Deneb review suggestions (2)
  testing/ef_tests/src/cases/kzg_blob_to_kzg_commitment.rs
  testing/ef_tests/src/cases/kzg_compute_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_compute_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof_batch.rs
  testing/ef_tests/src/cases/kzg_verify_kzg_proof.rs
Labels: ready-for-review, deneb

#4694 Deneb review suggestions (3)
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  testing/ef_tests/src/cases/kzg_blob_to_kzg_commitment.rs
  testing/ef_tests/src/cases/kzg_compute_kzg_proof.rs
Labels: deneb

#4677 Simplifications for ./crypto
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  consensus/types/Cargo.toml
  consensus/types/src/blob_sidecar.rs
  crypto/kzg/Cargo.toml
  crypto/kzg/src/kzg_commitment.rs
  crypto/kzg/src/kzg_proof.rs
Labels: ready-for-review, deneb

#4698 Deneb review `common/eth2`
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
Labels: ready-for-review, deneb

#4703 Fix `parent_beacon_block_root` during proposer prep
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
Labels: ready-for-bors, deneb

#4713 Fix duplicate `geth` startup command in `doppelganger_protection.sh`
  scripts/tests/doppelganger_protection.sh
Labels: ready-for-bors, deneb

#4708 Update `GET config/spec` endpoint to support Deneb config
  beacon_node/http_api/tests/tests.rs
  consensus/types/presets/gnosis/deneb.yaml
  consensus/types/presets/mainnet/deneb.yaml
  consensus/types/presets/minimal/deneb.yaml
  consensus/types/src/config_and_preset.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/lib.rs
  consensus/types/src/preset.rs
  validator_client/src/beacon_node_fallback.rs
  validator_client/src/http_api/test_utils.rs
  validator_client/src/http_api/tests.rs
Labels: val-client, ready-for-review, HTTP-API, deneb

#4710 Update `BlindedBlobsBundle` SSZ list max length and update builder tests
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  common/eth2/src/types.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/builder_bid.rs
  consensus/types/src/lib.rs
  consensus/types/src/payload.rs
  consensus/types/src/sidecar.rs
  scripts/local_testnet/README.md
  scripts/local_testnet/beacon_node.sh
  scripts/local_testnet/setup.sh
  scripts/local_testnet/vars.env
  scripts/tests/vars.env
Labels: ready-for-review, deneb

#4652 Tree states to support per-slot state diffs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hdiff.rs
  beacon_node/store/src/hot_cold_store.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-bors, tree-states

#4721 fix the missing components response code for block publish
  beacon_node/http_api/src/publish_blocks.rs
Labels: ready-for-review, low-hanging-fruit, deneb

#4588 increase the max topic subscriptions #4581
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/mod.rs
Labels: ready-for-bors, deneb

#4729 Tree states release v4.4.111-exp
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: tree-states

#4723 Blob references in ckzg
  Cargo.lock
  beacon_node/beacon_chain/src/kzg_utils.rs
  consensus/types/src/blob_sidecar.rs
  crypto/kzg/Cargo.toml
  crypto/kzg/src/lib.rs
  crypto/kzg/src/trusted_setup.rs
Labels: ready-for-review, deneb

#4716 Deneb PR feedback updates
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  crypto/kzg/src/kzg_proof.rs
Labels: ready-for-bors, deneb

#4744 Implement SSZ decoding for `SignedBlockContents`
  Cargo.lock
  common/eth2/src/types.rs
  consensus/types/src/blob_sidecar.rs
Labels: ready-for-review, deneb

#4762 Improve state cache eviction and reduce mem usage
  beacon_node/store/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/state_cache.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-review, optimization, tree-states

#4769 Tree states release v4.5.111-exp
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-review, tree-states

#4735 Update Deneb to 1.4.0-beta.2 (devnet-9)
  beacon_node/beacon_chain/src/blob_verification.rs
  book/src/api-vc-endpoints.md
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/prater/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/fork_choice/src/fork_choice.rs
  consensus/state_processing/src/per_epoch_processing/registry_updates.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/chain_spec.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
  testing/ef_tests/Makefile
  testing/ef_tests/src/cases/fork_choice.rs
Labels: ready-for-bors, backwards-incompat, deneb

#4782 Tree states release v4.5.222-exp
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: tree-states

#4779 reduce blob prune logging in forward sync
  beacon_node/store/src/hot_cold_store.rs
Labels: ready-for-review, low-hanging-fruit, deneb

#4783 Make deneb-enabled VCs compatible with pre-deneb beacon nodes
  consensus/types/src/chain_spec.rs
Labels: ready-for-review, deneb

#4780 insert cached child at the front of a chain of parent lookups
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
Labels: bug, low-hanging-fruit, ready-for-bors, deneb
