Repository sigp/lighthouse, pull requests merged in 2024-12, with the labels that each got.

#6604 Increase idle connection timeout
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-merge, Networking, v6.0.0

#6643 Backport stable to unstable
  FUNDING.json
Labels: ready-for-review, do-not-merge, v6.0.0

#6605 Release v6.0.0
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, backwards-incompat, v6.0.0

#6581 Add a security section to the book
  book/src/SUMMARY.md
  book/src/resources/2020-lh-trail-of-bits.pdf
  book/src/security.md
Labels: security, docs, ready-for-merge

#6630 Deprecate futures ticker
  Cargo.lock
  beacon_node/lighthouse_network/gossipsub/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
  beacon_node/lighthouse_network/gossipsub/src/behaviour/tests.rs
  beacon_node/lighthouse_network/gossipsub/src/peer_score.rs
Labels: ready-for-merge, Networking

#6671 Fix Kurtosis, web3signer and cargo-audit for CI
  .github/workflows/local-testnet.yml
  .github/workflows/test-suite.yml
  Makefile
  scripts/tests/doppelganger_protection.sh
Labels: ready-for-merge, infra-ci, v6.0.1

#6646 Correct flakey CI tests
  beacon_node/network/src/subnet_service/mod.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
Labels: test improvement, ready-for-merge, v6.0.1

#6676 Back merge 6.0.1
  .github/workflows/local-testnet.yml
  .github/workflows/test-suite.yml
  Makefile
  beacon_node/network/src/subnet_service/mod.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
  scripts/tests/doppelganger_protection.sh
Labels: ready-for-review, do-not-merge

#6668 Tweak reconstruction batch size
  beacon_node/beacon_chain/src/migrate.rs
Labels: optimization, ready-for-merge, database, v6.0.1

#6661 Remove `ZeroizeString` in favour of `Zeroizing<String>`
  Cargo.lock
  Cargo.toml
  account_manager/Cargo.toml
  account_manager/src/validator/create.rs
  account_manager/src/validator/import.rs
  account_manager/src/wallet/create.rs
  common/account_utils/src/lib.rs
  common/account_utils/src/validator_definitions.rs
  common/eth2/Cargo.toml
  common/eth2/src/lighthouse_vc/http_client.rs
  common/eth2/src/lighthouse_vc/std_types.rs
  common/eth2/src/lighthouse_vc/types.rs
  crypto/eth2_keystore/src/keystore.rs
  lighthouse/Cargo.toml
  lighthouse/tests/account_manager.rs
  validator_client/http_api/Cargo.toml
  validator_client/http_api/src/create_validator.rs
  validator_client/http_api/src/keystores.rs
  validator_client/http_api/src/test_utils.rs
  validator_client/http_api/src/tests.rs
  validator_client/http_api/src/tests/keystores.rs
  validator_client/initialized_validators/Cargo.toml
  validator_client/initialized_validators/src/lib.rs
  validator_manager/Cargo.toml
  validator_manager/src/common.rs
  validator_manager/src/import_validators.rs
  validator_manager/src/move_validators.rs
Labels: code-quality, ready-for-merge, v6.1.0

#6655 Fix: Docker CI to use org tokens
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: ready-for-merge, infra-ci, v6.0.1

#6669 Prevent reconstruction starting prematurely
  beacon_node/beacon_chain/src/builder.rs
Labels: ready-for-merge, database, UX-and-logs, v6.0.1

#6682 Fix subscribing to attestation subnets for aggregating (#6681)
  beacon_node/network/src/subnet_service/mod.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
Labels: bug, ready-for-merge, Networking, v6.0.1

#6658 Stuck lookup v6
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
Labels: ready-for-merge, v6.0.1

#6635 Fix for blank line in graffiti file
  validator_client/graffiti_file/src/lib.rs
Labels: bug, val-client, ready-for-merge, v6.1.0

#6650 Remove heading that isn't rendered correctly
  book/src/security.md
Labels: docs, ready-for-merge

#6667 Compact more when pruning states
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
  beacon_node/store/src/hot_cold_store.rs
Labels: ready-for-merge, database, v6.0.1

#6677 Correct `/nat` API for libp2p
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  common/system_health/src/lib.rs
Labels: ready-for-merge, v6.0.1

#6659 Release v6.0.1
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, v6.0.1

#6541 Track beacon processor import result metrics
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
Labels: ready-for-merge

#6700 Back merge v6.0.1 to unstable
  .github/workflows/docker.yml
  .github/workflows/release.yml
  Cargo.lock
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  beacon_node/network/src/subnet_service/mod.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/store/src/hot_cold_store.rs
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  common/system_health/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: do-not-merge

#6577 Add CLI flag for HTTP API token path (VC)
  Cargo.lock
  book/src/api-vc-auth-header.md
  book/src/api-vc-endpoints.md
  book/src/help_vc.md
  lighthouse/tests/validator_client.rs
  validator_client/http_api/Cargo.toml
  validator_client/http_api/src/api_secret.rs
  validator_client/http_api/src/lib.rs
  validator_client/http_api/src/test_utils.rs
  validator_client/http_api/src/tests.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/lib.rs
Labels: ready-for-merge, v6.1.0

#6583 builder gas limit & some refactoring
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/payload.rs
  testing/ef_tests/src/cases/fork_choice.rs
  testing/execution_engine_integration/src/test_rig.rs
Labels: ready-for-merge, builder API, v6.1.0

#6588 Fix web3signer test fails on macOS
  testing/web3signer_tests/src/lib.rs
  testing/web3signer_tests/tls/generate.sh
  testing/web3signer_tests/tls/lighthouse/cert.pem
  testing/web3signer_tests/tls/lighthouse/key.key
  testing/web3signer_tests/tls/lighthouse/key.p12
  testing/web3signer_tests/tls/lighthouse/key_legacy.p12
  testing/web3signer_tests/tls/lighthouse/web3signer.pem
  testing/web3signer_tests/tls/web3signer/cert.pem
  testing/web3signer_tests/tls/web3signer/key.key
  testing/web3signer_tests/tls/web3signer/key.p12
  testing/web3signer_tests/tls/web3signer/known_clients.txt
Labels: test improvement, ready-for-merge, v6.1.0

#6589 Remove req_id from CustodyId
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-merge, das

#6618 Write range sync tests in external event-driven form
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/block_storage.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  beacon_node/network/src/sync/range_sync/mod.rs
  beacon_node/network/src/sync/range_sync/range.rs
  beacon_node/network/src/sync/range_sync/sync_type.rs
  beacon_node/network/src/sync/tests/lookups.rs
  beacon_node/network/src/sync/tests/range.rs
Labels: syncing, ready-for-merge

#6686 Fix peer down-scoring behaviour when gossip blobs/columns are received after `getBlobs` or reconstruction
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: ready-for-merge, das

#6496 Electra alpha8 spec updates
  beacon_node/execution_layer/src/block_hash.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/engine_api/new_payload_request.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/store/src/partial_beacon_state.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_epoch_processing/errors.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/state_processing/src/upgrade/electra.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/tests.rs
  consensus/types/src/deposit_request.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/execution_block_header.rs
  consensus/types/src/execution_requests.rs
  consensus/types/src/lib.rs
  consensus/types/src/pending_deposit.rs
  consensus/types/src/preset.rs
  consensus/types/src/validator.rs
  testing/ef_tests/Makefile
  testing/ef_tests/src/cases/epoch_processing.rs
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-merge, electra, v6.1.0

#6627 Add spell check and update Lighthouse book
  .github/workflows/test-suite.yml
  .spellcheck.yml
  CONTRIBUTING.md
  README.md
  book/src/advanced_database.md
  book/src/advanced_networking.md
  book/src/api-lighthouse.md
  book/src/faq.md
  book/src/graffiti.md
  book/src/homebrew.md
  book/src/late-block-re-orgs.md
  book/src/ui-faqs.md
  book/src/ui-installation.md
  book/src/validator-inclusion.md
  book/src/validator-manager.md
  book/src/validator-monitoring.md
  scripts/local_testnet/README.md
  wordlist.txt
Labels: docs, ready-for-merge, infra-ci, v6.1.0

#6711 Unsaturate dial negotiation queue
  beacon_node/lighthouse_network/src/rpc/handler.rs
Labels: ready-for-merge, Networking

#6685 Fix Sse client api
  Cargo.lock
  beacon_node/beacon_chain/tests/store_tests.rs
  common/eth2/Cargo.toml
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
Labels: ready-for-merge, v6.1.0

#6631 Delete OTB verification service
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/otb_verification_service.rs
  beacon_node/client/src/builder.rs
  beacon_node/store/src/lib.rs
Labels: code-quality, ready-for-merge, v6.1.0

#6553 Revise Siren documentation
  book/src/SUMMARY.md
  book/src/api-vc-auth-header.md
  book/src/lighthouse-ui.md
  book/src/ui-authentication.md
  book/src/ui-configuration.md
  book/src/ui-faqs.md
  wordlist.txt
Labels: docs, ready-for-merge, v6.1.0

#6603 Ensure non-zero bits for each committee bitfield comprising an aggregate
  consensus/state_processing/src/common/get_attesting_indices.rs
  consensus/types/src/beacon_state.rs
Labels: ready-for-merge, electra, v6.1.0, electra-alpha9

#6738 Make sure we have fanout peers when publish
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
Labels: ready-for-review
