Repository sigp/lighthouse, pull requests merged in 2024-05, with the labels that each got.

#5675 Ensure block only range requests don't fail on download
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
Labels: bug, ready-for-merge, v5.2.0

#5483 Improve ENR updates
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: Networking

#5670 Update Cargo.lock
  Cargo.lock
  Cargo.toml
Labels: ready-for-merge, v5.2.0

#5688 Add metric for current epoch total balance
  consensus/state_processing/src/metrics.rs
  consensus/state_processing/src/per_epoch_processing/epoch_processing_summary.rs
  validator_client/src/duties_service.rs
Labels: low-hanging-fruit, ready-for-merge, UX-and-logs, v5.2.0

#5678 Add data columns by root to currently supported protocol list
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/network/src/router.rs
Labels: ready-for-review, das

#5699 Improve logging and metrics for block publication
  beacon_node/http_api/src/metrics.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/sync/block_lookups/parent_chain.rs
  validator_client/slashing_protection/src/slashing_database.rs
Labels: ready-for-merge, v5.2.0

#5698 Make modified helpers in electra fork aware
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_epoch_processing/registry_updates.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/types/src/validator.rs
Labels: consensus, ready-for-merge, electra, v5.2.0

#5718 One less listen address race
  watch/src/server/mod.rs
  watch/tests/tests.rs
Labels: test improvement, ready-for-merge, v5.2.0

#5692 web3Signer: set header "Accept: application/json" as we expect json in the response
  validator_client/src/signing_method.rs
Labels: low-hanging-fruit, ready-for-merge, v5.2.0

#5680 Report RPC Errors to the application on peer disconnections
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: v5.2.0

#5704 Move sync lookup trait function to its caller
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
Labels: ready-for-merge

#5720 Revise contributors guide
  CONTRIBUTING.md
Labels: docs, ready-for-merge

#5731 Fix simulator tests on `das` branch
  .github/workflows/test-suite.yml
  testing/simulator/src/basic_sim.rs
  testing/simulator/src/fallback_sim.rs
Labels: ready-for-review, das

#5353 DataColumnByRange boilerplate
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/config.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/rpc/rate_limiter.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/manager.rs
  consensus/types/src/data_column_sidecar.rs
Labels: ready-for-review, das

#5684 PeerDAS custody lookup sync
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/sampling.rs
Labels: ready-for-review, das

#5701 Add data column kzg verification and update `c-kzg`.
  Cargo.lock
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/eth_spec.rs
  crypto/kzg/src/lib.rs
Labels: ready-for-review, das

#5750 Rename `PEER_DAS_EPOCH` to `EIP7594_FORK_EPOCH`
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  consensus/types/src/chain_spec.rs
Labels: ready-for-review, das

#5742 fix get attesting indices
  beacon_node/beacon_chain/src/attestation_verification.rs
  consensus/state_processing/src/common/get_attesting_indices.rs
  consensus/types/src/beacon_state.rs
Labels: electra

#5753 Ef test fixes
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: electra

#5755 fix ssz
  consensus/types/src/attestation.rs
  consensus/types/src/eth_spec.rs
Labels: electra

#5752 Compute on chain aggregate impl
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/operation_pool/src/lib.rs
Labels: electra

#5760 update the naive agg pool interface
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/naive_aggregation_pool.rs
Labels: electra

#5747 Fetch custody columns in range sync
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/config.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/rpc/rate_limiter.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-review, das

#5759 Remove `BlobSidecar` construction and publish after PeerDAS activated
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_sidecar.rs
Labels: ready-for-review, das

#5748 #5684 review comments
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: ready-for-review, das

#5749 Optimise Electra op pool aggregation
  beacon_node/operation_pool/src/attestation.rs
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/operation_pool/src/lib.rs
  consensus/types/src/attestation.rs
Labels: ready-for-review, electra

#5722 Notify lookup sync of gossip processing results
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-review, v5.2.0

#5724 Do not request current child lookup peers
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: ready-for-review, v5.2.0

#5775 Make sampling tests deterministic
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: ready-for-merge, das

#5772 PeerDAS spec tests
  Cargo.lock
  consensus/types/src/data_column_subnet_id.rs
  consensus/types/src/lib.rs
  testing/ef_tests/Cargo.toml
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/get_custody_columns.rs
  testing/ef_tests/src/cases/kzg_blob_to_kzg_commitment.rs
  testing/ef_tests/src/cases/kzg_compute_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_compute_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_compute_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof_batch.rs
  testing/ef_tests/src/cases/kzg_verify_cell_kzg_proof_batch.rs
  testing/ef_tests/src/cases/kzg_verify_kzg_proof.rs
  testing/ef_tests/src/cases/merkle_proof_validity.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/src/lib.rs
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-review, das

#5781 Implement unconditional reconstruction for supernodes
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/data_column_subnet_id.rs
  crypto/kzg/src/lib.rs
Labels: ready-for-review, das

#5738 Log block import source
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/lib.rs
  testing/ef_tests/src/cases/fork_choice.rs
Labels: ready-for-review, UX-and-logs

#5786 use electra feature in notifier completeness check
  beacon_node/client/src/notifier.rs
Labels: ready-for-review, low-hanging-fruit

#5788 Add withhold attack mode for interop
  Cargo.lock
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-review

#5783 Add column gossip verification and handle unknown parent block
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/observed_data_sidecars.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context/requests.rs
  consensus/types/src/data_column_sidecar.rs
Labels: das

#5776 Trigger sampling on sync events
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
Labels: ready-for-review, das

#5779 PeerDAS parameter changes for devnet-0
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/discovery/subnet_predicate.rs
  beacon_node/lighthouse_network/src/rpc/config.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/network_context.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_subnet_id.rs
  consensus/types/src/eth_spec.rs
Labels: ready-for-review, das

#5793 Fix DAS branch CI
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  consensus/types/src/data_column_sidecar.rs
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/tests/tests.rs
Labels: ready-for-review, das

#5794 Only reconstruct column at most once per block
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
Labels: ready-for-review, das

#5798 Fix incorrect penalty on duplicate gossip columns
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: das

#5806 Avoid reconstructing data columns if we already have all the columns
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: ready-for-review, das

#5805 Multithread compute_cells_and_proofs
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/benches/benches.rs
  consensus/types/src/data_column_sidecar.rs
  crypto/kzg/src/lib.rs
Labels: das

#5808 Type sync network context send errors
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/chain.rs
Labels: ready-for-merge

#5813 Use JSON header by default for `/eth/v1/beacon/deposit_snapshot`
  beacon_node/http_api/src/lib.rs
Labels: ready-for-merge, HTTP-API, backwards-incompat

#5628 Reduce frequency of polling unknown validators to avoid overwhelming the Beacon Node
  validator_client/src/duties_service.rs
  validator_client/src/lib.rs
Labels: val-client, ready-for-review, v5.2.0

#5768 Fix hot state disk leak
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/store/src/hot_cold_store.rs
Labels: bug, ready-for-merge, database, v5.2.0

#5828 Move PeerDAS type-level config to configurable `ChainSpec`
  .github/workflows/test-suite.yml
  beacon_node/beacon_chain/benches/benches.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/child_components.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/observed_data_sidecars.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/discovery/subnet_predicate.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/sampling.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/prater/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/data_column_subnet_id.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/lib.rs
  consensus/types/src/runtime_var_list.rs
  lcli/src/generate_bootnode_enr.rs
  lcli/src/main.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
  testing/ef_tests/src/cases/get_custody_columns.rs
Labels: ready-for-review, das

#5824 Drop stuck lookups
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
Labels: ready-for-merge, v5.2.0

#5802 Suppress RPC Error disconnect log
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-review

#5821 Misc custody lookup improvements
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
  beacon_node/network/src/sync/network_context/requests.rs
Labels: ready-for-review, das

#5835 Fix validator logic
  validator_client/src/attestation_service.rs
Labels: ready-for-review, electra, skip-ci

#5816 Electra slashing handling
  consensus/types/src/indexed_attestation.rs
  slasher/src/array.rs
  slasher/src/lib.rs
  slasher/src/slasher.rs
Labels: electra, skip-ci

#5837 Do not double log uknown lookup
  beacon_node/network/src/sync/block_lookups/mod.rs
Labels: ready-for-merge

#5839 Do not drop lookups without peers while awaiting events
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/manager.rs
Labels: ready-for-merge

#5840 Ensure lookup sync checks caches correctly
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/network_context.rs
Labels: waiting-on-author

#5834 don't block mev boost till genesis finalization
  beacon_node/beacon_chain/src/beacon_chain.rs
Labels: low-hanging-fruit, ready-for-merge

#5812 Remove unused dependencies
  Cargo.lock
  account_manager/Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/beacon_processor/Cargo.toml
  beacon_node/builder_client/Cargo.toml
  beacon_node/client/Cargo.toml
  beacon_node/eth1/Cargo.toml
  beacon_node/execution_layer/Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/Cargo.toml
  beacon_node/network/Cargo.toml
  beacon_node/store/Cargo.toml
  boot_node/Cargo.toml
  common/eth2/Cargo.toml
  common/eth2_network_config/Cargo.toml
  common/lighthouse_metrics/Cargo.toml
  common/logging/Cargo.toml
  common/system_health/Cargo.toml
  consensus/types/Cargo.toml
  database_manager/Cargo.toml
  lcli/Cargo.toml
  lighthouse/Cargo.toml
  slasher/Cargo.toml
  testing/ef_tests/Cargo.toml
  testing/execution_engine_integration/Cargo.toml
  testing/simulator/Cargo.toml
  validator_manager/Cargo.toml
  watch/Cargo.toml
Labels: ready-for-merge

#5838 Add more info about why lookup is in AwaitingDownload
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-merge, Networking, v5.2.0

#5852 Rename deploy_block in network config (`das` branch)
  common/eth2_config/src/lib.rs
  common/eth2_network_config/built_in_network_configs/chiado/deposit_contract_block.txt
  common/eth2_network_config/built_in_network_configs/gnosis/deposit_contract_block.txt
  common/eth2_network_config/built_in_network_configs/holesky/deposit_contract_block.txt
  common/eth2_network_config/built_in_network_configs/mainnet/deposit_contract_block.txt
  common/eth2_network_config/built_in_network_configs/sepolia/deposit_contract_block.txt
  common/eth2_network_config/src/lib.rs
Labels: das

#5850 Rename deploy_block in network config
  common/eth2_config/src/lib.rs
  common/eth2_network_config/built_in_network_configs/chiado/deposit_contract_block.txt
  common/eth2_network_config/built_in_network_configs/gnosis/deposit_contract_block.txt
  common/eth2_network_config/built_in_network_configs/holesky/deposit_contract_block.txt
  common/eth2_network_config/built_in_network_configs/mainnet/deposit_contract_block.txt
  common/eth2_network_config/built_in_network_configs/sepolia/deposit_contract_block.txt
  common/eth2_network_config/src/lib.rs
Labels: ready-for-merge, backwards-incompat

#5823 Add `bls_to_execution_change` topic to `eth1/v1/events`
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/events.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/types.rs
Labels: ready-for-merge, HTTP-API

#5854 Fix BitVectors TestRandom implementation
  consensus/types/src/test_utils/test_random/bitfield.rs
Labels: ready-for-merge, electra

#5856 Electra attestation changes rm decode impl
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v20.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/operation_pool/src/persistence.rs
  beacon_node/store/src/metadata.rs
  consensus/state_processing/src/verify_operation.rs
  consensus/types/src/attestation.rs
  testing/ef_tests/src/cases/fork_choice.rs
  testing/ef_tests/src/cases/operations.rs
Labels: electra

#5810 Fix failing attestation tests and misc electra attestation cleanup
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/attestation_verification/batch.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/naive_aggregation_pool.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/sync_committee_verification.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_attestations.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/operation_pool/src/attestation.rs
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/operation_pool/src/lib.rs
  consensus/fork_choice/tests/tests.rs
  consensus/state_processing/src/common/get_attesting_indices.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
  consensus/types/src/attestation.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/indexed_attestation.rs
  consensus/types/src/signed_aggregate_and_proof.rs
  consensus/types/src/subnet_id.rs
  validator_client/src/attestation_service.rs
Labels: ready-for-review, electra, skip-ci

#5817 Fix/remove some Electra attestation todos
  beacon_node/beacon_chain/src/beacon_chain.rs
  consensus/types/src/attestation.rs
  consensus/types/src/attester_slashing.rs
  consensus/types/src/beacon_block.rs
Labels: electra, skip-ci

#5858 Add peers to parent lookups
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
Labels: ready-for-merge, v5.2.0

#5857 Add builder header timeout flag
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/builder_client/src/lib.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, builder API, v5.2.0

#5863 Fix attestations not getting added to the aggregation pool
  beacon_node/network/src/subnet_service/attestation_subnets.rs
Labels: ready-for-merge, v5.2.0
