Repository sigp/lighthouse, pull requests merged in 2024-11, with the labels that each got.

#5165 make `execution-endpoint` required
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, backwards-incompat, v6.0.0

#6558 Add error message for duration subtraction overflow in sim tests
  testing/simulator/src/basic_sim.rs
  testing/simulator/src/fallback_sim.rs
  testing/simulator/src/local_network.rs
Labels: test improvement, ready-for-merge

#6513 Send `IDONTWANT` on publish to avoid downloading data we already have
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
Labels: ready-for-merge, Networking, v6.0.0

#6434 Resolve some PeerDAS todos
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/peer_sampling.rs
Labels: ready-for-merge, das

#6569 Fix rpc decoding for blobs by range/root
  beacon_node/lighthouse_network/src/rpc/codec.rs
Labels: ready-for-merge

#6574 Remove `yq` installation on CI
  .github/workflows/local-testnet.yml
Labels: ready-for-review, infra-ci

#6268 Improving blob propagation post-PeerDAS with Decentralized Blob Building
  beacon_node/beacon_chain/benches/benches.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/fetch_blobs.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/observed_data_sidecars.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/events.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/signed_beacon_block.rs
  consensus/types/src/test_utils/generate_random_block_and_blobs.rs
  lighthouse/tests/beacon_node.rs
  testing/ef_tests/src/cases/fork_choice.rs
Labels: spec_change, optimization, ready-for-merge, das, v6.0.0

#6545 Additional light client metrics
  beacon_node/beacon_chain/src/light_client_server_cache.rs
  beacon_node/beacon_chain/src/metrics.rs
Labels: ready-for-merge, light-client

#6585 Test hdiff binary format stability
  beacon_node/store/Cargo.toml
  beacon_node/store/src/hdiff.rs
Labels: ready-for-review, tree-states

#5978 Hierarchical state diffs
  .github/workflows/test-suite.yml
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/notifier.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/metrics.rs
  beacon_node/http_api/src/state_id.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/lighthouse_network/src/types/sync_state.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/benches/hdiff.rs
  beacon_node/store/src/chunk_writer.rs
  beacon_node/store/src/chunked_vector.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/hdiff.rs
  beacon_node/store/src/historic_state_cache.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metadata.rs
  beacon_node/store/src/metrics.rs
  beacon_node/store/src/partial_beacon_state.rs
  beacon_node/store/src/reconstruct.rs
  beacon_node/tests/test.rs
  book/src/advanced_database.md
  book/src/help_bn.md
  book/src/imgs/db-freezer-layout.png
  common/eth2/src/lighthouse.rs
  common/eth2_config/src/lib.rs
  common/eth2_network_config/src/lib.rs
  common/metrics/src/lib.rs
  consensus/state_processing/src/common/update_progressive_balances_cache.rs
  consensus/state_processing/src/epoch_cache.rs
  consensus/state_processing/src/metrics.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/historical_summary.rs
  consensus/types/src/validator.rs
  database_manager/src/cli.rs
  database_manager/src/lib.rs
  lighthouse/tests/beacon_node.rs
  watch/README.md
Labels: optimization, ready-for-merge, database, backwards-incompat, tree-states, v6.0.0

#6486 Update to latest discovery
  Cargo.lock
  Cargo.toml
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  boot_node/src/server.rs
  common/system_health/src/lib.rs
Labels: ready-for-merge, v6.0.0

#6591 Fix v22 schema upgrade
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
Labels: bug, ready-for-review, database, tree-states, v6.0.0

#6578 Add additional metrics for idontwant
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
  beacon_node/lighthouse_network/gossipsub/src/behaviour/tests.rs
  beacon_node/lighthouse_network/gossipsub/src/metrics.rs
  beacon_node/lighthouse_network/gossipsub/src/types.rs
Labels: ready-for-merge, v6.0.0

#6595 Avoid computing rpc_blob_limits multiple times
  beacon_node/lighthouse_network/src/rpc/protocol.rs
Labels: low-hanging-fruit, optimization, ready-for-merge, v6.0.0

#6602 Add filecoin address to `FUNDING.json`
  FUNDING.json
Labels: ready-for-review

#6146 Simple Subnet Management
  Cargo.lock
  Cargo.toml
  beacon_node/network/src/service.rs
  beacon_node/network/src/service/tests.rs
  beacon_node/network/src/subnet_service/attestation_subnets.rs
  beacon_node/network/src/subnet_service/mod.rs
  beacon_node/network/src/subnet_service/sync_subnets.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/subnet_id.rs
Labels: ready-for-merge, v6.0.0

#6611 Update DB migrations in book
  book/src/database-migrations.md
Labels: docs, ready-for-merge, v6.0.0

#6608 Pin rust_eth_kzg to 0.5.1
  Cargo.toml
Labels: ready-for-merge, v6.0.0

#6628 Remove `error-chain` dependency
  Cargo.lock
  Cargo.toml
  beacon_node/client/Cargo.toml
  beacon_node/client/src/error.rs
  beacon_node/client/src/lib.rs
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/service/gossipsub_scoring_parameters.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/src/types/error.rs
  beacon_node/lighthouse_network/src/types/mod.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/error.rs
  beacon_node/network/src/lib.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/service.rs
Labels: code-quality, ready-for-merge, v6.0.0

#6629 Fix Rust 1.83 Clippy lints
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/observed_aggregates.rs
  beacon_node/lighthouse_network/gossipsub/src/backoff.rs
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/store/src/chunked_iter.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/iter.rs
  common/eth2/src/lighthouse.rs
  common/eth2_config/src/lib.rs
  common/logging/src/lib.rs
  common/validator_dir/src/insecure_keys.rs
  consensus/state_processing/src/block_replayer.rs
  consensus/types/src/aggregate_and_proof.rs
  consensus/types/src/attestation.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/beacon_committee.rs
  consensus/types/src/beacon_state/iter.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/indexed_attestation.rs
  consensus/types/src/light_client_header.rs
  consensus/types/src/light_client_update.rs
  consensus/types/src/payload.rs
  consensus/types/src/slot_epoch.rs
  crypto/bls/src/macros.rs
  crypto/kzg/src/trusted_setup.rs
  lighthouse/src/main.rs
  slasher/src/database/interface.rs
  testing/ef_tests/src/cases/fork_choice.rs
  validator_client/signing_method/src/lib.rs
  watch/src/database/mod.rs
Labels: ready-for-review, code-quality, v6.0.0

#6600 Fetch blobs from EL prior to block verification
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: optimization, ready-for-merge, v6.0.0
