Repository sigp/lighthouse, pull requests merged in 2024-03, with the labels that each got.

#5196 Add `DataColumnSidecarsByRoot ` req/resp protocol
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/availability_view.rs
  beacon_node/beacon_chain/src/data_availability_checker/child_components.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/processing_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/config.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/rpc/rate_limiter.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metadata.rs
  beacon_node/store/src/metrics.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_sidecar.rs
Labels: ready-for-review, das

#5325 Improve logging around peer scoring
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/score.rs
Labels: ready-for-review, v5.1.0

#5305 Fix duties override bug in VC
  validator_client/src/duties_service.rs
Labels: bug, val-client, ready-for-review, v5.1.0

#5351 Update dependency `whoami`
  Cargo.lock
Labels: ready-for-merge, dependencies

#5298 Delete milagro library
  .github/workflows/test-suite.yml
  Cargo.lock
  Makefile
  consensus/types/src/attestation.rs
  crypto/bls/Cargo.toml
  crypto/bls/src/impls/milagro.rs
  crypto/bls/src/impls/mod.rs
  crypto/bls/src/lib.rs
  crypto/bls/tests/tests.rs
  lighthouse/Cargo.toml
  lighthouse/src/main.rs
  testing/ef_tests/Cargo.toml
  testing/ef_tests/src/cases/bls_eth_aggregate_pubkeys.rs
  testing/ef_tests/src/decode.rs
Labels: code-quality, ready-for-merge

#5366 Fix block v3 header decoding
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/types.rs
Labels: bug, low-hanging-fruit, ready-for-merge, HTTP-API, v5.1.0

#5318 Fix 5288: Doesn't POST if attestations is empty.
  validator_client/src/attestation_service.rs
Labels: ready-for-merge, v5.1.0

#5357 Attempt to publish to at least mesh_n peers
  beacon_node/lighthouse_network/src/gossipsub/behaviour.rs
  beacon_node/lighthouse_network/src/gossipsub/behaviour/tests.rs
  beacon_node/lighthouse_network/src/gossipsub/error.rs
Labels: ready-for-merge, v5.1.0

#5344 Correct the metrics for topic subscriptions
  beacon_node/lighthouse_network/src/gossipsub/behaviour.rs
  beacon_node/lighthouse_network/src/gossipsub/metrics.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/mod.rs
  beacon_node/lighthouse_network/src/types/topics.rs
Labels: ready-for-review, v5.1.0

#5345 Improve peer performance for NAT'd nodes
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
Labels: ready-for-merge

#5333 Explicit peers
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-merge, t Networking, v5.1.0

#5266 Fix `AddrInUse` error in cli tests
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge

#5368 Optimise concurrent block production
  beacon_node/beacon_chain/src/beacon_chain.rs
Labels: optimization, ready-for-merge, HTTP-API, v5.1.0, dvt

#5381 Downgrade rate limited log
  Cargo.lock
  beacon_node/lighthouse_network/src/rpc/mod.rs
Labels: ready-for-review

#5372 Release v5.1.0
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: v5.1.0

#5386 Address Mark's review comments on single-pass
  beacon_node/beacon_chain/src/attestation_rewards.rs
  consensus/state_processing/src/common/initiate_validator_exit.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_epoch_processing/altair/inactivity_updates.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/chain_spec.rs
Labels: ready-for-review, tree-states

#5392 Fix tree-states macOS build by bumping `cc`
  Cargo.lock
Labels: infra-ci, tree-states

#5393 Fix macOS build by updating `cc`
  Cargo.lock
Labels: low-hanging-fruit, ready-for-merge, infra-ci, v5.2.0

#5396 Release v5.1.1
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge

#5210 feat: add DAS KZG in data col construction
  .github/workflows/test-suite.yml
  Cargo.lock
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/http_api/src/publish_blocks.rs
  consensus/types/Cargo.toml
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/data_column_sidecar.rs
  crypto/kzg/Cargo.toml
  crypto/kzg/src/lib.rs
Labels: ready-for-merge, das

#5364 Add attestation simulator, blobs info and some updates to Lighthouse Book
  book/src/SUMMARY.md
  book/src/advanced-blobs.md
  book/src/advanced-release-candidates.md
  book/src/advanced.md
  book/src/advanced_database.md
  book/src/checkpoint-sync.md
  book/src/database-migrations.md
  book/src/docker.md
  book/src/faq.md
  book/src/installation.md
  book/src/mainnet-validator.md
  book/src/merge-migration.md
  book/src/pi.md
  book/src/run_a_node.md
  book/src/slashing-protection.md
  book/src/validator-manager-move.md
  book/src/validator-monitoring.md
  book/src/voluntary-exit.md
Labels: ready-for-review, docs

#5414 Address Sean's review comments
  beacon_node/beacon_chain/src/attestation_rewards.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/operation_pool/src/lib.rs
  consensus/state_processing/src/all_caches.rs
  consensus/state_processing/src/common/base.rs
  consensus/state_processing/src/epoch_cache.rs
  consensus/state_processing/src/metrics.rs
  consensus/state_processing/src/per_epoch_processing/altair.rs
  consensus/state_processing/src/per_epoch_processing/base.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/epoch_cache.rs
Labels: ready-for-review, consensus, tree-states

#5432 Dedup parent blob requests
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: ready-for-review, low-hanging-fruit, v5.1.2

#4998 Improvements and Fixes in Documentation, Including Corrected Command Usage
  README.md
  account_manager/README.md
  book/src/lighthouse-ui.md
  book/src/setup.md
  book/src/validator-manager-create.md
  book/src/voluntary-exit.md
Labels: docs, ready-for-merge

#5404 Fix peer count metrics
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
Labels: ready-for-merge, t Networking, v5.1.2

#5385 Fix gossip verification of duplicate attester slashings
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/observed_operations.rs
  beacon_node/beacon_chain/tests/op_verification.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_block_processing/verify_attester_slashing.rs
Labels: ready-for-review, consensus, t Networking, v5.1.2

#5449 disable libp2p upnp
  beacon_node/lighthouse_network/src/service/behaviour.rs
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-merge, v5.1.2

#5453 Release v5.1.2
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-review, v5.1.2

#5451 Improve parent lookup logging
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: low-hanging-fruit, ready-for-merge, v5.2.0

#5456 fix: tail command typo
  scripts/local_testnet/README.md
Labels: ready-for-merge

#5440 chore: remove stale comment
  beacon_node/beacon_chain/src/execution_payload.rs
Labels: ready-for-merge

#5426 chore: reduce scope of commitment
  beacon_node/beacon_chain/src/data_availability_checker/availability_view.rs
  beacon_node/http_api/src/publish_blocks.rs
Labels: ready-for-merge

#5397 Fix one and hide all beacon-processor flags
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/src/cli.rs
  book/src/help_bn.md
Labels: ready-for-merge, UX-and-logs

#5418 Delete unused incomplete_processing_components
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/processing_cache.rs
Labels: low-hanging-fruit, ready-for-merge

#5383 Make sure all geth processes are killed when stopping a local testnet
  scripts/local_testnet/geth.sh
Labels: ready-for-merge

#5174 Verify whether validators really are unknown during sync committee duty API request
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/http_api/src/sync_committees.rs
  consensus/types/src/beacon_state.rs
Labels: ready-for-merge, v5.2.0

#5394 Built-in documentation text width in Lighthouse book
  book/src/help_bn.md
  book/src/help_general.md
  book/src/help_vc.md
  book/src/help_vm.md
  book/src/help_vm_create.md
  book/src/help_vm_import.md
  book/src/help_vm_move.md
  scripts/cli.sh
Labels: docs, ready-for-merge

#5406 Delete PRE_CAPELLA_ENGINE_CAPABILITIES
  beacon_node/execution_layer/src/engine_api/http.rs
Labels: code-quality, ready-for-merge, v5.2.0

#4946 Add Capella & Deneb light client support
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/light_client_finality_update_verification.rs
  beacon_node/beacon_chain/src/light_client_optimistic_update_verification.rs
  beacon_node/beacon_chain/src/light_client_server_cache.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/lib.rs
  consensus/types/src/light_client_bootstrap.rs
  consensus/types/src/light_client_finality_update.rs
  consensus/types/src/light_client_header.rs
  consensus/types/src/light_client_optimistic_update.rs
  consensus/types/src/light_client_update.rs
  consensus/types/src/test_utils/macros.rs
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
  testing/simulator/src/checks.rs
Labels: ready-for-merge, light-client

#5476 Fix double counted metrics
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
Labels: ready-for-review, t Networking

#5401 Move gossipsub into a separate crate
  Cargo.lock
  Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/CHANGELOG.md
  beacon_node/lighthouse_network/gossipsub/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/src/backoff.rs
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
  beacon_node/lighthouse_network/gossipsub/src/behaviour/tests.rs
  beacon_node/lighthouse_network/gossipsub/src/config.rs
  beacon_node/lighthouse_network/gossipsub/src/error.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/compat.proto
  beacon_node/lighthouse_network/gossipsub/src/generated/compat/mod.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/compat/pb.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/gossipsub/mod.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/gossipsub/pb.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/mod.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/rpc.proto
  beacon_node/lighthouse_network/gossipsub/src/gossip_promises.rs
  beacon_node/lighthouse_network/gossipsub/src/handler.rs
  beacon_node/lighthouse_network/gossipsub/src/lib.rs
  beacon_node/lighthouse_network/gossipsub/src/mcache.rs
  beacon_node/lighthouse_network/gossipsub/src/metrics.rs
  beacon_node/lighthouse_network/gossipsub/src/mod.rs
  beacon_node/lighthouse_network/gossipsub/src/peer_score.rs
  beacon_node/lighthouse_network/gossipsub/src/peer_score/params.rs
  beacon_node/lighthouse_network/gossipsub/src/peer_score/tests.rs
  beacon_node/lighthouse_network/gossipsub/src/protocol.rs
  beacon_node/lighthouse_network/gossipsub/src/rpc_proto.rs
  beacon_node/lighthouse_network/gossipsub/src/subscription_filter.rs
  beacon_node/lighthouse_network/gossipsub/src/time_cache.rs
  beacon_node/lighthouse_network/gossipsub/src/topic.rs
  beacon_node/lighthouse_network/gossipsub/src/transform.rs
  beacon_node/lighthouse_network/gossipsub/src/types.rs
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/src/service/behaviour.rs
  beacon_node/lighthouse_network/src/service/gossipsub_scoring_parameters.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/service/tests.rs
  common/logging/src/tracing_logging_layer.rs
Labels: ready-for-review, t Networking

#5475 Run fork choice after RPC blob import
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
Labels: bug, ready-for-merge, deneb, v5.2.0

#5488 Single lookup improvements
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: bug, ready-for-merge, deneb, v5.2.0

#5491 Lookup log improvements
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/manager.rs
Labels: ready-for-review, low-hanging-fruit

#5497 Release v5.1.3
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge
