Repository sigp/lighthouse, pull requests merged in 2024-02, with the labels that each got.

#4727 feat(config): add chiado bootnodes ENRs
  common/eth2_network_config/built_in_network_configs/chiado/boot_enr.yaml
Labels: ready-for-merge

#4986 Update gnosis bootnodes
  common/eth2_network_config/built_in_network_configs/gnosis/boot_enr.yaml
Labels: ready-for-merge

#5155 Re-disable block verification tests in debug
  beacon_node/beacon_chain/tests/block_verification.rs
Labels: code-quality, low-hanging-fruit, ready-for-merge, infra-ci

#5007 Config for web3signer keep-alive
  book/src/help_vc.md
  testing/web3signer_tests/src/lib.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/http_api/test_utils.rs
  validator_client/src/http_api/tests.rs
  validator_client/src/initialized_validators.rs
  validator_client/src/lib.rs
Labels: bug, val-client, ready-for-merge

#5171 Delete `lighthouse db diff`
  book/src/help_bn.md
  database_manager/src/lib.rs
Labels: ready-for-review, tree-states

#5050 1D PeerDAS prototype: Data format and Distribution
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/discovery/subnet_predicate.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/service/gossip_cache.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/lighthouse_network/src/types/subnet.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/service.rs
  consensus/types/presets/gnosis/deneb.yaml
  consensus/types/presets/mainnet/deneb.yaml
  consensus/types/presets/minimal/deneb.yaml
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/data_column_subnet_id.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/lib.rs
  consensus/types/src/preset.rs
Labels: ready-for-review, das

#5180 Fix Rust beta compiler errors (1.77)
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/state_advance_timer.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/http_api/src/attestation_performance.rs
  beacon_node/http_api/src/block_packing_efficiency.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/lighthouse_network/src/gossipsub/behaviour/tests.rs
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
  beacon_node/store/src/hot_cold_store.rs
  common/validator_dir/src/builder.rs
  consensus/cached_tree_hash/src/impls.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/historical_summary.rs
  consensus/types/src/participation_list.rs
  database_manager/src/lib.rs
  lighthouse/environment/src/lib.rs
Labels: ready-for-review

#5181 Fix incorrect value set for `blobs_by_root_request` rpc limit.
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge

#5164 Remove unused js file in Lighthouse book
  book/src/js/deposit.js
Labels: ready-for-merge

#4981 Optional slashing protection for remote keys
  book/src/help_vc.md
  lighthouse/tests/validator_client.rs
  testing/web3signer_tests/src/lib.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/signing_method.rs
  validator_client/src/validator_store.rs
Labels: val-client, optimization, ready-for-merge, v4.7.0

#5178 Small typo in testing config
  testing/network_testing/README.md
Labels: ready-for-merge

#5179 Update external LLVM version in preparation for Rust 1.76.
  .github/workflows/release.yml
  .github/workflows/test-suite.yml
Labels: ready-for-merge

#5203 Fix failing cargo-udeps
  Cargo.lock
  Cargo.toml
Labels: ready-for-merge, infra-ci

#5163 Downgrade gossipsub duplicate logs
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  book/src/redundancy.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge

#5170 Delete unused epoch processing code
  consensus/state_processing/src/per_epoch_processing/altair/rewards_and_penalties.rs
  testing/ef_tests/src/cases/rewards.rs
Labels: ready-for-review, tree-states

#5212 increment peer per topic count on graft messages
  beacon_node/lighthouse_network/src/gossipsub/behaviour.rs
Labels: ready-for-merge, v4.7.0

#5177 Improve network parameters
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/src/config.rs
Labels: ready-for-merge, v4.7.0

#5192 Fix backfill stalling
  beacon_node/network/src/sync/backfill_sync/mod.rs
Labels: ready-for-merge, v4.7.0

#4870 improve libp2p connected peer metrics
  beacon_node/http_api/src/lib.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  common/lighthouse_metrics/src/lib.rs
  common/system_health/src/lib.rs
Labels: ready-for-review, t Networking

#5029 chore(docs): amend port guidance to enable QUIC support
  book/src/advanced_networking.md
  book/src/docker.md
  book/src/faq.md
Labels: docs, ready-for-merge

#5214 Remove `curve25519-dalek` patch
  Cargo.lock
  Cargo.toml
Labels: ready-for-merge, dependencies, v4.7.0

#5172 Update to warp v0.3.6
  Cargo.lock
  Cargo.toml
Labels: ready-for-merge

#5094 Update to consensus spec v1.4.0-beta.6
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  consensus/proto_array/src/fork_choice_test_definition/ffg_updates.rs
  consensus/proto_array/src/fork_choice_test_definition/no_votes.rs
  consensus/proto_array/src/proto_array.rs
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/tests/tests.rs
Labels: low-hanging-fruit, ready-for-merge, deneb, v4.7.0

#5184 validator liveness endpoint should accept string encoded indices
  beacon_node/http_api/src/lib.rs
  common/eth2/src/lib.rs
Labels: ready-for-merge, backwards-incompat

#5223 Use epoch cache in block packing
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/operation_pool/src/attestation.rs
Labels: ready-for-review, tree-states

#5224 Remove progressive balances mode
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/beacon_chain/src/fork_revert.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/fork_choice/tests/tests.rs
  consensus/types/src/beacon_state/progressive_balances_cache.rs
  lighthouse/tests/beacon_node.rs
  testing/ef_tests/src/cases/fork_choice.rs
Labels: ready-for-review, tree-states

#5235 Quieten gossip republish logs
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: low-hanging-fruit, ready-for-merge, UX-and-logs, v5.0.0

#5233 Schedule Deneb on mainnet
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/src/lib.rs
  consensus/types/presets/mainnet/deneb.yaml
  consensus/types/src/chain_spec.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, v5.0.0

#4867 Add `distributed` flag to VC to enable support for DVT
  book/src/help_vc.md
  validator_client/Cargo.toml
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/duties_service.rs
  validator_client/src/duties_service/sync.rs
  validator_client/src/lib.rs
  validator_client/src/sync_committee_service.rs
Labels: ready-for-merge, v5.0.0

#5010 Handle unknown head during attestation publishing
  beacon_node/client/src/builder.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_attestations.rs
  beacon_node/http_api/src/task_spawner.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
Labels: enhancement, optimization, ready-for-merge, HTTP-API, v5.0.0

#4832 Verify Versioned Hashes During Optimistic Sync
  Cargo.lock
  Dockerfile
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/block_hash.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/new_payload_request.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/execution_layer/src/versioned_hashes.rs
  lcli/Dockerfile
  lighthouse/Cargo.toml
  testing/execution_engine_integration/src/test_rig.rs
Labels: ready-for-merge, backwards-incompat, deneb, v5.0.0

#5138 check the da cache and the attester cache in responding to RPC requests
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/availability_view.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/processing_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: ready-for-merge, deneb, v5.0.0

#5242 Add Deneb fork epoch for Gnosis
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge, v5.0.0

#5252 Download checkpoint blobs during checkpoint sync
  Cargo.lock
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  consensus/types/src/beacon_block_body.rs
Labels: ready-for-merge, v5.0.0

#5228 Deprecate env_log flag in tracing layer
  common/logging/src/lib.rs
  lighthouse/src/main.rs
Labels: ready-for-merge, v5.0.0

#5250 Deactivate RPC Connection Handler after goodbye message is sent
  Cargo.lock
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
Labels: v5.0.0

#5265 Revert libp2p metrics (#4870)
  beacon_node/http_api/src/lib.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  common/lighthouse_metrics/src/lib.rs
  common/system_health/src/lib.rs
Labels: ready-for-merge, v5.0.0

#5254 Release v5.0.0
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-review, v5.0.0

#5277 Fix tree-states tests
  beacon_node/beacon_chain/src/state_advance_timer.rs
  beacon_node/operation_pool/src/lib.rs
  consensus/fork_choice/tests/tests.rs
  consensus/state_processing/src/epoch_cache.rs
Labels: ready-for-review, tree-states

#5276 Tree states release v5.0.111-exp
  Cargo.lock
  beacon_node/Cargo.toml
  book/src/help_bn.md
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-review, tree-states

#5280 Simplify the exit cache
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/exit_cache.rs
Labels: ready-for-review, consensus, tree-states

#5225 Add build instructions for Fedora/RHEL/CentOS
  book/src/installation-source.md
Labels: docs, ready-for-merge

#5281 Delete ancient, unused HTTP docs
  book/src/http.md
Labels: code-quality, docs, ready-for-merge, v5.1.0

#5270 Add a cli option for the snapshot cache size
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/snapshot_cache.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, v5.1.0

#5275 Fix typos and make block hash calculation public
  beacon_node/execution_layer/src/engine_api/new_payload_request.rs
  beacon_node/execution_layer/src/lib.rs
Labels: low-hanging-fruit, ready-for-merge, v5.1.0

#5286 Remove milhouse export aliases
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/store/src/hdiff.rs
  consensus/state_processing/src/per_epoch_processing/altair/participation_flag_updates.rs
  consensus/state_processing/src/per_epoch_processing/epoch_processing_summary.rs
  consensus/state_processing/src/per_epoch_processing/resets.rs
  consensus/state_processing/src/upgrade/altair.rs
  consensus/state_processing/src/upgrade/capella.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/committee_cache/tests.rs
  consensus/types/src/beacon_state/compact_state.rs
  consensus/types/src/beacon_state/tests.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/historical_batch.rs
  consensus/types/src/lib.rs
  consensus/types/src/light_client_bootstrap.rs
  consensus/types/src/light_client_finality_update.rs
  consensus/types/src/light_client_update.rs
  consensus/types/src/sync_committee.rs
  testing/ef_tests/src/cases/ssz_generic.rs
Labels: ready-for-review, tree-states

#5285 as_store_bytes not fallible
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/otb_verification_service.rs
  beacon_node/beacon_chain/src/persisted_beacon_chain.rs
  beacon_node/beacon_chain/src/persisted_fork_choice.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v17.rs
  beacon_node/network/src/persisted_dht.rs
  beacon_node/operation_pool/src/persistence.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/hdiff.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/impls/execution_payload.rs
  beacon_node/store/src/impls/frozen_block_slot.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metadata.rs
  beacon_node/store/src/validator_pubkey_cache.rs
Labels: ready-for-review, tree-states

#5308 Track multiaddr in connection status
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
Labels: ready-for-review, v5.1.0

#4840 remove nat module and use libp2p upnp
  Cargo.lock
  Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/service/behaviour.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/nat.rs
  beacon_node/network/src/service.rs
Labels: waiting-on-author

#5183 remove exit-future
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/execution_layer/Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/service/tests.rs
  common/task_executor/Cargo.toml
  common/task_executor/src/lib.rs
  common/task_executor/src/test_utils.rs
  lighthouse/environment/Cargo.toml
  lighthouse/environment/src/lib.rs
  testing/execution_engine_integration/Cargo.toml
  testing/execution_engine_integration/src/test_rig.rs
  testing/web3signer_tests/Cargo.toml
  testing/web3signer_tests/src/lib.rs
  validator_client/Cargo.toml
Labels: ready-for-review

#5314 improve libp2p connected peer metrics
  Cargo.lock
  Cargo.toml
  beacon_node/http_api/src/lib.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  common/system_health/src/lib.rs
Labels: v5.0.1

#5304 Recognize the Caplin consensus client
  beacon_node/lighthouse_network/src/peer_manager/peerdb/client.rs
Labels: ready-for-review, v5.1.0

#5064 Optimise no-op PATCH ops in VC HTTP API
  validator_client/src/http_api/mod.rs
Labels: val-client, optimization, ready-for-merge, HTTP-API, v5.1.0

#5287 Drop address_change_broadcast
  beacon_node/client/src/address_change_broadcast.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/lib.rs
Labels: ready-for-merge
