Repository sigp/lighthouse, pull requests merged in 2024-08, with the labels that each got.

#6210 remove no longer required #[allow(clippy::mutable_key_type)]
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/network/src/lib.rs
Labels: code-quality, ready-for-merge

#6211 Work around UB in LMDB bindings
  slasher/src/database/lmdb_impl.rs
  slasher/tests/random.rs
Labels: bug, ready-for-merge, v5.3.0

#6179 chore: Use reference to an array representing a blob instead of an owned KzgBlob
  consensus/types/src/data_column_sidecar.rs
  crypto/kzg/src/lib.rs
  testing/ef_tests/src/cases/kzg_compute_cells_and_kzg_proofs.rs
Labels: waiting-on-author, das

#6073 Store changes to persist data columns
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  beacon_node/store/src/metadata.rs
  beacon_node/store/src/metrics.rs
Labels: ready-for-merge, das, das-unstable-merge

#6197 Import gossip data column into data availability checker
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/tests/store_tests.rs
Labels: ready-for-merge, das, das-unstable-merge

#6217 patch quick-protobuf
  Cargo.lock
  Cargo.toml
Labels: dependencies, v5.3.0

#6220 Downgrade re-org log to INFO
  beacon_node/beacon_chain/src/canonical_head.rs
  book/src/late-block-re-orgs.md
Labels: ready-for-merge, UX-and-logs, v5.3.0

#6207 Skip recursive discovery query if no useful ENRs
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
Labels: ready-for-merge

#6202 Remove double-locking in `eth/v1/node/syncing`
  beacon_node/http_api/src/lib.rs
Labels: low-hanging-fruit, optimization, ready-for-merge, HTTP-API, v5.3.1

#6221 Don't expect DAS config in HTTP spec response
  consensus/types/src/chain_spec.rs
Labels: val-client, ready-for-merge, v5.3.0

#6223 Broadcast VC requests in parallel and fix subscription error
  common/eth2/src/lib.rs
  validator_client/src/beacon_node_fallback.rs
  validator_client/src/duties_service.rs
  validator_client/src/lib.rs
Labels: ready-for-review, optimization, v5.3.0

#6194 Release v5.3.0
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, v5.3.0

#6234 add missing use std::sync::Lazylock to malloc_utils::glibc
  common/malloc_utils/src/glibc.rs
Labels: ready-for-merge

#6218 Store computed custody subnets in PeerDB and fix custody lookup test
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-review, das

#5545 Persist light client updates
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/light_client_server_cache.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/light_client.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/types/src/light_client_finality_update.rs
  consensus/types/src/light_client_header.rs
  consensus/types/src/light_client_optimistic_update.rs
  consensus/types/src/light_client_update.rs
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/light_client_verify_is_better_update.rs
  testing/ef_tests/src/decode.rs
  testing/ef_tests/src/error.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-merge, light-client

#5458 Add lcli command for manual rescue sync
  lcli/src/http_sync.rs
  lcli/src/main.rs
Labels: ready-for-merge, lcli

#6216 Add plumbing for PeerDAS supernodes (#5050, #5409, #5570, #5966)
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/client/src/builder.rs
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/src/service.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  consensus/types/src/chain_spec.rs
  lcli/src/generate_bootnode_enr.rs
  lcli/src/main.rs
Labels: ready-for-merge, das, das-unstable-merge

#6224 Implement data columns by network boilerplate
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/config.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/rpc/rate_limiter.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/manager.rs
Labels: ready-for-merge, das, das-unstable-merge

#6212 Add PeerDAS KZG lib integration (construction & KZG verification)
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/client/src/builder.rs
  consensus/types/src/data_column_sidecar.rs
  crypto/kzg/Cargo.toml
  crypto/kzg/benches/benchmark.rs
  crypto/kzg/src/lib.rs
  crypto/kzg/src/trusted_setup.rs
Labels: ready-for-merge, das, das-unstable-merge

#4380 Reuse password option prompts again on a wrong password
  account_manager/src/validator/import.rs
Labels: ready-for-merge

#6253 Merge `stable` into `unstable` after 5.3.0
  Cargo.lock
  Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/eth1/src/service.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  book/src/late-block-re-orgs.md
  boot_node/Cargo.toml
  common/eth2/src/lib.rs
  common/lighthouse_version/src/lib.rs
  consensus/types/src/chain_spec.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
  slasher/src/database/lmdb_impl.rs
  slasher/tests/random.rs
  validator_client/src/beacon_node_fallback.rs
  validator_client/src/duties_service.rs
  validator_client/src/lib.rs
Labels: do-not-merge, v5.3.1

#6245 Implement hierarchical state diffs config migration
  Cargo.lock
  beacon_node/store/Cargo.toml
  beacon_node/store/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
Labels: ready-for-merge, tree-states

#6255 Persist data columns to store
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
Labels: ready-for-merge, das, das-unstable-merge

#6172 Add Reth to execution clients suggested for installation
  book/src/installation.md
  book/src/merge-migration.md
  book/src/run_a_node.md
Labels: docs, ready-for-merge

#6257 Add sync lookup custody request state
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-review, das, das-unstable-merge

#6237 Implement PeerDAS RPC handlers
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: ready-for-review, das, das-unstable-merge

#6193 Implement DB schema upgrade for hierarchical state diffs
  Cargo.lock
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
  beacon_node/client/src/builder.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/config.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metadata.rs
  beacon_node/store/src/partial_beacon_state.rs
  book/src/help_bn.md
  common/eth2_config/src/lib.rs
  common/eth2_network_config/src/lib.rs
  database_manager/src/lib.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, tree-states

#6256 Batch sampling requests by peer
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/sampling.rs
Labels: Networking, das

#6247 Make `portable` the default in Lighthouse book and Makefile, update workflows
  .github/workflows/docker.yml
  .github/workflows/release.yml
  Makefile
  book/src/cross-compiling.md
  book/src/docker.md
  book/src/installation-binaries.md
  book/src/installation-source.md
Labels: docs, ready-for-merge, infra-ci, backwards-incompat

#6276 Fix PeerDAS stuck range sync when multiple columns are batched in a single request
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-review, das

#5987 add missing fields to get blob sidecars request
  beacon_node/http_api/src/block_id.rs
  beacon_node/http_api/src/lib.rs
  common/eth2/src/lib.rs
  consensus/types/src/blob_sidecar.rs
Labels: ready-for-merge, HTTP-API

#6254 Prevent fd leak in random slasher tests
  slasher/src/database.rs
  slasher/src/slasher.rs
  slasher/tests/random.rs
Labels: test improvement, ready-for-merge, slasher

#6013 Drop null_logger
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/shuffling_cache.rs
  beacon_node/eth1/Cargo.toml
  beacon_node/eth1/tests/test.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/genesis/tests/tests.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/tests/tests.rs
  beacon_node/http_metrics/Cargo.toml
  beacon_node/http_metrics/tests/tests.rs
  beacon_node/tests/test.rs
  common/logging/src/lib.rs
  common/task_executor/src/test_utils.rs
  lcli/Cargo.toml
  lcli/src/transition_blocks.rs
  lighthouse/environment/src/lib.rs
  lighthouse/environment/tests/environment_builder.rs
  testing/web3signer_tests/Cargo.toml
  testing/web3signer_tests/src/lib.rs
  validator_client/src/doppelganger_service.rs
Labels: ready-for-merge

#6154 Require manual confirmation to purge database with `purge-db`
  Cargo.lock
  account_manager/src/validator/create.rs
  account_manager/src/validator/exit.rs
  account_manager/src/validator/import.rs
  account_manager/src/validator/recover.rs
  account_manager/src/wallet/create.rs
  account_manager/src/wallet/recover.rs
  beacon_node/Cargo.toml
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  book/src/help_general.md
  book/src/help_vc.md
  book/src/help_vm.md
  book/src/help_vm_import.md
  book/src/help_vm_move.md
  common/account_utils/src/lib.rs
  lighthouse/src/main.rs
  lighthouse/tests/account_manager.rs
  validator_manager/src/common.rs
  validator_manager/src/create_validators.rs
  validator_manager/src/move_validators.rs
Labels: ready-for-merge, UX-and-logs, backwards-incompat

#6204 Add time metrics to aquire fork-choice lock
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/metrics.rs
Labels: ready-for-merge

#6282 Avoid redundant allocations in blob verification
  beacon_node/beacon_chain/src/blob_verification.rs
Labels: optimization, consensus, ready-for-merge

#6274 Add data columns by root sync request
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/network_context/requests/data_columns_by_root.rs
Labels: ready-for-merge, das, das-unstable-merge

#5937 Implement Electra `devnet-1` changes
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/validator_monitor.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/http_api/tests/tests.rs
  consensus/fork_choice/tests/tests.rs
  consensus/state_processing/src/genesis.rs
  consensus/state_processing/src/per_block_processing/block_signature_verifier.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/types/presets/gnosis/electra.yaml
  consensus/types/presets/mainnet/electra.yaml
  consensus/types/presets/minimal/electra.yaml
  consensus/types/src/attestation.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/consolidation_request.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/lib.rs
  consensus/types/src/payload.rs
  consensus/types/src/preset.rs
  consensus/types/src/signed_beacon_block.rs
  consensus/types/src/signed_consolidation.rs
  consensus/types/src/validator.rs
  consensus/types/src/withdrawal_request.rs
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/operations.rs
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-merge, electra, electra-v1.5.0-alpha.3

#6288 Remove VC response signing and update api-token in Lighthouse Book
  book/src/api-vc-auth-header.md
  book/src/api-vc-endpoints.md
  book/src/api-vc-sig-header.md
  book/src/validator-manager-move.md
Labels: docs, ready-for-merge

#6298 Update jsonwebtoken version to enable RISC-V builds
  Cargo.lock
  beacon_node/execution_layer/Cargo.toml
Labels: ready-for-merge

#6306 Bump diesel for CVE
  Cargo.lock
  Makefile
Labels: low-hanging-fruit, ready-for-merge, dependencies

#6305 Implement Electra spec v1.5.0-alpha.5
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
Labels: ready-for-review, consensus, electra

#6290 Update PeerDAS network parameters for peerdas-devnet-2
  beacon_node/lighthouse_network/src/discovery/enr.rs
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/types/src/chain_spec.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
  scripts/local_testnet/network_params_das_interop.yaml
Labels: ready-for-merge, das

#6303 Implement Metadatav3
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/src/types/globals.rs
Labels: ready-for-merge, das

#6309 chore!: Update rust_eth_kzg to v0.5.1 (formally known as peerdas-kzg)
  Cargo.lock
  Cargo.toml
  crypto/kzg/benches/benchmark.rs
  crypto/kzg/src/lib.rs
Labels: ready-for-merge, das

#6311 chore: Lazy initialize the KZG struct when running tests
  testing/ef_tests/src/cases/kzg_blob_to_kzg_commitment.rs
  testing/ef_tests/src/cases/kzg_compute_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_compute_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_compute_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_recover_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof_batch.rs
  testing/ef_tests/src/cases/kzg_verify_cell_kzg_proof_batch.rs
  testing/ef_tests/src/cases/kzg_verify_kzg_proof.rs
Labels: test improvement, ready-for-merge, das

#6316 Fix docker & release workflows
  .github/workflows/docker.yml
  .github/workflows/release.yml
  Makefile
Labels: ready-for-merge, infra-ci

#6313 Encode DataColumn responses with Electra context bytes
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-merge, das

#6312 chore: update and enable PeerDAS tests to latest spec test release (`1.5.0-alpha-5`)
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/kzg_recover_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_verify_cell_kzg_proof_batch.rs
  testing/ef_tests/tests/tests.rs
Labels: test improvement, ready-for-merge, das

#6315 Pin `ethereum-package` version to `4.2.0`
  scripts/local_testnet/network_params_das.yaml
  scripts/local_testnet/network_params_das_devnet_1.yaml
  scripts/local_testnet/network_params_das_interop.yaml
  scripts/local_testnet/start_local_testnet.sh
Labels: test improvement, ready-for-merge, das

#6326 Ignore flaky sampling test
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: ready-for-merge, das

#6318 Remove duplicate should_fetch_blobs check in sync lookup
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-merge, Networking

#6292 Increase priority for validator HTTP requests
  beacon_node/http_api/src/lib.rs
Labels: val-client, low-hanging-fruit, optimization, ready-for-merge, HTTP-API, v5.4.0

#6331 Return HTTP 404 for pruned blob requests
  beacon_node/http_api/src/block_id.rs
  beacon_node/http_api/tests/tests.rs
Labels: ready-for-merge, HTTP-API, backwards-incompat

#6317 Add reason of NoRequestNeeded to lookup sync
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
Labels: ready-for-merge, das
