Repository sigp/lighthouse, pull requests merged in 2024-06, with the labels that each got.

#5573 Make beacon processor queue sizes dynamic
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/client/src/builder.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
Labels: ready-for-merge, v5.2.0

#5845 Keep PendingComponents in da_checker during import_block
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
Labels: ready-for-merge, v5.2.0

#5882 Increase slog buffer size
  lighthouse/environment/src/lib.rs
Labels: ready-for-merge, UX-and-logs, v5.2.0

#5865 Replace local testnet script with Kurtosis
  .github/workflows/local-testnet.yml
  .github/workflows/test-suite.yml
  Cargo.lock
  beacon_node/genesis/tests/tests.rs
  lcli/Cargo.toml
  lcli/src/change_genesis_time.rs
  lcli/src/create_payload_header.rs
  lcli/src/deploy_deposit_contract.rs
  lcli/src/eth1_genesis.rs
  lcli/src/insecure_validators.rs
  lcli/src/interop_genesis.rs
  lcli/src/main.rs
  lcli/src/new_testnet.rs
  lcli/src/replace_state_pubkeys.rs
  scripts/local_testnet/.gitignore
  scripts/local_testnet/anvil_test_node.sh
  scripts/local_testnet/beacon_node.sh
  scripts/local_testnet/bootnode.sh
  scripts/local_testnet/clean.sh
  scripts/local_testnet/dump_logs.sh
  scripts/local_testnet/el_bootnode.sh
  scripts/local_testnet/genesis.json
  scripts/local_testnet/geth.sh
  scripts/local_testnet/kill_processes.sh
  scripts/local_testnet/network_params.yaml
  scripts/local_testnet/reset_genesis_time.sh
  scripts/local_testnet/setup.sh
  scripts/local_testnet/setup_time.sh
  scripts/local_testnet/start_local_testnet.sh
  scripts/local_testnet/stop_local_testnet.sh
  scripts/local_testnet/validator_client.sh
  scripts/local_testnet/vars.env
  scripts/tests/doppelganger_protection.sh
  scripts/tests/genesis.json
  scripts/tests/network_params.yaml
  scripts/tests/vars.env
  testing/eth1_test_rig/src/lib.rs
Labels: test improvement, ready-for-merge, infra-ci

#5006 Investigate `UnknownTargetRoot` slasher errors
  beacon_node/beacon_chain/src/attestation_verification.rs
Labels: ready-for-merge, UX-and-logs, slasher, v5.2.0

#5884 Fix getClientVersionV1 for Geth 1.13
  beacon_node/execution_layer/src/engine_api/json_structures.rs
Labels: ready-for-merge, UX-and-logs, v5.2.0

#5886 Update criterion
  Cargo.lock
  Cargo.toml
  consensus/swap_or_not_shuffle/benches/benches.rs
  consensus/types/benches/benches.rs
Labels: ready-for-review, code-quality, low-hanging-fruit, dependencies

#5867 Errors for all RPC Requests
  Cargo.lock
  Cargo.toml
  Dockerfile
  beacon_node/beacon_processor/src/work_reprocessing_queue.rs
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/self_limiter.rs
  beacon_node/lighthouse_network/src/service/gossip_cache.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/service.rs
  lighthouse/Cargo.toml
Labels: Networking, v5.2.0

#5876 Allow all RPC messages on disconnect
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: v5.2.0

#5902 Undo some CLI flag breakages
  beacon_node/src/cli.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
  lighthouse/tests/validator_client.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
Labels: val-client, ready-for-review, ready-for-merge, UX-and-logs, v5.2.0

#5916 Beta compiler fixes
  common/logging/src/async_record.rs
  common/validator_dir/src/validator_dir.rs
  validator_client/slashing_protection/src/interchange.rs
  validator_client/slashing_protection/src/interchange_test.rs
Labels: low-hanging-fruit, ready-for-merge

#5909 Fix skip-ci on `stable`
  .github/workflows/test-suite.yml
Labels: ready-for-merge, infra-ci

#5917 Fix panic on startup in debug build
  account_manager/src/lib.rs
  book/src/help_general.md
  validator_manager/src/lib.rs
Labels: ready-for-merge

#5927 Rust 1.79 lints
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/beacon_chain/src/validator_monitor.rs
  beacon_node/client/src/notifier.rs
  beacon_node/eth1/src/service.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/metrics.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/operation_pool/src/lib.rs
  common/deposit_contract/src/lib.rs
  consensus/proto_array/src/fork_choice_test_definition.rs
  consensus/proto_array/src/fork_choice_test_definition/votes.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/safe_arith/src/lib.rs
  consensus/state_processing/src/per_epoch_processing/base/validator_statuses.rs
  consensus/swap_or_not_shuffle/src/compute_shuffled_index.rs
  consensus/swap_or_not_shuffle/src/shuffle_list.rs
  consensus/types/benches/benches.rs
  consensus/types/src/beacon_state/committee_cache.rs
  consensus/types/src/slot_epoch.rs
  consensus/types/src/slot_epoch_macros.rs
  consensus/types/src/validator.rs
  crypto/eth2_key_derivation/tests/tests.rs
  crypto/eth2_wallet/src/wallet.rs
  scripts/local_testnet/start_local_testnet.sh
  scripts/tests/network_params.yaml
  validator_client/src/doppelganger_service.rs
  watch/src/blockprint/database.rs
  watch/src/blockprint/mod.rs
  watch/src/server/error.rs
  watch/src/updater/error.rs
  watch/src/updater/handler.rs
Labels: low-hanging-fruit, ready-for-merge

#5906 Fix slasher tests
  slasher/src/lib.rs
  slasher/src/test_utils.rs
  slasher/tests/attester_slashings.rs
Labels: slasher, electra

#5928 Remove some easy Electra TODOs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/store/src/partial_beacon_state.rs
  consensus/types/src/execution_payload_header.rs
Labels: ready-for-review, low-hanging-fruit, electra

#5929 Clean up Electra observed aggregates
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/observed_aggregates.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
Labels: ready-for-review, code-quality, electra

#5924 Append new `committee_bits` field to `Attestation`
  consensus/types/src/attestation.rs
Labels: electra-v1.5.0-alpha.3

#5932 Add `FUNDING.json` for DRIPS
  FUNDING.json
Labels: low-hanging-fruit, ready-for-merge

#5922 Remove `extern crate`
  beacon_node/client/src/lib.rs
  beacon_node/eth1/src/lib.rs
  beacon_node/eth1/src/metrics.rs
  beacon_node/execution_layer/src/versioned_hashes.rs
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/score.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/network/src/lib.rs
  beacon_node/network/src/metrics.rs
  beacon_node/src/lib.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metrics.rs
  common/compare_fields_derive/src/lib.rs
  common/eth2_interop_keypairs/src/lib.rs
  common/lighthouse_metrics/src/lib.rs
  common/logging/src/lib.rs
  common/logging/src/tracing_metrics_layer.rs
  common/slot_clock/src/lib.rs
  common/slot_clock/src/metrics.rs
  common/test_random_derive/src/lib.rs
  consensus/types/src/beacon_state/committee_cache/tests.rs
  consensus/types/src/beacon_state/tests.rs
  consensus/types/src/lib.rs
  consensus/types/src/subnet_id.rs
  consensus/types/src/sync_subnet_id.rs
  lcli/src/block_root.rs
  lcli/src/main.rs
  lcli/src/parse_ssz.rs
  lcli/src/skip_slots.rs
  lcli/src/state_root.rs
  lcli/src/transition_blocks.rs
  testing/simulator/src/main.rs
Labels: code-quality, low-hanging-fruit, ready-for-merge

#5787 Verify inclusion proof should not be fallible
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/sync/network_context/requests.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/test_utils/generate_random_block_and_blobs.rs
  consensus/types/src/test_utils/mod.rs
Labels: ready-for-merge

#5903 Fix SelfRateLimiter breaks the sequence of delayed_requests.
  Cargo.lock
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/rpc/self_limiter.rs
Labels: ready-for-merge, Networking, v5.2.1

#5896 Update local testnet documentation
  scripts/local_testnet/README.md
Labels: docs, ready-for-merge

#5890 Store data columns individually in store and caches
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/sync/network_context/custody.rs
  beacon_node/network/src/sync/sampling.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/lib.rs
Labels: ready-for-review, das

#5949 Fix `das` branch CI after `unstable` merge
  beacon_node/beacon_chain/benches/benches.rs
Labels: ready-for-review, das

#5959 Fix cargo audit: update curve25519-dalek
  Cargo.lock
Labels: ready-for-merge, dependencies

#5933 Update CI nethermind and LLVM versions
  .github/workflows/release.yml
  .github/workflows/test-suite.yml
  testing/execution_engine_integration/src/nethermind.rs
Labels: low-hanging-fruit, ready-for-merge, infra-ci

#5948 chore: change `impl Into<T> for U` to `impl From<U> for T`
  Makefile
  beacon_node/beacon_chain/src/beacon_fork_choice_store.rs
  beacon_node/beacon_chain/src/persisted_fork_choice.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  common/eth2/src/types.rs
  consensus/proto_array/src/proto_array.rs
  consensus/proto_array/src/ssz_container.rs
  consensus/types/src/graffiti.rs
  consensus/types/src/selection_proof.rs
  consensus/types/src/slot_epoch_macros.rs
  consensus/types/src/subnet_id.rs
  consensus/types/src/sync_selection_proof.rs
  consensus/types/src/sync_subnet_id.rs
  crypto/eth2_keystore/src/json_keystore/checksum_module.rs
  crypto/eth2_keystore/src/json_keystore/cipher_module.rs
  crypto/eth2_keystore/src/json_keystore/hex_bytes.rs
  crypto/eth2_keystore/src/json_keystore/kdf_module.rs
  crypto/eth2_wallet/src/json_wallet/mod.rs
  crypto/kzg/src/kzg_proof.rs
  validator_client/slashing_protection/src/lib.rs
Labels: code-quality, low-hanging-fruit, ready-for-merge

#5946 chore: simplify method to generate a random valid blob
  consensus/types/src/blob_sidecar.rs
Labels: test improvement, ready-for-merge

#5935 Lower tolerance of stale blobs on gossip
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: ready-for-merge, Networking, v5.2.1

#5942 report failed requests from `RPC` after being clear from rate limiter but not yet sent.
  beacon_node/lighthouse_network/src/rpc/mod.rs
Labels: ready-for-merge, v5.2.1

#5945 Ensure all handler events are covered
  beacon_node/lighthouse_network/src/rpc/handler.rs
Labels: ready-for-merge, v5.2.1

#5938 chore: add `recover_cells_and_compute_proofs` method
  consensus/types/src/data_column_sidecar.rs
  crypto/kzg/src/lib.rs
  testing/ef_tests/src/cases/kzg_compute_cells_and_kzg_proofs.rs
Labels: ready-for-merge, das

#5940 Electra attestations #5712 review
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/attester_cache.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/observed_aggregates.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/notifier.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/operation_pool/src/lib.rs
  common/eth2/src/types.rs
  consensus/state_processing/src/common/get_attesting_indices.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/types/src/aggregate_and_proof.rs
  consensus/types/src/attestation.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/beacon_state/committee_cache.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/fork_name.rs
  consensus/types/src/indexed_attestation.rs
  consensus/types/src/lib.rs
  consensus/types/src/signed_aggregate_and_proof.rs
  consensus/types/src/validator.rs
  slasher/src/array.rs
  slasher/src/database.rs
  slasher/src/lib.rs
  slasher/src/migrate.rs
  slasher/src/slasher.rs
  slasher/src/test_utils.rs
  testing/ef_tests/src/cases/fork_choice.rs
  validator_client/src/attestation_service.rs
  validator_client/src/validator_store.rs
Labels: electra

#5972 Electra attestation changes sean review
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/operation_pool/src/attestation.rs
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/operation_pool/src/lib.rs
  consensus/state_processing/src/verify_operation.rs
  consensus/types/src/aggregate_and_proof.rs
  consensus/types/src/attestation.rs
  consensus/types/src/fork_name.rs
  consensus/types/src/signed_aggregate_and_proof.rs
  consensus/types/src/sync_committee_contribution.rs
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: electra

#5980 Add electra lightclient types
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/lib.rs
  consensus/types/src/light_client_bootstrap.rs
  consensus/types/src/light_client_finality_update.rs
  consensus/types/src/light_client_header.rs
  consensus/types/src/light_client_optimistic_update.rs
  consensus/types/src/light_client_update.rs
Labels: ready-for-review, electra

#5975 Avoid changing slasher schema for Electra
  Cargo.lock
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/src/lib.rs
  consensus/types/src/indexed_attestation.rs
  consensus/types/src/lib.rs
  slasher/Cargo.toml
  slasher/src/database.rs
  slasher/src/error.rs
  slasher/src/migrate.rs
  slasher/src/slasher.rs
  slasher/src/test_utils.rs
  slasher/tests/attester_slashings.rs
  slasher/tests/proposer_slashings.rs
  slasher/tests/random.rs
  slasher/tests/wrap_around.rs
Labels: ready-for-review, slasher, electra

#5934 Update slasher DB size and Lighthouse book
  book/src/checkpoint-sync.md
  book/src/database-migrations.md
  book/src/faq.md
  book/src/slasher.md
  book/src/slashing-protection.md
  slasher/src/config.rs
Labels: docs, ready-for-merge, v5.2.1

#5974 Electra: `devnet-1` Rename and Move Stuff
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/store/src/partial_beacon_state.rs
  consensus/state_processing/src/per_block_processing/block_signature_verifier.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
  consensus/state_processing/src/upgrade/electra.rs
  consensus/types/presets/gnosis/electra.yaml
  consensus/types/presets/mainnet/electra.yaml
  consensus/types/presets/minimal/electra.yaml
  consensus/types/src/beacon_block.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/config_and_preset.rs
  consensus/types/src/consolidation_request.rs
  consensus/types/src/deposit_request.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/lib.rs
  consensus/types/src/payload.rs
  consensus/types/src/preset.rs
  consensus/types/src/signed_beacon_block.rs
  consensus/types/src/signed_consolidation.rs
  consensus/types/src/withdrawal_request.rs
  testing/ef_tests/src/cases/operations.rs
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: electra-v1.5.0-alpha.3

#5966 Update `csc` format in ENR and spec tests for devnet-1
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  consensus/types/src/data_column_subnet_id.rs
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/kzg_recover_cells_and_kzg_proofs.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-review, das, das-devnet-1

#5741 Block processing electra
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/genesis/src/eth1_genesis_service.rs
  beacon_node/http_api/src/builder_states.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
  consensus/state_processing/src/common/initiate_validator_exit.rs
  consensus/state_processing/src/common/slash_validator.rs
  consensus/state_processing/src/genesis.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/block_signature_verifier.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
  consensus/state_processing/src/per_block_processing/verify_attestation.rs
  consensus/state_processing/src/per_block_processing/verify_deposit.rs
  consensus/state_processing/src/per_block_processing/verify_exit.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/consolidation.rs
  consensus/types/src/payload.rs
  consensus/types/src/validator.rs
Labels: electra

#5997 Fix custody subnet count encoding
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
Labels: ready-for-review, das, das-devnet-1

#6000 Fix data column by range rpc request not being sent due to incorrect limits set
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
Labels: ready-for-review, das, das-devnet-1

#5969 Remove all batches related to a peer on disconnect
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-merge, v5.2.1

#5993 Attempt to continue lookups after adding peers
  beacon_node/network/src/sync/block_lookups/mod.rs
Labels: ready-for-merge, v5.2.1

#5995 Enable jemalloc by default on non windows targets
  Makefile
  lighthouse/Cargo.toml
  lighthouse/src/main.rs
Labels: low-hanging-fruit, ready-for-merge, backwards-incompat, v5.3.0

#5992 Avoid rayon in lighthouse block verification
  consensus/state_processing/src/per_block_processing/block_signature_verifier.rs
Labels: ready-for-merge, v5.3.0

#6008 Prevent connections from peers with a banned ip history
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
Labels: ready-for-merge, v5.3.0

#5705 Bound lookup parent chain length with tip extension
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: ready-for-review

#5710 Pass vec to range sync batch
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-review, Networking

#5989 Release v5.2.1 (testing branch)
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, v5.2.1

#6017 Merge v5.2.1 back into unstable
  Cargo.lock
  beacon_node/Cargo.toml
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: do-not-merge

#5761 Electra epoch processing
  consensus/state_processing/src/common/initiate_validator_exit.rs
  consensus/state_processing/src/epoch_cache.rs
  consensus/state_processing/src/per_epoch_processing/errors.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/validator.rs
Labels: ready-for-review, electra
