Repository sigp/lighthouse, pull requests merged in 2024-10, with the labels that each got.

#6441 Prevent Kurtosis container pollution
  scripts/local_testnet/stop_local_testnet.sh
Labels: test improvement, ready-for-merge

#5951 Add {fork_name}_enabled functions
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/client/src/notifier.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/http_api/src/build_block_contents.rs
  beacon_node/http_api/src/builder_states.rs
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/sync/range_sync/range.rs
  common/eth2/src/types.rs
  consensus/types/src/light_client_bootstrap.rs
  consensus/types/src/light_client_finality_update.rs
  consensus/types/src/light_client_header.rs
  consensus/types/src/light_client_optimistic_update.rs
  consensus/types/src/voluntary_exit.rs
  testing/ef_tests/src/cases/operations.rs
  testing/ef_tests/src/handler.rs
  validator_client/src/validator_store.rs
Labels: code-quality, ready-for-merge

#6266 Fix rolling file appender bug
  common/logging/src/lib.rs
  lighthouse/src/main.rs
Labels: bug, ready-for-merge, v6.0.0

#6433 Fit sampling log statements to fmt width
  beacon_node/network/src/sync/sampling.rs
Labels: ready-for-merge

#6454 Fix invalid data column sidecars getting accepted
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: bug, ready-for-review, ready-for-merge, das

#4393 Rework Validator Client fallback mechanism
  Cargo.lock
  book/src/help_vc.md
  common/eth2/Cargo.toml
  common/eth2/src/lib.rs
  lighthouse/tests/validator_client.rs
  testing/simulator/src/fallback_sim.rs
  validator_client/Cargo.toml
  validator_client/src/attestation_service.rs
  validator_client/src/beacon_node_fallback.rs
  validator_client/src/beacon_node_health.rs
  validator_client/src/block_service.rs
  validator_client/src/check_synced.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/doppelganger_service.rs
  validator_client/src/duties_service.rs
  validator_client/src/duties_service/sync.rs
  validator_client/src/http_api/mod.rs
  validator_client/src/http_api/test_utils.rs
  validator_client/src/http_api/tests.rs
  validator_client/src/lib.rs
  validator_client/src/notifier.rs
  validator_client/src/preparation_service.rs
  validator_client/src/sync_committee_service.rs
Labels: val-client, ready-for-review, v6.0.0

#6355 Output network-test logs into files in CI
  .github/workflows/test-suite.yml
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: ready-for-merge

#6410 Implement Subnet Sampling for PeerDAS
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/peer_sampling.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/types/src/chain_spec.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
Labels: ready-for-merge, das

#6307 Add test for ActiveSamplingRequest
  Cargo.lock
  beacon_node/network/Cargo.toml
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/peer_sampling.rs
Labels: ready-for-merge, das

#6422 Clean up temporary state flags while running
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/store/src/garbage_collection.rs
  beacon_node/store/src/hot_cold_store.rs
Labels: optimization, ready-for-merge, database, v6.0.0

#6464 Filter out BlsToExecutionChange messages for 0x02 validators
  beacon_node/operation_pool/src/bls_to_execution_changes.rs
  beacon_node/operation_pool/src/lib.rs
Labels: ready-for-review, electra

#6122 Transition block lookup sync to range sync
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-review

#6470 Add lockbud task to CI
  .github/workflows/test-suite.yml
  beacon_node/eth1/src/service.rs
  consensus/state_processing/src/consensus_context.rs
Labels: test improvement, code-quality, ready-for-merge, infra-ci

#6466 Bound min size of dynamic processor queues
  beacon_node/beacon_processor/src/lib.rs
Labels: ready-for-merge, v6.0.0

#6443 Prevent sync lookups from reverting to awaiting block
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-merge, das

#6156 Remove duplicated connection limits checks
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  beacon_node/lighthouse_network/src/service/behaviour.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
Labels: ready-for-review, Networking

#6483 Simplify hashing in shuffling
  Cargo.toml
  Makefile
  consensus/swap_or_not_shuffle/Cargo.toml
  consensus/swap_or_not_shuffle/src/shuffle_list.rs
  consensus/types/Cargo.toml
  consensus/types/benches/benches.rs
  crypto/kzg/benches/benchmark.rs
Labels: test improvement, code-quality, low-hanging-fruit, ready-for-merge, infra-ci

#6445 Electra updates for v1.5.0-alpha.6
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/engine_api/new_payload_request.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/config_and_preset.rs
  consensus/types/src/consolidation_request.rs
  consensus/types/src/deposit_request.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/execution_requests.rs
  consensus/types/src/lib.rs
  consensus/types/src/payload.rs
  consensus/types/src/signed_beacon_block.rs
  consensus/types/src/validator.rs
  consensus/types/src/withdrawal_request.rs
  testing/ef_tests/Makefile
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-review, electra, electra-v1.5.0-alpha.6

#6475 New historic state cache
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/hdiff.rs
  beacon_node/store/src/historic_state_cache.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metrics.rs
  beacon_node/store/src/reconstruct.rs
  book/src/help_bn.md
  common/lighthouse_metrics/src/lib.rs
  consensus/state_processing/src/common/update_progressive_balances_cache.rs
  consensus/state_processing/src/epoch_cache.rs
  consensus/state_processing/src/metrics.rs
  database_manager/src/lib.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-review, optimization, tree-states

#6403 Refactor data column reconstruction and avoid blocking processing
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
Labels: ready-for-merge, das

#6473 Better assert message in lookup sampling test
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/peer_sampling.rs
Labels: ready-for-merge, das

#6468 Use snap install yq in local_testnet
  scripts/local_testnet/README.md
Labels: docs, ready-for-merge, v6.0.0

#6481 Optimization to Redb slasher
  Cargo.lock
  slasher/Cargo.toml
  slasher/src/database/redb_impl.rs
Labels: optimization, ready-for-merge, slasher, v6.0.0

#6456 IDONTWANT message optimisation to cutoff for smaller messages
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
  beacon_node/lighthouse_network/gossipsub/src/behaviour/tests.rs
  beacon_node/lighthouse_network/gossipsub/src/config.rs
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
Labels: ready-for-merge, Networking

#6398 Generalize sync ActiveRequests
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/network_context/requests/blobs_by_root.rs
  beacon_node/network/src/sync/network_context/requests/blocks_by_root.rs
  beacon_node/network/src/sync/network_context/requests/data_columns_by_root.rs
  beacon_node/network/src/sync/peer_sampling.rs
Labels: syncing, ready-for-merge

#6502 Add Trin Execution ClientCode
  beacon_node/execution_layer/src/engine_api.rs
Labels: ready-for-merge, v6.0.0

#6383 Light client updates by range RPC
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/config.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/rpc/rate_limiter.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/router.rs
  consensus/types/src/light_client_update.rs
  lighthouse/environment/src/lib.rs
Labels: ready-for-merge, light-client, v6.0.0

#6490 Remove deprecated flags in prep for v6.0.0
  beacon_node/http_api/src/lib.rs
  beacon_node/operation_pool/src/attestation_id.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  book/src/help_general.md
  book/src/help_vc.md
  book/src/redundancy.md
  consensus/types/src/config_and_preset.rs
  lighthouse/src/main.rs
  lighthouse/tests/beacon_node.rs
  lighthouse/tests/validator_client.rs
  scripts/local_testnet/start_local_testnet.sh
  validator_client/src/cli.rs
  validator_client/src/config.rs
Labels: val-client, code-quality, ready-for-merge, backwards-incompat, v6.0.0

#6489 Remove TTD flags and `safe-slots-to-import-*`
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  book/src/api-vc-endpoints.md
  book/src/help_bn.md
  book/src/help_general.md
  book/src/help_vc.md
  book/src/help_vm.md
  book/src/help_vm_create.md
  book/src/help_vm_import.md
  book/src/help_vm_move.md
  common/clap_utils/src/lib.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/fork_choice/tests/tests.rs
  consensus/types/presets/gnosis/phase0.yaml
  consensus/types/presets/mainnet/phase0.yaml
  consensus/types/presets/minimal/phase0.yaml
  consensus/types/src/chain_spec.rs
  consensus/types/src/preset.rs
  lighthouse/src/main.rs
  lighthouse/tests/beacon_node.rs
  lighthouse/tests/exec.rs
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: code-quality, ready-for-merge, backwards-incompat, v6.0.0

#6524 Clarify command-line reference docs
  book/src/SUMMARY.md
  book/src/cli.md
  book/src/help_general.md
  scripts/cli.sh
Labels: docs, ready-for-merge

#6526 Fix BlobsByRange by reverting PR6462
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/rpc/rate_limiter.rs
  beacon_node/lighthouse_network/src/rpc/self_limiter.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/network_context.rs
Labels: bug, ready-for-merge, Networking, v6.0.0

#6523 VC: use block publication v2 SSZ API
  validator_client/src/block_service.rs
Labels: val-client, optimization, ready-for-merge, backwards-incompat, v6.0.0

#6531 Use `make cli-local` in CI test suite to remove redundant docker
  .github/workflows/test-suite.yml
  Makefile
Labels: ready-for-merge, infra-ci

#6534 RequestType::max_responses for LightClientUpdatesByRange
  beacon_node/lighthouse_network/src/rpc/protocol.rs
Labels: ready-for-merge

#6361 Fix electra light client types
  beacon_node/beacon_chain/src/light_client_server_cache.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/store/src/hot_cold_store.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/lib.rs
  consensus/types/src/light_client_bootstrap.rs
  consensus/types/src/light_client_finality_update.rs
  consensus/types/src/light_client_header.rs
  consensus/types/src/light_client_optimistic_update.rs
  consensus/types/src/light_client_update.rs
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/merkle_proof_validity.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-merge, light-client, electra

#6424 Modularize tracing executor and metrics rename
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_processor/Cargo.toml
  beacon_node/beacon_processor/src/metrics.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/metrics.rs
  beacon_node/eth1/Cargo.toml
  beacon_node/eth1/src/metrics.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/metrics.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/metrics.rs
  beacon_node/http_metrics/Cargo.toml
  beacon_node/http_metrics/src/metrics.rs
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/operation_pool/Cargo.toml
  beacon_node/operation_pool/src/metrics.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/metrics.rs
  common/lighthouse_metrics/Cargo.toml
  common/logging/Cargo.toml
  common/logging/src/lib.rs
  common/logging/src/tracing_metrics_layer.rs
  common/malloc_utils/Cargo.toml
  common/malloc_utils/src/glibc.rs
  common/malloc_utils/src/jemalloc.rs
  common/metrics/Cargo.toml
  common/metrics/src/lib.rs
  common/monitoring_api/Cargo.toml
  common/monitoring_api/src/gather.rs
  common/slot_clock/Cargo.toml
  common/slot_clock/src/metrics.rs
  common/task_executor/Cargo.toml
  common/task_executor/src/lib.rs
  common/task_executor/src/metrics.rs
  common/warp_utils/Cargo.toml
  common/warp_utils/src/metrics.rs
  consensus/fork_choice/Cargo.toml
  consensus/fork_choice/src/metrics.rs
  consensus/state_processing/Cargo.toml
  consensus/state_processing/src/common/update_progressive_balances_cache.rs
  consensus/state_processing/src/metrics.rs
  lighthouse/Cargo.toml
  lighthouse/src/metrics.rs
  slasher/Cargo.toml
  slasher/src/metrics.rs
  validator_client/Cargo.toml
  validator_client/src/http_metrics/metrics.rs
  validator_client/src/initialized_validators.rs
  validator_client/src/lib.rs
  validator_client/src/notifier.rs
Labels: ready-for-review

#6542 Simplify light client tests
  beacon_node/beacon_chain/tests/store_tests.rs
Labels: test improvement, low-hanging-fruit, ready-for-merge, v6.0.0

#6261 Validator manager commands for the Keymanager APIs
  Cargo.lock
  book/src/SUMMARY.md
  book/src/help_vm.md
  book/src/help_vm_import.md
  book/src/validator-manager-api.md
  book/src/validator-manager-create.md
  common/account_utils/src/lib.rs
  lighthouse/tests/validator_manager.rs
  validator_client/src/http_api/keystores.rs
  validator_manager/Cargo.toml
  validator_manager/src/create_validators.rs
  validator_manager/src/delete_validators.rs
  validator_manager/src/import_validators.rs
  validator_manager/src/lib.rs
  validator_manager/src/list_validators.rs
  validator_manager/src/move_validators.rs
Labels: val-client, ready-for-merge, v6.0.0

#6544 lower ListenerError log level
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-merge, Networking, v6.0.0

#6244 Correct gossipsub mesh and connected peer inconsistencies
  beacon_node/lighthouse_network/gossipsub/CHANGELOG.md
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
Labels: ready-for-merge, v6.0.0

#6550 Remove manual poll of the libp2p Swarm
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-merge

#6555 Pin `kurtosis-cli` version
  .github/workflows/local-testnet.yml
Labels: ready-for-review, infra-ci
