Repository sigp/lighthouse, pull requests merged in 2024-04, with the labels that each got.

#5514 Bump `h2` for RUSTSEC-2024-0332
  Cargo.lock
Labels: security, ready-for-merge, v5.2.0

#5136 Return `not synced` errors for endpoints that require syncing
  beacon_node/http_api/src/lib.rs
Labels: ready-for-merge, HTTP-API, v5.2.0

#5421 Remove DataAvailabilityView trait from ChildComponents
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/availability_view.rs
  beacon_node/beacon_chain/src/data_availability_checker/child_components.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
Labels: ready-for-merge

#5407 Add missing header to `eth/v1/builder/blinded_blocks`
  beacon_node/builder_client/src/lib.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
Labels: bug, ready-for-review, builder API, v5.2.0

#5525 Delete `ParticipationCache`
  consensus/state_processing/src/per_epoch_processing/altair/participation_cache.rs
Labels: code-quality, ready-for-merge

#5468 Use hashset to filter validators ids in http_api
  beacon_node/http_api/src/validators.rs
  common/eth2/src/types.rs
Labels: ready-for-merge

#5409 feat: add peerdas custody field to ENR
  Cargo.lock
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/discovery/subnet_predicate.rs
  beacon_node/network/src/service.rs
  consensus/types/src/data_column_subnet_id.rs
  consensus/types/src/eth_spec.rs
Labels: ready-for-review, Networking, das

#5531 Impl Ord on ForkName for ChainSpec usage
  consensus/types/src/chain_spec.rs
  consensus/types/src/fork_name.rs
Labels: ready-for-merge

#5352 Skip calculation of boosted_relay_value when builder_boost_factor pro…
  beacon_node/http_api/src/produce_block.rs
Labels: ready-for-merge, HTTP-API

#5534 Event-based block lookup tests
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-merge

#5420 Move processing cache out of DA
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/availability_view.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/processing_cache.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: ready-for-merge

#5546 Add logging in UnknownBlockHashFromAttestation handling
  beacon_node/network/src/sync/manager.rs
Labels: ready-for-merge

#5542 Bump ckzg to use the crates.io version
  Cargo.lock
  Cargo.toml
  crypto/kzg/Cargo.toml
Labels: ready-for-merge

#5536 Revert Arced pubkey optimization
  account_manager/src/validator/exit.rs
  beacon_node/beacon_chain/src/attestation_rewards.rs
  beacon_node/beacon_chain/src/beacon_block_reward.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/validator_monitor.rs
  beacon_node/beacon_chain/src/validator_pubkey_cache.rs
  beacon_node/beacon_chain/tests/op_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/genesis/src/interop.rs
  beacon_node/http_api/src/validator.rs
  beacon_node/http_api/src/validator_inclusion.rs
  beacon_node/http_api/src/validators.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/operation_pool/src/lib.rs
  common/eth2/src/types.rs
  consensus/fork_choice/tests/tests.rs
  consensus/proto_array/src/justified_balances.rs
  consensus/state_processing/src/common/initiate_validator_exit.rs
  consensus/state_processing/src/common/slash_validator.rs
  consensus/state_processing/src/common/update_progressive_balances_cache.rs
  consensus/state_processing/src/epoch_cache.rs
  consensus/state_processing/src/genesis.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
  consensus/state_processing/src/per_block_processing/verify_bls_to_execution_change.rs
  consensus/state_processing/src/per_block_processing/verify_exit.rs
  consensus/state_processing/src/per_epoch_processing/base/validator_statuses.rs
  consensus/state_processing/src/per_epoch_processing/effective_balance_updates.rs
  consensus/state_processing/src/per_epoch_processing/epoch_processing_summary.rs
  consensus/state_processing/src/per_epoch_processing/registry_updates.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/state_processing/src/per_epoch_processing/slashings.rs
  consensus/types/benches/benches.rs
  consensus/types/src/activation_queue.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/compact_state.rs
  consensus/types/src/beacon_state/exit_cache.rs
  consensus/types/src/beacon_state/slashings_cache.rs
  consensus/types/src/beacon_state/tests.rs
  consensus/types/src/lib.rs
  consensus/types/src/validator.rs
  lcli/src/new_testnet.rs
  lcli/src/replace_state_pubkeys.rs
  testing/state_transition_vectors/src/exit.rs
  watch/src/updater/mod.rs
Labels: tree-states

#5544 Remove availability view trait
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/availability_view.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
Labels: ready-for-merge

#5562 Nest lookup type into request id SingleBlock and SingleBlob
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-merge

#5555 Only load Kzg in tests if necessary and only load it once
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  crypto/kzg/src/lib.rs
Labels: test improvement, ready-for-merge

#5013 Use the `mesh_n` value from `NetworkLoad` for `PeerScoreSettings`
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/service/gossipsub_scoring_parameters.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/tests/common.rs
Labels: ready-for-merge, Networking

#5500 Deprecate `http-spec-fork` and `http-allow-sync-stalled`
  beacon_node/http_api/src/lib.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
  scripts/local_testnet/beacon_node.sh
  testing/simulator/src/sync_sim.rs
Labels: ready-for-merge

#5554 Allow 1 count block request to return 0 blocks
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/rpc/rate_limiter.rs
Labels: ready-for-merge

#5561 Sync lookup dedup range and blobs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-merge

#5556 Ensure proper ReqResp response stream termination
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: ready-for-merge

#5557 Use spawn_async in ByRoot handling workers
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: ready-for-merge

#5563 Make SingleLookupRequestState fields private
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/manager.rs
Labels: ready-for-merge

#5582 Ensure proper ReqResp blocks_by_* response stream termination
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: ready-for-merge

#5585 Restore Log on Error & Spawn Blocking in Streamer
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: ready-for-merge

#5591 Rename Functions to More Closely Match Spec
  beacon_node/genesis/src/eth1_genesis_service.rs
  consensus/state_processing/src/common/initiate_validator_exit.rs
  consensus/state_processing/src/genesis.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/types/src/beacon_state.rs
Labels: ready-for-merge

#5480 Revise `secrets-dir` flag in the VC
  account_manager/src/validator/create.rs
  book/src/validator-management.md
  validator_client/src/cli.rs
Labels: val-client, docs, ready-for-merge

#5598 Fix on-disk consensus context format
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/store/src/consensus_context.rs
  beacon_node/store/src/lib.rs
  consensus/state_processing/src/consensus_context.rs
Labels: bug, ready-for-review, database, deneb, v5.2.0

#5612 Fix cargo audit RUSTSEC-2024-0336
  Cargo.lock
  Cargo.toml
  consensus/int_to_bytes/Cargo.toml
  consensus/int_to_bytes/src/lib.rs
Labels: ready-for-merge

#5583 Handle sync lookup request streams in network context
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests.rs
Labels: ready-for-merge

#5611 Delete repetitive execute command in local testnet scripts
  scripts/local_testnet/start_local_testnet.sh
Labels: ready-for-merge

#5607 Electra: Add New Containers
  consensus/types/src/consolidation.rs
  consensus/types/src/deposit_receipt.rs
  consensus/types/src/execution_layer_withdrawal_request.rs
  consensus/types/src/lib.rs
  consensus/types/src/pending_balance_deposit.rs
  consensus/types/src/pending_consolidation.rs
  consensus/types/src/pending_partial_withdrawal.rs
  consensus/types/src/signed_consolidation.rs
Labels: electra

#5510 Add timing for block availability
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_times_cache.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: ready-for-merge, UX-and-logs, backwards-incompat, deneb

#5606 Electra: Add Preset, Constants, & Config
  consensus/types/src/chain_spec.rs
  consensus/types/src/eth_spec.rs
Labels: electra

#5614 Only `portable` builds (docker)
  .github/workflows/docker.yml
  lcli/Dockerfile.cross
Labels: ready-for-review, infra-ci, backwards-incompat, v5.2.0

#5633 Add missing lcli targets in makefile
  Makefile
Labels: ready-for-merge

#5635 Yaml rust2
  Cargo.lock
  consensus/int_to_bytes/Cargo.toml
  consensus/int_to_bytes/src/lib.rs
Labels: bug, low-hanging-fruit, ready-for-merge

#5641 Bump jobserver and fix non-portable builds
  Cargo.lock
  Cargo.toml
Labels: low-hanging-fruit, ready-for-merge, infra-ci

#5620 Drop lookup type trait for a simple arg
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/manager.rs
Labels: ready-for-merge

#5290 Encode Execution Engine Client Version In Graffiti
  Cargo.lock
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/graffiti_calculator.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/engines.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/src/config.rs
  common/lighthouse_version/src/lib.rs
  consensus/types/src/graffiti.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, v5.2.0

#5570 Send custody data column to `DataAvailabilityChecker` for determining block importability
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/client/src/builder.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/task_executor/Cargo.toml
  common/task_executor/src/test_utils.rs
  consensus/types/Cargo.toml
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/data_column_subnet_id.rs
  consensus/types/src/eth_spec.rs
  crypto/kzg/Cargo.toml
  crypto/kzg/src/lib.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, das

#5647 Fix execution integration tests
  testing/execution_engine_integration/src/test_rig.rs
Labels: low-hanging-fruit, ready-for-merge

#5630 Add electra presets to beacon API
  consensus/types/presets/gnosis/electra.yaml
  consensus/types/presets/mainnet/electra.yaml
  consensus/types/presets/minimal/electra.yaml
  consensus/types/src/chain_spec.rs
  consensus/types/src/config_and_preset.rs
  consensus/types/src/consts.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/preset.rs
Labels: ready-for-merge, electra

#5654 Deterministic block generation for tests
  consensus/types/src/test_utils/test_random/secret_key.rs
  consensus/types/src/test_utils/test_random/signature.rs
Labels: ready-for-merge

#5616 DAS sampling on sync
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/sampling.rs
  consensus/types/src/data_column_sidecar.rs
Labels: work-in-progress, das

#5656 Ignore gossip blob already imported
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: v5.2.0

#5659 Beta compiler fix
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/manager.rs
  common/logging/src/lib.rs
  common/logging/src/tracing_logging_layer.rs
  validator_client/src/duties_service.rs
  validator_client/src/http_metrics/mod.rs
Labels: ready-for-review, low-hanging-fruit

#4796 fix(validator_client): raise soft fd limit
  Cargo.lock
  validator_client/Cargo.toml
  validator_client/src/lib.rs
Labels: ready-for-review, UX-and-logs, v5.2.0

#5569 Re-process early sampling requests
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
  beacon_node/beacon_processor/src/work_reprocessing_queue.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/sync/sampling.rs
Labels: ready-for-review, das

#5665 pin macos release runner to `macos-13`
  .github/workflows/release.yml
Labels: low-hanging-fruit, ready-for-merge, infra-ci, v5.2.0

#5661 Remove snapshot cache related code
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/snapshot_cache.rs
  beacon_node/src/cli.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, v5.2.0

#5644 Attestation superstruct changes for EIP 7549
  beacon_node/beacon_chain/src/attestation_simulator.rs
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/attestation_verification/batch.rs
  beacon_node/beacon_chain/src/beacon_block_reward.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_reward.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/naive_aggregation_pool.rs
  beacon_node/beacon_chain/src/observed_aggregates.rs
  beacon_node/beacon_chain/src/observed_operations.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/validator_monitor.rs
  beacon_node/http_api/src/block_packing_efficiency.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_attestations.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/subnet_service/attestation_subnets.rs
  beacon_node/operation_pool/src/attestation.rs
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/operation_pool/src/persistence.rs
  beacon_node/store/src/consensus_context.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/fork_choice/tests/tests.rs
  consensus/state_processing/src/common/get_attesting_indices.rs
  consensus/state_processing/src/common/get_indexed_attestation.rs
  consensus/state_processing/src/consensus_context.rs
  consensus/state_processing/src/per_block_processing/block_signature_verifier.rs
  consensus/state_processing/src/per_block_processing/is_valid_indexed_attestation.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
  consensus/state_processing/src/per_block_processing/tests.rs
  consensus/state_processing/src/per_block_processing/verify_attestation.rs
  consensus/state_processing/src/per_block_processing/verify_attester_slashing.rs
  consensus/state_processing/src/verify_operation.rs
  consensus/types/src/aggregate_and_proof.rs
  consensus/types/src/attestation.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/indexed_attestation.rs
  consensus/types/src/signed_aggregate_and_proof.rs
  lcli/src/indexed_attestations.rs
  slasher/src/array.rs
  slasher/src/attestation_queue.rs
  slasher/src/attester_record.rs
  slasher/src/config.rs
  slasher/src/database.rs
  slasher/src/slasher.rs
  slasher/src/test_utils.rs
  testing/web3signer_tests/src/lib.rs
  validator_client/src/attestation_service.rs
  validator_client/src/http_api/tests/keystores.rs
  validator_client/src/validator_store.rs
Labels: electra

#5291 Uncomment self_hosted_runner after PR Merge #5137
  .github/workflows/test-suite.yml
Labels: ready-for-merge, v5.2.0

#5615 Only `portable` builds (binaries)
  .github/workflows/release.yml
Labels: ready-for-merge, infra-ci, v5.2.0

#5655 Merge parent and current sync lookups
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/child_components.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/parent_chain.rs
  beacon_node/network/src/sync/block_lookups/parent_lookup.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  common/lru_cache/src/time.rs
Labels: ready-for-review, v5.2.0

#5672  delete spammy log
  beacon_node/network/src/sync/manager.rs
Labels: ready-for-review, low-hanging-fruit, v5.2.0
