Repository sigp/lighthouse, pull requests merged in 2024-01, with the labels that each got.

#5023 Track shared memory in metrics
  Cargo.lock
  common/eth2/Cargo.toml
  common/eth2/src/lighthouse.rs
  common/warp_utils/src/metrics.rs
Labels: ready-for-review, v4.6.0

#5035 Block v3 builder boost factor
  Makefile
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/mock_execution_layer.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/http_api/src/produce_block.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/builders.md
  book/src/help_bn.md
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  lighthouse/tests/beacon_node.rs
  scripts/local_testnet/README.md
  testing/execution_engine_integration/src/test_rig.rs
Labels: ready-for-merge, HTTP-API, deneb, v4.6.0

#5036 update goerli config
  common/eth2_network_config/built_in_network_configs/prater/config.yaml
Labels: ready-for-merge, deneb, v4.6.0

#5041 Add hint for solving CLI tests failure
  Makefile
  scripts/cli.sh
Labels: ready-for-merge

#4813 Use blocks v3 endpoint in the VC
  book/src/help_vc.md
  lighthouse/tests/validator_client.rs
  validator_client/src/block_service.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/validator_store.rs
Labels: val-client, ready-for-merge, deneb, v4.6.0

#4841 Runtime rpc request sizes
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/lighthouse_network/src/rpc/codec/base.rs
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
  beacon_node/lighthouse_network/src/rpc/config.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/store/src/hot_cold_store.rs
  consensus/state_processing/src/per_block_processing/deneb.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/consts.rs
  consensus/types/src/fork_context.rs
  consensus/types/src/lib.rs
  consensus/types/src/runtime_var_list.rs
  crypto/kzg/src/lib.rs
Labels: ready-for-review, deneb, v4.6.0

#5038 Disallow genesis sync outside blob pruning window
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: v4.6.0

#5026 chore: remove needless Into
  beacon_node/http_api/src/produce_block.rs
Labels: optimization

#5049 Fix block v3 reward encodings
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/http_api/src/produce_block.rs
  beacon_node/http_api/src/version.rs
  common/eth2/src/types.rs
Labels: ready-for-merge, HTTP-API, deneb, v4.6.0

#5048 Fix `IncorrectAttestationSource` error in attn. simulator
  beacon_node/beacon_chain/src/attestation_simulator.rs
  beacon_node/beacon_chain/src/validator_monitor.rs
Labels: ready-for-merge, v4.6.0

#5042 v4.6.0-rc.0
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, v4.6.0

#4879 Add cache for parallel HTTP requests
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/parallel_state_cache.rs
  beacon_node/beacon_chain/src/shuffling_cache.rs
  beacon_node/beacon_chain/src/state_advance_timer.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/state_id.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  common/promise_cache/Cargo.toml
  common/promise_cache/src/lib.rs
  lighthouse/tests/beacon_node.rs
Labels: work-in-progress, optimization, HTTP-API, tree-states

#5057 Tree states release v4.6.111-exp
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-review, tree-states

#5056 Fix asset paths in release CI upload job
  .github/workflows/release.yml
Labels: bug, ready-for-merge, infra-ci, v4.6.0

#5062 Fix content type header for block v3 ssz response
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/produce_block.rs
  beacon_node/http_api/src/version.rs
  common/eth2/src/lib.rs
Labels: ready-for-merge, deneb, v4.6.0

#5052 Update teku's bootnodes
  common/eth2_network_config/built_in_network_configs/mainnet/boot_enr.yaml
Labels: ready-for-merge

#5059 docs: fix typos
  Makefile
  beacon_node/src/cli.rs
  beacon_node/src/lib.rs
  book/src/help_bn.md
  book/src/redundancy.md
  book/src/slasher.md
  book/src/validator-manager-create.md
  common/malloc_utils/src/jemalloc.rs
Labels: docs, ready-for-merge

#5021 Fix zero port error
  beacon_node/src/config.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge

#4979 add tracing metrics layer for dependency logging
  Cargo.lock
  Cargo.toml
  book/src/help_general.md
  boot_node/src/lib.rs
  common/logging/Cargo.toml
  common/logging/src/lib.rs
  common/logging/src/tracing_metrics_layer.rs
  lighthouse/Cargo.toml
  lighthouse/src/main.rs
Labels: ready-for-merge

#4988 Critical dependency logging
  Cargo.lock
  Cargo.toml
  common/directory/src/lib.rs
  common/logging/Cargo.toml
  common/logging/src/lib.rs
  common/logging/src/tracing_logging_layer.rs
  lighthouse/src/main.rs
Labels: ready-for-merge

#5081 Remove the `blobs_db` directory when `--purge-db` flag is present.
  beacon_node/src/config.rs
Labels: bug, ready-for-review, deneb

#5085 Bump h2
  Cargo.lock
Labels: low-hanging-fruit, ready-for-merge, v4.6.0

#5078 Fix PublishBlockRequest SSZ decoding
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/types/src/signed_beacon_block.rs
Labels: bug, ready-for-merge, HTTP-API, v4.6.0

#5084 Hold HeadTracker lock until persisting to disk
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/head_tracker.rs
Labels: ready-for-merge, database, v4.6.0

#5089 set deneb fork on testnets
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
Labels: ready-for-merge, deneb, v4.6.0

#5108 Upgrade shlex to 1.3.0
  Cargo.lock
Labels: ready-for-merge, v4.6.0

#5098 Small Readability Improvement in Sync Code
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
Labels: code-quality, ready-for-merge

#5104 Reduce size of futures in HTTP API to prevent stack overflows
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  common/eth2/src/types.rs
  consensus/fork_choice/tests/tests.rs
  consensus/state_processing/src/per_block_processing/tests.rs
  testing/state_transition_vectors/src/exit.rs
  validator_client/src/block_service.rs
Labels: bug, ready-for-review, optimization, v4.6.0

#5110 Gossipsub fanout correction
  Cargo.lock
  Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
Labels: ready-for-review, v4.6.0

#5111 Correct a bug that would cause unnecessary discovery requests
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
Labels: ready-for-review, v4.6.0

#5119 Backfill blob storage fix
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v19.rs
  beacon_node/store/src/metadata.rs
  book/src/database-migrations.md
Labels: bug, ready-for-merge, deneb, v4.6.0

#5118 Fix indices filter in blobs_sidecar http endpoint
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
Labels: bug, ready-for-merge, deneb, v4.6.0

#5113 Correct multiple dial bug
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-review, v4.6.0

#5086 Expose additional builder booster related flags in the vc
  account_manager/src/validator/import.rs
  book/src/api-vc-endpoints.md
  book/src/builders.md
  book/src/help_vc.md
  book/src/help_vm_create.md
  book/src/help_vm_move.md
  common/account_utils/src/validator_definitions.rs
  common/eth2/src/lighthouse_vc/http_client.rs
  common/eth2/src/lighthouse_vc/types.rs
  lighthouse/tests/account_manager.rs
  lighthouse/tests/validator_client.rs
  lighthouse/tests/validator_manager.rs
  testing/web3signer_tests/src/lib.rs
  validator_client/src/block_service.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/http_api/create_validator.rs
  validator_client/src/http_api/keystores.rs
  validator_client/src/http_api/mod.rs
  validator_client/src/http_api/remotekeys.rs
  validator_client/src/http_api/test_utils.rs
  validator_client/src/http_api/tests.rs
  validator_client/src/http_api/tests/keystores.rs
  validator_client/src/initialized_validators.rs
  validator_client/src/validator_store.rs
  validator_manager/src/common.rs
  validator_manager/src/create_validators.rs
  validator_manager/src/move_validators.rs
Labels: ready-for-review, v4.6.0

#5123 v4.6.0
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, v4.6.0

#5121 Remove erroneous bash evaluation from `scripts/cli.sh`
  scripts/cli.sh
Labels: bug, ready-for-merge, infra-ci

#5126 Update Mergify commit message template to use PR title instead of commit message
  .github/mergify.yml
Labels: ready-for-merge, infra-ci

#5132 Fix new CLI tests for tree-states
  lighthouse/tests/beacon_node.rs
Labels: ready-for-review, tree-states

#5103 #5102 Fix load_state_for_block_production metric mapping
  beacon_node/beacon_chain/src/beacon_chain.rs
Labels: bug, ready-for-merge

#5135 Increase attestation cache sizes
  beacon_node/beacon_chain/src/observed_aggregates.rs
  beacon_node/beacon_chain/src/observed_attesters.rs
Labels: bug, ready-for-merge, deneb, v4.7.0

#5120 Fix off-by-one in backfill sig verification
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/tests/store_tests.rs
Labels: bug, ready-for-merge, deneb

#5065 Remove custom SSZ beacon states route
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lighthouse.rs
Labels: ready-for-merge, HTTP-API, backwards-incompat

#5097 Fix tree-states sub-epoch diffs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/hdiff.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  beacon_node/store/src/metadata.rs
  beacon_node/store/src/reconstruct.rs
  database_manager/src/lib.rs
Labels: bug, ready-for-review, tree-states

#5144 `fsync` during backfill to prevent DB corruption
  beacon_node/beacon_chain/src/historical_blocks.rs
Labels: ready-for-review, tree-states

#5147 Tree states v4.6.222-exp
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: deneb, tree-states

#5037 Delete temporary mitigation for equivocation via RPC
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
Labels: code-quality, security, low-hanging-fruit, ready-for-merge

#4575 Assume Content-Type is json for endpoints that require json
  Cargo.lock
  beacon_node/http_api/src/lib.rs
  common/eth2/src/lib.rs
  common/warp_utils/Cargo.toml
  common/warp_utils/src/json.rs
  common/warp_utils/src/lib.rs
  common/warp_utils/src/reject.rs
Labels: ready-for-merge, HTTP-API

#4969 Compute recent lightclient updates
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/light_client_finality_update_verification.rs
  beacon_node/beacon_chain/src/light_client_optimistic_update_verification.rs
  beacon_node/beacon_chain/src/light_client_server_cache.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_processor/src/work_reprocessing_queue.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/client/src/compute_light_client_updates.rs
  beacon_node/client/src/lib.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/router.rs
  beacon_node/src/config.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/light_client_bootstrap.rs
  consensus/types/src/light_client_finality_update.rs
  lighthouse/tests/beacon_node.rs
  testing/simulator/src/checks.rs
  testing/simulator/src/eth1_sim.rs
Labels: ready-for-merge, light-client

#4959 Update deterministic subnets upgrade to allow prefix computation
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/prater/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/types/src/chain_spec.rs
  consensus/types/src/subnet_id.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
Labels: ready-for-review, t Networking

#5068 Move from igd to igd-next
  Cargo.lock
  beacon_node/network/Cargo.toml
  beacon_node/network/src/nat.rs
Labels: ready-for-review

#5066 Add gossipsub as a Lighthouse behaviour
  Cargo.lock
  Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/gossipsub/backoff.rs
  beacon_node/lighthouse_network/src/gossipsub/behaviour.rs
  beacon_node/lighthouse_network/src/gossipsub/behaviour/tests.rs
  beacon_node/lighthouse_network/src/gossipsub/config.rs
  beacon_node/lighthouse_network/src/gossipsub/error.rs
  beacon_node/lighthouse_network/src/gossipsub/generated/compat.proto
  beacon_node/lighthouse_network/src/gossipsub/generated/compat/mod.rs
  beacon_node/lighthouse_network/src/gossipsub/generated/compat/pb.rs
  beacon_node/lighthouse_network/src/gossipsub/generated/gossipsub/mod.rs
  beacon_node/lighthouse_network/src/gossipsub/generated/gossipsub/pb.rs
  beacon_node/lighthouse_network/src/gossipsub/generated/mod.rs
  beacon_node/lighthouse_network/src/gossipsub/generated/rpc.proto
  beacon_node/lighthouse_network/src/gossipsub/gossip_promises.rs
  beacon_node/lighthouse_network/src/gossipsub/handler.rs
  beacon_node/lighthouse_network/src/gossipsub/mcache.rs
  beacon_node/lighthouse_network/src/gossipsub/metrics.rs
  beacon_node/lighthouse_network/src/gossipsub/mod.rs
  beacon_node/lighthouse_network/src/gossipsub/peer_score.rs
  beacon_node/lighthouse_network/src/gossipsub/peer_score/params.rs
  beacon_node/lighthouse_network/src/gossipsub/peer_score/tests.rs
  beacon_node/lighthouse_network/src/gossipsub/protocol.rs
  beacon_node/lighthouse_network/src/gossipsub/rpc_proto.rs
  beacon_node/lighthouse_network/src/gossipsub/subscription_filter.rs
  beacon_node/lighthouse_network/src/gossipsub/time_cache.rs
  beacon_node/lighthouse_network/src/gossipsub/topic.rs
  beacon_node/lighthouse_network/src/gossipsub/transform.rs
  beacon_node/lighthouse_network/src/gossipsub/types.rs
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/src/service/behaviour.rs
  beacon_node/lighthouse_network/src/service/gossipsub_scoring_parameters.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/service/tests.rs
Labels: ready-for-merge

#5143 Add a note about validator monitoring in Lighthouse book
  book/src/validator-monitoring.md
Labels: docs, ready-for-merge

#5109 Test backfill
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/builder.rs
Labels: ready-for-merge

#5000 Some updates in Lighthouse Book
  book/src/advanced_database.md
  book/src/api-bn.md
  book/src/api-vc-endpoints.md
  book/src/database-migrations.md
  book/src/faq.md
  book/src/slasher.md
  book/src/ui-configuration.md
  book/src/ui-faqs.md
  book/src/validator-web3signer.md
Labels: docs, ready-for-merge
