Repository sigp/lighthouse, pull requests merged in 2024-07, with the labels that each got.

#6027 Delete duplicated serde code
  consensus/types/src/indexed_attestation.rs
Labels: ready-for-review, code-quality

#5743 Electra engine api
  beacon_node/beacon_chain/src/electra_readiness.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/store/src/partial_beacon_state.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/state_processing/src/upgrade/electra.rs
  consensus/types/presets/gnosis/electra.yaml
  consensus/types/presets/mainnet/electra.yaml
  consensus/types/presets/minimal/electra.yaml
  consensus/types/src/beacon_state.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/config_and_preset.rs
  consensus/types/src/deposit_receipt.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/lib.rs
  consensus/types/src/payload.rs
  consensus/types/src/preset.rs
Labels: electra

#6025 Fix incorrect inbound request count causing rate limiting.
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
Labels: ready-for-review, das

#6035 Fix SigVerifiedOp SSZ implementation
  Cargo.lock
  Cargo.toml
  consensus/state_processing/Cargo.toml
  consensus/state_processing/src/verify_operation.rs
  consensus/types/src/attester_slashing.rs
  consensus/types/src/test_utils/test_random.rs
Labels: bug, ready-for-review, database

#6005 Update pending balance deposit processing
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
Labels: ready-for-review, consensus, electra, electra-v1.5.0-alpha.3

#5976 Broadcast validator registration to all synced beacon nodes
  validator_client/src/preparation_service.rs
Labels: val-client, ready-for-merge

#6024 Update MDBX
  Cargo.lock
  slasher/Cargo.toml
Labels: low-hanging-fruit, ready-for-merge, slasher

#6037 Update Sepolia Bootnodes
  common/eth2_network_config/built_in_network_configs/sepolia/boot_enr.yaml
Labels: ready-for-merge, v5.3.0

#6040 Tree states archive metrics
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/store/src/hdiff.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/metrics.rs
Labels: work-in-progress

#6007 Downgrade duplication log of attestation to Debug
  beacon_node/beacon_chain/src/validator_monitor.rs
Labels: ready-for-merge, UX-and-logs, v5.3.0

#5897 Store pubkey cache decompressed on disk
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v20.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v21.rs
  beacon_node/beacon_chain/src/validator_pubkey_cache.rs
  beacon_node/store/src/metadata.rs
  crypto/bls/src/generic_public_key.rs
  crypto/bls/src/impls/blst.rs
  crypto/bls/src/impls/fake_crypto.rs
  crypto/bls/src/lib.rs
  crypto/bls/tests/tests.rs
Labels: ready-for-review, optimization, database, backwards-incompat, v5.3.0

#6001 Update `engine-api` for `devnet-1`
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  consensus/types/src/execution_payload_header.rs
Labels: ready-for-review, electra-v1.5.0-alpha.3

#6046 Record `BEACON_BLOCK_DELAY_GOSSIP` metric only after a bock is verified
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: bug, ready-for-merge, v5.3.0

#6014 Drop skip too large condition for liveness safety
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
Labels: ready-for-merge

#6050 Increase penalty for old block gossip spam
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: ready-for-merge, Networking, v5.3.0

#6039 Show `blst` hardware support in `lighthouse --version`
  lighthouse/src/main.rs
Labels: ready-for-merge, UX-and-logs

#5968 Add kurtosis config for DAS testing
  scripts/local_testnet/network_params.yaml
  scripts/local_testnet/network_params_das_devnet_1.yaml
  scripts/local_testnet/network_params_das_interop.yaml
  scripts/local_testnet/network_params_das_local.yaml
  scripts/local_testnet/start_local_testnet.sh
Labels: ready-for-review, das, skip-ci

#6060 Delete `cached_tree_hash`
  Cargo.lock
  Cargo.toml
  consensus/cached_tree_hash/Cargo.toml
  consensus/cached_tree_hash/src/cache.rs
  consensus/cached_tree_hash/src/cache_arena.rs
  consensus/cached_tree_hash/src/impls.rs
  consensus/cached_tree_hash/src/lib.rs
  consensus/cached_tree_hash/src/test.rs
  consensus/types/Cargo.toml
  consensus/types/src/beacon_state.rs
  consensus/types/src/historical_summary.rs
  consensus/types/src/lib.rs
  consensus/types/src/participation_list.rs
Labels: ready-for-review, code-quality

#6032 Remove generic Id param from RequestId
  beacon_node/lighthouse_network/src/rpc/self_limiter.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/lighthouse_network/src/service/behaviour.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-merge, Networking

#6051 Delete old database schemas
  beacon_node/beacon_chain/src/beacon_fork_choice_store.rs
  beacon_node/beacon_chain/src/persisted_fork_choice.rs
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v17.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v18.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v19.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/eth1/src/deposit_cache.rs
  beacon_node/eth1/src/inner.rs
  beacon_node/eth1/src/lib.rs
  book/src/database-migrations.md
  consensus/proto_array/src/lib.rs
  consensus/proto_array/src/proto_array.rs
  consensus/proto_array/src/ssz_container.rs
Labels: code-quality, ready-for-merge, v5.3.0

#5822 Add randomization in sync retry batch peer selection
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/range_sync/chain.rs
Labels: ready-for-review, Networking

#5422 Implement gossipsub IDONTWANT
  Cargo.lock
  Cargo.toml
  beacon_node/lighthouse_network/gossipsub/CHANGELOG.md
  beacon_node/lighthouse_network/gossipsub/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
  beacon_node/lighthouse_network/gossipsub/src/behaviour/tests.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/gossipsub/pb.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/rpc.proto
  beacon_node/lighthouse_network/gossipsub/src/gossip_promises.rs
  beacon_node/lighthouse_network/gossipsub/src/metrics.rs
  beacon_node/lighthouse_network/gossipsub/src/protocol.rs
  beacon_node/lighthouse_network/gossipsub/src/types.rs
  beacon_node/lighthouse_network/src/service/utils.rs
Labels: ready-for-review, Networking

#5941 chore: add rust PeerdasKZG crypto library for peerdas functionality and rollback c-kzg dependency to 4844 version
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/kzg_utils.rs
  consensus/types/src/data_column_sidecar.rs
  crypto/kzg/Cargo.toml
  crypto/kzg/src/lib.rs
  testing/ef_tests/src/cases/kzg_recover_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_verify_cell_kzg_proof_batch.rs
Labels: ready-for-review, crypto, das

#6049 Add sync network context cache size metrics
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-review

#6042 Drop unused store metrics
  beacon_node/store/src/metrics.rs
Labels: ready-for-review

#5913 Add PeerDAS DataColumn type
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/lib.rs
  crypto/kzg/src/lib.rs
Labels: ready-for-review, das

#6056 update windows logo location in release template
  .github/workflows/release.yml
Labels: ready-for-merge

#6069 Update PeerDAS interop testnet config
  scripts/local_testnet/network_params.yaml
  scripts/local_testnet/network_params_das_interop.yaml
Labels: test improvement, ready-for-review, das

#5891 Drop overflow cache
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/store/src/lib.rs
Labels: ready-for-merge, v5.3.0

#5859 Log warning on startup if chain spec contains misaligned fork epochs
  beacon_node/src/lib.rs
  consensus/types/src/fork_name.rs
Labels: ready-for-merge, light-client

#5862 Reject `octet-stream` content type when we expect `json`
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
  common/warp_utils/src/json.rs
  common/warp_utils/src/reject.rs
Labels: ready-for-merge, HTTP-API

#6077 Fix builds with `slasher-redb`
  Makefile
  slasher/src/database/redb_impl.rs
  slasher/tests/backend.rs
Labels: bug, low-hanging-fruit, ready-for-merge, v5.3.0

#5898 Change DB Manager Clap usage to derive
  Cargo.lock
  Cargo.toml
  beacon_node/src/config.rs
  book/src/help_general.md
  database_manager/Cargo.toml
  database_manager/src/cli.rs
  database_manager/src/lib.rs
  lighthouse/src/cli.rs
  lighthouse/src/main.rs
Labels: code-quality, ready-for-merge

#6015 Bound max count of lookups
  beacon_node/network/src/sync/block_lookups/mod.rs
Labels: ready-for-merge, Networking

#6083 Unimplement `TreeHash` for `BeaconState`
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/http_api/tests/fork_tests.rs
  beacon_node/http_api/tests/interactive_tests.rs
  boot_node/src/config.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/light_client_update.rs
  testing/ef_tests/src/cases/common.rs
  testing/ef_tests/src/cases/ssz_generic.rs
  testing/ef_tests/src/cases/ssz_static.rs
  testing/ef_tests/src/handler.rs
Labels: code-quality, consensus, ready-for-merge, tree-states

#6087 Update Dockerfile to work on latest version of Docker
  Dockerfile
  lcli/Dockerfile
Labels: low-hanging-fruit, ready-for-merge

#6095 Add range sync metrics to track efficiency
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-review

#6093 Enable the outbound rate limiter by default, and update blobs method quotas
  beacon_node/lighthouse_network/src/rpc/config.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
Labels: ready-for-review, backwards-incompat

#5744 Beacon api + validator electra
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/fork_tests.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/types/src/attestation.rs
  consensus/types/src/attester_slashing.rs
  validator_client/src/attestation_service.rs
Labels: ready-for-review, electra

#6092 Bump default `logfile-max-number` to 10
  book/src/help_bn.md
  book/src/help_general.md
  book/src/help_vc.md
  book/src/help_vm.md
  book/src/help_vm_create.md
  book/src/help_vm_import.md
  book/src/help_vm_move.md
  lighthouse/src/main.rs
Labels: low-hanging-fruit, ready-for-merge, backwards-incompat

#5864 Add `block_gossip` Beacon API events
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/events.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/types.rs
Labels: ready-for-merge, HTTP-API, v5.3.0

#6089 Measure consensus verification time
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_times_cache.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/metrics.rs
Labels: ready-for-merge, UX-and-logs, v5.3.0

#6103 Remove trace logging
  Cargo.toml
Labels: ready-for-merge

#6084 Avoid retrying same sampling peer that previously failed
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/sampling.rs
Labels: ready-for-review, das, das-devnet-1

#6004 Various fixes to custody range sync
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/sampling.rs
Labels: work-in-progress, das, das-devnet-1

#5529 Remove VC response signing and fix HTTP error handling
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/task_spawner.rs
  common/eth2/src/lighthouse_vc/http_client.rs
  common/eth2/src/lighthouse_vc/mod.rs
  common/warp_utils/src/reject.rs
  common/warp_utils/src/task.rs
  validator_client/src/http_api/api_secret.rs
  validator_client/src/http_api/mod.rs
Labels: val-client, ready-for-merge, HTTP-API, backwards-incompat, v5.3.0

#5758 Ef tests electra
  beacon_node/beacon_chain/src/eth1_chain.rs
  consensus/state_processing/src/common/initiate_validator_exit.rs
  consensus/state_processing/src/genesis.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/state_processing/src/upgrade/electra.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/deposit_request.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/execution_payload_header.rs
  consensus/types/src/fork_name.rs
  consensus/types/src/lib.rs
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/epoch_processing.rs
  testing/ef_tests/src/cases/operations.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/src/lib.rs
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-review, electra

#6118 chore: update peerdas-kzg library
  Cargo.lock
  Cargo.toml
  crypto/kzg/Cargo.toml
  crypto/kzg/benches/benchmark.rs
  crypto/kzg/src/lib.rs
Labels: ready-for-review, das

#6041 Track store metrics by DB column
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metrics.rs
Labels: ready-for-merge

#6117 chore: update the trusted setup to match the consensus-specs version
  common/eth2_network_config/built_in_network_configs/trusted_setup.json
  crypto/kzg/src/trusted_setup.rs
Labels: ready-for-merge

#6125 Fix `proposer-nodes` cli flag name
  lighthouse/tests/validator_client.rs
  validator_client/src/config.rs
Labels: bug, val-client, ready-for-merge

#6115 Disable slasher default features
  Cargo.toml
Labels: ready-for-merge, v5.3.0

#6079 Add requires `suggested-fee-recipient` flag when `always-prepare-payload` is set
  beacon_node/src/cli.rs
  book/src/api-bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-review, UX-and-logs, backwards-incompat, v5.3.0

#6065 Add an option to keep existing enclave when starting local testnet
  scripts/local_testnet/network_params.yaml
  scripts/local_testnet/start_local_testnet.sh
Labels: test improvement, ready-for-merge

#6129 Return syncing on HTTP when sync is stalled
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
Labels: ready-for-merge, Networking, HTTP-API, v5.3.0

#6131 Delete `--builder-profit-threshold` flag
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
Labels: bug, ready-for-merge, backwards-incompat, v5.3.0

#6134 Attempt to fix flaky basic sim test
  testing/simulator/src/basic_sim.rs
  testing/simulator/src/fallback_sim.rs
  testing/simulator/src/local_network.rs
Labels: test improvement, ready-for-merge

#6143 Upgrade `openssl` to address cargo audit issue
  Cargo.lock
Labels: ready-for-merge

#6127 Add PeerDAS presets and configs.
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/types/presets/gnosis/eip7594.yaml
  consensus/types/presets/mainnet/eip7594.yaml
  consensus/types/presets/minimal/eip7594.yaml
  consensus/types/src/chain_spec.rs
  consensus/types/src/preset.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
Labels: ready-for-merge, das, das-unstable-merge

#6076 Update `is_available` check to support PeerDAS.
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/lib.rs
  consensus/types/src/blob_sidecar.rs
Labels: ready-for-merge, das, das-unstable-merge

#4789 Make proposer duties work pre-genesis
  beacon_node/http_api/src/proposer_duties.rs
Labels: ready-for-merge

#6148 level down libp2p quic accept and close errors
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-review, Networking, v5.3.0

#5301 Remove use of ethers core
  Cargo.lock
  Cargo.toml
  beacon_node/execution_layer/Cargo.toml
  beacon_node/execution_layer/src/block_hash.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/keccak.rs
  beacon_node/execution_layer/src/versioned_hashes.rs
  consensus/types/Cargo.toml
  consensus/types/src/execution_block_header.rs
  consensus/types/src/lib.rs
Labels: code-quality, ready-for-merge, dependencies, v5.3.0

#5979 Siren Docs Upgrade
  book/src/imgs/ui-auth.png
  book/src/imgs/ui-bls-modal.png
  book/src/imgs/ui-bls-required.png
  book/src/imgs/ui-session.png
  book/src/imgs/ui-settings.png
  book/src/imgs/ui-val-edit.png
  book/src/imgs/ui-val-exit.png
  book/src/imgs/ui-val-modal.png
  book/src/ui-authentication.md
  book/src/ui-configuration.md
  book/src/ui-faqs.md
  book/src/ui-installation.md
  book/src/ui-usage.md
Labels: ready-for-review, docs

#6163 Revert --image-download always flag to avoid CI getting rate limited
  scripts/local_testnet/start_local_testnet.sh
Labels: ready-for-merge, infra-ci

#6159 Update msrv to 1.78.0
  Cargo.lock
  lighthouse/Cargo.toml
Labels: ready-for-merge, backwards-incompat, v5.3.0

#6153 Show correct total validator count during validator recovery
  account_manager/src/validator/recover.rs
Labels: bug, ready-for-merge, UX-and-logs

#6168 Remove backwards compatibility for `el_offline` and `is_optimstic`
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/status_tests.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/types.rs
  validator_client/src/check_synced.rs
Labels: ready-for-merge, HTTP-API, backwards-incompat

#6170 Use `then` instead of `then_some` when checking `upnp_enabled` to avoid useless UPnP query
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-review, Networking

#6162 Prevent continuous searches for low-peer networks
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
Labels: ready-for-review, das

#6147 Add `DataColumnSidecar` gossip topic and message handling
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/discovery/subnet_predicate.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/service/gossip_cache.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/lighthouse_network/src/types/subnet.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/manager.rs
  consensus/types/src/data_column_subnet_id.rs
  consensus/types/src/lib.rs
Labels: ready-for-review, das, das-unstable-merge

#6140 Fix unexpected `Marking peer disconnected in DHT`
  beacon_node/lighthouse_network/src/discovery/mod.rs
Labels: ready-for-review

#6183 Rust 1.80.0 lints
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/eth1/src/block_cache.rs
  beacon_node/genesis/src/eth1_genesis_service.rs
  beacon_node/lighthouse_network/gossipsub/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/src/lib.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/range.rs
  beacon_node/operation_pool/src/max_cover.rs
  common/lighthouse_metrics/src/lib.rs
  common/logging/src/async_record.rs
  common/validator_dir/src/lib.rs
  consensus/proto_array/src/proto_array.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/state_processing/src/per_block_processing/block_signature_verifier.rs
  consensus/swap_or_not_shuffle/src/lib.rs
  consensus/types/src/shuffling_id.rs
  lighthouse/tests/beacon_node.rs
  slasher/src/database.rs
  validator_client/src/http_api/api_secret.rs
  validator_client/src/validator_store.rs
  watch/src/updater/handler.rs
Labels: ready-for-review, low-hanging-fruit

#5895 Iterate expired components from the da_checker
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
Labels: ready-for-merge

#6091 Fix `lighthouse account validator` subcommands help text
  account_manager/src/validator/mod.rs
  account_manager/src/wallet/mod.rs
Labels: ready-for-merge, UX-and-logs

#6184 limit dial concurrency on Swarm
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-review, Networking

#6048 Remove timeout locks
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/attestation_verification/batch.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/state_advance_timer.rs
  beacon_node/beacon_chain/src/sync_committee_verification.rs
  beacon_node/beacon_chain/src/timeout_rw_lock.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  book/src/faq.md
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge

#5292 default vc to block v3 endpoint and deprecate block-v3 flag
  book/src/help_vc.md
  lighthouse/tests/validator_client.rs
  testing/simulator/src/cli.rs
  validator_client/src/block_service.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/http_metrics/metrics.rs
  validator_client/src/validator_store.rs
Labels: val-client, ready-for-merge, backwards-incompat, v5.3.0

#6190 Use upgradable read lock for pubkey cache
  beacon_node/beacon_chain/src/beacon_chain.rs
Labels: optimization, ready-for-merge

#6034 Visualisation logging for sync batch states
  Cargo.lock
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
Labels: ready-for-merge, UX-and-logs

#6181 Data column gossip validation and error handling
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/observed_data_sidecars.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
Labels: ready-for-merge, das, das-unstable-merge

#6195 Update database migration docs for 5.3
  book/src/database-migrations.md
Labels: docs, ready-for-merge

#6203 Swap finalized chains based on processed batches
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
Labels: ready-for-merge, v5.3.0

#6201 Use blinded blocks for light client proofs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/light_client_server_cache.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/light_client_bootstrap.rs
  consensus/types/src/light_client_finality_update.rs
  consensus/types/src/light_client_header.rs
  consensus/types/src/light_client_optimistic_update.rs
  consensus/types/src/light_client_update.rs
Labels: bug, ready-for-merge, database, light-client, v5.3.1
