Repository sigp/lighthouse, pull requests merged in 2024-09, with the labels that each got.

#6325 Fix context bytes logic for DataColumn RPC responses
  beacon_node/lighthouse_network/src/rpc/codec/ssz_snappy.rs
Labels: ready-for-merge, das

#6249 update libp2p to version 0.54
  Cargo.lock
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
  beacon_node/lighthouse_network/gossipsub/src/behaviour/tests.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-review, Networking

#6328 Fix tree states upgrade migration
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
  beacon_node/store/src/chunked_vector.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/partial_beacon_state.rs
Labels: ready-for-merge, database, tree-states

#5735 Drop block data from BlockError and BlobError
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/manager.rs
Labels: code-quality, ready-for-merge

#6338 Update manual checkpoint sync content in Lighthouse book
  book/src/checkpoint-sync.md
  book/src/faq.md
Labels: docs, ready-for-merge

#6299 Light Client Bug Fix
  consensus/types/src/light_client_header.rs
Labels: ready-for-merge, light-client

#6357 Ignore Rust 1.82 warnings about void patterns
  beacon_node/lighthouse_network/gossipsub/src/handler.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  common/warp_utils/src/reject.rs
Labels: ready-for-merge

#6343 Enable `large_stack_frames` lint
  Makefile
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/src/cli.rs
  testing/simulator/src/basic_sim.rs
  testing/state_transition_vectors/src/macros.rs
  watch/tests/tests.rs
Labels: code-quality, ready-for-merge

#6340 Add blob count label to `DATA_COLUMN_SIDECAR_COMPUTATION` metric
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/metrics.rs
  common/lighthouse_metrics/src/lib.rs
Labels: ready-for-merge, das

#6336 Metadata request ordering
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
Labels: ready-for-merge, Networking

#6342 Clarify validator monitor block log
  beacon_node/beacon_chain/src/validator_monitor.rs
Labels: low-hanging-fruit, ready-for-merge, UX-and-logs

#5893 Check known parent on rpc blob process
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/tests/events.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
Labels: ready-for-review, syncing

#6363 Fix lints for Rust 1.81
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/eth1/src/inner.rs
  beacon_node/store/src/leveldb_store.rs
  common/account_utils/src/lib.rs
  common/logging/src/lib.rs
Labels: code-quality, ready-for-merge

#6354 Use tikv-jemallocator instead of jemallocator
  .cargo/config.toml
  Cargo.lock
  common/malloc_utils/Cargo.toml
  common/malloc_utils/src/jemalloc.rs
Labels: ready-for-merge, dependencies

#6308 Improve `get_custody_columns` validation, caching and error handling
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/discovery/subnet_predicate.rs
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  consensus/types/src/data_column_subnet_id.rs
  testing/ef_tests/src/cases/get_custody_columns.rs
Labels: ready-for-merge, das

#6213 Delete legacy payload reconstruction
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/beacon_chain/src/bellatrix_readiness.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/metrics.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  testing/execution_engine_integration/src/test_rig.rs
Labels: code-quality, ready-for-merge, dependencies, v5.4.0

#6304 simplify rpc codec logic
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/codec/base.rs
  beacon_node/lighthouse_network/src/rpc/codec/mod.rs
  beacon_node/lighthouse_network/src/rpc/outbound.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
Labels: ready-for-review, Networking

#6371 Add more granularity to data column proof computation metric
  beacon_node/beacon_chain/src/metrics.rs
Labels: low-hanging-fruit, ready-for-merge, das

#6012 Register processor queue length as histogram
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/range_sync/range.rs
  common/lighthouse_metrics/src/lib.rs
Labels: ready-for-merge, backwards-incompat

#5915 Persist light client bootstrap
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/light_client_server_cache.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/light_client.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/status_tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  consensus/types/src/lib.rs
  consensus/types/src/light_client_bootstrap.rs
Labels: ready-for-merge, light-client, v6.0.0

#6385 Upgrade to discv5 0.7.0
  Cargo.lock
  Cargo.toml
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/persisted_dht.rs
  boot_node/src/server.rs
Labels: ready-for-review, v6.0.0

#6382 Set custody subnets on tests
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
Labels: ready-for-merge, das

#6272 Move sync active requests to own modules
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/network_context/requests/blobs_by_root.rs
  beacon_node/network/src/sync/network_context/requests/blocks_by_root.rs
Labels: ready-for-merge

#6386 Tree states archive - review comments and metrics
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/metadata.rs
  beacon_node/store/src/metrics.rs
  beacon_node/store/src/reconstruct.rs
Labels: ready-for-review

#6400 Improve rpc logic
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/service/mod.rs
Labels: ready-for-review, Networking

#5101 Fix phase0 block reward in rewards API
  beacon_node/beacon_chain/src/attestation_rewards.rs
  beacon_node/beacon_chain/src/beacon_block_reward.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/tests/rewards.rs
  beacon_node/http_api/src/standard_block_rewards.rs
  consensus/state_processing/src/per_epoch_processing/base/rewards_and_penalties.rs
  testing/ef_tests/src/cases/rewards.rs
Labels: ready-for-merge, HTTP-API, v6.0.0

#6407 Fix test failure on Rust v1.81
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
Labels: bug, test improvement, ready-for-merge

#6412 Fix deadlock on block cache.
  beacon_node/beacon_chain/src/eth1_chain.rs
Labels: bug, ready-for-merge, database, v6.0.0

#6397 Simplify database anchor
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/notifier.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/lighthouse_network/src/types/sync_state.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/metadata.rs
  beacon_node/store/src/reconstruct.rs
  common/eth2/src/lighthouse.rs
  database_manager/src/lib.rs
Labels: tree-states

#6402 Correct ENR decoding on extension trait
  Cargo.lock
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  boot_node/Cargo.toml
  boot_node/src/config.rs
Labels: ready-for-merge, Networking

#6414 Update blog reference to new combined blog
  README.md
Labels: docs, ready-for-merge

#6267 Make `BeaconChain::kzg` field mandatory
  Cargo.lock
  beacon_node/beacon_chain/benches/benches.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/events.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/client/src/config.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
  beacon_node/src/config.rs
  common/eth2_network_config/Cargo.toml
  common/eth2_network_config/src/lib.rs
  crypto/kzg/Cargo.toml
  crypto/kzg/benches/benchmark.rs
  crypto/kzg/src/lib.rs
  crypto/kzg/src/trusted_setup.rs
  crypto/kzg/trusted_setup.json
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof.rs
  testing/simulator/Cargo.toml
  testing/simulator/src/local_network.rs
Labels: code-quality, ready-for-merge, v6.0.0

#6417 Allow custody by root requests to have no peers
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
Labels: ready-for-review, syncing, das

#6377 Attribute invalid column proof error to correct peer
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/network_context.rs
Labels: ready-for-review, das

#5574 Lenient duplicate checks on HTTP API for block publication
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/events.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/http_api/tests/fork_tests.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/tests.rs
  beacon_node/network/src/sync/network_context.rs
  common/eth2/src/types.rs
  consensus/types/src/data_column_sidecar.rs
  testing/ef_tests/src/cases/fork_choice.rs
Labels: ready-for-merge, HTTP-API, v6.0.0

#6420 Remove Score Ord, PartialOrd, Eq and PartialEq impls
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/score.rs
  book/src/developers.md
Labels: waiting-on-author, code-quality, Networking
