Repository sigp/lighthouse, pull requests merged in 2025-01, with the labels that each got.

#6762 add joao CODEOWNERS
  .github/CODEOWNERS
Labels: ready-for-merge

#6537 Add 'beacon_' prefix to PeerDAS metrics names
  beacon_node/beacon_chain/src/metrics.rs
Labels: ready-for-merge, das

#6755 Implement `getBlobSidecars` support for PeerDAS
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/http_api/src/block_id.rs
  consensus/types/src/blob_sidecar.rs
Labels: ready-for-merge, HTTP-API, das

#6761 Fix incorrect data column metric name
  beacon_node/beacon_chain/src/metrics.rs
Labels: low-hanging-fruit, ready-for-merge, das

#6748 Fix incorrect VC default HTTP token path when the `--datadir` flag is present
  lighthouse/tests/validator_client.rs
  validator_client/http_api/src/lib.rs
  validator_client/src/config.rs
Labels: bug, val-client, ready-for-merge, v6.1.0

#6770 Anchor pre-PR: Decouple eth2
  Cargo.lock
  beacon_node/execution_layer/Cargo.toml
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/database.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/types/mod.rs
  common/eth2/Cargo.toml
  common/eth2/src/lib.rs
  common/eth2/src/lighthouse.rs
  common/eth2/src/lighthouse/sync_state.rs
  common/eth2/src/types.rs
Labels: anchor

#6769 Anchor pre-PR: Dependency cleanup
  Cargo.lock
  Cargo.toml
  account_manager/src/validator/create.rs
  account_manager/src/validator/recover.rs
  account_manager/src/wallet/mod.rs
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/attestation_performance.rs
  beacon_node/http_api/src/attester_duties.rs
  beacon_node/http_api/src/block_id.rs
  beacon_node/http_api/src/block_packing_efficiency.rs
  beacon_node/http_api/src/block_rewards.rs
  beacon_node/http_api/src/build_block_contents.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/produce_block.rs
  beacon_node/http_api/src/proposer_duties.rs
  beacon_node/http_api/src/standard_block_rewards.rs
  beacon_node/http_api/src/state_id.rs
  beacon_node/http_api/src/sync_committee_rewards.rs
  beacon_node/http_api/src/sync_committees.rs
  beacon_node/http_api/src/ui.rs
  beacon_node/http_metrics/Cargo.toml
  beacon_node/http_metrics/src/metrics.rs
  common/account_utils/Cargo.toml
  common/account_utils/src/validator_definitions.rs
  common/directory/src/lib.rs
  common/eth2/Cargo.toml
  common/eth2/src/lighthouse.rs
  common/health_metrics/Cargo.toml
  common/health_metrics/src/lib.rs
  common/health_metrics/src/metrics.rs
  common/health_metrics/src/observe.rs
  common/monitoring_api/Cargo.toml
  common/monitoring_api/src/gather.rs
  common/monitoring_api/src/lib.rs
  common/validator_dir/Cargo.toml
  common/validator_dir/src/builder.rs
  common/warp_utils/Cargo.toml
  common/warp_utils/src/lib.rs
  common/warp_utils/src/reject.rs
  validator_client/http_api/Cargo.toml
  validator_client/http_api/src/lib.rs
  validator_client/http_metrics/Cargo.toml
  validator_client/http_metrics/src/lib.rs
Labels: anchor

#6777 Add libssl install to udeps task
  .github/workflows/test-suite.yml
Labels: ready-for-merge, infra-ci

#6745 Use oldest_block_slot to break off pruning payloads
  beacon_node/store/src/hot_cold_store.rs
Labels: ready-for-merge, tree-states

#6774 Add missing crates to cargo workspace
  Cargo.toml
  beacon_node/genesis/Cargo.toml
  beacon_node/operation_pool/Cargo.toml
  common/filesystem/Cargo.toml
  consensus/merkle_proof/Cargo.toml
  consensus/types/Cargo.toml
Labels: ready-for-merge

#6737 Refactor feature testing for spec tests
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/get_custody_columns.rs
  testing/ef_tests/src/cases/kzg_blob_to_kzg_commitment.rs
  testing/ef_tests/src/cases/kzg_compute_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_compute_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_compute_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_recover_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof.rs
  testing/ef_tests/src/cases/kzg_verify_blob_kzg_proof_batch.rs
  testing/ef_tests/src/cases/kzg_verify_cell_kzg_proof_batch.rs
  testing/ef_tests/src/cases/kzg_verify_kzg_proof.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: test improvement, ready-for-merge

#6731 Electra spec changes for `v1.5.0-beta.0`
  beacon_node/beacon_chain/tests/validator_monitor.rs
  beacon_node/execution_layer/src/engine_api/new_payload_request.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/network/src/sync/tests/range.rs
  consensus/fork_choice/tests/tests.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_block_processing/process_operations.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/state_processing/src/upgrade/electra.rs
  consensus/types/presets/gnosis/electra.yaml
  consensus/types/presets/mainnet/altair.yaml
  consensus/types/presets/mainnet/electra.yaml
  consensus/types/presets/mainnet/phase0.yaml
  consensus/types/presets/minimal/altair.yaml
  consensus/types/presets/minimal/deneb.yaml
  consensus/types/presets/minimal/electra.yaml
  consensus/types/presets/minimal/phase0.yaml
  consensus/types/src/beacon_state.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/pending_partial_withdrawal.rs
  consensus/types/src/preset.rs
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/genesis_initialization.rs
  testing/ef_tests/src/cases/genesis_validity.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-review, consensus, electra, electra-alpha10

#6801 Execution requests with prefix
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  consensus/types/src/execution_requests.rs
  consensus/types/src/lib.rs
Labels: ready-for-merge, electra-alpha10

#6803 Implement changes for EIP 7691
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/src/types/mod.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge, electra-alpha10

#6756 Fix data columns not persisting for PeerDAS due to a `getBlobs` race condition
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/fetch_blobs.rs
  beacon_node/beacon_chain/tests/block_verification.rs
Labels: ready-for-merge, das

#6736 Implement PeerDAS subnet decoupling (aka custody groups)
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/observed_data_sidecars.rs
  beacon_node/http_api/src/block_id.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/discovery/subnet_predicate.rs
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/tests/lookups.rs
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_custody_group.rs
  consensus/types/src/data_column_subnet_id.rs
  consensus/types/src/lib.rs
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/compute_columns_for_custody_groups.rs
  testing/ef_tests/src/cases/get_custody_groups.rs
  testing/ef_tests/src/cases/kzg_compute_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_recover_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_verify_cell_kzg_proof_batch.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-merge, das

#6798 Remove ineffectual block RPC limits post merge
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/execution_payload.rs
Labels: ready-for-merge

#6814 Do not send column requests if there is no blob for the block.
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
Labels: bug, low-hanging-fruit, ready-for-merge, das

#6815 Fix custodial peer assumption on lookup custody requests
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
Labels: ready-for-merge, Networking, das

#6793 Add EIP-7636 support
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/discovery/enr.rs
  common/lighthouse_version/src/lib.rs
Labels: enhancement, ready-for-merge, Networking

#6827 Add MetaData V3 support to `node/identity` API
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/types.rs
Labels: ready-for-merge, HTTP-API, das

#6816 Avoid computing columns from EL blobs if block has already been imported
  beacon_node/beacon_chain/src/fetch_blobs.rs
Labels: bug, low-hanging-fruit, ready-for-merge, das

#6836 Update discv5
  Cargo.lock
Labels: ready-for-merge, v6.1.0

#6597 add new features to mergify config
  .github/mergify.yml
Labels: ready-for-review, infra-ci

#6839 Electra minor refactorings
  beacon_node/operation_pool/src/attestation_storage.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/state_processing/src/upgrade/electra.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/validator.rs
Labels: ready-for-merge, electra

#4718 Modularize beacon node backend
  Cargo.lock
  Makefile
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v21.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/op_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/src/lib.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/chunked_vector.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/database.rs
  beacon_node/store/src/database/interface.rs
  beacon_node/store/src/database/leveldb_impl.rs
  beacon_node/store/src/database/redb_impl.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/garbage_collection.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/impls/beacon_state.rs
  beacon_node/store/src/leveldb_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  beacon_node/store/src/metrics.rs
  beacon_node/store/src/partial_beacon_state.rs
  book/src/help_bn.md
  book/src/installation-source.md
  database_manager/src/cli.rs
  database_manager/src/lib.rs
  lighthouse/Cargo.toml
  lighthouse/tests/beacon_node.rs
  wordlist.txt
Labels: ready-for-merge, database, v6.1.0

#6871 Update to EF tests v1.5.0-beta.1
  testing/ef_tests/Makefile
Labels: low-hanging-fruit, ready-for-merge, electra

#6832 Add tests for ExecutionRequests decoding errors
  beacon_node/execution_layer/src/engine_api/json_structures.rs
Labels: ready-for-merge, electra

#6519 Detect invalid proposer signature on RPC block processing
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/sync/tests/lookups.rs
Labels: ready-for-merge

#6856 Fix Redb implementation and add CI checks
  Makefile
  beacon_node/store/src/database/redb_impl.rs
  beacon_node/store/src/forwards_iter.rs
  beacon_node/store/src/hot_cold_store.rs
Labels: bug, ready-for-merge, database, v6.1.0

#6873 More gossipsub metrics
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
  beacon_node/lighthouse_network/gossipsub/src/gossip_promises.rs
  beacon_node/lighthouse_network/gossipsub/src/metrics.rs
Labels: ready-for-merge, Networking

#6847 Fork aware max values in rpc
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/service/utils.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests/blobs_by_root.rs
  beacon_node/network/src/sync/network_context/requests/blocks_by_root.rs
  beacon_node/network/src/sync/tests/lookups.rs
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge, Networking, electra

#6861 Some sync/backfill format nits
  beacon_node/network/src/sync/backfill_sync/mod.rs
Labels: ready-for-merge

#6831 Increase jemalloc aarch64 page size limit (#5244)
  .cargo/config.toml
  Cross.toml
  Makefile
  common/malloc_utils/src/jemalloc.rs
  common/malloc_utils/src/lib.rs
  lighthouse/src/main.rs
Labels: ready-for-merge, backwards-incompat

#6885 Underflow and Typo
  beacon_node/network/src/sync/peer_sync_info.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
Labels: ready-for-merge

#6868 Make range sync chain Id sequential
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
Labels: syncing, ready-for-merge

#6795 Implement PeerDAS Fulu fork activation
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/fulu_readiness.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/test_utils/fixtures/test_data_column_sidecars.ssz
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/tests/lookups.rs
  beacon_node/network/src/sync/tests/range.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/metadata.rs
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  consensus/fork_choice/tests/tests.rs
  consensus/types/presets/gnosis/deneb.yaml
  consensus/types/presets/gnosis/eip7594.yaml
  consensus/types/presets/gnosis/fulu.yaml
  consensus/types/presets/mainnet/eip7594.yaml
  consensus/types/presets/mainnet/fulu.yaml
  consensus/types/presets/minimal/eip7594.yaml
  consensus/types/presets/minimal/fulu.yaml
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/fork_name.rs
  consensus/types/src/preset.rs
  crypto/kzg/src/lib.rs
  scripts/local_testnet/network_params_das.yaml
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/compute_columns_for_custody_groups.rs
  testing/ef_tests/src/cases/get_custody_groups.rs
  testing/ef_tests/src/cases/kzg_compute_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_recover_cells_and_kzg_proofs.rs
  testing/ef_tests/src/cases/kzg_verify_cell_kzg_proof_batch.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-merge, das

#6848 Cargo update without `rust_eth_kzg`
  Cargo.lock
  Dockerfile
  crypto/kzg/Cargo.toml
  lcli/Dockerfile
  lighthouse/Cargo.toml
Labels: ready-for-merge, backwards-incompat, dependencies, v6.1.0

#6867 `POST /eth/v2/beacon/pool/attestations` bugfixes
  Cargo.lock
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_attestations.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  common/eth2/Cargo.toml
  common/eth2/src/lib.rs
  consensus/types/src/attestation.rs
  consensus/types/src/subnet_id.rs
  validator_client/validator_services/Cargo.toml
  validator_client/validator_services/src/attestation_service.rs
Labels: bug, ready-for-merge, HTTP-API, electra, v6.1.0

#6891 Fix mdbook build.
  .github/workflows/book.yml
Labels: ready-for-merge, infra-ci

#6760 Compute columns in post-PeerDAS checkpoint sync
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/store/src/hot_cold_store.rs
Labels: ready-for-merge, das, peerdas-devnet-4

#6896 update MSRV
  lighthouse/Cargo.toml
Labels: ready-for-merge, backwards-incompat, trivial

#6889 update libp2p to 0.55
  Cargo.lock
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/src/handler.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/Cargo.toml
Labels: ready-for-merge, backwards-incompat, v6.1.0, trivial
