Repository sigp/lighthouse, pull requests merged in 2025-03, with the labels that each got.

#7059 Manual finalization endpoint
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  common/eth2/src/types.rs
  consensus/fork_choice/src/fork_choice.rs
Labels: v7.0.0-beta.2

#7062 Reuse milhouse subtrees to shrink inactivity_scores in memory
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/rewards.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  common/malloc_utils/src/jemalloc.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_epoch_processing/errors.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/types/src/attestation.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/sync_aggregate.rs
  consensus/types/src/sync_committee_contribution.rs
Labels: optimization, v7.0.0-beta.2

#7066 Split block root lookups between fork choice and store on BBR response
  beacon_node/http_api/Cargo.toml
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: ready-for-review

#7071 Add CI fixes to `holesky-rescue`
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/lib.rs
  beacon_node/store/src/hot_cold_store.rs
  book/src/help_bn.md
  book/src/help_vc.md
  consensus/proto_array/src/proto_array.rs
Labels: v7.0.0-beta.2

#7072 Manual compaction endpoint
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/http_api/src/lib.rs
Labels: ready-for-review, v7.0.0-beta.2

#7073 Bump version to v7.0.0-beta.2
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: v7.0.0-beta.2

#7047 Add `--long-timeouts-multiplier` CLI flag
  book/src/help_vc.md
  lighthouse/tests/validator_client.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/lib.rs
Labels: ready-for-merge, v7.0.0-beta.clean

#7050 Make ExecutionBlock::total_difficulty Optional
  beacon_node/beacon_chain/src/bellatrix_readiness.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
Labels: bug, ready-for-merge, v7.0.0-beta.clean

#7074 Schedule Chiado testnet Electra hard fork
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
Labels: ready-for-merge

#7081 Validator Registration ssz support
  consensus/types/src/validator_registration_data.rs
Labels: ready-for-merge

#7044 Use `sync_tolerance_epochs` flag to control the proposer prep routines
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/src/config.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, v7.0.0-beta.clean

#7092 Temporarily ignore cargo audit failures
  Makefile
Labels: ready-for-merge

#7082 Optimise status processing
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: ready-for-merge, v7.0.0, v7.0.0-beta.clean

#7094 Back merge v7 to unstable
  Makefile
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/bellatrix_readiness.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/src/config.rs
  book/src/help_vc.md
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  lighthouse/tests/beacon_node.rs
  lighthouse/tests/validator_client.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/lib.rs
  validator_client/validator_services/src/attestation_service.rs
  validator_client/validator_services/src/duties_service.rs
  validator_client/validator_services/src/sync_committee_service.rs
Labels: ready-for-review, do-not-merge

#6915 Bump SSZ version for larger bitfield `SmallVec`
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/rewards.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  common/malloc_utils/src/jemalloc.rs
  consensus/state_processing/src/per_block_processing/errors.rs
  consensus/state_processing/src/per_epoch_processing/errors.rs
  consensus/types/src/attestation.rs
  consensus/types/src/sync_aggregate.rs
  consensus/types/src/sync_committee_contribution.rs
Labels: optimization, ready-for-merge

#7086 Address cargo audit failure `RUSTSEC-2025-0009`
  Cargo.lock
  Cargo.toml
  Makefile
Labels: ready-for-merge

#7020 chore: update to rust-eth-kzg to 0.5.4
  Cargo.lock
  Cargo.toml
Labels: ready-for-merge, das

#7101 Change state cache size default to 32
  beacon_node/src/cli.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, v7.0.0, v7.0.0-beta.clean

#7105 Fix descent from split check
  beacon_node/beacon_chain/src/block_verification.rs
Labels: bug, ready-for-review

#7109 Remove duplicate sync_tolerance_epochs config
  beacon_node/http_api/src/lib.rs
  beacon_node/src/config.rs
Labels: code-quality, ready-for-merge

#7057 switch to upstream gossipsub
  Cargo.lock
  Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/CHANGELOG.md
  beacon_node/lighthouse_network/gossipsub/Cargo.toml
  beacon_node/lighthouse_network/gossipsub/src/backoff.rs
  beacon_node/lighthouse_network/gossipsub/src/behaviour.rs
  beacon_node/lighthouse_network/gossipsub/src/behaviour/tests.rs
  beacon_node/lighthouse_network/gossipsub/src/config.rs
  beacon_node/lighthouse_network/gossipsub/src/error.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/compat.proto
  beacon_node/lighthouse_network/gossipsub/src/generated/compat/mod.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/compat/pb.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/gossipsub/mod.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/gossipsub/pb.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/mod.rs
  beacon_node/lighthouse_network/gossipsub/src/generated/rpc.proto
  beacon_node/lighthouse_network/gossipsub/src/gossip_promises.rs
  beacon_node/lighthouse_network/gossipsub/src/handler.rs
  beacon_node/lighthouse_network/gossipsub/src/lib.rs
  beacon_node/lighthouse_network/gossipsub/src/mcache.rs
  beacon_node/lighthouse_network/gossipsub/src/metrics.rs
  beacon_node/lighthouse_network/gossipsub/src/mod.rs
  beacon_node/lighthouse_network/gossipsub/src/peer_score.rs
  beacon_node/lighthouse_network/gossipsub/src/peer_score/params.rs
  beacon_node/lighthouse_network/gossipsub/src/peer_score/tests.rs
  beacon_node/lighthouse_network/gossipsub/src/protocol.rs
  beacon_node/lighthouse_network/gossipsub/src/rpc_proto.rs
  beacon_node/lighthouse_network/gossipsub/src/subscription_filter.rs
  beacon_node/lighthouse_network/gossipsub/src/time_cache.rs
  beacon_node/lighthouse_network/gossipsub/src/topic.rs
  beacon_node/lighthouse_network/gossipsub/src/transform.rs
  beacon_node/lighthouse_network/gossipsub/src/types.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/Cargo.toml
Labels: ready-for-merge, Networking

#7113 Set `epochs-per-blob-prune` default to 256
  beacon_node/src/cli.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, v7.0.0, v7.0.0-beta.clean

#7114 Address cargo audit failure `RUSTSEC-2024-0437`
  Cargo.lock
  Cargo.toml
  Makefile
Labels: ready-for-merge

#6991 Log range sync download errors
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: ready-for-merge, das

#6680 decouple `eth2` from `store` and `lighthouse_network`
  Cargo.lock
  beacon_node/beacon_chain/src/attestation_rewards.rs
  beacon_node/beacon_chain/src/beacon_block_reward.rs
  beacon_node/beacon_chain/src/sync_committee_rewards.rs
  beacon_node/beacon_chain/tests/rewards.rs
  beacon_node/execution_layer/Cargo.toml
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/database.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/peer.rs
  beacon_node/http_api/src/standard_block_rewards.rs
  beacon_node/http_api/src/sync_committee_rewards.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/types/mod.rs
  common/eth2/Cargo.toml
  common/eth2/src/lib.rs
  common/eth2/src/lighthouse.rs
  common/eth2/src/lighthouse/attestation_rewards.rs
  common/eth2/src/lighthouse/standard_block_rewards.rs
  common/eth2/src/lighthouse/sync_committee_rewards.rs
  common/eth2/src/lighthouse/sync_state.rs
  common/eth2/src/types.rs
  common/warp_utils/Cargo.toml
  testing/validator_test_rig/Cargo.toml
Labels: ready-for-review, code-quality, ready-for-merge, v7.1.0

#7130 update gossipsub to the latest upstream revision
  Cargo.lock
  Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/Cargo.toml
Labels: ready-for-merge, Networking

#7137 Log `file appender` initialization errors properly
  common/logging/src/lib.rs
Labels: ready-for-merge

#7006 feat: implement new beacon APIs(accessors for pending_deposits/pending_partial_withdrawals)
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
Labels: ready-for-merge, v7.0.0, v7.0.0-beta.clean

#7149 Remove unnecessary `filter_layer` in logger builder
  lighthouse/environment/src/tracing_common.rs
  lighthouse/src/main.rs
  testing/simulator/src/basic_sim.rs
  testing/simulator/src/fallback_sim.rs
Labels: ready-for-merge, UX-and-logs

#7150 Remove `discv5` logs from logfile output
  lighthouse/environment/src/lib.rs
Labels: ready-for-merge, UX-and-logs

#7042 Add block ban flag `--invalid-block-roots`
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, v7.0.0, v7.0.0-beta.clean

#7095 State cache tweaks
  beacon_node/beacon_chain/src/attestation_rewards.rs
  beacon_node/beacon_chain/src/attester_cache.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/fork_revert.rs
  beacon_node/beacon_chain/src/light_client_server_cache.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/beacon_chain/tests/rewards.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/sync_committee_verification.rs
  beacon_node/http_api/src/attestation_performance.rs
  beacon_node/http_api/src/block_packing_efficiency.rs
  beacon_node/http_api/src/block_rewards.rs
  beacon_node/http_api/src/state_id.rs
  beacon_node/http_api/src/sync_committee_rewards.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/state_cache.rs
  book/src/help_bn.md
  consensus/fork_choice/tests/tests.rs
  consensus/state_processing/src/per_block_processing/tests.rs
  lighthouse/tests/beacon_node.rs
  testing/ef_tests/src/cases/fork_choice.rs
Labels: ready-for-merge, v7.0.0, v7.0.0-beta.clean

#7145 Support Hoodi testnet
  book/src/help_bn.md
  book/src/help_general.md
  book/src/help_vc.md
  book/src/help_vm.md
  book/src/help_vm_create.md
  book/src/help_vm_import.md
  book/src/help_vm_move.md
  common/eth2_config/src/lib.rs
  common/eth2_network_config/built_in_network_configs/hoodi/boot_enr.yaml
  common/eth2_network_config/built_in_network_configs/hoodi/config.yaml
  common/eth2_network_config/built_in_network_configs/hoodi/deposit_contract_block.txt
Labels: ready-for-merge, v7.0.0, v7.0.0-beta.clean

#7103 Pseudo finalization endpoint
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  common/eth2/src/types.rs
  consensus/fork_choice/src/fork_choice.rs
Labels: ready-for-merge, HTTP-API, v7.0.0, v7.0.0-beta.clean

#7104 Manual compaction endpoint backport
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/http_api/src/lib.rs
Labels: ready-for-merge, HTTP-API, v7.0.0, v7.0.0-beta.clean

#7084 Reject attestations to blocks prior to the split
  beacon_node/beacon_chain/src/attestation_verification.rs
Labels: ready-for-merge, UX-and-logs, v7.0.0, v7.0.0-beta.clean

#7164 Update ring to 0.17.14 to fix build compat
  Cargo.lock
Labels: crypto, ready-for-merge, dependencies, v7.0.0-beta.clean

#7162 Release v7.0.0-beta.4
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, v7.0.0-beta.clean

#6998 Track request IDs in RangeBlockComponentsRequest
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
Labels: syncing, ready-for-merge, das

#7183 Add missing `osaka-time` lcli param
  lcli/src/main.rs
Labels: low-hanging-fruit, ready-for-merge, fulu

#7182 Ensure sqlite and rusqlite are optional in `consensus/types`
  consensus/types/Cargo.toml
Labels: ready-for-merge

#7033 Remove CGC from data_availability checker
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/fetch_blobs.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/tests/lookups.rs
  beacon_node/network/src/sync/tests/range.rs
Labels: ready-for-merge, das

#7169 Remove `crit` as an option from the CLI entirely
  book/src/help_bn.md
  book/src/help_general.md
  book/src/help_vc.md
  book/src/help_vm.md
  book/src/help_vm_create.md
  book/src/help_vm_import.md
  book/src/help_vm_move.md
  lighthouse/src/main.rs
Labels: ready-for-merge, UX-and-logs, backwards-incompat

#7209 Prevent duplicate effective balance processing
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
Labels: bug, consensus, ready-for-merge, electra

#7174 Fix xdelta3 output buffer issue
  Cargo.lock
  Cargo.toml
  beacon_node/store/src/hdiff.rs
  beacon_node/store/src/metrics.rs
Labels: bug, database, tree-states, v7.0.0

#7210 Release v7.0.0-beta.5
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, v7.0.0-beta.clean

#7217 Top-up pubkey cache on startup
  beacon_node/beacon_chain/src/builder.rs
Labels: ready-for-merge, database, v7.0.0

#7198 Admin add/remove peer
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/service.rs
  common/eth2/src/lighthouse.rs
  common/eth2/src/types.rs
Labels: ready-for-merge, v7.0.0, v7.0.0-beta.clean

#7224 Backmerge mar 29
  Cargo.lock
  Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/service.rs
  beacon_node/store/src/hdiff.rs
  beacon_node/store/src/metrics.rs
  boot_node/Cargo.toml
  common/eth2/src/lighthouse.rs
  common/eth2/src/types.rs
  common/lighthouse_version/src/lib.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-review, do-not-merge
