Repository sigp/lighthouse, pull requests merged in 2025-02, with the labels that each got.

#6901 Cargo update for openssl vuln
  Cargo.lock
  Makefile
Labels: low-hanging-fruit, ready-for-merge, infra-ci

#6890 Fix subnet unsubscription time
  beacon_node/network/src/subnet_service/mod.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
Labels: ready-for-merge, v6.1.0

#6849 Subscribe to PeerDAS topics on Fulu fork
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/lighthouse_network/src/types/mod.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/network/src/service.rs
Labels: ready-for-merge, das

#6859 Add builder SSZ flow
  Cargo.lock
  beacon_node/builder_client/Cargo.toml
  beacon_node/builder_client/src/lib.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/store/src/hot_cold_store.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/types/src/builder_bid.rs
  consensus/types/src/execution_payload.rs
  consensus/types/src/fork_versioned_response.rs
  consensus/types/src/lib.rs
  consensus/types/src/signed_beacon_block.rs
  testing/ef_tests/src/cases/operations.rs
Labels: ready-for-merge, builder API, electra

#6851 Use data column batch verification consistently
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
Labels: ready-for-merge, das

#6300 Migrate validator client to clap derive
  Cargo.lock
  account_manager/src/lib.rs
  account_manager/src/validator/mod.rs
  account_manager/src/wallet/mod.rs
  beacon_node/src/cli.rs
  book/src/help_vc.md
  boot_node/src/cli.rs
  database_manager/src/cli.rs
  lighthouse/src/cli.rs
  lighthouse/src/main.rs
  lighthouse/tests/validator_client.rs
  validator_client/beacon_node_fallback/Cargo.toml
  validator_client/beacon_node_fallback/src/beacon_node_health.rs
  validator_client/beacon_node_fallback/src/lib.rs
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/lib.rs
  validator_manager/src/lib.rs
Labels: code-quality, ready-for-merge, backwards-incompat, v6.1.0

#6906 chore: update peerDAS KZG library to 0.5.3
  Cargo.lock
  Cargo.toml
  crypto/kzg/Cargo.toml
Labels: crypto, ready-for-merge

#6796 UX Network Fixes
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/advanced_networking.md
  book/src/help_bn.md
Labels: ready-for-review, Networking, v6.1.0

#6898 Add check to Lockbud CI job
  .github/workflows/test-suite.yml
  scripts/ci/check-lockbud.sh
Labels: bug, ready-for-merge, infra-ci

#6568 Add test to beacon node fallback feature
  Cargo.lock
  Cargo.toml
  testing/validator_test_rig/Cargo.toml
  testing/validator_test_rig/src/lib.rs
  testing/validator_test_rig/src/mock_beacon_node.rs
  validator_client/Cargo.toml
  validator_client/beacon_node_fallback/Cargo.toml
  validator_client/beacon_node_fallback/src/lib.rs
  validator_client/src/lib.rs
Labels: test improvement, ready-for-merge

#6911 Return error if getBlobs not supported
  beacon_node/execution_layer/src/lib.rs
Labels: ready-for-review, ready-for-merge, das

#6497 Add individual by_range sync requests
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/self_limiter.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/network_context/requests/blobs_by_range.rs
  beacon_node/network/src/sync/network_context/requests/blobs_by_root.rs
  beacon_node/network/src/sync/network_context/requests/blocks_by_range.rs
  beacon_node/network/src/sync/network_context/requests/data_columns_by_range.rs
  beacon_node/network/src/sync/network_context/requests/data_columns_by_root.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/tests/range.rs
Labels: syncing, ready-for-merge

#6863 Update metrics.rs
  beacon_node/beacon_chain/src/metrics.rs
Labels: ready-for-merge

#6924 Fix attestation queue length metric
  beacon_node/beacon_processor/src/lib.rs
Labels: low-hanging-fruit, ready-for-merge, v7.0.0-beta.0

#6936 Use old geth version due to breaking changes.
  testing/execution_engine_integration/src/geth.rs
Labels: ready-for-merge, v7.0.0-beta.0

#6933 Reduce ForkName boilerplate in fork-context
  consensus/types/src/fork_context.rs
  consensus/types/src/fork_name.rs
Labels: ready-for-merge

#6817 Remove unused metrics
  beacon_node/beacon_chain/src/metrics.rs
Labels: ready-for-merge

#6940 Fix fetch blobs in all-null case
  beacon_node/beacon_chain/src/fetch_blobs.rs
Labels: ready-for-merge, UX-and-logs, v7.0.0-beta.0

#6934 Optimise and refine `SingleAttestation` conversion
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/single_attestation.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/http_api/src/publish_attestations.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  consensus/types/src/attestation.rs
  consensus/types/src/sync_committee_contribution.rs
Labels: optimization, ready-for-merge, electra, v7.0.0-beta.0

#6953 Remove duplicated fork_epoch and fork_version implementation
  consensus/types/src/fork_context.rs
  consensus/types/src/fork_name.rs
Labels: ready-for-merge

#6926 Fix aggregate attestation v2 response
  beacon_node/http_api/src/aggregate_attestation.rs
  beacon_node/http_api/src/lib.rs
Labels: ready-for-merge, HTTP-API, electra, v7.0.0-beta.0

#6819 Update attestation rewards API for Electra
  beacon_node/beacon_chain/src/attestation_rewards.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/rewards.rs
  beacon_node/genesis/src/interop.rs
  beacon_node/genesis/src/lib.rs
  beacon_node/http_api/tests/fork_tests.rs
Labels: ready-for-merge, HTTP-API, electra, v7.0.0-beta.0

#6949 Schedule Sepolia and Holesky Electra forks
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
Labels: ready-for-merge, electra, v7.0.0-beta.0

#6950 Enable Light Client server by default
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, light-client, v7.0.0-beta.0

#6914 Sync active request byrange ids logs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/network/src/sync/network_context.rs
Labels: syncing, ready-for-merge, UX-and-logs, v7.0.0-beta.0

#6958 Update EF tests to spec v1.5.0-beta.2
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/handler.rs
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-merge, v7.0.0-beta.0

#6808 IPv6 By Default
  Cargo.lock
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
Labels: ready-for-merge, v7.0.0-beta.0

#6972 Address cargo audit failure `RUSTSEC-2025-0006`
  Cargo.lock
Labels: ready-for-merge

#6977 Merge v7 to unstable
  Cargo.lock
Labels: do-not-merge

#6862 Fix misc PeerDAS todos
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
  beacon_node/network/src/sync/tests/lookups.rs
  consensus/types/src/data_column_custody_group.rs
Labels: ready-for-merge, das

#6928 Add PeerDAS metrics to track subnets without peers
  beacon_node/lighthouse_network/src/peer_manager/peerdb/peer_info.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/sync/range_sync/chain.rs
Labels: ready-for-merge, das

#6932 Unsubscribe blob topics at Fulu fork
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/lighthouse_network/src/types/mod.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/network/src/service.rs
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge, das

#6984 Ensure `GET v2/validator/aggregate_attestation` is backwards compatible
  beacon_node/http_api/src/aggregate_attestation.rs
  beacon_node/http_api/tests/tests.rs
Labels: bug, ready-for-merge, HTTP-API, electra, v7.0.0-beta.0

#6993 Fix light client plumbing in beacon processor
  beacon_node/beacon_processor/src/lib.rs
Labels: bug, ready-for-merge, light-client, v7.0.0-beta.0

#6962 Release v7.0.0-beta.0
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, v7.0.0-beta.0

#6997 Update mergify conditions for `trivial` and `ready-for-merge` labels to satisfy if base is not `stable`
  .github/mergify.yml
Labels: ready-for-merge, infra-ci

#6999 Merge v7.0.0-beta.0 to unstable
  Cargo.lock
  beacon_node/Cargo.toml
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/http_api/src/aggregate_attestation.rs
  beacon_node/http_api/tests/tests.rs
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-review, do-not-merge

#7007 Fix light client merkle proofs
  consensus/merkle_proof/src/lib.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/beacon_state.rs
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases/merkle_proof_validity.rs
  testing/ef_tests/src/handler.rs
  testing/ef_tests/tests/tests.rs
Labels: bug, ready-for-review, ready-for-merge, light-client, electra, v7.0.0

#6634 Use RpcSend on RPC::self_limiter::ready_requests
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/self_limiter.rs
Labels: ready-for-merge, Networking, trivial

#7019 Rust 1.85 lints
  .github/workflows/test-suite.yml
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_times_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/shuffling_cache.rs
  beacon_node/beacon_chain/src/validator_monitor.rs
  beacon_node/client/src/notifier.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/genesis/src/eth1_genesis_service.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/produce_block.rs
  beacon_node/http_api/src/validators.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/peer_manager/network_behaviour.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/operation_pool/src/bls_to_execution_changes.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/operation_pool/src/reward_cache.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  common/account_utils/src/validator_definitions.rs
  consensus/state_processing/src/per_block_processing/block_signature_verifier.rs
  consensus/types/src/beacon_block_body.rs
  consensus/types/src/runtime_var_list.rs
  slasher/src/database.rs
  testing/web3signer_tests/src/get_web3signer.rs
  testing/web3signer_tests/src/lib.rs
  validator_client/http_api/src/lib.rs
  validator_client/slashing_protection/src/slashing_database.rs
  validator_client/validator_services/src/duties_service.rs
  validator_client/validator_services/src/sync.rs
  validator_client/validator_store/src/lib.rs
Labels: ready-for-merge, v7.0.0

#7012 Add spamoor_blob in network_params.yaml
  scripts/local_testnet/network_params.yaml
Labels: test improvement, ready-for-merge

#6829 Expose blst internals
  crypto/bls/src/generic_secret_key.rs
  crypto/bls/src/generic_signature.rs
  crypto/bls/src/impls/blst.rs
  crypto/bls/src/impls/fake_crypto.rs
  crypto/bls/src/lib.rs
  crypto/bls/tests/tests.rs
Labels: crypto, ready-for-merge

#6866 Block availability data enum
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/tests/attestation_production.rs
  beacon_node/beacon_chain/tests/store_tests.rs
Labels: ready-for-merge, das

#6947 feat: adds CLI flags to delay publishing for edge case testing on PeerDAS devnets
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, das

#7017 Remove LC server config from HTTP API
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/src/config.rs
  lighthouse/tests/beacon_node.rs
  testing/simulator/src/local_network.rs
Labels: code-quality, ready-for-merge, light-client

#7034 Cache validator registration only after successful publish
  validator_client/validator_services/src/preparation_service.rs
Labels: low-hanging-fruit, ready-for-merge

#7045 Add test flag to override `SYNC_TOLERANCE_EPOCHS` for range sync testing (#7030)
  beacon_node/http_api/src/lib.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  lighthouse/tests/beacon_node.rs
  scripts/local_testnet/network_params_das.yaml
Labels: do-not-merge, v7.0.0-beta.2

#7046 Add `--disable-attesting` flag to validator client
  book/src/help_vc.md
  validator_client/src/cli.rs
  validator_client/src/config.rs
  validator_client/src/lib.rs
  validator_client/validator_services/src/attestation_service.rs
  validator_client/validator_services/src/duties_service.rs
  validator_client/validator_services/src/sync_committee_service.rs
Labels: val-client, ready-for-merge, v7.0.0-beta.2

#7054 Optimise status processing on release-v.7.0.0-beta.2 (TESTING branch)
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: do-not-merge, v7.0.0-beta.2

#7058 Load block roots from fork choice where possible when serving `BlocksByRange` requests
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
Labels: ready-for-review, v7.0.0-beta.2

#7055 Change state cache size default to 32
  beacon_node/src/cli.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-review
