Repository sigp/lighthouse, pull requests merged in 2025-05, with the labels that each got.

#7304 Compute proposer shuffling only once in gossip verification
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/beacon_proposer_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  common/logging/Cargo.toml
Labels: optimization, ready-for-merge, das

#7359 Make sure to log SyncingChain ID
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/chain_collection.rs
  beacon_node/network/src/sync/range_sync/range.rs
Labels: syncing, ready-for-merge, UX-and-logs

#7387 docs: fix broken link to voluntary exit guide
  book/src/faq.md
Labels: docs, ready-for-merge

#7378 Change slog to tracing in comments
  common/logging/src/sse_logging_components.rs
Labels: ready-for-merge

#6922 Make range sync peer loadbalancing PeerDAS-friendly
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
  beacon_node/network/src/sync/tests/lookups.rs
Labels: syncing, ready-for-merge, das

#7405 Add requires --http when using vc subcommands --http-port
  lighthouse/tests/validator_client.rs
  validator_client/src/cli.rs
Labels: val-client, ready-for-merge

#7409 Don't publish data columns reconstructed from RPC columns to the gossip network
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
Labels: ready-for-merge, das

#7400 Add a default timeout to all `BeaconNodeHttpClient` requests
  common/eth2/src/lib.rs
  validator_client/src/lib.rs
Labels: val-client, ready-for-merge, v7.1.0

#7416 Add ARM binary for macOS in release
  .github/workflows/release.yml
Labels: ready-for-merge, infra-ci

#7199 Add Electra forks to basic sim tests
  .github/workflows/test-suite.yml
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  testing/node_test_rig/src/lib.rs
  testing/simulator/src/basic_sim.rs
  testing/simulator/src/checks.rs
Labels: test improvement, ready-for-merge, das, electra

#7394 simulator: Persist beacon logs
  .github/workflows/test-suite.yml
  testing/simulator/src/basic_sim.rs
  testing/simulator/src/cli.rs
  testing/simulator/src/fallback_sim.rs
Labels: test improvement, ready-for-merge

#7284 update gossipsub to the latest upstream revision
  Cargo.lock
  Cargo.toml
Labels: ready-for-merge, Networking, trivial

#7399 `peerdas-devnet-7`: update `DataColumnSidecarsByRoot` request to use `DataColumnsByRootIdentifier`
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests/data_columns_by_root.rs
  beacon_node/network/src/sync/tests/lookups.rs
  beacon_node/store/src/hot_cold_store.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/lib.rs
  scripts/local_testnet/network_params_das.yaml
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-merge, das

#7404 Siren installation improvement
  book/src/SUMMARY.md
  book/src/ui.md
  book/src/ui_authentication.md
  book/src/ui_faqs.md
  book/src/ui_installation.md
Labels: docs, ready-for-merge

#7396 Siren Pectra Feature Updates
  book/src/imgs/consolidation-source.png
  book/src/imgs/consolidation-target.png
  book/src/imgs/deposit-funds.png
  book/src/imgs/partial-withdrawal-siren.png
  book/src/imgs/ui-dep-1.png
  book/src/imgs/ui-dep-2.png
  book/src/imgs/ui-dep-3.png
  book/src/imgs/ui-dep-4.png
  book/src/imgs/ui-dep-5.png
  book/src/imgs/ui-dep-6.png
  book/src/imgs/ui-session.png
  book/src/imgs/ui-val-modal.png
  book/src/ui_faqs.md
  book/src/ui_usage.md
Labels: ready-for-review, docs, electra

#7370 impl test random for some types
  consensus/types/src/builder_bid.rs
  consensus/types/src/signed_beacon_block.rs
Labels: ready-for-merge

#7443 Next sync committee branch bug
  beacon_node/beacon_chain/src/light_client_server_cache.rs
Labels: bug, ready-for-merge, light-client

#7460 Make DAG construction more permissive
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v23.rs
  beacon_node/beacon_chain/src/summaries_dag.rs
Labels: bug, ready-for-merge, database, tree-states

#7451 Add additional mergify rules to automate triaging
  .github/mergify.yml
Labels: ready-for-review, infra-ci, skip-ci

#7463 Fix mergify infinite loop.
  .github/mergify.yml
Labels: infra-ci, skip-ci

#7458 Added E::slots_per_epoch() to deneb time calculation
  beacon_node/client/src/builder.rs
Labels: ready-for-merge

#7433 simulator: Write dependency logs to separate files
  Cargo.lock
  lighthouse/environment/src/tracing_common.rs
  testing/simulator/Cargo.toml
  testing/simulator/src/basic_sim.rs
  testing/simulator/src/fallback_sim.rs
  testing/simulator/src/main.rs
Labels: test improvement, ready-for-merge

#7470 Prevent mergify from updating labels while CI is still running
  .github/mergify.yml
Labels: waiting-on-author, skip-ci

#7472 One more attempt to fix mergify condition
  .github/mergify.yml
Labels: infra-ci, skip-ci

#7471 Rust clippy 1.87 lint fixes
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/eth1_finalization_cache.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/beacon_chain/src/fetch_blobs.rs
  beacon_node/beacon_chain/src/state_advance_timer.rs
  beacon_node/beacon_chain/src/sync_committee_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_attestations.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/src/sync_committees.rs
  beacon_node/http_api/src/validator.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/store/src/errors.rs
  common/eth2/src/lib.rs
  consensus/state_processing/src/per_epoch_processing/altair.rs
  consensus/state_processing/src/per_epoch_processing/epoch_processing_summary.rs
  testing/ef_tests/src/cases/merkle_proof_validity.rs
Labels: code-quality, ready-for-merge

#7369 impl from hash256 for `ExecutionBlockHash`
  consensus/types/src/execution_block_hash.rs
Labels: code-quality, ready-for-merge

#7417 Change default EngineState to online
  beacon_node/execution_layer/src/engines.rs
  beacon_node/http_api/tests/tests.rs
Labels: waiting-on-author, ready-for-merge

#7481 Update mdlint to disable descriptive-link-text
  scripts/mdlint.sh
Labels: low-hanging-fruit, ready-for-merge, infra-ci

#7411 Silence `Uninitialized` warn log on start-up
  validator_client/beacon_node_fallback/src/lib.rs
Labels: val-client, low-hanging-fruit, ready-for-merge, UX-and-logs

#6799 feat: Add docker reproducible builds
  Cargo.toml
  Dockerfile.reproducible
  Makefile
Labels: enhancement, ready-for-merge, infra-ci, v7.1.0, stale

#7455 Some updates to Lighthouse book
  book/src/advanced_database_migrations.md
  book/src/advanced_release_candidates.md
  book/src/advanced_web3signer.md
  book/src/api_vc_auth_header.md
  book/src/api_vc_endpoints.md
  book/src/archived_key_management.md
  book/src/faq.md
  book/src/installation_docker.md
  book/src/mainnet_validator.md
  book/src/run_a_node.md
  book/src/ui_installation.md
  book/src/validator_voluntary_exit.md
  scripts/local_testnet/README.md
  wordlist.txt
Labels: docs, ready-for-merge

#7484 Move MD059 rule to configuration file
  book/.markdownlint.yml
  scripts/mdlint.sh
Labels: ready-for-merge

#5047 Correct reward denominator in op pool
  beacon_node/beacon_chain/src/block_reward.rs
  beacon_node/operation_pool/src/attestation.rs
  beacon_node/operation_pool/src/lib.rs
Labels: low-hanging-fruit, ready-for-merge, v7.1.0

#7474 Empty list `[]` to return all validators balances
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/validators.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/types.rs
  common/warp_utils/src/json.rs
Labels: ready-for-merge, HTTP-API

#7495 Fix blob download from checkpointz servers
  common/eth2/src/lib.rs
Labels: ready-for-merge, v7.1.0

#7497 Pass blobs into `ValidatorStore::sign_block`
  Cargo.lock
  testing/web3signer_tests/Cargo.toml
  testing/web3signer_tests/src/lib.rs
  validator_client/lighthouse_validator_store/src/lib.rs
  validator_client/validator_services/src/block_service.rs
  validator_client/validator_store/Cargo.toml
  validator_client/validator_store/src/lib.rs
Labels: val-client, ready-for-merge, anchor

#7427 Move notifier and latency service to `validator_services`
  validator_client/src/lib.rs
  validator_client/validator_services/Cargo.toml
  validator_client/validator_services/src/latency_service.rs
  validator_client/validator_services/src/lib.rs
  validator_client/validator_services/src/notifier_service.rs
Labels: val-client, ready-for-merge

#7494 Update mergify rule to avoid unnecessarily firing some rules
  .github/mergify.yml
Labels: waiting-on-author, infra-ci, skip-ci

#7352 Fix PeerDAS sync scoring
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/error.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/score.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/network_context/requests/blobs_by_range.rs
  beacon_node/network/src/sync/network_context/requests/blocks_by_range.rs
  beacon_node/network/src/sync/network_context/requests/data_columns_by_range.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/mod.rs
  beacon_node/network/src/sync/range_sync/range.rs
  beacon_node/network/src/sync/tests/range.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
Labels: ready-for-review, syncing, das

#7507 Use slice.is_sorted now that it's stable
  beacon_node/beacon_chain/src/test_utils.rs
Labels: code-quality, low-hanging-fruit, ready-for-merge

#7506 Enable stdout logging in rpc_tests
  beacon_node/lighthouse_network/tests/rpc_tests.rs
Labels: test improvement, ready-for-merge

#7500 Send execution_requests in fulu
  beacon_node/execution_layer/src/lib.rs
Labels: ready-for-merge, builder API, fulu

#7459 Revive network-test logs files in CI
  .github/workflows/test-suite.yml
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/sync/tests/lookups.rs
  beacon_node/network/src/sync/tests/mod.rs
Labels: test improvement, ready-for-merge

#7180 Improve log readability during rpc_tests
  beacon_node/lighthouse_network/tests/rpc_tests.rs
Labels: test improvement, ready-for-merge

#7052 Publish EL Info in Metrics
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/metrics.rs
Labels: ready-for-merge

#7512 Fix formatting errors from cargo-sort
  Cargo.toml
  beacon_node/Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/client/Cargo.toml
  beacon_node/eth1/Cargo.toml
  beacon_node/genesis/Cargo.toml
  beacon_node/lighthouse_network/Cargo.toml
  beacon_node/network/Cargo.toml
  beacon_node/operation_pool/Cargo.toml
  beacon_node/store/Cargo.toml
  common/compare_fields/Cargo.toml
  common/deposit_contract/Cargo.toml
  common/eth2/Cargo.toml
  common/eth2_network_config/Cargo.toml
  common/health_metrics/Cargo.toml
  common/malloc_utils/Cargo.toml
  consensus/merkle_proof/Cargo.toml
  consensus/state_processing/Cargo.toml
  consensus/swap_or_not_shuffle/Cargo.toml
  consensus/types/Cargo.toml
  crypto/bls/Cargo.toml
  lcli/Cargo.toml
  lighthouse/Cargo.toml
  testing/execution_engine_integration/Cargo.toml
  testing/state_transition_vectors/Cargo.toml
  validator_client/slashing_protection/Cargo.toml
Labels: ready-for-merge

#7505 Update `engine_getBlobsV2` response type and add `getBlobsV2` tests
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/fetch_blobs/fetch_blobs_beacon_adapter.rs
  beacon_node/beacon_chain/src/fetch_blobs/mod.rs
  beacon_node/beacon_chain/src/fetch_blobs/tests.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/lib.rs
Labels: ready-for-merge, das

#7493 Verify `getBlobsV2` response and avoid reprocessing imported data columns
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/fetch_blobs/fetch_blobs_beacon_adapter.rs
  beacon_node/beacon_chain/src/fetch_blobs/mod.rs
  beacon_node/beacon_chain/src/fetch_blobs/tests.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/sync/tests/lookups.rs
Labels: ready-for-merge, das

#7332 Remove support for database migrations prior to schema version v22
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v20.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v21.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v22.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/src/builder.rs
  beacon_node/store/src/hot_cold_store.rs
  book/src/advanced_database_migrations.md
  database_manager/src/lib.rs
  wordlist.txt
Labels: code-quality, ready-for-merge, database, v7.1.0

#7522 Mitigate flakiness in test_delayed_rpc_response
  beacon_node/lighthouse_network/tests/rpc_tests.rs
Labels: test improvement, ready-for-merge

#7533 Prevent `AvailabilityCheckError` when there's no new custody columns to import
  beacon_node/beacon_chain/src/fetch_blobs/mod.rs
  beacon_node/beacon_chain/src/fetch_blobs/tests.rs
Labels: bug, ready-for-merge, das

#7529 Add `console-subscriber` feature for debugging
  Cargo.lock
  Cargo.toml
  lighthouse/Cargo.toml
  lighthouse/src/main.rs
Labels: ready-for-merge
