Repository sigp/lighthouse, pull requests merged in 2025-09, with the labels that each got.

#7964 Remove dependency on target_info.
  Cargo.lock
  common/lighthouse_version/Cargo.toml
  common/lighthouse_version/src/lib.rs
Labels: ready-for-merge, dependencies, v8.0.0-rc.0

#7902 chore: small refactor of `epoch` method
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
Labels: code-quality, ready-for-merge

#7957 Remove `expect` usage in `kzg_utils`
  beacon_node/beacon_chain/src/kzg_utils.rs
Labels: low-hanging-fruit, ready-for-merge, v8.0.0-rc.0

#7961 Fix data availability checker race condition causing partial data columns to be served over RPC
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
Labels: bug, ready-for-merge, v8.0.0-rc.0

#7981 Update tracing
  Cargo.lock
Labels: ready-for-merge

#7016 Implement `selections` Beacon API endpoints to support DVT middleware
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  consensus/types/src/selection_proof.rs
  consensus/types/src/sync_selection_proof.rs
  validator_client/src/lib.rs
  validator_client/validator_services/src/duties_service.rs
  validator_client/validator_services/src/sync.rs
  validator_client/validator_store/src/lib.rs
Labels: ready-for-merge, dvt, v8.0.0-rc.0

#7987 Add `tls-roots` feature to `opentelemetry_otlp` to support exporting traces over https
  Cargo.lock
  Cargo.toml
  lighthouse/src/main.rs
Labels: low-hanging-fruit, ready-for-merge, tracing

#7989 Simplify length methods on BeaconBlockBody
  consensus/types/src/beacon_block_body.rs
Labels: code-quality, low-hanging-fruit, ready-for-merge

#7999 Fix incorrect prune test logic
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
Labels: test improvement, low-hanging-fruit, ready-for-merge

#7998 Fix data column reconstruction error
  beacon_node/beacon_chain/benches/benches.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
Labels: bug, low-hanging-fruit, ready-for-merge, v8.0.0-rc.0

#7993 Add co-author to mergify commits
  .github/mergify.yml
Labels: waiting-on-author, low-hanging-fruit, skip-ci

#8017 Instrument tracing on block production code path
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/execution_payload.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/http_api/src/produce_block.rs
  beacon_node/lighthouse_tracing/src/lib.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/state_processing/src/per_slot_processing.rs
Labels: ready-for-merge, v8.0.0-rc.0, tracing

#8007 Reduce noise in `Debug` impl of `RuntimeVariableList`
  consensus/types/src/runtime_fixed_vector.rs
  consensus/types/src/runtime_var_list.rs
Labels: low-hanging-fruit, ready-for-merge

#7874 Remove cargo test targets, use nextest exclusively
  .github/workflows/test-suite.yml
  CLAUDE.md
  Makefile
  book/src/contributing_setup.md
  wordlist.txt
Labels: test improvement, ready-for-merge, infra-ci

#8038 Update engine methods in notifier
  beacon_node/client/src/notifier.rs
Labels: low-hanging-fruit, ready-for-merge, UX-and-logs, v8.0.0-rc.0

#8050 Another check to prevent duplicate block imports
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/tests/block_verification.rs
Labels: optimization, ready-for-merge, fulu

#8051 Remove column reconstruction when processing rpc requests
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
Labels: ready-for-merge, das

#8053 Reduce reconstruction queue capacity
  beacon_node/beacon_processor/src/lib.rs
Labels: ready-for-merge, das

#8049 Add instrumentation to `recompute_head_at_slot`
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/lighthouse_tracing/src/lib.rs
  beacon_node/store/src/hot_cold_store.rs
  consensus/state_processing/src/all_caches.rs
Labels: ready-for-merge, UX-and-logs, tracing

#8052 Enable reconstruction for nodes custodying more than 50% of columns and instrument tracing
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/validator_custody.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
Labels: ready-for-merge, das, tracing

#8042 Don't penalize peers for extending ignored chains
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/tests/lookups.rs
Labels: ready-for-merge, v8.0.0-rc.0

#8023 Prevent silently dropping cell proof chunks
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/http_api/src/publish_blocks.rs
  consensus/types/src/data_column_sidecar.rs
Labels: ready-for-merge, das, v8.0.0-rc.0

#8065 Fix reprocess queue memory leak
  beacon_node/beacon_processor/src/scheduler/work_reprocessing_queue.rs
Labels: bug, ready-for-merge, v8.0.0-rc.0, hardening

#7751 Add experimental complete-blob-backfill flag
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, database, deneb, v8.0.0-rc.0

#8045 Consolidate `reqresp_pre_import_cache` into `data_availability_checker`
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/tests/lookups.rs
Labels: bug, code-quality, ready-for-merge, v8.0.0-rc.0

#8083 Rename `--subscribe-all-data-column-subnets` to `--supernode` and make it visible in help
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: docs, low-hanging-fruit, ready-for-merge, v8.0.0-rc.0

#8082 Always upload sim test logs
  .github/workflows/test-suite.yml
Labels: low-hanging-fruit, ready-for-merge, infra-ci

#8098 Refine HTTP status logs
  beacon_node/http_api/src/lib.rs
Labels: low-hanging-fruit, ready-for-merge, UX-and-logs, fulu, v8.0.0-rc.0

#8075 Run reconstruction inside a scoped rayon pool
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_processor/Cargo.toml
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/rayon_manager.rs
  beacon_node/client/src/builder.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  common/task_executor/Cargo.toml
  common/task_executor/src/lib.rs
  common/task_executor/src/rayon_pool_provider.rs
Labels: optimization, ready-for-merge, v8.0.0-rc.0, beacon-processor

#8112 Only mark block lookups as pending if block is importing from gossip
  beacon_node/beacon_chain/src/beacon_block_streamer.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/network/src/sync/block_lookups/single_block_lookup.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/tests/lookups.rs
  consensus/types/src/beacon_block.rs
Labels: bug, ready-for-merge, v8.0.0-rc.0

#8101 Fix bugs in proposer calculation post-Fulu
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/beacon_proposer_cache.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/errors.rs
  beacon_node/beacon_chain/src/validator_monitor.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/validator_monitor.rs
  beacon_node/http_api/src/proposer_duties.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/state_processing/src/all_caches.rs
  consensus/state_processing/src/epoch_cache.rs
  consensus/state_processing/src/upgrade/fulu.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/epoch_cache.rs
  testing/ef_tests/src/cases/fork.rs
Labels: bug, security, ready-for-merge, fulu, v8.0.0-rc.0, queued

#8121 Fix bug in fork calculation at fork boundaries
  beacon_node/beacon_chain/src/beacon_proposer_cache.rs
Labels: ready-for-merge, v8.0.0-rc.0, queued

#8132 Update book for DB schema v28
  book/src/advanced_database_migrations.md
  wordlist.txt
Labels: docs, low-hanging-fruit, ready-for-merge, queued
