Repository sigp/lighthouse, pull requests merged in 2025-06, with the labels that each got.

#6882 Run Assertoor tests in CI
  .github/workflows/local-testnet.yml
  scripts/local_testnet/start_local_testnet.sh
Labels: test improvement, ready-for-merge

#7541 Fix unexpected blob error and duplicate import in fetch blobs
  beacon_node/beacon_chain/src/fetch_blobs/mod.rs
  beacon_node/beacon_chain/src/fetch_blobs/tests.rs
  beacon_node/beacon_chain/src/observed_data_sidecars.rs
Labels: bug, ready-for-merge

#7521 Implement EIP-7892 BPO hardforks
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  common/eth2/src/lib.rs
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge, fulu

#7518 Update `staking-deposit-cli` to `ethstaker-deposit-cli`
  account_manager/src/validator/import.rs
  book/src/archived_key_management.md
  book/src/faq.md
  book/src/help_vm.md
  book/src/help_vm_create.md
  book/src/help_vm_import.md
  book/src/installation_homebrew.md
  book/src/mainnet_validator.md
  book/src/validator_manager.md
  book/src/validator_manager_api.md
  book/src/validator_manager_create.md
  book/src/validator_slashing_protection.md
  book/src/validator_voluntary_exit.md
  common/account_utils/src/validator_definitions.rs
  validator_manager/src/common.rs
  validator_manager/src/create_validators.rs
  validator_manager/src/import_validators.rs
  validator_manager/test_vectors/generate.py
  wordlist.txt
Labels: docs, ready-for-merge

#7544 Add a name to the Tokio task
  common/task_executor/Cargo.toml
  common/task_executor/src/lib.rs
Labels: ready-for-merge

#7549 Checkpoint sync without the blobs from Fulu
  beacon_node/beacon_chain/src/builder.rs
Labels: syncing, ready-for-merge, fulu

#7530 Add e2e sync tests to CI
  .github/workflows/local-testnet.yml
  scripts/ci/check-success-job.sh
  scripts/tests/checkpoint-sync-config-devnet.yaml
  scripts/tests/checkpoint-sync-config-sepolia.yaml
  scripts/tests/checkpoint-sync.sh
Labels: test improvement, syncing, ready-for-merge

#7538 Add support for nightly tests
  Makefile
  testing/ef_tests/Makefile
  testing/ef_tests/download_test_vectors.sh
Labels: ready-for-merge

#7566 Reduce number of basic sim test nodes from 7 to 4
  testing/simulator/src/cli.rs
Labels: test improvement, ready-for-merge

#7579 Store the libp2p/discv5 logs when stopping local-testnet
  scripts/local_testnet/stop_local_testnet.sh
Labels: test improvement, ready-for-merge

#7559 Changes for `fusaka-devnet-1`
  beacon_node/beacon_chain/src/beacon_proposer_cache.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/state_advance_timer.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/beacon_chain/tests/validator_monitor.rs
  beacon_node/http_api/src/proposer_duties.rs
  beacon_node/store/src/partial_beacon_state.rs
  consensus/state_processing/src/per_epoch_processing/errors.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/state_processing/src/upgrade/fulu.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/eth_spec.rs
  testing/ef_tests/Makefile
  testing/ef_tests/src/cases/epoch_processing.rs
  testing/ef_tests/src/lib.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-merge, fusaka-devnet-1

#7574 Optimise parallelism in compute cells operations by zipping first
  beacon_node/beacon_chain/src/kzg_utils.rs
Labels: optimization, ready-for-merge, das

#7587 Data column sidecar event
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/events.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/events.rs
  beacon_node/http_api/src/lib.rs
  common/eth2/src/types.rs
Labels: ready-for-merge, fulu

#7578 Implement basic validator custody framework (no backfill)
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/persisted_custody.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/validator_custody.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/lighthouse_network/src/types/topics.rs
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/tests/lookups.rs
  beacon_node/network/src/sync/tests/range.rs
  beacon_node/store/src/lib.rs
  consensus/types/src/chain_spec.rs
  scripts/local_testnet/network_params_das.yaml
  scripts/tests/checkpoint-sync-config-devnet.yaml
  scripts/tests/genesis-sync-config-fulu.yaml
  testing/ef_tests/src/cases/fork_choice.rs
Labels: syncing, ready-for-merge, fulu

#7582 Batch verify KZG proofs for getBlobsV2
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/fetch_blobs/fetch_blobs_beacon_adapter.rs
  beacon_node/beacon_chain/src/fetch_blobs/mod.rs
  beacon_node/beacon_chain/src/fetch_blobs/tests.rs
  beacon_node/beacon_chain/src/observed_data_sidecars.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
Labels: ready-for-merge, das

#7594 Drop stale registrations without reducing CGC
  beacon_node/beacon_chain/src/validator_custody.rs
Labels: ready-for-review, ready-for-merge, das

#7591 Add data columns sidecars debug beacon API
  beacon_node/http_api/src/block_id.rs
  beacon_node/http_api/src/lib.rs
  common/eth2/src/types.rs
Labels: ready-for-merge, HTTP-API, das

#7444 Single attestation "Full" implementation
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/attestation_verification/batch.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/single_attestation.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/attestation_verification.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/beacon_chain/tests/tests.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_attestations.rs
  beacon_node/http_api/tests/fork_tests.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/service.rs
  common/eth2/src/lib.rs
  consensus/fork_choice/tests/tests.rs
  consensus/types/src/attestation.rs
  validator_client/validator_services/src/attestation_service.rs
Labels: optimization, ready-for-merge, backwards-incompat, electra, v7.1.0

#7615 Hot hdiff buffer cache
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  beacon_node/store/src/config.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/metrics.rs
  beacon_node/store/src/state_cache.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: optimization, tree-states

#7437 Remove reprocess channel
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/scheduler/mod.rs
  beacon_node/beacon_processor/src/scheduler/work_reprocessing_queue.rs
  beacon_node/client/src/builder.rs
  beacon_node/client/src/compute_light_client_updates.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/publish_attestations.rs
  beacon_node/http_api/src/task_spawner.rs
  beacon_node/http_api/src/test_utils.rs
  beacon_node/http_api/tests/interactive_tests.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/service/tests.rs
Labels: code-quality, ready-for-merge, v7.1.0

#7611 Send byrange responses in the correct requested range
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: syncing, ready-for-merge, v7.1.0

#7462 Implement `validator_identities` Beacon API endpoint
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/validators.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
Labels: ready-for-merge, HTTP-API, v7.1.0

#7632 Un-ignore EF test for v1.6.0-alpha.1
  testing/ef_tests/src/cases/operations.rs
Labels: test improvement, low-hanging-fruit, ready-for-merge, v7.1.0

#7644 Rust 1.89 compiler lint fix
  beacon_node/beacon_chain/src/attestation_verification.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/store/src/database/interface.rs
  beacon_node/store/src/database/leveldb_impl.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/state_processing/src/consensus_context.rs
  consensus/state_processing/src/per_block_processing/signature_sets.rs
  consensus/types/src/attestation.rs
  consensus/types/src/attester_slashing.rs
  consensus/types/src/beacon_state.rs
  consensus/types/src/beacon_state/committee_cache.rs
  consensus/types/src/slot_epoch.rs
  consensus/types/src/sqlite.rs
  slasher/src/array.rs
  slasher/src/database.rs
  slasher/src/database/interface.rs
  slasher/src/database/lmdb_impl.rs
  validator_client/initialized_validators/src/lib.rs
Labels: code-quality, ready-for-merge, v7.1.0

#7652 Add gossip check
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/store/src/hot_cold_store.rs
Labels: ready-for-merge, v7.1.0

#7656 Fix incorrect `waker` update condition
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/network/src/subnet_service/attestation_subnets.rs
  beacon_node/network/src/subnet_service/mod.rs
  beacon_node/network/src/subnet_service/sync_subnets.rs
Labels: bug, low-hanging-fruit, ready-for-merge

#7597 feat: better error message for light_client/bootstrap endpoint
  beacon_node/beacon_chain/src/light_client_server_cache.rs
Labels: ready-for-merge

#7667 Add Michael as codeowner for store crate
  .github/CODEOWNERS
Labels: low-hanging-fruit, ready-for-merge, infra-ci
