Repository sigp/lighthouse, pull requests merged in 2025-07, with the labels that each got.

#7683 Update `SAMPLES_PER_SLOT` to be number of custody groups instead of data columns
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/validator_custody.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge, das, fulu

#7646 Update fulu network configs and add `MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS`
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/store/src/hot_cold_store.rs
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/hoodi/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge, fulu

#7695 Bump default gas limit
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/http_api/tests/tests.rs
  book/src/help_vc.md
  lighthouse/tests/validator_client.rs
  validator_client/lighthouse_validator_store/src/lib.rs
  validator_client/src/cli.rs
Labels: ready-for-merge, v7.1.0

#7706 Update LH book for v7.1.0
  book/src/advanced_builders.md
  book/src/advanced_database_migrations.md
Labels: docs, low-hanging-fruit, ready-for-merge

#7707 Remove unneeded spans that caused debug logs to appear when level is set to `info`
  beacon_node/network/src/sync/range_sync/chain.rs
Labels: low-hanging-fruit, ready-for-merge, UX-and-logs, v7.1.0

#7271 Upgrade to c-kzg 2.1.0 and alloy-primitives 1.0
  Cargo.lock
  Cargo.toml
  consensus/types/src/attestation.rs
  crypto/kzg/benches/benchmark.rs
  crypto/kzg/src/lib.rs
  crypto/kzg/src/trusted_setup.rs
  testing/simulator/src/basic_sim.rs
  testing/simulator/src/fallback_sim.rs
Labels: ready-for-merge, dependencies, stale

#7663 Error from RPC `send_response` when request doesn't exist on the active inbound requests
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/src/service.rs
Labels: ready-for-merge, Networking, v7.1.0

#7717 Improve data column KZG verification metric buckets
  beacon_node/beacon_chain/src/metrics.rs
Labels: low-hanging-fruit, ready-for-merge, das

#7655 Final changes for `fusaka-devnet-2`
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/http_api/src/light_client.rs
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/discovery/enr.rs
  beacon_node/lighthouse_network/src/discovery/mod.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/rpc/rate_limiter.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/service/tests.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  consensus/types/src/beacon_block.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/enr_fork_id.rs
  consensus/types/src/fork_context.rs
  consensus/types/src/fork_name.rs
  consensus/types/src/signed_beacon_block.rs
  lcli/src/generate_bootnode_enr.rs
  scripts/tests/checkpoint-sync-config-devnet.yaml
Labels: syncing, ready-for-merge, fusaka-devnet-2

#7733 Sync peer attribution
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb/sync_status.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/batch.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/tests/range.rs
  scripts/tests/genesis-sync-config-fulu.yaml
Labels: syncing, ready-for-merge, das, fulu

#7729 Allow /validator apis to work pre-genesis
  beacon_node/http_api/src/attester_duties.rs
  beacon_node/http_api/src/lib.rs
Labels: ready-for-merge, HTTP-API

#7325 Add additional broadcast validation tests for Fulu/PeerDAS
  .github/workflows/test-suite.yml
  Makefile
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
Labels: test improvement, ready-for-merge, das, fulu

#7753 Serialize bpo schedule in asending order
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge, fulu

#7764 Add heaptrack support
  Cargo.toml
  lighthouse/Cargo.toml
  lighthouse/src/main.rs
Labels: ready-for-merge

#7648 Data column custody info
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v27.rs
  beacon_node/beacon_chain/src/validator_custody.rs
  beacon_node/beacon_chain/tests/schema_stability.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/lib.rs
  beacon_node/network/src/status.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metadata.rs
Labels: ready-for-merge, database, backwards-incompat, das, fusaka-devnet-3

#7239 Control span data through tracing Extensions
  common/logging/src/tracing_logging_layer.rs
Labels: code-quality, ready-for-merge, UX-and-logs

#7705 Refine delayed head block logging
  beacon_node/beacon_chain/src/canonical_head.rs
Labels: low-hanging-fruit, ready-for-merge, UX-and-logs

#7768 Remove peer sampling code
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
  beacon_node/beacon_processor/src/scheduler/work_reprocessing_queue.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/mod.rs
  beacon_node/network/src/sync/peer_sampling.rs
  beacon_node/network/src/sync/tests/lookups.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  lighthouse/tests/beacon_node.rs
Labels: code-quality, syncing, ready-for-merge, das

#7779 Skip serializing blob_schedule before Fulu
  consensus/types/src/chain_spec.rs
  consensus/types/src/config_and_preset.rs
Labels: low-hanging-fruit, ready-for-merge, HTTP-API, das, fulu, fusaka-devnet-3

#7787 Bump Rust version to 1.88
  Dockerfile.reproducible
  Makefile
  common/warp_utils/src/reject.rs
  lcli/Dockerfile
  lighthouse/Cargo.toml
Labels: ready-for-merge, backwards-incompat

#7786 Update spec tests to 1.6.0-alpha.3
  testing/ef_tests/Makefile
  testing/ef_tests/src/cases/fork_choice.rs
  testing/ef_tests/src/handler.rs
Labels: ready-for-merge, fusaka-devnet-3

#7771 Remove KZG verification on blobs fetched from the EL
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/fetch_blobs/fetch_blobs_beacon_adapter.rs
  beacon_node/beacon_chain/src/fetch_blobs/mod.rs
  beacon_node/beacon_chain/src/fetch_blobs/tests.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
Labels: optimization, ready-for-merge

#7778 Add builder blinded_blocks v2
  beacon_node/builder_client/src/lib.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/http_api/tests/broadcast_validation_tests.rs
Labels: ready-for-merge, builder API, fulu, fusaka-devnet-3
