Repository sigp/lighthouse, pull requests merged in 2025-08, with the labels that each got.

#7826 Fix Clippy for Rust 1.90 beta
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/genesis/src/interop.rs
  beacon_node/http_api/src/aggregate_attestation.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/store/src/database/redb_impl.rs
  consensus/state_processing/src/per_block_processing/tests.rs
  crypto/bls/tests/tests.rs
  crypto/eth2_keystore/src/json_keystore/hex_bytes.rs
  slasher/src/config.rs
  testing/ef_tests/src/cases/fork_choice.rs
  testing/ef_tests/src/cases/operations.rs
  validator_client/initialized_validators/src/key_cache.rs
  validator_manager/src/list_validators.rs
Labels: low-hanging-fruit, ready-for-merge

#7734 Fix: RPC test failures
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
Labels: test improvement, ready-for-merge

#7825 Adjust DA checker cache size
  beacon_node/beacon_chain/src/data_availability_checker.rs
Labels: low-hanging-fruit, ready-for-merge

#7844 Fix Rust 1.89 compiler warnings in slasher tests.
  slasher/src/database/mdbx_impl.rs
  slasher/src/database/redb_impl.rs
Labels: ready-for-merge

#7816 Instrument tracing spans for block processing and import
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/blob_verification.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/fetch_blobs/mod.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/state_advance_timer.rs
  beacon_node/beacon_chain/src/validator_monitor.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/subnet_service/mod.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_lookups/mod.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  beacon_node/network/src/sync/range_sync/range.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/state_cache.rs
  book/src/help_bn.md
  book/src/help_general.md
  book/src/help_vc.md
  book/src/help_vm.md
  book/src/help_vm_create.md
  book/src/help_vm_import.md
  book/src/help_vm_move.md
  common/task_executor/src/lib.rs
  consensus/fork_choice/src/fork_choice.rs
  consensus/state_processing/Cargo.toml
  consensus/state_processing/src/common/update_progressive_balances_cache.rs
  consensus/state_processing/src/epoch_cache.rs
  consensus/state_processing/src/per_block_processing.rs
  consensus/state_processing/src/per_epoch_processing.rs
  consensus/state_processing/src/per_epoch_processing/single_pass.rs
  consensus/state_processing/src/per_slot_processing.rs
  consensus/types/src/beacon_state.rs
  lighthouse/Cargo.toml
  lighthouse/src/main.rs
  slasher/service/src/service.rs
Labels: ready-for-merge, tracing

#7853 Add a flag to disable getBlobs
  beacon_node/beacon_chain/src/chain_config.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, fulu

#7808 Add metrics to track beacon processor queue times
  beacon_node/beacon_processor/src/lib.rs
  beacon_node/beacon_processor/src/metrics.rs
Labels: code-quality, ready-for-merge

#7762 Backfill peer attribution
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/network/src/sync/backfill_sync/mod.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  scripts/tests/checkpoint-sync-config-devnet.yaml
Labels: syncing, ready-for-merge, fusaka-devnet-3

#7852 Re-export `context_deserialize_derive` inside `context_deserialize`
  Cargo.lock
  Cargo.toml
  consensus/context_deserialize/Cargo.toml
  consensus/context_deserialize/context_deserialize/Cargo.toml
  consensus/context_deserialize/context_deserialize/src/impls/core.rs
  consensus/context_deserialize/context_deserialize/src/impls/milhouse.rs
  consensus/context_deserialize/context_deserialize/src/impls/mod.rs
  consensus/context_deserialize/context_deserialize/src/impls/ssz.rs
  consensus/context_deserialize/context_deserialize/src/lib.rs
  consensus/context_deserialize/context_deserialize_derive/Cargo.toml
  consensus/context_deserialize/context_deserialize_derive/src/lib.rs
  consensus/context_deserialize/context_deserialize_derive/tests/context_deserialize_derive.rs
  consensus/types/Cargo.toml
  consensus/types/src/attestation_data.rs
  consensus/types/src/beacon_block_header.rs
  consensus/types/src/checkpoint.rs
  consensus/types/src/fork.rs
  consensus/types/src/fork_data.rs
  consensus/types/src/lib.rs
  testing/ef_tests/Cargo.toml
  testing/ef_tests/src/cases/ssz_generic.rs
Labels: code-quality, ready-for-merge

#7862 Deprecate macOS-x86 binaries
  .github/workflows/release.yml
Labels: ready-for-merge, backwards-incompat, v8.0.0-rc.0

#7867 Disable sccache to fix Windows builds
  .cargo/config.toml
  .github/workflows/test-suite.yml
Labels: ready-for-merge, infra-ci

#7873 Try using sccache instead of disabling
  .cargo/config.toml
  .github/workflows/book.yml
  .github/workflows/docker.yml
  .github/workflows/linkcheck.yml
  .github/workflows/local-testnet.yml
  .github/workflows/release.yml
  .github/workflows/test-suite.yml
Labels: ready-for-merge, infra-ci

#7872 Yeet env_logger into the sun
  Cargo.lock
  Cargo.toml
  consensus/state_processing/Cargo.toml
  consensus/state_processing/src/per_epoch_processing/tests.rs
  lcli/Cargo.toml
  lcli/src/main.rs
Labels: code-quality, ready-for-merge, dependencies, v8.0.0-rc.0

#7806 Fix ssz formatting for `/light_client/updates` beacon API endpoint
  beacon_node/http_api/src/light_client.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
Labels: bug, ready-for-merge, light-client, v8.0.0-rc.0

#7890 Fulu update to spec v1.6.0-alpha.4
  beacon_node/beacon_chain/benches/benches.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/observed_data_sidecars.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/src/validator_custody.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/events.rs
  beacon_node/http_api/src/block_id.rs
  beacon_node/lighthouse_network/src/discovery/subnet_predicate.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/types/globals.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
  beacon_node/network/src/sync/network_context/requests/data_columns_by_root.rs
  beacon_node/network/src/sync/tests/lookups.rs
  beacon_node/network/src/sync/tests/range.rs
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/hoodi/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/types/presets/gnosis/fulu.yaml
  consensus/types/presets/mainnet/fulu.yaml
  consensus/types/presets/minimal/fulu.yaml
  consensus/types/src/beacon_block.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/data_column_custody_group.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/preset.rs
  crypto/kzg/src/lib.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/common.rs
  testing/ef_tests/src/cases/compute_columns_for_custody_groups.rs
  testing/ef_tests/src/cases/ssz_generic.rs
  testing/ef_tests/src/cases/ssz_static.rs
  testing/ef_tests/src/lib.rs
  testing/ef_tests/src/type_name.rs
  testing/ef_tests/tests/tests.rs
Labels: ready-for-merge, fulu, v8.0.0-rc.0

#7897 Avoid unnecessary database lookups in data column RPC requests
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/validator_custody.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
Labels: optimization, ready-for-merge, das, v8.0.0-rc.0

#7831 Implement tracing spans for data columm RPC requests and responses
  CLAUDE.md
  Cargo.lock
  Cargo.toml
  beacon_node/beacon_chain/Cargo.toml
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/lighthouse_tracing/Cargo.toml
  beacon_node/lighthouse_tracing/src/lib.rs
  beacon_node/network/Cargo.toml
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/network_beacon_processor/sync_methods.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/custody.rs
  beacon_node/network/src/sync/network_context/requests.rs
  beacon_node/network/src/sync/range_sync/chain.rs
  lighthouse/Cargo.toml
Labels: ready-for-merge, tracing

#7877 Re-assess Lighthouse's peer count for Fusaka
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
Labels: ready-for-merge, fulu, v8.0.0-rc.0

#7912 Prioritise `StatusV2` over `StatusV1` RPC protocol
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
Labels: low-hanging-fruit, ready-for-merge, v8.0.0-rc.0

#7916 use DEFAULT_TARGET_PEERS for target peers everywhere
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/peer_manager/config.rs
Labels: ready-for-merge

#7909 Use Fork variants instead of version for JsonPayload types
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
Labels: code-quality, ready-for-merge

#7928 Fix `DataColumnsByRoot` request limit validation bug
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  consensus/types/src/chain_spec.rs
Labels: bug, ready-for-merge, v8.0.0-rc.0

#7929 Run sync tests on CI by default.
  .github/workflows/local-testnet.yml
Labels: test improvement, ready-for-merge

#7940 Notify lookup after gossip data column processing resulted in an import
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
Labels: bug, ready-for-merge, das

#7942 Fix data columns by range returning all columns
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
Labels: ready-for-merge, fulu, v8.0.0-rc.0

#7930 Delete `RuntimeVariableList::from_vec`
  Cargo.lock
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/network_context/requests/blobs_by_root.rs
  beacon_node/network/src/sync/network_context/requests/blocks_by_root.rs
  beacon_node/network/src/sync/network_context/requests/data_columns_by_root.rs
  beacon_node/network/src/sync/tests/lookups.rs
  beacon_node/store/Cargo.toml
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  consensus/types/src/blob_sidecar.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/runtime_var_list.rs
Labels: code-quality, consensus, ready-for-merge, Networking, das, v8.0.0-rc.0

#7959 Fix doppelganger protection script
  scripts/tests/doppelganger_protection.sh
Labels: low-hanging-fruit, ready-for-merge

#7962 Avoid serving validator endpoints while the node is far behind syncing head
  beacon_node/http_api/src/lib.rs
Labels: ready-for-merge, v8.0.0-rc.0
