Repository sigp/lighthouse, pull requests merged in 2025-10, with the labels that each got.

#8144 Improve spec compliance for `/eth/v1/config/spec` API
  consensus/types/src/chain_spec.rs
  consensus/types/src/preset.rs
Labels: low-hanging-fruit, ready-for-merge, HTTP-API, v8.0.0, queued

#8151 Fulu ASCII art
  beacon_node/network/src/service.rs
  consensus/types/src/fork_name.rs
Labels: ready-for-merge, fulu, v8.0.0, queued

#8167 Quote `BeaconState::proposer_lookahead` in JSON repr
  consensus/types/src/beacon_state.rs
Labels: bug, low-hanging-fruit, ready-for-merge, HTTP-API, fulu, v8.0.0, queued

#8142 Remove deprecated CLI flags and references for v8.0.0
  beacon_node/src/cli.rs
  beacon_node/src/config.rs
  book/src/help_bn.md
  lighthouse/src/main.rs
  lighthouse/tests/beacon_node.rs
Labels: low-hanging-fruit, ready-for-merge, backwards-incompat, v8.0.0, queued

#8156 Block proposal optimisations
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/state_advance_timer.rs
  beacon_node/operation_pool/src/lib.rs
Labels: optimization, ready-for-merge, v8.0.0, queued
