Repository sigp/lighthouse, pull requests merged in 2025-04, with the labels that each got.

#7112 Change `genesis-state-url-timeout`
  book/src/help_bn.md
  book/src/help_general.md
  book/src/help_vc.md
  book/src/help_vm.md
  book/src/help_vm_create.md
  book/src/help_vm_import.md
  book/src/help_vm_move.md
  lighthouse/src/main.rs
  lighthouse/tests/beacon_node.rs
Labels: low-hanging-fruit, ready-for-merge

#7168 Tracing cleanup
  Cargo.lock
  Cargo.toml
  common/logging/Cargo.toml
  common/logging/src/lib.rs
  common/logging/src/tracing_libp2p_discv5_logging_layer.rs
  common/logging/src/tracing_logging_layer.rs
  common/logging/src/utils.rs
  common/workspace_members/Cargo.toml
  common/workspace_members/src/lib.rs
  lighthouse/environment/src/lib.rs
  lighthouse/environment/src/tracing_common.rs
  lighthouse/src/main.rs
  testing/simulator/src/basic_sim.rs
  testing/simulator/src/fallback_sim.rs
Labels: ready-for-merge, UX-and-logs, v7.1.0

#7231 Consensus spec tests beta4
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
Labels: ready-for-merge, v7.0.0

#7243 Backmerge apr 2
  beacon_node/store/Cargo.toml
Labels: ready-for-review, do-not-merge

#7222 feat: add more bootnodes for Hoodi and Sepolia
  common/eth2_network_config/built_in_network_configs/hoodi/boot_enr.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/boot_enr.yaml
Labels: ready-for-merge, v7.0.0

#7176 Fix test OOM issues on tree-states-hot
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v24.rs
  beacon_node/beacon_chain/src/summaries_dag.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/impls/beacon_state.rs
  beacon_node/store/src/iter.rs
  beacon_node/store/src/lib.rs
  common/malloc_utils/src/glibc.rs
Labels: work-in-progress, tree-states

#7244 Attempt to fix flaky network tests
  beacon_node/network/src/subnet_service/tests/mod.rs
Labels: test improvement, ready-for-merge

#7238 RPC RequestId Cleanup
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/self_limiter.rs
  beacon_node/lighthouse_network/src/service/api_types.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/router.rs
  beacon_node/network/src/service.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/tests/lookups.rs
  beacon_node/network/src/sync/tests/range.rs
Labels: ready-for-merge, Networking

#7254 Rust 1.86.0 lints
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/beacon_proposer_cache.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/eth1_finalization_cache.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/types/sync_state.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/tests/lookups.rs
  common/eth2_wallet_manager/src/locked_wallet.rs
  consensus/proto_array/src/proto_array.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/types/src/sync_committee_contribution.rs
  consensus/types/src/test_utils/test_random/bitfield.rs
  crypto/bls/src/lib.rs
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/fork_choice.rs
  validator_client/http_api/src/tests/keystores.rs
  validator_client/validator_store/src/lib.rs
Labels: ready-for-merge

#7257 Backmerge `release-v7.0.0` into `unstable`
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/beacon_proposer_cache.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/eth1_finalization_cache.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/lighthouse_network/src/peer_manager/mod.rs
  beacon_node/lighthouse_network/src/peer_manager/peerdb.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/sync/manager.rs
  beacon_node/network/src/sync/tests/lookups.rs
  common/eth2/src/lighthouse/sync_state.rs
  common/eth2_network_config/built_in_network_configs/hoodi/boot_enr.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/boot_enr.yaml
  common/eth2_wallet_manager/src/locked_wallet.rs
  consensus/proto_array/src/proto_array.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/types/src/sync_committee_contribution.rs
  consensus/types/src/test_utils/test_random/bitfield.rs
  crypto/bls/src/lib.rs
  testing/ef_tests/Makefile
  testing/ef_tests/check_all_files_accessed.py
  testing/ef_tests/src/cases.rs
  testing/ef_tests/src/cases/fork_choice.rs
  validator_client/http_api/src/tests/keystores.rs
  validator_client/validator_store/src/lib.rs
Labels: ready-for-review

#7240 Disable log color when running in non-interactive mode
  lighthouse/src/main.rs
Labels: ready-for-merge, UX-and-logs, v7.1.0

#7188 Fix the `getBlobs` metric and ensure it is recorded promptly to prevent miscounts
  beacon_node/beacon_chain/src/fetch_blobs.rs
  beacon_node/beacon_chain/src/metrics.rs
Labels: low-hanging-fruit, ready-for-merge, das

#6990 Add missing error log and remove redundant id field from lookup logs
  beacon_node/network/src/sync/network_context/custody.rs
Labels: low-hanging-fruit, ready-for-merge, das, peerdas-devnet-4

#7263 Bump openssl to fix cargo audit failure
  Cargo.lock
Labels: security, ready-for-merge

#7264 Fix the `cargo audit` failure by backmerging `release-v7.0.0` into `unstable`
  Cargo.lock
Labels: ready-for-review

#7265 Remove CLI conflict for secrets-dir and datadir
  lighthouse/tests/validator_client.rs
  validator_client/src/cli.rs
Labels: val-client, low-hanging-fruit, ready-for-merge, UX-and-logs

#7256 Align logs
  common/logging/src/tracing_logging_layer.rs
Labels: ready-for-merge, UX-and-logs

#7098 Compute roots for unfinalized by_range requests with fork-choice
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
Labels: optimization, ready-for-merge, v7.0.0, v7.0.0-beta.clean

#7248 Return eth1_data early post transition
  beacon_node/beacon_chain/src/eth1_chain.rs
Labels: ready-for-merge, v7.0.0

#6744 Drop head tracker for summaries DAG
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/canonical_head.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_availability_checker/state_lru_cache.rs
  beacon_node/beacon_chain/src/head_tracker.rs
  beacon_node/beacon_chain/src/lib.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/migrate.rs
  beacon_node/beacon_chain/src/persisted_beacon_chain.rs
  beacon_node/beacon_chain/src/schema_change.rs
  beacon_node/beacon_chain/src/schema_change/migration_schema_v23.rs
  beacon_node/beacon_chain/src/state_advance_timer.rs
  beacon_node/beacon_chain/src/summaries_dag.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/store/src/database/leveldb_impl.rs
  beacon_node/store/src/errors.rs
  beacon_node/store/src/garbage_collection.rs
  beacon_node/store/src/hot_cold_store.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/metadata.rs
  consensus/proto_array/src/proto_array.rs
  consensus/proto_array/src/proto_array_fork_choice.rs
Labels: ready-for-merge, backwards-incompat, tree-states, v7.1.0

#7269 Bump version to v7.1.0-beta.0 (not a release)
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, tree-states

#7258 Fullnodes to publish data columns from EL `getBlobs`
  beacon_node/network/src/network_beacon_processor/mod.rs
Labels: ready-for-merge, das

#7117 Offloading KZG Proof Computation from the beacon node
  beacon_node/beacon_chain/benches/benches.rs
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/data_availability_checker.rs
  beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs
  beacon_node/beacon_chain/src/data_column_verification.rs
  beacon_node/beacon_chain/src/early_attester_cache.rs
  beacon_node/beacon_chain/src/fetch_blobs.rs
  beacon_node/beacon_chain/src/fulu_readiness.rs
  beacon_node/beacon_chain/src/historical_blocks.rs
  beacon_node/beacon_chain/src/kzg_utils.rs
  beacon_node/beacon_chain/src/metrics.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/execution_layer/src/engine_api.rs
  beacon_node/execution_layer/src/engine_api/http.rs
  beacon_node/execution_layer/src/engine_api/json_structures.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/execution_layer/src/test_utils/execution_block_generator.rs
  beacon_node/execution_layer/src/test_utils/fixtures/mainnet/test_blobs_bundle_v2.ssz
  beacon_node/execution_layer/src/test_utils/handle_rpc.rs
  beacon_node/execution_layer/src/test_utils/mock_builder.rs
  beacon_node/execution_layer/src/test_utils/mod.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/network_beacon_processor/gossip_methods.rs
  beacon_node/network/src/network_beacon_processor/mod.rs
  consensus/types/src/data_column_sidecar.rs
  consensus/types/src/eth_spec.rs
  consensus/types/src/lib.rs
  crypto/kzg/src/lib.rs
  scripts/local_testnet/network_params_das.yaml
Labels: ready-for-merge, das, fulu, peerdas-devnet-6

#7275 Mainnet Electra fork epoch
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge, electra, v7.0.0

#7285 Fix builder API electra json response
  Cargo.lock
  common/eth2/Cargo.toml
  common/eth2/src/types.rs
Labels: ready-for-merge, builder API, electra, v7.0.0

#7175 Clarify network limits
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/src/config.rs
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/hoodi/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/types/src/chain_spec.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
Labels: ready-for-merge, v7.0.0

#6982 Remove/document remaining Electra TODOs
  beacon_node/execution_layer/src/lib.rs
  consensus/state_processing/src/genesis.rs
  consensus/state_processing/src/per_block_processing/verify_attestation.rs
  consensus/types/src/validator.rs
Labels: low-hanging-fruit, ready-for-merge, electra, v7.0.0

#7192 Fix for #6296: Deterministic RNG in peer DAS publish block tests
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/builder.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/client/Cargo.toml
  beacon_node/client/src/builder.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/subnet_service/tests/mod.rs
Labels: test improvement, ready-for-merge, das

#7290 Add `pending_consolidations` Beacon API endpoint
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
Labels: ready-for-merge, electra, v7.0.0

#7300 Downgrade light client errors
  beacon_node/beacon_chain/src/beacon_chain.rs
Labels: ready-for-merge, UX-and-logs, light-client, v7.0.0

#7303 Update and cleanup Electra preset
  consensus/types/presets/mainnet/electra.yaml
  consensus/types/presets/minimal/electra.yaml
  consensus/types/src/preset.rs
Labels: low-hanging-fruit, ready-for-merge, electra, v7.0.0

#7296 Gnosis Pectra fork epoch
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  consensus/types/src/chain_spec.rs
Labels: ready-for-merge, electra, v7.0.0

#7313 Update crossbeam to fix `cargo audit` failure
  Cargo.lock
Labels: security, ready-for-merge, v7.0.0

#7230 Ensure `light_client/updates` endpoint returns spec compliant SSZ data
  beacon_node/http_api/src/light_client.rs
  common/eth2/src/types.rs
Labels: bug, ready-for-merge, HTTP-API, light-client, v7.0.0

#7298 Ensure `/eth/v2/beacon/pool/attestations` honors `committee_index`
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/operation_pool/src/lib.rs
  consensus/types/src/attestation.rs
Labels: bug, ready-for-merge, HTTP-API, electra, v7.0.0

#7315 Backmerge `release-v7.0.0` to `unstable`
  Cargo.lock
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/beacon_chain/src/eth1_chain.rs
  beacon_node/execution_layer/src/lib.rs
  beacon_node/http_api/Cargo.toml
  beacon_node/http_api/src/lib.rs
  beacon_node/http_api/src/light_client.rs
  beacon_node/http_api/tests/tests.rs
  beacon_node/lighthouse_network/src/config.rs
  beacon_node/lighthouse_network/src/lib.rs
  beacon_node/lighthouse_network/src/rpc/codec.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/protocol.rs
  beacon_node/lighthouse_network/src/service/mod.rs
  beacon_node/lighthouse_network/src/types/pubsub.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
  beacon_node/network/src/metrics.rs
  beacon_node/network/src/network_beacon_processor/rpc_methods.rs
  beacon_node/operation_pool/src/attestation_storage.rs
  beacon_node/operation_pool/src/lib.rs
  beacon_node/src/config.rs
  common/eth2/Cargo.toml
  common/eth2/src/lib.rs
  common/eth2/src/types.rs
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/hoodi/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/proto_array/src/proto_array_fork_choice.rs
  consensus/state_processing/src/genesis.rs
  consensus/state_processing/src/per_block_processing/verify_attestation.rs
  consensus/types/presets/mainnet/electra.yaml
  consensus/types/presets/minimal/electra.yaml
  consensus/types/src/attestation.rs
  consensus/types/src/chain_spec.rs
  consensus/types/src/preset.rs
  consensus/types/src/validator.rs
  lighthouse/environment/tests/testnet_dir/config.yaml
Labels: do-not-merge

#7281 Fix wrong custody column count for lookup blocks
  beacon_node/beacon_chain/src/block_verification.rs
  beacon_node/beacon_chain/src/block_verification_types.rs
  beacon_node/beacon_chain/src/test_utils.rs
  beacon_node/beacon_chain/tests/block_verification.rs
  beacon_node/beacon_chain/tests/payload_invalidation.rs
  beacon_node/beacon_chain/tests/store_tests.rs
  beacon_node/http_api/src/publish_blocks.rs
  beacon_node/network/src/network_beacon_processor/tests.rs
  beacon_node/network/src/sync/block_lookups/common.rs
  beacon_node/network/src/sync/block_sidecar_coupling.rs
  beacon_node/network/src/sync/network_context.rs
  beacon_node/network/src/sync/tests/range.rs
  testing/ef_tests/src/cases/fork_choice.rs
Labels: bug, ready-for-merge, das

#6996 Fix execution engine integration tests with latest geth version
  Cargo.lock
  Cargo.toml
  testing/execution_engine_integration/Cargo.toml
  testing/execution_engine_integration/src/geth.rs
  testing/execution_engine_integration/src/main.rs
  testing/execution_engine_integration/src/test_rig.rs
Labels: test improvement, ready-for-merge

#7161 Add `MAX_BLOBS_PER_BLOCK_FULU` config
  beacon_node/network/src/network_beacon_processor/tests.rs
  common/eth2_network_config/built_in_network_configs/chiado/config.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/config.yaml
  common/eth2_network_config/built_in_network_configs/holesky/config.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/config.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/config.yaml
  consensus/types/src/chain_spec.rs
Labels: low-hanging-fruit, ready-for-merge, das, fulu

#7311 Delete `transaction_mutex` in store
  beacon_node/beacon_chain/src/beacon_chain.rs
  beacon_node/store/src/database/interface.rs
  beacon_node/store/src/database/leveldb_impl.rs
  beacon_node/store/src/database/redb_impl.rs
  beacon_node/store/src/lib.rs
  beacon_node/store/src/memory_store.rs
Labels: waiting-on-author, tree-states

#7316 Update proposer_slashings and attester_slashings amounts for electra.
  beacon_node/beacon_chain/src/beacon_block_reward.rs
  beacon_node/beacon_chain/tests/rewards.rs
  beacon_node/http_api/tests/tests.rs
  common/eth2/src/lib.rs
Labels: under-review, ready-for-merge, HTTP-API, rewards-api, v7.0.0

#7333 Release v7.0.0-beta.7
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: v7.0.0

#7225 Restore HTTP API logging and add more metrics
  beacon_node/http_api/src/lib.rs
Labels: ready-for-merge, HTTP-API, UX-and-logs

#7279 feat: update mainnet bootnodes
  common/eth2_network_config/built_in_network_configs/mainnet/boot_enr.yaml
  lighthouse/tests/beacon_node.rs
Labels: ready-for-merge, Networking

#7280 Update Lighthouse Book for Electra features
  .github/workflows/release.yml
  account_manager/src/validator/exit.rs
  beacon_node/client/src/notifier.rs
  book/src/SUMMARY.md
  book/src/advanced_blobs.md
  book/src/advanced_database_migrations.md
  book/src/archived.md
  book/src/archived_key_management.md
  book/src/archived_merge_migration.md
  book/src/developers_architecture.md
  book/src/faq.md
  book/src/imgs/developers_architecture.svg
  book/src/mainnet_validator.md
  book/src/validator_consolidation.md
  book/src/validator_management.md
  book/src/validator_sweep.md
  book/src/validator_voluntary_exit.md
  scripts/tests/doppelganger_protection.sh
  wordlist.txt
Labels: docs, ready-for-merge, electra

#7288 Release v7.0.0
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: do-not-merge, v7.0.0

#7343 Fix Kurtosis doppelganger CI
  scripts/tests/doppelganger_protection.sh
Labels: ready-for-merge, infra-ci

#7340 Fix GitHub releases page looks bad in GitHub dark theme
  .github/workflows/release.yml
Labels: ready-for-merge, UX-and-logs

#7324 Revise logging when `queue is full`
  beacon_node/beacon_processor/src/work_reprocessing_queue.rs
Labels: ready-for-merge, UX-and-logs

#7346 Enable cross-compiling for riscv64 architecture
  Cross.toml
  Makefile
  book/src/installation_cross_compiling.md
Labels: ready-for-merge, v7.1.0

#7350 Fix Kurtosis testnet
  scripts/local_testnet/network_params.yaml
Labels: ready-for-merge

#5923 Delayed RPC Send Using Tokens
  beacon_node/lighthouse_network/src/metrics.rs
  beacon_node/lighthouse_network/src/rpc/handler.rs
  beacon_node/lighthouse_network/src/rpc/methods.rs
  beacon_node/lighthouse_network/src/rpc/mod.rs
  beacon_node/lighthouse_network/src/rpc/rate_limiter.rs
  beacon_node/lighthouse_network/src/rpc/response_limiter.rs
  beacon_node/lighthouse_network/src/rpc/self_limiter.rs
  beacon_node/lighthouse_network/tests/common.rs
  beacon_node/lighthouse_network/tests/rpc_tests.rs
Labels: ready-for-merge, Networking

#6747 feat: presign for validator account
  Cargo.lock
  account_manager/Cargo.toml
  account_manager/src/validator/exit.rs
Labels: ready-for-merge

#7351 Revise consolidation info in Lighthouse book
  book/src/validator_consolidation.md
Labels: docs, ready-for-merge, electra

#6956 Changing `boot_enr.yaml` to expect `bootstap_nodes.yaml` for pectra devnet
  common/eth2_config/src/lib.rs
  common/eth2_network_config/built_in_network_configs/chiado/bootstrap_nodes.yaml
  common/eth2_network_config/built_in_network_configs/gnosis/bootstrap_nodes.yaml
  common/eth2_network_config/built_in_network_configs/holesky/bootstrap_nodes.yaml
  common/eth2_network_config/built_in_network_configs/hoodi/bootstrap_nodes.yaml
  common/eth2_network_config/built_in_network_configs/mainnet/bootstrap_nodes.yaml
  common/eth2_network_config/built_in_network_configs/sepolia/bootstrap_nodes.yaml
  common/eth2_network_config/src/lib.rs
Labels: ready-for-merge, backwards-incompat, v7.1.0

#7364 Change default state cache size back to 128
  beacon_node/src/cli.rs
  beacon_node/store/src/state_cache.rs
  book/src/help_bn.md
  lighthouse/tests/beacon_node.rs
  scripts/tests/doppelganger_protection.sh
Labels: ready-for-merge

#7374 Release v7.0.1
  Cargo.lock
  beacon_node/Cargo.toml
  boot_node/Cargo.toml
  common/lighthouse_version/src/lib.rs
  lcli/Cargo.toml
  lighthouse/Cargo.toml
Labels: ready-for-merge, v7.0.1

#6897 vc: increase default gas limit
  book/src/help_vc.md
  lighthouse/tests/validator_client.rs
  validator_client/src/cli.rs
  validator_client/validator_store/src/lib.rs
Labels: ready-for-merge, backwards-incompat, v7.1.0

#6653 Add documentation for VC API `/lighthouse/beacon/health`
  book/src/advanced_redundancy.md
  book/src/api_vc_endpoints.md
  validator_client/http_api/src/lib.rs
Labels: val-client, docs, ready-for-merge

#7326 Optimize `validate_data_columns`
  beacon_node/beacon_chain/src/kzg_utils.rs
Labels: optimization, ready-for-merge, das, fulu
